Repository AudiusProject/audius-client, pull requests merged in 2020-11, with the labels that each got.

#103 Fix dropdown placement
  src/components/general/Modal.js
  src/components/source-files-modal/SourceFilesModal.module.css
  src/components/track/EditTrackModal.js
Labels: bug

#102 Allow track null in polling confirmation
  package-lock.json
  package.json
  src/services/audius-api-client/AudiusAPIClient.ts
  src/store/confirmer/sagas.js
Labels: bug

#101 Reject non audio mime upfront
  src/containers/upload-page/store/utils/processFiles.ts
Labels: refactor

#107 Add Track Upload Metrics
  src/containers/upload-page/store/sagas.js
  src/containers/upload-page/store/utils/sagaHelpers.ts
  src/services/analytics.ts
  src/store/application/ui/stemsUpload/sagas.ts
Labels: bug, feature

#122 Cleanup unused AudiusBackend methods
  src/services/AudiusBackend.js
Labels: refactor

#123 Update content node sp type
  package-lock.json
  package.json
  src/containers/nav/mobile/NavBar.module.css
  src/containers/service-selection/store/store.test.js
Labels: refactor
