Repository AudiusProject/audius-client, pull requests merged in 2021-12, with the labels that each got.

#677 [AUD-1114] Add slot diff remote config
  package-lock.json
  package.json
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/services/AudiusBackend.js
Labels: size/S

#702 Ignore scripts in CI
  .circleci/config.yml
Labels: size/XS

#703 Fix crash for missing owner id of track
  package-lock.json
  package.json
  src/common/store/cache/collections/selectors.ts
  src/common/store/errors/sagas.ts
  src/services/sentry.ts
Labels: size/S

#701 [AUD-1007] Api Rewards Explainer in RN
  src/containers/audio-rewards-page/components/modals/TopAPI.tsx
Labels: size/XS

#706 Remove console.time
  src/common/services/remote-config/remote-config.ts
Labels: size/XS

#705 Add current discovery node to preview
  src/containers/confirmer-preview/ConfirmerPreview.module.css
  src/containers/discovery-node-selection/DiscoveryNodeSelection.module.css
  src/containers/discovery-node-selection/DiscoveryNodeSelection.tsx
Labels: size/M

#704 Upgrade to react@17.0.2
  package-lock.json
  package.json
  src/components/animated-button/AnimatedButtonProvider.tsx
Labels: size/XS

#708 [AUD-1035] Hidden tracks
  package-lock.json
  package.json
  src/components/general/alt-button/FavoriteButton.module.css
  src/components/general/alt-button/FavoriteButton.tsx
  src/components/general/alt-button/RepostButton.module.css
  src/components/general/alt-button/RepostButton.tsx
  src/components/general/alt-button/ShareButton.module.css
  src/components/general/alt-button/ShareButton.tsx
  src/components/track/ArtistPick.tsx
  src/components/track/TrackBannerIcon.module.css
  src/components/track/TrackBannerIcon.tsx
  src/components/track/desktop/ConnectedTrackTile.tsx
  src/components/track/desktop/TrackTile.module.css
  src/components/track/desktop/TrackTile.tsx
  src/components/track/helpers.ts
  src/components/track/mobile/BottomButtons.tsx
  src/components/track/mobile/ConnectedTrackTile.tsx
  src/components/track/mobile/TrackTile.module.css
  src/components/track/mobile/TrackTile.tsx
  src/components/track/types.ts
  src/containers/lineup/LineupProvider.tsx
  src/containers/profile-page/components/desktop/ProfilePage.tsx
  src/containers/profile-page/store/lineups/tracks/retrieveUserTracks.ts
  src/containers/profile-page/store/lineups/tracks/sagas.js
  src/services/AudiusBackend.js
  src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/L

#710 [AUD-1035] Fix bug with skeletons not loading on trending
  src/containers/lineup/LineupProvider.tsx
  src/containers/profile-page/store/lineups/tracks/reducer.js
Labels: size/XS

#711 0.24.37
  .gitignore
  package-lock.json
  package.json
Labels: size/XS

#712 Hotfix missing track in collection
  src/common/store/cache/collections/selectors.ts
Labels: size/M

#709 Retroactive Referrals
  src/containers/App.js
  src/containers/app-redirect-popover/components/AppRedirectPopover.tsx
  src/containers/sign-on/SignOnProvider.tsx
  src/containers/sign-on/store/sagas.js
Labels: size/M

#707 Remove update npm statements from CI config
  .circleci/config.yml
Labels: size/S

#713 [AUD-1037] Send filename instead of title
  src/services/audius-backend/TrackDownload.js
  src/services/native-mobile-interface/downloadTrack.ts
Labels: size/XS

#714 Fix user id
  src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/XS

#715 [AUD-1015] TikTok Sharing in react native
  package-lock.json
  src/common/hooks/useTikTokAuth.ts
  src/common/store/ui/share-sound-to-tiktok-modal/selectors.ts
  src/common/store/ui/share-sound-to-tiktok-modal/slice.ts
  src/common/store/ui/share-sound-to-tiktok-modal/types.ts
  src/containers/share-sound-to-tiktok-modal/ShareSoundToTikTokModal.module.css
  src/containers/share-sound-to-tiktok-modal/ShareSoundToTikTokModal.tsx
  src/containers/share-sound-to-tiktok-modal/store/sagas.ts
  src/hooks/useTikTokAuth.ts
Labels: size/L
