Repository AudiusProject/audius-client, pull requests merged in 2022-02, with the labels that each got.

#849 0.24.41
  .circleci/config.yml
  package-lock.json
  package.json
Labels: size/M

#822 Add amplitude user bank tracking
  src/common/models/Analytics.ts
  src/services/AudiusBackend.js
  src/services/audius-backend/waudio.ts
Labels: size/M

#850 Start fetching challenges on get account
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/XS

#830 Optimistically update ui for listen streak challenge
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
  src/store/social/tracks/sagas.ts
Labels: bug, size/L

#848 [AUD-1414] Forgot password helper QA Fixes
  src/pages/sign-on/components/desktop/ForgotPasswordHelper.module.css
  src/pages/sign-on/components/desktop/ForgotPasswordHelper.tsx
Labels: size/M

#839 Update useImageSize hook to optionally accept dispatch
  src/common/hooks/useImageSize.ts
  src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  src/components/artist-recommendations/ArtistRecommendations.tsx
  src/components/artist/ArtistCard.js
  src/components/artist/ArtistChip.js
  src/components/artist/ArtistPopover.tsx
  src/components/card/UserCard.js
  src/components/card/desktop/Card.tsx
  src/components/card/desktop/CollectionArtCard.tsx
  src/components/card/desktop/UserArtCard.tsx
  src/components/card/mobile/Card.tsx
  src/components/collection/desktop/CollectionHeader.js
  src/components/collection/mobile/CollectionHeader.js
  src/components/cover-photo/CoverPhoto.tsx
  src/components/create-playlist/CreatePlaylistModal.js
  src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  src/components/first-upload-modal/FirstUploadModal.tsx
  src/components/nav/desktop/CurrentlyPlaying.tsx
  src/components/nav/desktop/NavColumn.js
  src/components/notification/components/TrackContent.tsx
  src/components/notification/components/desktop/UserHeader.tsx
  src/components/notification/components/mobile/ConnectedUserHeader.tsx
  src/components/now-playing/NowPlaying.tsx
  src/components/play-bar/desktop/components/PlayingTrackInfo.tsx
  src/components/play-bar/mobile/PlayBar.tsx
  src/components/profile-picture/ProfilePicture.js
  src/components/remix-card/ConnectedRemixCard.tsx
  src/components/remix-settings-modal/RemixSettingsModal.tsx
  src/components/track/EditTrackModal.js
  src/components/track/GiantArtwork.tsx
  src/components/track/desktop/Artwork.tsx
  src/components/track/desktop/stats/ProfileImage.tsx
  src/components/track/mobile/TrackListItem.tsx
  src/components/track/mobile/TrackTileArt.tsx
  src/hooks/useCollectionCoverArt.ts
  src/hooks/useImageSize.test.tsx
  src/hooks/useTrackCoverArt.ts
  src/hooks/useUserCoverPhoto.ts
  src/hooks/useUserProfilePicture.ts
  src/pages/artist-dashboard-page/components/ArtistProfile.js
  src/pages/deleted-page/components/desktop/DeletedPage.tsx
  src/pages/deleted-page/components/mobile/DeletedPage.tsx
  src/pages/profile-page/components/mobile/ProfileHeader.tsx
  src/pages/settings-page/components/desktop/VerificationModal.tsx
  src/pages/settings-page/components/mobile/AccountSettingsPage.tsx
  src/pages/settings-page/components/mobile/SettingsPage.tsx
  src/pages/settings-page/components/mobile/VerificationPage.tsx
  src/pages/track-page/components/mobile/TrackHeader.tsx
  src/pages/visualizer/VisualizerProvider.tsx
Labels: size/L

#851 Always release staging electron app
  .circleci/config.yml
Labels: size/S

#853 Fix Heavy Rotation
  src/pages/smart-collection/store/sagas.ts
Labels: bug, size/XS

#855 Add types to the sagas for the explore page
  src/pages/smart-collection/store/sagas.ts
  src/services/audius-backend/Explore.ts
  src/store/recommendation/sagas.ts
Labels: size/M

#779 Replace year trending with all time
  src/common/models/TimeRange.ts
  src/common/store/pages/feed/types.ts
  src/components/trending-genre-selection/TrendingGenreSelectionPage.tsx
  src/pages/trending-page/TrendingPageProvider.js
  src/pages/trending-page/components/desktop/TrendingPageContent.tsx
  src/pages/trending-page/components/mobile/TrendingPageContent.tsx
  src/pages/trending-page/store/lineups/trending/actions.js
  src/pages/trending-page/store/lineups/trending/reducer.js
  src/pages/trending-page/store/lineups/trending/sagas.js
  src/pages/trending-page/store/lineups/trending/selectors.ts
  src/pages/trending-page/store/reducer.js
  src/pages/trending-page/store/selectors.js
  src/pages/trending-page/store/types.ts
  src/pages/trending-page/types.ts
  src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/L

#858 [AUD-1429] Clicking "Visit Track Page" from artist dashboard not redirecting bug fix
  src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Labels: size/XS

#857 [AUD-1253] Move artist dashboard query to use discovery node
  src/pages/artist-dashboard-page/store/sagas.js
  src/services/AudiusBackend.js
Labels: size/M

#859 [AUD-83] Fix linux builds and rename desktop "bounce" app to "staging"
  .circleci/config.yml
  resources/icons/AudiusStagingDmgIcon.icns
  resources/icons/AudiusStagingIcon.icns
  resources/icons/AudiusStagingIcon.iconset/icon_128x128.png
  resources/icons/AudiusStagingIcon.iconset/icon_128x128@2x.png
  resources/icons/AudiusStagingIcon.iconset/icon_16x16.png
  resources/icons/AudiusStagingIcon.iconset/icon_16x16@2x.png
  resources/icons/AudiusStagingIcon.iconset/icon_256x256.png
  resources/icons/AudiusStagingIcon.iconset/icon_256x256@2x.png
  resources/icons/AudiusStagingIcon.iconset/icon_32x32.png
  resources/icons/AudiusStagingIcon.iconset/icon_32x32@2x.png
  resources/icons/AudiusStagingIcon.iconset/icon_512x512.png
  resources/icons/AudiusStagingIcon.iconset/icon_512x512@2x.png
  resources/icons/AudiusStagingIcon.png
  scripts/dist.js
  src/services/download-app/DownloadApp.ts
Labels: size/M

#861 [AUD-1436] Add additional error context to amplitude
  src/common/models/Analytics.ts
  src/common/store/errors/sagas.ts
  src/pages/something-wrong/SomethingWrong.tsx
Labels: size/S

#860 Update broken discord link
  LICENSE
  src/utils/route.ts
Labels: size/XS

#864 Validate sol token address
  src/services/audius-backend/waudio.ts
  src/store/wallet/sagas.ts
Labels: size/S

#854 Swap out old favorite/repost buttons in play bar
  src/components/alt-button/FavoriteButton.module.css
  src/components/alt-button/FavoriteButton.tsx
  src/components/alt-button/RepostButton.module.css
  src/components/alt-button/RepostButton.tsx
  src/components/favorite-button/FavoriteButton.js
  src/components/favorite-button/FavoriteButton.module.css
  src/components/play-bar/desktop/PlayBar.js
  src/components/play-bar/desktop/PlayBar.module.css
  src/components/repost-button/RepostButton.module.css
  src/components/repost-button/RepostButton.tsx
  src/components/styles/FavoriteButton.module.module.css
  src/components/tracks-table/TableFavoriteButton.js
  src/components/tracks-table/TableFavoriteButton.module.css
Labels: size/L

#865 [AUD-1394] Upgrade to stems 0.3.21
  package-lock.json
  package.json
Labels: size/XS

#862 [AUD-1439] Move profile-page store to common
  src/app.tsx
  src/common/store/index.ts
  src/common/store/pages/profile/actions.js
  src/common/store/pages/profile/lineups/feed/actions.js
  src/common/store/pages/profile/lineups/feed/reducer.js
  src/common/store/pages/profile/lineups/feed/retrieveUserReposts.ts
  src/common/store/pages/profile/lineups/feed/sagas.js
  src/common/store/pages/profile/lineups/tracks/actions.js
  src/common/store/pages/profile/lineups/tracks/reducer.js
  src/common/store/pages/profile/lineups/tracks/retrieveUserTracks.ts
  src/common/store/pages/profile/lineups/tracks/sagas.js
  src/common/store/pages/profile/reducer.js
  src/common/store/pages/profile/sagas.js
  src/common/store/pages/profile/selectors.ts
  src/common/store/pages/profile/types.ts
  src/components/artist/ArtistPopover.tsx
  src/components/collectibles/components/CollectibleDetails.tsx
  src/components/collectibles/components/CollectiblesPage.tsx
  src/components/profile-progress/ConnectedProfileCompletionHeroCard.js
  src/components/unfollow-confirmation-modal/UnfollowConfirmationModal.tsx
  src/components/user-badges/hooks.tsx
  src/components/user-list/UserList.tsx
  src/pages/artist-dashboard-page/store/sagas.js
  src/pages/deleted-page/store/lineups/more-by/sagas.ts
  src/pages/profile-page/ProfilePageProvider.tsx
  src/pages/profile-page/components/desktop/ProfilePage.tsx
  src/pages/profile-page/components/mobile/ProfilePage.tsx
  src/pages/track-page/store/lineups/tracks/sagas.js
  src/store/account/mobileSagas.ts
  src/store/lineup/lineupForRoute.js
  src/store/playlist-library/sagas.ts
  src/store/reducers.js
  src/store/sagas.js
  src/store/token-dashboard/sagas.ts
  src/store/types.ts
  src/utils/route/userRouteParser.ts
Labels: size/L

#866 Support new verified referrals challenge in client
  src/common/models/AudioRewards.ts
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/config.tsx
Labels: size/S

#863 [AUD-1442] Handle errors at root saga
  package-lock.json
  package.json
  src/app.tsx
  src/common/store/errors/actions.ts
  src/common/store/errors/level.ts
  src/common/store/errors/reportToSentry.ts
  src/common/store/errors/sagas.ts
  src/common/utils/errorSagas.ts
  src/components/notification/store/errorSagas.ts
  src/components/pull-to-refresh/hooks.ts
  src/pages/App.test.tsx
  src/pages/AppErrorBoundary.tsx
  src/pages/upload-page/store/types.ts
  src/services/AudioManager.ts
  src/services/native-mobile-interface/helpers.ts
  src/services/native-mobile-interface/types.ts
  src/store/account/sagas.js
  src/store/configureStore.ts
  src/store/reducers.ts
  src/store/routing/sagas.ts
  src/store/sagas.ts
  src/utils/clientUtil.ts
  src/utils/history.js
  src/utils/history.ts
Labels: size/L

#868 [AUD-1421] Track download buttons in react native
  src/common/hooks/useDownloadTrackButtons.ts
  src/common/models/Stems.ts
  src/common/store/index.ts
  src/common/store/stems-upload/selectors.ts
  src/common/store/stems-upload/slice.ts
  src/components/download-buttons/DownloadButtons.tsx
  src/components/edit-track/EditTrackModal.tsx
  src/components/source-files-modal/SourceFilesModal.tsx
  src/pages/upload-page/store/utils/stems.ts
  src/store/application/ui/stemsUpload/sagas.ts
  src/store/application/ui/stemsUpload/selectors.ts
  src/store/reducers.ts
  src/store/types.ts
Labels: size/L

#869 Fix two field visibility bugs
  src/common/store/cache/tracks/utils/reformat.ts
  src/components/track/desktop/TrackTile.tsx
Labels: size/M

#870 Move profile sagas back to pages/ from common/
  src/pages/profile-page/sagas.js
  src/store/account/mobileSagas.ts
  src/store/playlist-library/sagas.ts
  src/store/sagas.ts
  src/store/token-dashboard/sagas.ts
Labels: size/S

#871 Move profile progress selectors to common
  src/common/models/User.ts
  src/common/store/challenges/selectors.ts
  src/components/profile-progress/ConnectedProfileCompletionHeroCard.js
  src/components/profile-progress/ConnectedProfileCompletionPane.js
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/hooks.ts
Labels: size/M

#872 Convert optimistic challenges hooks into selector
  src/common/models/AudioRewards.ts
  src/common/store/challenges/selectors/optimistic-challenges.ts
  src/common/store/challenges/selectors/profile-progress.ts
  src/components/nav/desktop/NavAudio.tsx
  src/components/profile-progress/ConnectedProfileCompletionHeroCard.js
  src/components/profile-progress/ConnectedProfileCompletionPane.js
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/config.tsx
Labels: size/L

#874 Change 2020 to current year on home page
  src/components/public-site/Footer.tsx
Labels: size/XS

#875 0.24.42
  package-lock.json
  package.json
Labels: size/XS

#877 Adds retry claim with exponential backoff
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
Labels: size/L

#879 Fix tracking create user bank
  src/services/audius-backend/waudio.ts
Labels: bug, size/XS

#876 [AUD-1440] Add support for aggregate challenges
  package-lock.json
  package.json
  src/common/models/AudioRewards.ts
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/common/store/challenges/selectors/optimistic-challenges.ts
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/components/nav/desktop/NavAudio.tsx
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/config.tsx
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
  src/services/AudiusBackend.js
  src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/L

#881 Fix profile completion selector for profile pic/cover photo
  src/common/models/User.ts
  src/common/store/challenges/selectors/profile-progress.ts
Labels: size/XS

#882 [AUD-1478] Adds support for optimistic disbursements of aggregate challenges
  src/common/models/AudioRewards.ts
  src/common/store/challenges/selectors/optimistic-challenges.ts
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/components/nav/desktop/NavAudio.tsx
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
Labels: size/L

#885 [AUD-1468] Go to rewards page on rewards notification click
  src/components/notification/components/desktop/NotificationBlock.tsx
  src/components/notification/components/mobile/Notification.tsx
Labels: size/S

#886 Bump libs 1.2.65
  package-lock.json
  package.json
Labels: size/XS

#887 Fix sentry state pruner
  src/services/sentry.ts
  src/store/configureStore.ts
  src/store/types.ts
Labels: bug, size/S

#889 Improve error handling for challenges
  package-lock.json
  package.json
  src/common/models/AudioRewards.ts
  src/pages/audio-rewards-page/store/sagas.ts
  src/services/AudiusBackend.js
Labels: size/M

#880 Support Multiple Fee Payers
  src/common/store/index.ts
  src/common/store/solana/selectors.ts
  src/common/store/solana/slice.ts
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
  src/pages/sign-on/store/sagas.js
  src/services/AudiusBackend.js
  src/services/audius-backend/waudio.ts
  src/store/account/sagas.js
  src/store/sagas.ts
  src/store/solana/sagas.ts
Labels: size/L

#894 [AUD-1504] Fix optimistic disbursement of challenge rewards
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/common/store/challenges/selectors/optimistic-challenges.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/store/sagas.ts
Labels: bug, size/M

#895 Fix fee payer
  package-lock.json
  package.json
  src/services/AudiusBackend.js
Labels: size/XS

#896 Add reward analytics
  package-lock.json
  package.json
  src/common/models/Analytics.ts
  src/services/AudiusBackend.js
  src/services/audius-backend/Rewards.ts
Labels: size/L

#897 0.24.43
  package-lock.json
  package.json
Labels: size/XS

#901 [AUD-1522] [AUD-1470] [AUD-1467] Fix profile completion stages display
  packages/mobile/package-lock.json
  packages/mobile/src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: bug, size/M

#899 [AUD-1412] Add EditProfileScreen
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/assets/images/iconTikTokInverted.svg
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/hooks/usePressColorAnimation.ts
  packages/mobile/src/screens/edit-profile-screen/CoverPhotoInput.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/ProfilePictureInput.tsx
  packages/mobile/src/screens/edit-profile-screen/ProfileTextInput.tsx
  packages/mobile/src/screens/edit-profile-screen/launchSelectImageActionSheet.ts
  packages/mobile/src/screens/edit-profile-screen/types.ts
  packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/XL

#900 [AUD-1517] Fix ProfileScreen scroll
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/patches/README.md
  packages/mobile/patches/react-native-tab-view+3.1.1.patch
  packages/mobile/src/components/core/VirtualizedScrollView.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
Labels: size/L

#902 [AUD-1342] Fix whitespace clipping at bottom of CollectibleDetailsDrawer
  packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
Labels: size/L

#904 Add RewardsBanner, `as` prop to Tile
  packages/mobile/src/assets/images/iconCrown.svg
  packages/mobile/src/components/core/Tile.tsx
  packages/mobile/src/screens/trending-screen/RewardsBanner.tsx
Labels: size/L

#906 [AUD-1039] Feed Filter Drawer
  packages/mobile/src/App.tsx
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/feed-filter-drawer/FeedFilterDrawer.tsx
  packages/mobile/src/components/feed-filter-drawer/index.ts
  packages/mobile/src/components/header-button/HeaderButton.tsx
  packages/mobile/src/components/header-button/index.ts
  packages/mobile/src/components/screen-header/ScreenHeader.tsx
  packages/mobile/src/components/screen-header/index.ts
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedFilterButton.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/feed-screen/index.ts
  packages/mobile/src/styles/types.ts
  packages/web/src/common/hooks/useModalState.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/pages/feed-page/components/mobile/FeedFilterDrawer.tsx
  packages/web/src/pages/feed-page/components/mobile/FeedFilterModal.module.css
  packages/web/src/pages/feed-page/components/mobile/FeedFilterModal.tsx
  packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
  packages/web/src/store/configureStore.ts
Labels: size/L

#907 [AUD-1527] Migrate trending store to common
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/trending/actions.js
  packages/web/src/common/store/pages/trending/lineup/actions.js
  packages/web/src/common/store/pages/trending/lineup/reducer.js
  packages/web/src/common/store/pages/trending/lineup/selectors.ts
  packages/web/src/common/store/pages/trending/reducer.js
  packages/web/src/common/store/pages/trending/selectors.js
  packages/web/src/common/store/pages/trending/types.ts
  packages/web/src/components/trending-genre-selection/TrendingGenreSelectionPage.tsx
  packages/web/src/pages/track-page/store/retrieveTrending.ts
  packages/web/src/pages/trending-page/TrendingPageProvider.js
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/store/lineups/trending/sagas.js
  packages/web/src/store/lineup/lineupForRoute.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#912 Hotfix challenge
  packages/web/src/pages/sign-on/store/sagas.js
Labels: size/XS

#913 [AUD-1532] Change solana cluster endpoint
  packages/web/.env/.env.prod
Labels: size/XS

#910 Report claim reward retry if not on final attempt
  package-lock.json
  package.json
  src/common/models/Analytics.ts
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
  src/services/AudiusBackend.js
  src/services/audius-backend/Rewards.ts
Labels: size/L

#915 Track retry for rewards analytics if not final attempt
  packages/mobile/package-lock.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/models/Analytics.ts
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/audio-rewards-page/store/store.test.ts
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/audius-backend/Rewards.ts
Labels: size/L

#916 Set listen streak challenges steps when complete
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/pages/audio-rewards/slice.ts
Labels: size/S

#911 Fix @web-jobs sentry push
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#919 Styling updates for PurpleBox for properly formatted single and double line view
  packages/web/src/pages/audio-rewards-page/components/PurpleBox.module.css
  packages/web/src/pages/audio-rewards-page/components/ReceiveBody.module.css
Labels: size/XS

#908 Add core Button Component
  packages/mobile/src/App.tsx
  packages/mobile/src/components/button/Button.tsx
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/core/DynamicImage/index.ts
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/components/enable-push-notifications-drawer/index.ts
  packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
  packages/mobile/src/screens/profile-screen/FollowButton.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/screens/track-screen/TrackScreenHeader.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
Labels: size/L

#909 [AUD-1530] Add TrendingScreen Lineups
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/core/Tile.tsx
  packages/mobile/src/components/screen-header/ScreenHeader.tsx
  packages/mobile/src/screens/edit-profile-screen/CoverPhotoInput.tsx
  packages/mobile/src/screens/edit-profile-screen/ProfilePictureInput.tsx
  packages/mobile/src/screens/trending-screen/RewardsBanner.tsx
  packages/mobile/src/screens/trending-screen/TrendingFilterButton.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
  packages/mobile/src/screens/trending-screen/index.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/trending/reducer.js
  packages/web/src/common/store/pages/trending/selectors.js
  packages/web/src/common/store/pages/trending/selectors.ts
  packages/web/src/common/store/pages/trending/types.ts
  packages/web/src/pages/trending-page/TrendingPageProvider.js
Labels: size/L

#922 [AUD-1473] Add TrendingFilterDrawer
  packages/mobile/src/App.tsx
  packages/mobile/src/components/core/SearchInput.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/trending-screen/TrendingFilterButton.tsx
  packages/mobile/src/screens/trending-screen/TrendingFilterDrawer.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
  packages/web/src/common/store/pages/trending/actions.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/common/utils/genres.ts
  packages/web/src/components/trending-genre-selection/TrendingGenreSelectionPage.tsx
  packages/web/src/pages/track-page/store/retrieveTrending.ts
Labels: size/L

#923 Consolidate audio-rewards
  packages/mobile/src/components/audio-rewards/IconAudioBadge.tsx
  packages/mobile/src/components/audio-rewards/audioTier.ts
  packages/mobile/src/components/audio-rewards/index.ts
  packages/mobile/src/components/notifications/NotificationBlock.tsx
  packages/mobile/src/components/notifications/content/TierChange.tsx
  packages/mobile/src/components/notifications/content/TwitterShare.tsx
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
  packages/mobile/src/screens/profile-screen/constants.ts
  packages/mobile/src/store/notifications/types.ts
Labels: size/L

#924 Move drawers to separate file, standardize imports
  packages/mobile/src/App.tsx
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
  packages/mobile/src/components/api-rewards-drawer/index.ts
  packages/mobile/src/components/audio-rewards/index.ts
  packages/mobile/src/components/challenge-rewards-drawer/index.ts
  packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
  packages/mobile/src/components/collectible-details-drawer/index.ts
  packages/mobile/src/components/connect-wallets-drawer/ConnectWalletsDrawer.tsx
  packages/mobile/src/components/connect-wallets-drawer/index.ts
  packages/mobile/src/components/deactivate-account-confirmation-drawer/index.ts
  packages/mobile/src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
  packages/mobile/src/components/download-track-progress-drawer/index.ts
  packages/mobile/src/components/forgot-password-drawer/ForgotPasswordDrawer.tsx
  packages/mobile/src/components/forgot-password-drawer/index.ts
  packages/mobile/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
  packages/mobile/src/components/mobile-upload-drawer/index.ts
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/index.ts
  packages/mobile/src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx
  packages/mobile/src/components/share-to-tiktok-drawer/index.ts
  packages/mobile/src/components/transfer-audio-mobile-drawer/TransferAudioMobileDrawer.tsx
  packages/mobile/src/components/transfer-audio-mobile-drawer/index.ts
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/components/trending-rewards-drawer/index.ts
  packages/mobile/src/screens/trending-screen/index.ts
Labels: size/L

#926 Combine Header and ScreenHeader, refactor HeaderButton
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/header-button/HeaderButton.tsx
  packages/mobile/src/components/header-button/index.ts
  packages/mobile/src/components/header/Header.tsx
  packages/mobile/src/components/header/HeaderButton.tsx
  packages/mobile/src/components/header/index.ts
  packages/mobile/src/components/screen-header/ScreenHeader.tsx
  packages/mobile/src/components/screen-header/index.ts
  packages/mobile/src/components/search/Search.tsx
  packages/mobile/src/components/search/SearchHistory.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedFilterButton.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingFilterButton.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Labels: size/L

#931 Prevent wormhole from sending 0 audio
  packages/web/src/common/store/pages/token-dashboard/slice.ts
  packages/web/src/services/wallet-client/WalletClient.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/S

#933 Add PR template and remove old CI
  .github/pull_request_template.md
  packages/mobile/.circleci/config.yml
  packages/web/.circleci/config.yml
  packages/web/.github/pull_request_template.md
Labels: size/XXL

#914 Optimize happy path $AUDIO nav balance
  packages/web/src/common/models/User.ts
  packages/web/src/components/nav/desktop/NavAudio.tsx
Labels: size/S

#935 Bump stems to 0.3.22 (for Modal sub components and button update)
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#936 Add remote config for libs discovery block diff
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/services/remote-config/defaults.ts
  packages/web/src/common/services/remote-config/types.ts
  packages/web/src/services/AudiusBackend.js
Labels: size/S

#939 1.2.80
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#941 Add size prop to ArtistCard Stats
  packages/web/src/components/artist/ArtistCard.js
Labels: size/XS

#942 Upgrade libs to 1.2.81
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#938 [AUD-1009] Add TiersExplainerDrawer
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/audio-rewards/TierText.tsx
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/components/audio-rewards/audioTier.ts
  packages/mobile/src/components/audio-rewards/index.ts
  packages/mobile/src/components/core/GradientText.tsx
  packages/mobile/src/components/drawer/AppDrawer.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/screens/edit-profile-screen/index.ts
  packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
Labels: size/L

#943 Bump Stems to 0.3.23 for small icons and ModalTitle fix
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#944 Allow cognito retry
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/audio-rewards-page/store/store.test.ts
Labels: size/S

#934 [AUD-967] Feed screen navigation fixes
  packages/mobile/package-lock.json
  packages/mobile/src/components/app-navigator/AppNavigator.tsx
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/track-tile/TrackTile.tsx
  packages/mobile/src/components/track-tile/TrackTileMetadata.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/explore-screen/components/ArtistCard.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenHeader.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/utils/navigation.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/store/routing/mobileSagas.ts
Labels: size/L

#945 [AUD-1423] Add FavoritedScreen
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/track-tile/TrackTile.tsx
  packages/mobile/src/components/track-tile/TrackTileStats.tsx
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/components/user-badges/index.ts
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx
  packages/mobile/src/screens/user-list-screen/FavoritesList.tsx
  packages/mobile/src/screens/user-list-screen/FollowingList.tsx
  packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserChip.tsx
  packages/mobile/src/screens/user-list-screen/index.ts
Labels: size/L

#947 [AUD-1678] Update blank image to correct path
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/components/card/desktop/CollectionArtCard.tsx
  packages/web/src/components/card/desktop/UserArtCard.tsx
  packages/web/src/components/card/mobile/Card.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/search-bar/ConnectedSearchBar.js
  packages/web/src/components/search/SearchBarResult.js
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/hooks/useCollectionCoverArt.ts
  packages/web/src/hooks/useTrackCoverArt.ts
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/upload-page/components/FinishPage.js
Labels: size/S

#949 Bump Libs to 1.2.84 and use processChallenges
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/AudiusBackend.js
Labels: size/M

#946 [AUD-1424] Add RepostsScreen, FollowingScreen
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/track-tile/TrackTile.tsx
  packages/mobile/src/components/track-tile/TrackTileStats.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
  packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx
  packages/mobile/src/screens/user-list-screen/index.ts
Labels: size/M

#953 Migrate lineup action to ts, implement play/pause in lineup
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/web/src/common/store/lineup/actions.ts
Labels: size/L

#954 [AUD-1581] Add social proof UI
  packages/web/src/common/models/Analytics.ts
  packages/web/src/common/models/Status.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/components/social-proof/SocialProof.module.css
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
  packages/web/src/pages/settings-page/components/TwitterAccountVerified.js
  packages/web/src/services/wallet-client/WalletClient.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/L

#959 Fix social proof bugs
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/components/twitter-auth/TwitterAuth.js
Labels: size/XS

#960 Fix onconfirm send bug
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
Labels: size/XS

#962 Update copy in SocialProof
  packages/web/src/components/social-proof/SocialProof.tsx
Labels: size/XS

#963 Revert "Optimize happy path $AUDIO nav balance (#914)"
  packages/web/src/common/models/User.ts
  packages/web/src/components/nav/desktop/NavAudio.tsx
Labels: size/S

#964 Add feature flag to disable sign up confirmation
  packages/web/src/common/models/Analytics.ts
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/pages/sign-on/store/sagas.js
Labels: size/M

#965 Debug error from getLocation call
  packages/web/src/services/Location.ts
Labels: size/XS

#966 Do not require social meta for insta in proof
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/instagram-button/InstagramButton.tsx
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/pages/settings-page/components/InstagramAccountVerified.tsx
Labels: size/M

#967 Fix analytics
  packages/web/src/common/models/Analytics.ts
  packages/web/src/components/social-proof/SocialProof.tsx
Labels: size/S

#925 Fix sign on redirect for existing users on native mobile
  packages/web/src/pages/sign-on/SignOn.tsx
  packages/web/src/pages/sign-on/SignOnProvider.tsx
Labels: size/M

#956 Migrate trending-underground to common
  packages/web/src/common/models/Lineup.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/lineup/reducer.ts
  packages/web/src/common/store/pages/trending-underground/lineup/actions.ts
  packages/web/src/common/store/pages/trending-underground/lineup/reducer.ts
  packages/web/src/common/store/pages/trending-underground/lineup/selectors.ts
  packages/web/src/common/store/pages/trending-underground/slice.ts
  packages/web/src/pages/deleted-page/store/lineups/more-by/reducer.ts
  packages/web/src/pages/search-page/store/actions.ts
  packages/web/src/pages/search-page/store/lineups/tracks/reducer.ts
  packages/web/src/pages/search-page/store/reducer.ts
  packages/web/src/pages/search-page/store/types.ts
  packages/web/src/pages/trending-playlists/store/lineups/collections/reducer.ts
  packages/web/src/pages/trending-underground/TrendingUndergroundPage.tsx
  packages/web/src/pages/trending-underground/store/lineups/tracks/sagas.ts
  packages/web/src/pages/trending-underground/store/lineups/tracks/selectors.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#968 [AUD-1549] Add UndergroundTrendingScreen
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
  packages/mobile/src/components/audio-rewards/index.ts
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/explore-screen/collections.ts
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingUndergroundScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/index.ts
  packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Labels: size/L

#969 [AUD-1571] Add ArtistPick to Profile TrackList
  packages/mobile/src/components/lineup/Delineator.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/delineate.ts
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
Labels: size/M

#970 [AUD-1595] Refactor TabSlider to SegmentedControl
  packages/mobile/src/components/core/SegmentedControl.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/tab-slider/TabSlider.tsx
  packages/mobile/src/components/tab-slider/index.ts
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
Labels: size/L

#971 [AUD-593] Add SettingsScreen
  packages/mobile/src/assets/images/iconSettings.svg
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/TopBar.tsx
  packages/mobile/src/components/app-navigator/TopBarIconButton.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/Divider.tsx
  packages/mobile/src/screens/settings-screen/SettingRowLabel.tsx
  packages/mobile/src/screens/settings-screen/SettingsRow.tsx
  packages/mobile/src/screens/settings-screen/SettingsRowDescription.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/index.ts
  packages/mobile/src/styles/typography.ts
  packages/mobile/src/utils/theme.ts
Labels: size/L

#972 Adds Follows You indicator to react native profile header
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/S

#973 Fix missing space in ios:update-signing-cert script
  packages/mobile/package.json
Labels: size/XS

#974 [AUD-1596] Add AccountSettingsScreen
  packages/mobile/src/assets/images/emojis/lock.png
  packages/mobile/src/assets/images/iconMail.svg
  packages/mobile/src/assets/images/iconSignOut.svg
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsItem.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsRow.tsx
  packages/mobile/src/screens/settings-screen/SettingsRowDescription.tsx
  packages/mobile/src/screens/settings-screen/index.ts
Labels: size/L

#976 [AUD-1597] Add AboutScreen
  packages/mobile/src/assets/images/appIcon.png
  packages/mobile/src/assets/images/iconCareers.svg
  packages/mobile/src/assets/images/iconContact.svg
  packages/mobile/src/assets/images/iconDiscord.svg
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/core/Link.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/text/Text.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingRowLabel.tsx
  packages/mobile/src/screens/settings-screen/SettingsRow.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/index.ts
  packages/mobile/src/styles/typography.ts
Labels: size/L

#975 [AUD-1476] Collection Tile
  packages/mobile/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/IconButton.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileTrackList.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileArt.tsx
  packages/mobile/src/components/lineup-tile/LineupTileBannerIcon.tsx
  packages/mobile/src/components/lineup-tile/LineupTileCoSign.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/LineupTileRankIcon.tsx
  packages/mobile/src/components/lineup-tile/LineupTileRoot.tsx
  packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/index.ts
  packages/mobile/src/components/lineup-tile/styles.ts
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/components/track-tile/TrackTile.tsx
  packages/mobile/src/components/track-tile/index.ts
  packages/mobile/src/components/track-tile/types.ts
  packages/mobile/src/types/gesture.ts
  packages/web/src/components/track/mobile/PlaylistTile.tsx
Labels: size/XXL

#979 Style fixes for artist popover width
  packages/web/src/components/artist/ArtistCard.module.css
Labels: size/XS

#980 [AUD-1602] Implement appearance setting
  packages/mobile/src/App.tsx
  packages/mobile/src/components/theme/ThemeContext.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/mobile/src/styles/makeStyles.ts
  packages/mobile/src/utils/theme.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/ui/theme/actions.ts
  packages/web/src/common/store/ui/theme/reducer.ts
  packages/web/src/common/store/ui/theme/selectors.ts
  packages/web/src/common/store/ui/theme/types.ts
  packages/web/src/components/play-bar/desktop/PlayBar.js
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/not-found-page/NotFoundPage.tsx
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/store/application/ui/theme/sagas.ts
  packages/web/src/store/application/ui/theme/selectors.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#905 [AUD-1413] Allow for controlled AnimatedButtonProvider
  packages/mobile/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
Labels: size/M

#977 [AUD-734] Add mobile Favorites Page
  packages/mobile/package-lock.json
  packages/mobile/src/assets/images/iconFilter.svg
  packages/mobile/src/assets/images/pbIconPause.svg
  packages/mobile/src/components/core/SearchInput.tsx
  packages/mobile/src/components/track-list/TablePlayButton.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/components/track-list/index.ts
  packages/mobile/src/components/track-list/types.ts
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/EmptyTab.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/FilterInput.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/favorites-screen/types.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/saved-page/actions.js
  packages/web/src/common/store/pages/saved-page/lineups/tracks/actions.js
  packages/web/src/common/store/pages/saved-page/lineups/tracks/reducer.js
  packages/web/src/common/store/pages/saved-page/reducer.js
  packages/web/src/common/store/pages/saved-page/selectors.ts
  packages/web/src/common/store/pages/saved-page/types.ts
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/saved-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/saved-page/store/sagas.js
  packages/web/src/pages/saved-page/store/selectors.ts
  packages/web/src/store/lineup/lineupForRoute.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/XXL

#984 [AUD-974] Add SearchResultsScreen
  packages/mobile/src/App.tsx
  packages/mobile/src/components/app-navigator/AppNavigator.tsx
  packages/mobile/src/components/app-navigator/TopBar.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/core/SearchInput.tsx
  packages/mobile/src/components/loading-spinner/LoadingSpinner.tsx
  packages/mobile/src/components/search/content/MoreContainer.tsx
  packages/mobile/src/components/signon/FirstFollows.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/search-results-screen/EmptyResults.tsx
  packages/mobile/src/screens/search-results-screen/SearchResultsScreen.tsx
  packages/mobile/src/screens/search-results-screen/index.ts
  packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
  packages/mobile/src/screens/search-screen/Fade.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/mobile/src/screens/search-screen/SearchHistory.tsx
  packages/mobile/src/screens/search-screen/SearchResults.tsx
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
  packages/mobile/src/screens/search-screen/SearchScreenLegacy.tsx
  packages/mobile/src/screens/search-screen/TopBar.tsx
  packages/mobile/src/screens/search-screen/content/EmptySearch.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/search-screen/content/SearchSectionHeader.tsx
  packages/mobile/src/screens/search-screen/content/SeeMoreResultsButton.tsx
  packages/mobile/src/screens/search-screen/index.ts
  packages/mobile/src/screens/search-screen/utils.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/search-results/actions.ts
  packages/web/src/common/store/pages/search-results/lineup/tracks/actions.js
  packages/web/src/common/store/pages/search-results/lineup/tracks/reducer.ts
  packages/web/src/common/store/pages/search-results/reducer.ts
  packages/web/src/common/store/pages/search-results/selectors.ts
  packages/web/src/common/store/pages/search-results/types.ts
  packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
  packages/web/src/pages/search-page/SearchPageProvider.js
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
  packages/web/src/pages/search-page/helpers.ts
  packages/web/src/pages/search-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/search-page/store/sagas.js
  packages/web/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/store/lineup/lineupForRoute.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/XL

#988 [AUD-1526] Improve ProfileScreen styles
  packages/mobile/src/App.tsx
  packages/mobile/src/components/app-navigator/navigationThemes.ts
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/EmptyCard.tsx
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/L

#983 Connect now playing action bar
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/web/src/common/store/cast/sagas.ts
  packages/web/src/common/store/cast/selectors.ts
  packages/web/src/common/store/cast/slice.ts
  packages/web/src/common/store/index.ts
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/now-playing/components/ActionsBar.tsx
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
  packages/web/src/pages/settings-page/store/actions.ts
  packages/web/src/pages/settings-page/store/reducer.ts
  packages/web/src/pages/settings-page/store/sagas.ts
  packages/web/src/pages/settings-page/store/selectors.ts
  packages/web/src/pages/settings-page/store/types.ts
Labels: size/L

#986 [AUD-1413] Connect repeat and shuffle native buttons
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/store/audio/actions.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/queue/selectors.ts
  packages/web/src/common/store/queue/slice.ts
  packages/web/src/common/store/queue/types.ts
  packages/web/src/components/lineup/hooks.ts
  packages/web/src/components/nav/desktop/NavColumn.js
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.js
  packages/web/src/components/play-bar/mobile/PlayBar.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/deleted-page/DeletedPageProvider.tsx
  packages/web/src/pages/feed-page/FeedPageProvider.js
  packages/web/src/pages/history-page/HistoryPageProvider.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/saved-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/search-page/SearchPageProvider.js
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/pages/trending-page/TrendingPageProvider.js
  packages/web/src/pages/upload-page/UploadPage.js
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/services/native-mobile-interface/queue.ts
  packages/web/src/store/lineup/sagas.js
  packages/web/src/store/lineup/store.test.js
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/queue/mobileSagas.ts
  packages/web/src/store/queue/sagas.ts
  packages/web/src/store/queue/store.test.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#982 Poll identity for cognito existence
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/audio-rewards-page/store/store.test.ts
  packages/web/src/services/audius-backend/Cognito.ts
Labels: size/M

#989 Add native navigation flag for stage template
  packages/mobile/.env.stage.tmpl
Labels: size/XS

#981 [AUD-1598] Add NotificationSettingsScreen
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/core/Switch.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/EmailFrequencyControlRow.tsx
  packages/mobile/src/screens/settings-screen/NotificationRow.tsx
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingRowLabel.tsx
  packages/mobile/src/screens/settings-screen/SettingsRowContent.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/index.ts
  packages/mobile/src/styles/types.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/settings/actions.ts
  packages/web/src/common/store/pages/settings/reducer.ts
  packages/web/src/common/store/pages/settings/selectors.ts
  packages/web/src/common/store/pages/settings/types.ts
  packages/web/src/components/browser-push-confirmation-modal/BrowserPushConfirmationModal.tsx
  packages/web/src/components/menu/NotificationMenu.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/settings-page/components/desktop/NotificationSettings.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/NotificationsSettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
  packages/web/src/pages/settings-page/store/errorSagas.ts
  packages/web/src/pages/settings-page/store/mobileSagas.ts
  packages/web/src/pages/settings-page/store/sagas.ts
  packages/web/src/pages/settings-page/store/selectors.ts
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
  packages/web/src/store/account/sagas.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#990 [AUD-1611] Fix airplay and cast for native
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/web/src/common/store/cast/sagas.ts
  packages/web/src/common/store/cast/slice.ts
  packages/web/src/common/store/index.ts
  packages/web/src/store/configureStore.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#992 [AUD-1610] Fix ProfileReposts lineup
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/web/src/common/store/pages/profile/actions.ts
  packages/web/src/common/store/pages/profile/lineups/feed/actions.ts
  packages/web/src/common/store/pages/profile/lineups/feed/reducer.ts
Labels: size/L

#991 [AUD-972] Add $AUDIO screen skeleton
  packages/mobile/src/assets/images/iconCrown.svg
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/audio-screen/index.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/L
