Repository AudiusProject/audius-client, pull requests merged in 2022-01, with the labels that each got.

#717 0.24.38
  package-lock.json
  package.json
Labels: size/XS

#719 Consume libs 1.2.42
  package-lock.json
  package.json
Labels: size/XS

#720 [AUD-1088] Fix CardLineup layout when only 1-2 cards present
  src/components/card/mobile/Card.module.css
  src/components/card/mobile/Card.tsx
  src/containers/lineup/CardLineup.module.css
  src/containers/lineup/CardLineup.tsx
Labels: size/M

#723 Force libs make request on 404 of resource with optimistic api client
  package-lock.json
  package.json
  src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/XS

#724 Add Solana staging config
  .env/.env.stage
Labels: size/S

#722 [AUD-1034] Fix default CoverPhoto tiling
  src/components/general/CoverPhoto.tsx
Labels: size/M

#725 Refactor CoverPhotoProps to use Nullable util type
  src/components/general/CoverPhoto.tsx
Labels: size/XS

#726 Add misc rewards fixes
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/containers/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/XS

#727 Refactor IconButton to use button element
  src/components/general/IconButton.module.css
  src/components/general/IconButton.tsx
Labels: size/S

#729 [AUD-1194] DynamicImage in react native
  src/common/assets/image/1x1-transparent.png
  src/common/assets/image/imageBlank2x.png
  src/common/assets/image/imageCoverPhotoBlank.jpg
  src/common/assets/image/imageProfilePicEmpty2X.png
  src/common/hooks/useImageSize.ts
  src/components/artist/ArtistCard.js
  src/components/artist/ArtistChip.js
  src/components/artist/ArtistPopover.tsx
  src/components/card/UserCard.js
  src/components/card/desktop/Card.tsx
  src/components/card/desktop/CollectionArtCard.tsx
  src/components/card/desktop/UserArtCard.tsx
  src/components/card/mobile/Card.tsx
  src/components/collection/desktop/CollectionHeader.js
  src/components/collection/mobile/CollectionHeader.js
  src/components/create-playlist/CreatePlaylistModal.js
  src/components/dynamic-image/DynamicImage.tsx
  src/components/general/CoverPhoto.tsx
  src/components/general/ProfilePicture.js
  src/components/remix-settings-modal/RemixSettingsModal.tsx
  src/components/search/SearchBarResult.js
  src/components/track/EditTrackModal.js
  src/components/track/GiantArtwork.tsx
  src/components/track/desktop/Artwork.tsx
  src/components/track/desktop/stats/ProfileImage.tsx
  src/components/track/mobile/TrackListItem.tsx
  src/components/track/mobile/TrackTileArt.tsx
  src/components/upload/UploadArtwork.js
  src/containers/add-to-playlist/desktop/AddToPlaylistModal.tsx
  src/containers/artist-dashboard-page/components/ArtistProfile.js
  src/containers/artist-recommendations/ArtistRecommendations.tsx
  src/containers/deleted-page/components/desktop/DeletedPage.tsx
  src/containers/deleted-page/components/mobile/DeletedPage.tsx
  src/containers/edit-playlist/mobile/EditPlaylistPage.tsx
  src/containers/first-upload-modal/FirstUploadModal.tsx
  src/containers/nav/desktop/CurrentlyPlaying.tsx
  src/containers/nav/desktop/NavColumn.js
  src/containers/notification/components/TrackContent.tsx
  src/containers/notification/components/desktop/UserHeader.tsx
  src/containers/notification/components/mobile/ConnectedUserHeader.tsx
  src/containers/now-playing/NowPlaying.tsx
  src/containers/play-bar/desktop/components/PlayingTrackInfo.tsx
  src/containers/play-bar/mobile/PlayBar.tsx
  src/containers/profile-page/components/mobile/ProfileHeader.tsx
  src/containers/remix/ConnectedRemixCard.tsx
  src/containers/search-bar/SearchBar.js
  src/containers/settings-page/components/desktop/VerificationModal.tsx
  src/containers/settings-page/components/mobile/AccountSettingsPage.tsx
  src/containers/settings-page/components/mobile/SettingsPage.tsx
  src/containers/settings-page/components/mobile/VerificationPage.tsx
  src/containers/sign-on/components/ProfileForm.js
  src/containers/track-page/components/mobile/TrackHeader.tsx
  src/containers/upload-page/components/FinishPage.js
  src/containers/visualizer/VisualizerProvider.tsx
  src/hooks/useImageSize.test.tsx
  src/services/AudiusBackend.js
Labels: size/L

#728 [AUD-1187] Replace kebab-menu with share-user-button
  src/containers/profile-page/components/mobile/ProfilePage.module.css
  src/containers/profile-page/components/mobile/ProfilePage.tsx
  src/containers/profile-page/components/mobile/ShareUserButton.module.css
  src/containers/profile-page/components/mobile/ShareUserButton.tsx
Labels: size/L

#716 Updates SPL Audio UI
  .env/.env.prod
  package-lock.json
  package.json
  src/assets/fonts/emojis/warning.png
  src/assets/styles/emoji.css
  src/assets/styles/type.css
  src/common/hooks/useLocalStorage.ts
  src/common/models/User.ts
  src/common/models/Wallet.ts
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/common/store/pages/token-dashboard/selectors.ts
  src/common/store/pages/token-dashboard/slice.ts
  src/common/store/pages/token-dashboard/types.ts
  src/common/store/wallet/slice.ts
  src/containers/audio-rewards-page/WalletModal.module.css
  src/containers/audio-rewards-page/WalletModal.tsx
  src/containers/audio-rewards-page/components/ClickableAddress.module.css
  src/containers/audio-rewards-page/components/ClickableAddress.tsx
  src/containers/audio-rewards-page/components/MigrationModalBody.module.css
  src/containers/audio-rewards-page/components/MigrationModalBody.tsx
  src/containers/audio-rewards-page/components/PurpleBox.tsx
  src/containers/audio-rewards-page/components/ReceiveBody.module.css
  src/containers/audio-rewards-page/components/ReceiveBody.tsx
  src/containers/audio-rewards-page/components/SendInputBody.module.css
  src/containers/audio-rewards-page/components/SendInputBody.tsx
  src/hooks/useLocalStorage.ts
  src/services/AudiusBackend.js
  src/services/LocalStorage.ts
  src/services/wallet-client/WalletClient.ts
  src/store/token-dashboard/sagas.ts
  src/store/wallet/sagas.ts
Labels: size/XL

#721 [AUD-1148] Get visualizer working with 3 album art colors
  package-lock.json
  package.json
  src/common/store/cache/tracks/sagas.js
  src/containers/nav/desktop/CurrentlyPlaying.tsx
  src/containers/nav/desktop/NavColumn.js
  src/containers/now-playing/NowPlaying.tsx
  src/containers/visualizer/VisualizerProvider.tsx
  src/store/application/ui/average-color/slice.ts
  src/utils/imageProcessingUtil.js
  src/utils/visualizer/shaders/visualizer-1.frag
  src/utils/visualizer/visualizer-1.js
  src/workers/averageRgb.worker.js
  src/workers/dominantColor.worker.js
Labels: size/L

#732 Remove resumable upload flag
  src/services/AudiusBackend.js
Labels: size/XS

#730 [AUD-1189] Challenges config tweaks
  src/common/models/AudioRewards.ts
  src/containers/audio-rewards-page/ChallengeRewardsTile.tsx
  src/containers/audio-rewards-page/config.tsx
Labels: size/S

#731 [AUD-1196] Add icons/styling options to ActionDrawer
  src/components/action-drawer/ActionDrawer.module.css
  src/components/action-drawer/ActionDrawer.tsx
Labels: size/M

#733 Remove extraneous ActionIcon import
  src/components/action-drawer/ActionDrawer.tsx
Labels: size/XS

#735 [AUD-1198] Add and connect ShareModal
  src/common/store/index.ts
  src/common/store/ui/modals/slice.ts
  src/common/store/ui/share-modal/sagas.ts
  src/common/store/ui/share-modal/slice.ts
  src/common/store/ui/share-modal/types.ts
  src/containers/Modals.tsx
  src/containers/share-modal/ShareModal.tsx
  src/containers/share-modal/components/ShareDrawer.module.css
  src/containers/share-modal/components/ShareDrawer.tsx
  src/store/sagas.js
Labels: size/L

#734 Update audio balances on /audio page
  src/services/wallet-client/WalletClient.ts
  src/store/wallet/sagas.ts
Labels: size/M

#738 Optimistic challenge complete and balance update
  src/common/store/pages/audio-rewards/slice.ts
  src/common/store/wallet/slice.ts
  src/common/utils/wallet.ts
  src/containers/audio-rewards-page/components/ClaimRewardButton.tsx
Labels: size/M

#737 [AUD-1218] Add copy-link-to-track action to ShareDrawer
  src/common/store/ui/share-modal/sagas.ts
  src/common/store/ui/share-modal/selectors.ts
  src/common/store/ui/share-modal/slice.ts
  src/common/store/ui/share-modal/types.ts
  src/components/action-drawer/ActionDrawer.tsx
  src/containers/share-modal/components/ShareDrawer.module.css
  src/containers/share-modal/components/ShareDrawer.tsx
Labels: size/M

#740 Don't crash if Userbank creation fails
  src/services/AudiusBackend.js
Labels: size/S

#741 [AUD-1227] Create userbanks if needed
  src/services/audius-backend/waudio.ts
  src/store/account/sagas.js
Labels: size/M

#743 Consume libs 1.2.49
  package-lock.json
  package.json
Labels: size/XS

#739 [AUD-1220] Add share-to-twitter action to ShareDrawer
  src/common/models/Analytics.ts
  src/containers/share-modal/components/ShareDrawer.module.css
  src/containers/share-modal/components/ShareDrawer.tsx
Labels: size/M

#742 [AUD-1221]: Add share-to-titktok action to ShareDrawer
  src/containers/share-modal/components/ShareDrawer.tsx
Labels: size/L

#744 [AUD-1224] Add DesktopShareModal
  src/containers/share-modal/components/DesktopShareModal.module.css
  src/containers/share-modal/components/DesktopShareModal.tsx
  src/containers/share-modal/components/ShareDrawer.tsx
  src/containers/share-modal/messages.ts
Labels: size/L

#745 [AUD-1230] Combine desktop and mobile share-modal
  src/components/action-drawer/ActionDrawer.tsx
  src/containers/share-modal/ShareModal.tsx
  src/containers/share-modal/components/IconTikTok.tsx
  src/containers/share-modal/components/ShareDialog.module.css
  src/containers/share-modal/components/ShareDialog.tsx
  src/containers/share-modal/components/ShareDrawer.module.css
  src/containers/share-modal/components/ShareDrawer.tsx
  src/containers/share-modal/messages.ts
  src/containers/share-modal/types.ts
Labels: size/L

#746 Consume libs breaking change from Challenge => Rewards
  src/services/AudiusBackend.js
Labels: size/XS

#749 Fix ActionButton margins
  src/containers/track-page/components/mobile/ActionButtonRow.module.css
Labels: size/XS

#750 Add small rewards UI fixes
  src/components/image-selection/PropTypes.js
  src/containers/audio-rewards-page/RewardsTile.module.css
  src/containers/audio-rewards-page/components/modals/ChallengeRewards.module.css
Labels: size/S

#748 [AUD-1247]: Open ShareModal when sharing tracks
  package-lock.json
  src/components/action-drawer/ActionDrawer.module.css
  src/components/track/GiantTrackTile.js
  src/components/track/desktop/ConnectedTrackTile.tsx
  src/components/track/desktop/TrackTile.tsx
  src/components/track/mobile/BottomButtons.tsx
  src/components/track/mobile/ConnectedTrackTile.tsx
  src/containers/now-playing/NowPlaying.tsx
  src/containers/now-playing/components/ActionsBar.tsx
  src/containers/share-modal/ShareModal.tsx
  src/containers/share-modal/components/ShareDialog.module.css
  src/containers/share-modal/components/ShareDialog.tsx
  src/containers/share-modal/components/ShareDrawer.tsx
  src/containers/share-modal/types.ts
  src/containers/track-page/TrackPageProvider.tsx
  src/containers/track-page/components/mobile/ActionButtonRow.tsx
  src/containers/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#751 [AUD-1249]: Remove share-to-tiktok from overflow-menus
  src/common/store/ui/mobile-overflow-menu/types.ts
  src/components/track/GiantTrackTile.js
  src/components/track/desktop/ConnectedTrackTile.tsx
  src/components/track/desktop/TrackListItem.tsx
  src/components/track/mobile/ConnectedTrackListItem.tsx
  src/components/track/mobile/ConnectedTrackTile.tsx
  src/containers/menu/TrackMenu.tsx
  src/containers/now-playing/NowPlaying.tsx
  src/containers/share-modal/components/ShareDrawer.tsx
  src/containers/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  src/containers/track-overflow-modal/components/MobileOverflowModal.tsx
  src/containers/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#755 Add 'Claim Your Reward' button text for undisbursed challenges
  src/containers/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/XS

#752 Add rewards config and userbank check
  .env/.env.prod
  package-lock.json
  package.json
  src/containers/audio-rewards-page/config.tsx
  src/services/audius-backend/waudio.ts
Labels: size/M

#757 [AUD-1249] Remove extranous shareTikTok references
  src/components/tracks-table/TableOptionsButton.js
  src/containers/now-playing/NowPlaying.tsx
Labels: size/XS

#758 Add scripts start:dev:mobile and start:dev:mobile:cloud
  package.json
Labels: size/XS

#754 [AUD-1240] Extend ShareModal to share profiles
  src/common/store/ui/share-modal/sagas.ts
  src/common/store/ui/share-modal/selectors.ts
  src/common/store/ui/share-modal/slice.ts
  src/common/store/ui/share-modal/types.ts
  src/components/general/StatBanner.js
  src/components/track/desktop/ConnectedTrackTile.tsx
  src/components/track/mobile/ConnectedTrackTile.tsx
  src/containers/now-playing/NowPlaying.tsx
  src/containers/profile-page/ProfilePageProvider.tsx
  src/containers/profile-page/components/mobile/ShareUserButton.tsx
  src/containers/share-modal/ShareModal.tsx
  src/containers/share-modal/components/ShareDialog.tsx
  src/containers/share-modal/components/ShareDrawer.tsx
  src/containers/share-modal/messages.ts
  src/containers/share-modal/types.ts
  src/containers/track-page/TrackPageProvider.tsx
Labels: size/L

#760 Fix challenge descriptions
  src/containers/audio-rewards-page/config.tsx
Labels: size/M

#759 Fix earn audio balance for total balance
  src/containers/nav/desktop/NavAudio.tsx
Labels: bug, size/XS

#761 [AUD-1258] Share collections with ShareMenu
  src/common/models/Analytics.ts
  src/common/store/ui/share-modal/sagas.ts
  src/common/store/ui/share-modal/types.ts
  src/components/track/desktop/ConnectedPlaylistTile.tsx
  src/components/track/mobile/ConnectedPlaylistTile.tsx
  src/containers/collection-page/CollectionPageProvider.tsx
  src/containers/share-modal/ShareModal.tsx
  src/containers/share-modal/components/ShareDialog.module.css
  src/containers/share-modal/components/ShareDialog.tsx
  src/containers/share-modal/components/ShareDrawer.module.css
  src/containers/share-modal/messages.ts
  src/containers/share-modal/utils.ts
Labels: size/L

#768 [AUD-1247] Improve matrix mode, styles, fix share button
  src/common/store/ui/share-modal/selectors.ts
  src/components/actions-tab/ActionsTab.js
  src/components/collection/desktop/CollectionHeader.js
  src/components/collection/mobile/CollectionHeader.js
  src/components/track/desktop/TrackListItem.tsx
  src/components/track/mobile/ConnectedPlaylistTile.tsx
  src/components/track/mobile/ConnectedTrackListItem.tsx
  src/components/track/mobile/ConnectedTrackTile.tsx
  src/containers/now-playing/NowPlaying.tsx
  src/containers/now-playing/components/ActionsBar.tsx
  src/containers/share-modal/ShareModal.tsx
  src/containers/share-modal/components/IconTikTok.tsx
  src/containers/share-modal/components/ShareDialog.module.css
  src/containers/share-modal/components/ShareDialog.tsx
  src/containers/share-modal/components/ShareDrawer.module.css
  src/containers/share-modal/components/ShareDrawer.tsx
  src/containers/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#766 Add no tier icon to nav audio balance
  src/containers/nav/desktop/NavAudio.tsx
Labels: size/XS

#767 Claim Button already disbursed success
  src/common/models/AudioRewards.ts
  src/containers/audio-rewards-page/components/ClaimRewardButton.tsx
Labels: size/XS

#765 Adds Cognito Flow URL Mobile Saga
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/store/mobileSagas.ts
  src/services/audius-backend/Cognito.ts
Labels: size/L

#764 Allows native mobile to navigate and retain history
  src/store/routing/mobileSagas.ts
Labels: size/XS

#774 Fix rewards progress exceeds total steps
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: bug, size/XS

#771 Add new Modal for Cognito Flow
  src/common/store/ui/modals/slice.ts
  src/pages/audio-rewards-page/components/modals/CognitoModal.tsx
  src/pages/audio-rewards-page/components/modals/RewardsModals.tsx
Labels: size/L

#773 Add sagas for claiming challenge rewards
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/L

#775 Decouple HCaptcha modal from Rewards
  src/pages/audio-rewards-page/components/modals/HCaptchaModal.tsx
Labels: size/S

#778 [AUD-1280] Move models from src to common
  src/common/models/Client.ts
  src/common/models/Collection.ts
  src/common/models/Lineup.ts
  src/common/models/OS.ts
  src/common/models/OnChain.ts
  src/common/models/Playable.ts
  src/common/models/Theme.ts
  src/components/app-redirect-popover/AppRedirectListener.tsx
  src/components/lineup/LineupProvider.tsx
  src/components/lineup/hooks.ts
  src/components/nav/Navigator.tsx
  src/components/nav/desktop/NavHeader.js
  src/pages/App.js
  src/pages/Modals.tsx
  src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  src/pages/audio-rewards-page/components/ExplainerTile.tsx
  src/pages/audio-rewards-page/components/modals/TrendingRewards.tsx
  src/pages/collection-page/store/types.ts
  src/pages/deleted-page/DeletedPage.tsx
  src/pages/deleted-page/DeletedPageProvider.tsx
  src/pages/deleted-page/components/desktop/DeletedPage.tsx
  src/pages/deleted-page/components/mobile/DeletedPage.tsx
  src/pages/feed-page/store/types.ts
  src/pages/feed-page/types.ts
  src/pages/history-page/store/types.ts
  src/pages/profile-page/components/desktop/ProfilePage.tsx
  src/pages/profile-page/components/mobile/ProfilePage.tsx
  src/pages/profile-page/store/types.ts
  src/pages/requires-update/RequiresUpdate.tsx
  src/pages/saved-page/components/desktop/SavedPage.tsx
  src/pages/saved-page/components/mobile/SavedPage.tsx
  src/pages/saved-page/store/types.ts
  src/pages/search-page/SearchPage.tsx
  src/pages/search-page/components/mobile/SearchPageContent.tsx
  src/pages/search-page/store/types.ts
  src/pages/settings-page/SettingsPageProvider.tsx
  src/pages/settings-page/components/desktop/SettingsPage.tsx
  src/pages/settings-page/components/mobile/SettingsPage.tsx
  src/pages/something-wrong/SomethingWrong.tsx
  src/pages/track-page/components/desktop/TrackPage.tsx
  src/pages/track-page/components/mobile/TrackPage.tsx
  src/pages/track-page/store/types.ts
  src/pages/trending-page/store/lineups/trending/selectors.ts
  src/pages/trending-page/store/types.ts
  src/pages/trending-page/types.ts
  src/services/audius-api-client/types.ts
  src/services/download-app/DownloadApp.test.ts
  src/services/download-app/DownloadApp.ts
  src/services/native-mobile-interface/theme.ts
  src/store/analytics/providers/segment.ts
  src/store/application/ui/theme/actions.ts
  src/store/application/ui/theme/sagas.ts
  src/store/application/ui/theme/types.ts
  src/store/lineup/selectors.ts
  src/utils/clientUtil.ts
  src/utils/theme/theme.ts
Labels: size/L

#782 Enable using the cognito modal in the saga
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/S

#784 [AUD-1215] Add typed-redux-sagas
  package-lock.json
  package.json
  src/common/store/ui/share-modal/sagas.ts
Labels: size/S

#783 Remove ClaimRewardButton from ChallengeRewards, use sagas instead
  src/pages/audio-rewards-page/components/ClaimRewardButton.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: size/L

#772 Add profile completion optimistic update and refresh user challenges periodically
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/hooks.ts
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/L

#780 [AUD-1182 Visualizer performance
  src/components/nav/desktop/CurrentlyPlaying.module.css
  src/components/nav/desktop/NavColumn.js
  src/pages/visualizer/Visualizer.tsx
  src/pages/visualizer/VisualizerProvider.module.css
  src/pages/visualizer/VisualizerProvider.tsx
  src/pages/visualizer/store/slice.ts
  src/utils/visualizer/visualizer-1.js
  src/workers/dominantColor.worker.js
Labels: size/XL

#786 [AUD-1295] Fix broken staging build
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: size/XS

#788 0.24.39
  package-lock.json
  package.json
Labels: size/XS

#787 Add notifications with rewards ff
  src/common/services/remote-config/feature-flags.ts
  src/components/notification/store/sagas.ts
  src/services/AudiusBackend.js
Labels: size/M

#792 Libs 1.2.52
  package-lock.json
  package.json
Labels: size/XS

#790 Update profile bio logic
  src/components/profile-progress/store/selectors.js
  src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/XS

#791 Only override current step count if challenge is not complete
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: size/XS

#789 Consume AAO config in client for local dev
  scripts/configureLocalEnv.js
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/M

#793 Don't reset UserChallenges state on polling refresh
  src/common/store/pages/audio-rewards/slice.ts
Labels: size/XS

#794 Cancel reward claim on modal close
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/M

#795 Consume UserChallenge amount instead of using config
  src/common/models/AudioRewards.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/config.tsx
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/M

#797 [AUD-1281] Add config for referred challenge for notifications
  src/common/models/AudioRewards.ts
  src/pages/audio-rewards-page/config.tsx
Labels: size/S

#798 Use native challenge rewards drawer
  src/pages/audio-rewards-page/components/modals/RewardsModals.tsx
Labels: size/XS

#796 Ms visualizer bug fixes
  src/common/store/cache/tracks/sagas.js
  src/components/nav/desktop/CurrentlyPlaying.module.css
  src/components/nav/desktop/CurrentlyPlaying.tsx
  src/components/nav/desktop/NavColumn.js
  src/pages/visualizer/VisualizerProvider.tsx
  src/utils/visualizer/visualizer-1.js
Labels: size/M

#801 Bump libs to v1.2.54
  package-lock.json
  package.json
Labels: size/XS

#802 Update react-router-dom types
  package-lock.json
  package.json
Labels: size/XS

#803 Update modal slice for mobile edit collectibles drawer
  src/common/store/ui/modals/slice.ts
  src/components/collectibles/components/CollectiblesPage.tsx
Labels: size/M

#808 [AUD-1328] Reward amounts should be numbers
  src/common/models/AudioRewards.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/config.tsx
  src/services/audius-api-client/AudiusAPIClient.ts
Labels: bug, size/M

#806 [AUD-1305] Move what is audio tile to bottom of rewards page
  src/pages/audio-rewards-page/AudioRewardsPage.module.css
  src/pages/audio-rewards-page/AudioRewardsPage.tsx
  src/pages/audio-rewards-page/Tiers.module.css
  src/pages/audio-rewards-page/components/ExplainerTile.module.css
Labels: size/S

#810 Npm install => npm ci
  .circleci/config.yml
Labels: size/XS

#809 Lazy-load sign-in page, reinstate analyzeBundle
  package-lock.json
  package.json
  scripts/analyzeBundle.js
  src/pages/App.js
Labels: size/S

#807 Consolidate stepCountOverride into useOptimisticUserChallenge hook
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/hooks.ts
Labels: size/L

#811 Upgrade redux-saga from v0.16.0 to v1.1.3
  package-lock.json
  package.json
  src/common/store/cache/collections/utils/retrieveCollections.ts
  src/common/store/cache/tracks/utils/retrieveTracks.ts
  src/components/first-upload-modal/store/sagas.ts
  src/components/notification/store/mobileSagas.ts
  src/components/notification/store/sagas.ts
  src/pages/deactivate-account-page/store/sagas.ts
  src/pages/profile-page/store/sagas.js
  src/pages/sign-on/store/sagas.js
  src/store/backend/sagas.js
  src/store/configureStore.js
  src/store/confirmer/sagas.js
  src/store/lineup/sagas.js
  src/store/lineup/store.test.js
  src/store/player/sagas.ts
  src/store/queue/sagas.ts
  src/store/queue/store.test.js
  src/store/reachability/sagas.ts
  src/store/sagas.js
  src/store/social/tracks/sagas.ts
  src/store/social/users/sagas.ts
  src/store/wallet/sagas.ts
  src/utils/sagaHelpers.js
Labels: size/L

#804 [AUD-1282] Forgot password helper for Desktop
  src/assets/img/iconQuestionMark.svg
  src/pages/sign-on/components/desktop/EmailPage.module.css
  src/pages/sign-on/components/desktop/EmailPage.tsx
  src/pages/sign-on/components/desktop/ForgotPasswordHelper.module.css
  src/pages/sign-on/components/desktop/ForgotPasswordHelper.tsx
  src/pages/sign-on/components/desktop/MetaMaskOption.module.css
  src/pages/sign-on/components/desktop/SignInPage.js
  src/pages/sign-on/components/desktop/SignInPage.module.css
  src/pages/sign-on/components/desktop/SignInPage.tsx
  src/pages/sign-on/components/desktop/SignOnPage.tsx
Labels: size/XL

#813 [AUD-1353] Improve a11y to simplify probers e2e flows
  package-lock.json
  package.json
  src/components/browser-push-confirmation-modal/BrowserPushConfirmationModal.tsx
  src/components/data-entry/Input.js
  src/components/lineup/LineupProvider.tsx
  src/components/play-bar/PlayButton.js
  src/components/sign-on/EnterPassword.tsx
  src/pages/App.module.css
  src/pages/sign-on/components/LoadingPage.js
  src/pages/sign-on/components/ProfileForm.js
  src/pages/sign-on/components/desktop/AppCTA.tsx
  src/pages/sign-on/components/desktop/EmailPage.tsx
  src/pages/sign-on/components/desktop/FollowPage.tsx
  src/pages/sign-on/components/desktop/PasswordPage.js
  src/pages/sign-on/components/desktop/ProfilePage.js
  src/pages/sign-on/components/desktop/SignInPage.tsx
  src/pages/sign-on/components/desktop/StartPlatformPage.js
  src/pages/sign-on/components/desktop/TwitterOverlay.js
  src/pages/sign-on/components/desktop/TwitterOverlay.module.css
  src/pages/sign-on/components/mobile/PasswordPage.tsx
  src/pages/trending-page/components/desktop/TrendingPageContent.tsx
Labels: size/L

#812 [AUD-1288] Show reward claimed toast when identity claims on user's behalf
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/components/reward-claimed-toast/RewardClaimedToast.module.css
  src/components/reward-claimed-toast/RewardClaimedToast.tsx
  src/components/toast/mobile/ToastLinkContent.tsx
  src/pages/App.js
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/store/sagas.ts
  src/utils/sagaPollingDaemons.ts
Labels: size/L

#814 Fix bug where notifs weren't being fetched on refocus
  src/components/notification/store/sagas.ts
Labels: size/XS

#815 [AUD-1357] Fix hash routing config
  .env/.env.dev
  .env/.env.prod
  .env/.env.stage
  public/index.html
  scripts/configureLocalEnv.js
  src/pages/search-page/helpers.ts
  src/utils/history.js
  src/utils/route.ts
  src/utils/sagaPollingDaemons.ts
Labels: size/S

#816 Handle referrals-verified challenge
  src/common/models/AudioRewards.ts
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/config.tsx
Labels: size/M

#817 Add feature flag enable_spl_audio
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/feature-flags.ts
  src/common/services/remote-config/types.ts
  src/pages/audio-rewards-page/WalletModal.tsx
  src/pages/audio-rewards-page/components/ReceiveBody.tsx
  src/pages/audio-rewards-page/components/SendInputBody.tsx
  src/store/wallet/sagas.ts
Labels: size/M

#805 Add tests for claim rewards saga
  src/__mocks__/AudiusBackend.js
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
  src/services/audius-api-client/AudiusAPIClient.ts
  src/services/remote-config/__mocks__/remote-config-instance.ts
Labels: size/XL

#819 Fix challenges flashing
  src/common/services/remote-config/feature-flags.ts
Labels: bug, size/XS

#818 [AUD-1331] Move Explore page state to common pages part of the store
  src/common/store/index.ts
  src/common/store/pages/explore/actions.ts
  src/common/store/pages/explore/exploreCollections/sagas.ts
  src/common/store/pages/explore/exploreCollections/selectors.ts
  src/common/store/pages/explore/exploreCollections/slice.ts
  src/common/store/pages/explore/reducer.ts
  src/common/store/pages/explore/sagas.ts
  src/common/store/pages/explore/selectors.ts
  src/common/store/pages/explore/types.ts
  src/components/nav/mobile/ConnectedBottomBar.tsx
  src/pages/App.js
  src/pages/explore-page/ExploreCollectionsPage.tsx
  src/pages/explore-page/ExploreCollectionsPageProvider.tsx
  src/pages/explore-page/ExplorePageProvider.tsx
  src/pages/explore-page/collections.ts
  src/pages/explore-page/components/desktop/ExplorePage.tsx
  src/pages/explore-page/components/mobile/ExplorePage.tsx
  src/store/reducers.js
  src/store/sagas.js
  src/store/types.ts
Labels: size/M

#820 [AUD-1363] Add a11y fixes for e2e flows
  package-lock.json
  package.json
  src/components/alt-button/RepostButton.module.css
  src/components/alt-button/RepostButton.tsx
  src/components/data-entry/DropdownInput.js
  src/components/data-entry/FormTile.js
  src/components/image-selection/ImageSelectionButton.js
  src/components/track/GiantTrackTile.js
  src/components/track/GiantTrackTile.module.css
  src/components/track/desktop/TrackTile.tsx
  src/components/upload/Dropzone.js
  src/components/upload/Dropzone.module.css
  src/components/upload/ProgressBar.js
  src/pages/upload-page/components/FinishPage.js
  src/pages/upload-page/components/FinishPage.module.css
Labels: size/L

#824 0.24.40
  package-lock.json
  package.json
Labels: size/XS

#777 Use typed getCognitoSignature
  src/pages/audio-rewards-page/components/modals/CognitoModal.tsx
  src/pages/check-page/CheckPage.tsx
  src/services/AudiusBackend.js
Labels: size/M

#823 Fix height of mobile reward challenges
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/RewardsTile.module.css
Labels: size/XS

#821 Add new UI for verified challenges
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/PurpleBox.module.css
  src/pages/audio-rewards-page/components/PurpleBox.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/config.tsx
  src/pages/audio-rewards-page/hooks.ts
Labels: size/L

#826 [AUD-1385] Fix challenge complete state
  src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: size/S

#829 Check for social links being a string rather than truthy
  src/services/AudiusBackend.js
Labels: bug, size/S

#825 Move feed slice to common
  src/common/store/index.ts
  src/common/store/pages/feed/actions.js
  src/common/store/pages/feed/lineup/actions.js
  src/common/store/pages/feed/lineup/reducer.js
  src/common/store/pages/feed/reducer.js
  src/common/store/pages/feed/selectors.ts
  src/common/store/pages/feed/types.ts
  src/common/utils/selectorHelpers.ts
  src/components/track/desktop/stats/Stats.tsx
  src/pages/feed-page/FeedPageProvider.js
  src/pages/feed-page/components/desktop/FeedPageContent.tsx
  src/pages/feed-page/components/mobile/FeedPageContent.tsx
  src/pages/feed-page/store/lineups/feed/sagas.ts
  src/pages/feed-page/store/sagas.ts
  src/pages/feed-page/store/selectors.js
  src/pages/search-page/store/selectors.js
  src/pages/trending-page/store/selectors.js
  src/store/lineup/lineupForRoute.js
  src/store/queue/sagas.ts
  src/store/reducers.js
  src/store/types.ts
Labels: size/L

#831 Fix ui jumping on copy referral
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: bug, size/XS

#828 Add 'Claim Rewards' button in nav
  src/common/services/remote-config/defaults.ts
  src/common/services/remote-config/types.ts
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/components/nav/desktop/NavAudio.module.css
  src/components/nav/desktop/NavAudio.tsx
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
Labels: size/L

#833 Add type defs for App
  src/app.tsx
  src/pages/App.d.ts
Labels: size/S

#836 [AUD-1402] Move toast logic to redux
  src/common/store/errors/actions.ts
  src/common/store/errors/sagas.ts
  src/common/store/index.ts
  src/common/store/ui/toast/sagas.ts
  src/common/store/ui/toast/slice.ts
  src/components/toast/ToastContext.tsx
  src/store/sagas.js
Labels: size/L

#838 Fetch balance refresh on reward notification
  src/components/notification/store/sagas.ts
Labels: bug, size/S

#837 Update invite friends link to use copylink
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: bug, size/XS

#827 [AUD-1346] Add already claimed check and client side retries
  src/common/models/AudioRewards.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
Labels: size/M

#834 [AUD-985] Consolidate error flow
  package-lock.json
  package.json
  src/app.tsx
  src/common/store/errors/actions.ts
  src/common/store/errors/sagas.ts
  src/common/utils/errorSagas.ts
  src/pages/App.js
  src/pages/AppErrorBoundary.tsx
  src/pages/something-wrong/SomethingWrong.tsx
Labels: size/L

#835 [AUD-985] Prevent full refresh on error
  src/pages/something-wrong/SomethingWrong.tsx
Labels: size/S

#840 Fix app test
  src/pages/App.test.tsx
Labels: size/S

#832 Remove delay logic, show bubble whenever a challenge is undisbursed but completed
  src/common/store/pages/audio-rewards/selectors.ts
  src/common/store/pages/audio-rewards/slice.ts
  src/components/nav/desktop/NavAudio.tsx
  src/pages/audio-rewards-page/hooks.ts
  src/pages/audio-rewards-page/store/sagas.ts
  src/pages/audio-rewards-page/store/store.test.ts
Labels: size/L

#841 Refactor Rewards Sagas
  src/pages/audio-rewards-page/store/sagas.ts
Labels: size/L

#842 Convert craco config to typescript
  craco.config.js
  craco.config.ts
  package-lock.json
  package.json
Labels: size/M

#844 Consume Libs 1.2.61
  package-lock.json
  package.json
Labels: size/XS

#843 [AUD-1405] Treeshake lodash
  .env/.env.bundle
  craco.config.ts
  package-lock.json
  package.json
  scripts/analyzeBundle.js
Labels: size/M

#845 [AUD-1406] Replace moment-tz with dayjs
  package-lock.json
  package.json
  src/services/AudiusBackend.js
Labels: size/S

#846 [AUD-1124] Move average artwork to common
  src/common/store/average-color/slice.ts
  src/common/store/cache/tracks/sagas.js
  src/common/store/index.ts
  src/components/nav/desktop/NavColumn.js
  src/components/now-playing/NowPlaying.tsx
  src/pages/visualizer/VisualizerProvider.tsx
  src/store/reducers.js
  src/store/types.ts
Labels: size/M
