Repository AudiusProject/audius-client, pull requests merged in 2022-06, with the labels that each got.

#1393 Fix badges stacked up
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
Labels: size/XS

#1394 [PAY-275] Add native tipping notifications
  packages/mobile/src/components/core/AudioText.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/notifications-screen/Notification/NotificationText.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationTile.tsx
  packages/mobile/src/screens/notifications-screen/Notification/TipText.tsx
  packages/mobile/src/screens/notifications-screen/Notification/UserNameLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/index.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/exploding_head.json
  packages/mobile/src/screens/notifications-screen/Reaction/fire.json
  packages/mobile/src/screens/notifications-screen/Reaction/index.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/partying_face.json
  packages/mobile/src/screens/notifications-screen/Reaction/smiling_face_with_heart_eyes.json
  packages/mobile/src/screens/tip-artist-screen/TipHeader.tsx
  packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
  packages/mobile/src/screens/user-list-screen/Tip.tsx
  packages/web/src/common/store/notifications/types.ts
Labels: size/L

#1395 [PAY-280] Add TipReceivedNotification
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/index.ts
  packages/mobile/src/screens/notifications-screen/Reaction/reactions.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/L

#1388 Display latest tip support state optimistically
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistChipTips.tsx
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/components/tipping/support/SupportingList.tsx
  packages/web/src/components/tipping/support/TopSupporters.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/pages/supporting-page/sagas.ts
  packages/web/src/pages/top-supporters-page/sagas.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/tipping/storageUtils.ts
Labels: size/XL

#1398 [PAY-286][PAY-291] Fix cover photo stretch and displayname overflow in supporting tiles
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/components/tipping/support/SupportingTile.tsx
Labels: size/S

#1397 [PAY-281] Fetch current user tip amount if not already loaded when tipping
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/M

#1399 Upgrade to @audius/sdk
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/LocalStorage.ts
  packages/web/src/services/audius-backend/AudiusLibsLazyLoader.ts
Labels: size/M

#1405 [PAY-121] Remove legacy user-list-modal
  packages/web/src/common/store/pages/profile/selectors.ts
  packages/web/src/common/store/pages/profile/types.ts
  packages/web/src/components/artist/UserListModal.module.css
  packages/web/src/components/artist/UserListModal.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx
  packages/web/src/store/application/ui/userListModal/sagas.ts
Labels: size/L

#1402 [PAY-268 PAY-270 PAY-271] Fix announcement formatting, scroll, and spacing
  packages/mobile/src/screens/notifications-screen/Notification/NotificationTile.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/UserNameLink.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/AnnouncementNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
Labels: size/L

#1401 Fix Snapchat browser going to GA
  packages/web/scripts/workers-site/index.js
Labels: bug, size/XS

#1404 Update scrollbar in UserListModal
  packages/web/src/components/user-list-modal/components/UserListModal.module.css
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
Labels: bug, size/M

#1396 Add feed tip tile on mobile
  packages/mobile/src/assets/images/iconClose.svg
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/mobile/src/components/feed-tip-tile/constants.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/message/handleMessage.ts
  packages/mobile/src/message/handlers/tipping.ts
  packages/mobile/src/message/types.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTileSkeleton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupportersList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ViewAllSupportingTile.tsx
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/SupportingInfo.tsx
  packages/mobile/src/screens/user-list-screen/Tip.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
  packages/mobile/src/store/tipping/storageUtils.ts
  packages/web/src/common/models/Tipping.ts
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
  packages/web/src/components/artist/ArtistChipTips.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/services/native-mobile-interface/tipping.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/store/tipping/mobileSagas.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/tipping/storageUtils.ts
  packages/web/src/utils/constants.ts
Labels: size/XXL

#1409 Update mobile package lock
  packages/mobile/package-lock.json
Labels: size/XS

#1411 Add error message helper
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/utils/error.ts
Labels: size/M

#1412 [PAY-224] Dismiss Popover when navigating away
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/artist/ArtistCardCover.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/artist/ArtistSupporting.tsx
Labels: size/M

#1407 Add mobile profile top supporters
  packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileHeaderV2.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
  packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
Labels: size/L

#1413 [PAY-292] Adjust Supporting tile gradient
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/components/tipping/support/SupportingTile.tsx
Labels: bug, size/S

#1416 Fix border radius on profile mutuals tile
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
Labels: size/XS

#1418 [PAY-307][PAY-226][PAY-310][PAY-249] Hotfixes for Mutuals Tile
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
Labels: bug, size/S

#1419 [PAY-276] Add touch target for entire list modal row
  packages/web/src/components/artist/ArtistChip.tsx
Labels: size/XS

#1417 [PAY-311] Add transition for text and icon color in profile tiles
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
Labels: size/XS

#1420 [PAY-312] Add hover purple text
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
Labels: size/XS

#1422 [PAY-308] Don't scroll user list popovers
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/user-list/components/UserList.tsx
Labels: size/S

#1408 Add response mode param to Oauth
  packages/web/src/common/models/Analytics.ts
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/M

#1423 [PAY-295] Left align socials on sidebar, always collapse if bio or socials present
  packages/web/src/hooks/useCollapse.ts
  packages/web/src/pages/profile-page/components/SocialLink.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
Labels: size/M

#1424 [PAY-316] Fix follow button font size and misc other QA
  packages/web/src/components/stat-banner/StatBanner.js
  packages/web/src/components/stat-banner/StatBanner.module.css
  packages/web/src/components/user-list-modal/components/UserListModal.module.css
Labels: size/S

#1430 [C-571] Update Artist Popover positioning and badge height
  packages/web/src/components/tracks-table/TracksTable.module.css
Labels: size/XS

#1433 [PAY-320] Use correct number for total followee follow count
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
Labels: size/S

#1432 C-570 Update vertical tooltip styles to avoid arrow overlap
  packages/web/src/components/tooltip/Tooltip.module.css
Labels: size/XS

#1434 Use correct number for total followee follow count
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
Labels: size/S

#1425 Return profile picture in OAuth response
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/S

#1428 Udpate profile support and mutuals tiles and and content transitions
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
Labels: size/S

#1435 [PAY-317][PAY-321] Fix tooltip, +N tile in mutuals tile
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.module.css
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
Labels: bug, size/M

#1439 Bump stems to 0.3.37 in web client
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1438 [PAY-295][PAY-319] Fix sidebar / bio issues
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/hooks/useSize.ts
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
Labels: size/L

#1437 [PAY-315] Fix mutuals profile pics loading
  packages/web/src/common/store/cache/users/sagas.js
Labels: size/M

#1440 [PAY-323] Don't dismiss modal when clicking the follow button
  packages/web/src/components/follow-button/FollowButton.js
  packages/web/src/components/user-list/components/UserList.tsx
Labels: bug, size/S

#1441 [PAY-323] Stop immediate propagation on follow button click
  packages/web/src/components/follow-button/FollowButton.js
Labels: bug, size/XS

#1427 Hide profile top supporters on mobile if none
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
Labels: size/XS

#1431 [PAY-277] Fix spacing between rank and audio amount
  packages/web/src/components/artist/ArtistChip.module.css
  packages/web/src/components/artist/ArtistChipTips.tsx
Labels: size/S

#1447 Only apply onClickOutside when visible
  packages/stems/package.json
  packages/stems/src/components/Modal/Modal.tsx
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/hooks/useClickOutside.ts
Labels: size/S

#1429 [PAY-302] Update tipping analytics for web and mobile
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
  packages/mobile/src/screens/profile-screen/TipArtistButton.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/web/src/common/models/Analytics.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/store/tipping/sagas.ts
Labels: size/L

#1445 [PAY-278] Render empty container when artist supporting is loading
  packages/web/src/components/artist/ArtistSupporting.module.css
  packages/web/src/components/artist/ArtistSupporting.tsx
Labels: size/XS

#1449 Upgrade stems to 0.3.38
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1450 [C-576] Fix NotificationUsersScreen title, large list
  packages/mobile/src/screens/notifications-screen/routeUtil.ts
  packages/mobile/src/screens/user-list-screen/NotificationUsersScreen.tsx
Labels: size/XS

#1451 Stop propagation on follow button in artist card
  packages/web/src/components/artist/ArtistCard.tsx
Labels: size/XS

#1444 [C-556] Add commonPasswordCheck to lazy load the commonPasswordList
  packages/web/src/components/sign-on/EnterPassword.tsx
  packages/web/src/pages/sign-on/components/desktop/PasswordPage.js
  packages/web/src/pages/sign-on/components/mobile/PasswordPage.tsx
  packages/web/src/utils/commonPasswordCheck.ts
  packages/web/src/utils/passwordListLazyLoader.ts
Labels: size/XL

#1406 [CON-111] check is_available flag
  packages/web/package-lock.json
  packages/web/src/common/models/Track.ts
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/services/audius-api-client/ResponseAdapter.ts
  packages/web/src/services/audius-api-client/types.ts
Labels: size/S

#1415 [PAY-287] Add prompt to become top or first supporter
  packages/mobile/src/screens/tip-artist-screen/BecomeFirstSupporter.tsx
  packages/mobile/src/screens/tip-artist-screen/BecomeTopSupporter.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/TipArtistModal.tsx
  packages/web/src/common/models/User.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/hooks/useGetFirstOrTopSupporter.ts
  packages/web/src/services/audius-api-client/types.ts
  packages/web/src/services/audius-backend/Tipping.ts
  packages/web/src/store/tipping/sagas.ts
Labels: size/XL

#1410 [AUD-1404] Remove persistent cache
  packages/web/package-lock.json
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/pages/settings-page/store/mobileSagas.ts
  packages/web/src/utils/clientUtil.ts
  packages/web/src/utils/persistentCache.ts
  packages/web/tsconfig.json
Labels: size/L

#1443 [PAY-324] Add +N UI on mobile profile picture list component
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ViewAllSupportingTile.tsx
Labels: size/L

#1426 [PAY-296] Show display name in top supporters modal / drawer from feed
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.module.css
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
Labels: size/M

#1457 Fix bad import and use
  packages/web/src/store/backend/sagas.js
Labels: size/XS

#1452 [PAY-325] Fix user profile picture list extra logic and consolidate profile tiles
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.tsx
  packages/web/src/components/notification/Notification/utils.ts
  packages/web/src/components/profile-page-nav-section-title/ProfilePageNavSectionTitle.module.css
  packages/web/src/components/profile-page-nav-section-title/ProfilePageNavSectionTitle.tsx
  packages/web/src/components/profile-picture-list-tile/ProfilePictureListTile.module.css
  packages/web/src/components/profile-picture-list-tile/ProfilePictureListTile.tsx
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/components/tipping/support/SupportingList.tsx
  packages/web/src/components/tipping/support/TopSupporters.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
Labels: size/L

#1453 Keep profile picture shape the same for legacy prof pics in Oauth response
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/XS

#1456 [C-364, C-374, C-430, C-435] Antd package update
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/artist/ArtistPopover.module.css
  packages/web/src/components/co-sign/CoSign.module.css
  packages/web/src/components/co-sign/CoSign.tsx
  packages/web/src/components/data-entry/DropdownInput.js
  packages/web/src/components/data-entry/DropdownInput.module.css
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/components/navigation/Dropdown.module.css
  packages/web/src/components/play-bar/VolumeBar.module.css
  packages/web/src/components/profile-progress/components/ProfileCompletionTooltip.js
  packages/web/src/components/profile-progress/components/ProfileCompletionTooltip.module.css
  packages/web/src/components/search/SearchBar.js
  packages/web/src/components/search/SearchBar.module.css
  packages/web/src/components/search/SearchBarResult.module.css
  packages/web/src/components/tooltip/Tooltip.js
  packages/web/src/components/tooltip/Tooltip.module.css
  packages/web/src/components/tooltip/Tooltip.tsx
  packages/web/src/components/tooltip/types.ts
  packages/web/src/components/tracks-table/TracksTable.js
  packages/web/src/components/tracks-table/TracksTable.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
  packages/web/src/utils/theme/theme.ts
Labels: size/XL

#1460 [C-591] Upgrade stems react to v17
  packages/stems/.eslintrc.js
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/components/Button/Button.stories.tsx
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/IconButton/IconButton.stories.tsx
  packages/stems/src/components/IconButton/IconButton.tsx
  packages/stems/src/components/IconButton/types.ts
  packages/stems/src/components/Icons/1-Icons.stories.tsx
  packages/stems/src/components/Icons/BgWave.stories.tsx
  packages/stems/src/components/Modal/Modal.stories.tsx
  packages/stems/src/components/Modal/Modal.tsx
  packages/stems/src/components/Modal/ModalContent.stories.tsx
  packages/stems/src/components/Modal/ModalContent.tsx
  packages/stems/src/components/Modal/ModalFooter.stories.tsx
  packages/stems/src/components/Modal/ModalFooter.tsx
  packages/stems/src/components/Modal/ModalHeader.stories.tsx
  packages/stems/src/components/Modal/ModalHeader.tsx
  packages/stems/src/components/Modal/types.ts
  packages/stems/src/components/Popup/Popup.stories.tsx
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/components/PopupMenu/PopupMenu.stories.tsx
  packages/stems/src/components/PopupMenu/PopupMenu.tsx
  packages/stems/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/stems/src/components/ProgressBar/ProgressBar.tsx
  packages/stems/src/components/Scrollbar/Scrollbar.stories.tsx
  packages/stems/src/components/Scrollbar/Scrollbar.tsx
  packages/stems/src/components/Scrubber/Scrubber.stories.tsx
  packages/stems/src/components/Scrubber/Scrubber.tsx
  packages/stems/src/components/Scrubber/Slider.tsx
  packages/stems/src/components/Scrubber/hooks.ts
  packages/stems/src/components/SegmentedControl/SegmentedControl.stories.tsx
  packages/stems/src/components/SegmentedControl/SegmentedControl.tsx
  packages/stems/src/components/TokenValueInput/TokenValueInput.tsx
  packages/stems/src/components/TokenValueSlider/TokenValueSlider.tsx
  packages/stems/tsconfig.json
Labels: size/L

#1459 Cherry pick Hotfix: comment out icons on modal titles
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
Labels: size/S

#1461 [PAY-228][PAY-300][PAY-301] Various "Send a Tip" Modal Bugfixes
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/store/tipping/sagas.ts
Labels: bug, size/L

#1463 Bump stems to v0.3.39
  packages/stems/package-lock.json
  packages/stems/package.json
Labels: size/XS

#1400 [PAY-283][PAY-284] Integrate Tipping Notifications on Web and Mobile
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/reactions.tsx
  packages/web/src/common/hooks/useUIAudio.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
  packages/web/src/common/store/ui/reactions/slice.ts
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/TipReactionNotification.tsx
  packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notification/TipSentNotification.tsx
  packages/web/src/components/notification/Notification/TopSupporterNotification.tsx
  packages/web/src/components/notification/Notification/TopSupportingNotification.tsx
  packages/web/src/components/notification/Notification/components/Reaction/index.tsx
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/store/sagas.ts
Labels: size/XL

#1464 Consume Stems v0.3.39
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1466 [PAY-303] Native Mobile QA
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterAndSupportingNotificationContent.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
Labels: size/L

#1467 Stems: Fix for modals not reopening after close
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/hooks/useClickOutside.ts
Labels: size/XS

#1468 Consume stems v0.3.40
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1471 [PAY-330][PAY-334][PAY-341][PAY-343][PAY-335] Misc Mobile QA Fixes
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileHeaderV2.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SocialLink.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/TipArtistButton.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
  packages/mobile/src/screens/tip-artist-screen/BecomeTopSupporter.tsx
  packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.module.css
Labels: size/M

#1472 [PAY-339] [PAY-327][PAY-326] [PAY-274] Fix some QA issues
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistSupporting.module.css
  packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
  packages/web/src/store/tipping/sagas.ts
Labels: size/M

#1474 [PAY-346][PAY-345][PAY-347][PAY-337] Additional mobile tipping QA
  packages/mobile/src/assets/images/iconDonate.svg
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
Labels: size/M

#1475 [PAY-332][PAY-328][PAY-266][PAY-306][PAY-338] Fix mobile QA issues
  packages/mobile/package-lock.json
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SocialsAndSites.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ViewAllSupportingTile.tsx
  packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/SupportingInfo.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/web/package-lock.json
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/common/store/user-list/selectors.ts
  packages/web/src/components/user-list/UserList.tsx
Labels: size/L

#1477 [C-596] Fix small notifications bugs
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/web/src/common/store/notifications/reducer.ts
Labels: size/S

#1476 [C-558] Add FeatureFlagOverrideModal
  packages/web/src/common/hooks/useFeatureFlag.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.module.css
  packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
  packages/web/src/components/feature-flag-override-modal/index.ts
  packages/web/src/hooks/useRemoteConfig.ts
  packages/web/src/pages/Modals.tsx
  packages/web/src/utils/zIndex.ts
Labels: size/L

#1480 v1.1.9
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1484 Fix mutuals user list title
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
Labels: size/XS

#1485 [PAY-342][PAY-344] Fix user list modal issues
  packages/web/src/components/user-list/UserList.tsx
Labels: size/S

#1487 Add feature flag helper for flag overrides
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/pages/audio-rewards-page/components/ReceiveBody.tsx
  packages/web/src/pages/audio-rewards-page/components/SendInputBody.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/sign-on/store/sagas.js
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/remote-config/featureFlagHelpers.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/L

#1488 C-599 Update dev-mode based on query param
  packages/web/src/components/dev-mode-manager/DevModeManager.tsx
  packages/web/src/pages/App.js
Labels: size/S

#1481 [PAY-356] Add fetchTwitterHandle action, update TwitterButton
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/components/core/Link.tsx
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationTwitterButton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/index.ts
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/web/package-lock.json
  packages/web/src/common/store/cache/users/actions.js
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/notification/Notification/MilestoneNotification.tsx
  packages/web/src/pages/profile-page/sagas.js
Labels: size/L

#1489 [PAY-101] $AUDIO Modal for VIP tiers goes to wrong page
  packages/web/src/components/user-badges/TierExplainerModal.tsx
Labels: size/XS

#1482 [PAY-279] Add tipping twitter button
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/web/src/common/models/Analytics.ts
Labels: size/L

#1478 [PAY-350] Web: Supporting Tile Redesign
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/components/tipping/support/SupportingList.module.css
  packages/web/src/components/tipping/support/SupportingList.tsx
  packages/web/src/components/tipping/support/SupportingTile.module.css
  packages/web/src/components/tipping/support/SupportingTile.tsx
  packages/web/src/components/tipping/support/TopSupporters.module.css
  packages/web/src/components/tipping/support/TopSupporters.tsx
Labels: size/L

#1483 [PAY-350][PAY-355] Mobile: Supporting Tile Redesign
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ViewAllSupportingTile.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/L

#1490 [PAY-364] Web: Use static white for the +N in UserProfilePictureList
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.module.css
Labels: bug, size/XS

#1492 Close user list modals when a nested popover triggers a navigation
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
  packages/web/src/components/notification/Notification/components/UserNameLink.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/components/UserList.tsx
Labels: size/M

#1495 [PAY-366][PAY-357] Fix more mobile QA issues
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
Labels: size/M

#1499 Don't propagate clicks inside modals to other content
  packages/stems/src/components/Modal/Modal.tsx
Labels: size/S

#1500 Stems: Upgrade to v1.1.10
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1497 [PAY-373] Mobile: Fix default cover art on supporting tile
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
Labels: bug, size/XS

#1496 [PAY-377] Mobile: Fix single supporting tile margins
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
Labels: bug, size/XS

#1501 Pass entity through to milestone notif
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
Labels: size/XS

#1507 Fix fill on arrow and download icons
  packages/stems/src/assets/icons/iconArrow.svg
  packages/stems/src/assets/icons/iconDownload.svg
Labels: size/XS

#1509 Bump Stems to 1.1.11
  packages/stems/package-lock.json
  packages/stems/package.json
Labels: size/XS

#1503 [PAY-353] Mobile: Update user list items
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/Tip.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
Labels: bug, size/S

#1502 [PAY-354] Mobile: Make Top Supporters a larger touch target
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
Labels: bug, size/S

#1504 [PAY-374] Mobile: Resolve clash between Artist Recs UI and Tip Audio button
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileHeaderV2.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
Labels: size/S

#1510 Add root npm install to init command
  package.json
Labels: size/XS

#1511 [PAY-330] Add icons back to web userlist modals
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
Labels: size/S

#1513 [PAY-378] [PAY-368] Address Reaction Perf
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Labels: size/L

#1515 Update pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS

#1514 [PAY-369][PAY-349][PAY-331][PAY-376][PAY-389][PAY-219] Fix more tipping QA issues
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationText.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SocialLink.tsx
  packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
Labels: size/L

#1517 v1.1.11
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1520 Fix redirect links
  packages/web/src/pages/App.js
  packages/web/src/root.tsx
  packages/web/src/utils/route.ts
Labels: size/M

#1523 Mobile: Remove unnecessary padding from send tip button
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
Labels: bug, size/XS

#1524 [PAY-380] Web: Make trophy icon neutral fill
  packages/web/src/components/tipping/support/TopSupporters.module.css
Labels: bug, size/XS

#1530 Update deprecated xcode images
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#1525 Fix challenge confetti re-render
  packages/web/src/common/store/pages/audio-rewards/selectors.ts
  packages/web/src/common/store/pages/audio-rewards/slice.ts
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/audio-rewards-page/store/store.test.ts
Labels: size/L

#1528 [PAY-398] Improve reaction perf when drawer closed
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
Labels: size/XS

#1532 [C-618] Remove unnecessary calls to onClickArtistName in ArtistChip to avoid multiple route changes
  packages/web/src/components/artist/ArtistChip.tsx
Labels: size/XS

#1526 [PAY-391] Redirect user to signup page when click on tip audio button and not signed in
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
Labels: size/S

#1529 [C-613] Add general slider component to fix volume bar
  packages/web/src/components/play-bar/VolumeBar.js
  packages/web/src/components/play-bar/VolumeBar.module.css
  packages/web/src/components/play-bar/slider/Slider.module.css
  packages/web/src/components/play-bar/slider/Slider.tsx
  packages/web/src/components/play-bar/slider/index.ts
  packages/web/src/components/play-bar/slider/types.ts
Labels: size/L

#1518 [PAY-379] Fix Twitter icon in referral challenge modal in matrix mode
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
Labels: size/XS

#1534 Add package.json and tar file to web-build ci command
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@web-jobs.yml
Labels: size/S

#1536 Update build command to add build tar file to the build folder
  .circleci/src/commands/@web-commands.yml
Labels: size/XS

#1537 [C-410] Automate creation of release branch
  .circleci/config.yml
  .circleci/src/jobs/@root-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  .circleci/src/workflows/root.yml
  .circleci/src/workflows/web.yml
Labels: size/L
