Repository AudiusProject/audius-client, pull requests merged in 2022-07, with the labels that each got.

#1543 Deploy Storybook to stems.audius.co upon Stems commit to main
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/jobs/@stems-jobs.yml
  .circleci/src/workflows/stems.yml
  packages/stems/.gitignore
  packages/stems/scripts/workers-site/.cargo-ok
  packages/stems/scripts/workers-site/.gitignore
  packages/stems/scripts/workers-site/index.js
  packages/stems/scripts/workers-site/package-lock.json
  packages/stems/scripts/workers-site/package.json
  packages/stems/wrangler.toml
Labels: size/L

#1527 [PAY-397] Add v2 user-list headers
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileMutualsButton.tsx
  packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
  packages/mobile/src/screens/user-list-screen/MutualsScreen.tsx
  packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx
  packages/mobile/src/screens/user-list-screen/SupportingUsersScreen.tsx
  packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
Labels: size/L

#1541 [PAY-383] Created Web UI For First Tip Challenge
  packages/web/src/assets/fonts/emojis/money-mouth-face.png
  packages/web/src/assets/styles/emoji.css
  packages/web/src/common/models/AudioRewards.ts
  packages/web/src/common/services/remote-config/defaults.ts
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/M

#1546 [C-601] Add missing mobile profile badges
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/S

#1538 [PAY-304] Adjust feed tip tile for small screens
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/Button/hooks.ts
  packages/stems/src/hooks/useMediaQueryListener.ts
  packages/stems/src/index.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
Labels: size/L

#1547 Bump stems
  packages/stems/package-lock.json
  packages/stems/package.json
Labels: size/XS

#1548 Consume stems 1.1.12 in web
  packages/stems/package-lock.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1549 [C-656] Fix z-index for collection header overflow menu popup
  packages/stems/src/components/Popup/Popup.module.css
Labels: size/XS

#1542 [C-649] Use lerna bootstrap
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  README.md
  package.json
  packages/mobile/README.md
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/content/ChallengeReward.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/README.md
  packages/web/craco.config.ts
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#1551 [C-650] Update dropdown input styles for dark mode
  packages/web/src/components/data-entry/DropdownInput.module.css
Labels: size/XS

#1550 Move CP of tar file to s3 step
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@web-jobs.yml
  package-lock.json
  packages/web/package-lock.json
Labels: size/S

#1552 v1.1.12
  .circleci/config.yml
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1553 Rework CI to use lerna bootstrap and singular npm install
  .circleci/config.yml
  .circleci/src/commands/@commands.yml
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@stems-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/L

#1554 [PAY-384] Created First Tip Challenge Mobile UI
  packages/mobile/src/assets/images/emojis/money-mouth-face.png
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/content/ChallengeReward.tsx
  packages/mobile/src/utils/challenges.tsx
Labels: size/M

#1508 Upgrade CRA and webpack to v5
  .circleci/config.yml
  .circleci/src/jobs/@web-jobs.yml
  package-lock.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/web/.eslintrc.js
  packages/web/craco.config.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/audio/AudioStream.test.js
  packages/web/src/audio/AudioStream.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/AboutSettingsPage.tsx
  packages/web/src/store/analytics/providers/index.ts
  packages/web/src/types/css/css.d.ts
  packages/web/src/utils/visualizer/gl-vignette-background/index.js
  packages/web/src/utils/visualizer/visualizer-1.js
  packages/web/tsconfig.json
Labels: size/L

#1555 [C-400] Add logic for mobile app minimum version
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/hooks/useUpdateRequired.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/update-required-screen/UpdateRequiredScreen.tsx
  packages/web/src/common/services/remote-config/defaults.ts
  packages/web/src/common/services/remote-config/types.ts
Labels: size/L

#1559 [C-654] Improve web modal usage and performance
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/components/Modal/Modal.tsx
  packages/stems/src/components/Modal/types.ts
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/components/ShareDialog.module.css
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/types.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/modals/AppModal.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/modals/useModalState.ts
Labels: size/L

#1560 [C-575] Fix sentry and dev warnings
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/nav/desktop/CurrentlyPlaying.tsx
  packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx
  packages/web/src/components/search/SearchBar.js
  packages/web/src/components/service-selection/SelectedServices.tsx
  packages/web/src/components/service-selection/index.ts
  packages/web/src/components/service-selection/utils.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/sign-on/store/actions.ts
  packages/web/src/pages/sign-on/store/errorSagas.ts
  packages/web/src/pages/upload-page/components/SelectPage.js
  packages/web/src/services/AudiusBackend.js
Labels: size/L

#1561 [C-581] Improve probers upload flow a11y
  packages/stems/src/components/Popup/Popup.tsx
  packages/web/src/components/loading-spinner/LoadingSpinner.tsx
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/components/upload/UploadArtwork.module.css
Labels: size/M

#1558 [PAY-405] Fixed Claim Rewards Pill To Respect Optimizely Config
  packages/web/src/components/nav/desktop/NavAudio.tsx
Labels: size/M

#1562 Fix various mobile types
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/M

#1564 [C-667] Fix desktop build on mac
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1565 [PAY-386] [PAY-387] Created Mobile + Web UIs for First Playlist Challenge
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/content/ChallengeReward.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/common/models/AudioRewards.ts
  packages/web/src/common/services/remote-config/defaults.ts
  packages/web/src/components/nav/desktop/NavAudio.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/M

#1566 Fix jitter
  packages/web/src/components/artist/ArtistSupporting.module.css
Labels: size/XS

#1572 Remove extra stylelint step in pre-commit
  packages/web/.hooks/pre-commit.json
Labels: size/XS

#1571 Fix sign-on action types
  packages/mobile/src/store/oauth/actions.ts
  packages/web/src/common/store/account/reducer.ts
  packages/web/src/pages/sign-on/SignOnProvider.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
  packages/web/src/pages/sign-on/components/mobile/ProfilePage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
  packages/web/src/pages/sign-on/store/actions.ts
Labels: size/L

#1570 [C-409] Add eslint-config-audius, use in packages
  package-lock.json
  package.json
  packages/eslint-config-audius/README.md
  packages/eslint-config-audius/package.json
  packages/eslint-config-audius/src/index.js
  packages/mobile/.eslintrc.js
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/stems/.eslintrc.js
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/components/TokenValueInput/TokenValueInput.tsx
  packages/web/.eslintrc.js
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XL

#1574 [PAY-415] Clicking tipping notifications goes to profile
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/useGoToProfile.ts
  packages/web/src/components/notification/Notification/TipReactionNotification.tsx
  packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notification/TipSentNotification.tsx
  packages/web/src/components/notification/Notification/TopSupporterNotification.tsx
  packages/web/src/components/notification/Notification/TopSupportingNotification.tsx
  packages/web/src/components/notification/Notification/useGoToProfile.ts
Labels: size/M

#1580 Fix solana phantom provider types
  packages/web/src/services/web3-modal/index.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/M

#1582 [PAY-414] Fix unsending reactions
  packages/web/src/common/store/ui/reactions/sagas.ts
Labels: size/XS

#1573 [PAY-399] Fix reaction notification selection bug
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Labels: size/L

#1575 Fix native milestone notification
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/utils.ts
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/content/AddTrackToPlaylist.tsx
  packages/mobile/src/screens/notifications-screen/content/TwitterShare.tsx
  packages/web/src/common/store/notifications/types.ts
Labels: size/M

#1576 [CON-234] Add write quorum feature flag
  packages/web/README.md
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/services/AudiusBackend.js
Labels: size/S

#1581 Fix sdk lazyload and upgrade to sdk 0.0.12
  package-lock.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/audius-backend/AudiusLibsLazyLoader.ts
Labels: size/S

#1585 Fix entity and solana types in web
  packages/web/src/components/notification/Notification/AddTrackToPlaylistNotification.tsx
  packages/web/src/components/notification/Notification/components/EntityLink.tsx
  packages/web/src/components/notification/Notification/utils.ts
  packages/web/src/services/web3-modal/index.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/S

#1587 [PAY-393] Fix active state animation on mobile SupportingTile
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
Labels: size/XS

#1590 [C678] Limit prod mobile builds to main & release branches
  .circleci/src/workflows/mobile.yml
Labels: size/XS

#1593 [PAY-423] Fix matrix-mode send-tip web styles
  packages/stems/src/components/TokenValueInput/TokenValueInput.module.css
  packages/stems/src/components/TokenValueInput/TokenValueInput.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Labels: size/M

#1596 [PAY-424] Remove search icon in user-lists
  packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
Labels: size/XS

#1591 [C-679] Fix Probers
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#1595 [C-677] Fix profile-screen icon hit-slop and color
  packages/mobile/src/components/core/IconButton.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/S

#1594 [PAY-422] Fix tip icon notification matrix color
  packages/common/package.json
  packages/web/src/components/notification/Notification/components/icons.module.css
Labels: size/S

#1597 Add main role
  packages/web/src/components/upload/ButtonUploadTrack.module.css
  packages/web/src/pages/App.js
Labels: size/M

#1599 [PAY-432] Freeze balance briefly after sending a tip
  packages/web/src/common/store/wallet/selectors.ts
  packages/web/src/common/store/wallet/slice.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/M

#1567 Change logout from sync to async due to SDK changes
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/sign-out/sagas.ts
  packages/web/src/components/nav/mobile/SignOut.tsx
  packages/web/src/utils/signOut.js
Labels: size/S

#1539 Update explore endpoints in libs to use v1
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/services/audius-backend/Explore.ts
Labels: size/M

#1604 Remove antd table shadow pseudoelements
  packages/web/src/components/tracks-table/TracksTable.module.css
Labels: size/XS

#1586 [PAY-425] Fix optimistic trophy icon for supporting
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/components/tipping/support/SupportingTile.module.css
Labels: bug, size/M

#1600 [PLAT-254] Remove is_creator usage
  packages/mobile/src/store/search/types.ts
  packages/web/src/common/models/User.ts
  packages/web/src/common/store/account/selectors.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/components/service-selection/store/sagas.ts
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/sign-on/components/mobile/PasswordPage.tsx
  packages/web/src/pages/upload-page/components/FinishPage.js
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/schemas/index.js
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/audius-api-client/types.ts
  packages/web/src/store/account/sagas.js
Labels: size/L

#1606 [C-694] Add DeactivateAccount setting for native
  packages/mobile/src/assets/images/emojis/door.png
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/deactivate-account-confirmation-drawer/DeactivateAccountConfirmationDrawer.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
Labels: size/L

#1601 Move TipProfilePic to top level ProfileInfo component
  packages/web/src/components/profile-info/ProfileInfo.module.css
  packages/web/src/components/profile-info/ProfileInfo.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/L

#1609 Revert "Update explore endpoints in libs to use v1 (#1539)"
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/services/audius-backend/Explore.ts
Labels: size/M

#1610 [C-411] Remove simplebar
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/notification/NotificationModal.module.css
  packages/web/src/components/notification/NotificationModal.tsx
  packages/web/src/components/notification/NotificationPanel.module.css
  packages/web/src/components/service-selection/ServiceSelectionModal.js
  packages/web/src/components/service-selection/ServiceSelectionModal.module.css
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.module.css
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.module.css
  packages/web/src/index.css
  packages/web/src/pages/audio-rewards-page/components/ErrorBody.module.css
  packages/web/src/pages/audio-rewards-page/components/ErrorBody.tsx
  packages/web/src/pages/sign-on/components/desktop/FollowPage.module.css
  packages/web/src/pages/sign-on/components/desktop/FollowPage.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOn.module.css
  packages/web/src/pages/trending-page/components/desktop/GenreSelectionModal.module.css
  packages/web/src/pages/trending-page/components/desktop/GenreSelectionModal.tsx
  packages/web/src/pages/upload-page/components/TracksPreview.js
  packages/web/src/pages/upload-page/components/TracksPreview.module.css
  packages/web/src/types/simplebar-react/index.d.ts
Labels: size/L

#1611 [C-697] Set border radius on TrackTile stats profile picture skeleton
  packages/web/src/components/track/desktop/stats/ProfileImage.module.css
  packages/web/src/components/track/desktop/stats/ProfileImage.tsx
Labels: size/XS

#1612 Bump ios version
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#1613 Update helpers.ts
  packages/mobile/src/utils/postMessage.ts
  packages/web/src/services/native-mobile-interface/helpers.ts
Labels: size/M

#1614 Prefer verified always
  packages/web/src/common/store/cache/reducer.js
Labels: size/XS

#1615 Bump iOS 1.1.22
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#1603 [C-635] Fix mobile publishing and add ui to indicate publishing to the user
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/store/search/types.ts
Labels: size/S

#1619 Fix style for tippers in feed tip tile
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
Labels: size/XS

#1620 [C-702] Fix canOpenUrl on android
  packages/mobile/android/app/src/main/AndroidManifest.xml
Labels: size/XS

#1622 [PAY-446] Show top supporters for logged out users
  packages/web/src/pages/profile-page/sagas.js
Labels: size/XS

#1623 [PAY-450] Dont show mutuals on owner's profile
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ExpandedSection.tsx
Labels: size/XS

#1624 [PAY-453] Update feed-tip-tile sender styles
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
Labels: size/S

#1626 [PAY-452] Fetch audio balance on audio/tip-screen
  packages/mobile/src/screens/app-screen/AppScreen.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
Labels: size/M

#1627 Fix rank tie logic
  packages/web/src/common/store/tipping/selectors.ts
Labels: size/XS

#1628 Fix feed-tip-tile receiver opacity
  packages/mobile/src/components/feed-tip-tile/PressableText.tsx
  packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
Labels: size/L

#1629 Close user-list when navigating to sign-in page
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
Labels: size/XS

#1630 Fix mobile lint based on tipping fixes
  packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/web/src/components/menu/CollectionMenu.tsx
Labels: size/S

#1631 Bump ios to 1.1.23
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#1632 Web/Mobile: Fix "maintenance" typo
  packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/pages/audio-rewards-page/components/MigrationModalBody.tsx
Labels: size/XS

#1636 Remove recaptcha
  packages/web/public/index.html
Labels: size/S

#1634 Add mobile skeleton shimmer animation
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/image-skeleton/ImageSkeleton.tsx
  packages/mobile/src/components/image-skeleton/index.ts
  packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
  packages/mobile/src/components/skeleton/Skeleton.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/L

#1635 [C-705] Fix mac desktop build
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1589 [PAY-406] Web: Add Coinbase Pay Button
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-addCrypto.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-addCrypto@2x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-addCrypto@3x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-addETH.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-addETH@2x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-addETH@3x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-buy.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-buy@2x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-buy@3x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-continue.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-continue@2x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-continue@3x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-generic-condensed.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-generic-condensed@2x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-generic-condensed@3x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-generic.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-generic@2x.png
  packages/web/src/assets/img/coinbase-pay/compact/button-cbPay-compact-generic@3x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-addCrypto.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-addCrypto@2x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-addCrypto@3x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-addETH.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-addETH@2x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-addETH@3x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-buy.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-buy@2x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-buy@3x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-continue.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-continue@2x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-continue@3x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-generic-condensed.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-generic-condensed@2x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-generic-condensed@3x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-generic.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-generic@2x.png
  packages/web/src/assets/img/coinbase-pay/normal/button-cbPay-normal-generic@3x.png
  packages/web/src/components/coinbase-pay-button/CoinbasePayButton.module.css
  packages/web/src/components/coinbase-pay-button/CoinbasePayButton.tsx
  packages/web/src/components/coinbase-pay-button/CoinbasePayButtonProvider.tsx
Labels: feature, size/L

#1637 [C-687] Update some colors and styles for matrix mode
  packages/web/src/components/tracks-table/TableDragHandle.js
  packages/web/src/components/tracks-table/TableDragHandle.module.css
  packages/web/src/components/tracks-table/TableFavoriteButton.js
  packages/web/src/components/tracks-table/TracksTable.module.css
Labels: size/M

#1638 [C-687] Update trending svgs to display properly in matrix mode
  packages/mobile/src/assets/images/iconAllTime.svg
  packages/mobile/src/assets/images/iconDay.svg
  packages/mobile/src/assets/images/iconMonth.svg
Labels: size/XS

#1639 [C-639] Update track list item title to display the deleted by artist text better
  packages/mobile/src/components/track-list/TrackListItem.tsx
Labels: size/M

#1640 Fix rate limit issue with sign-up on some devices
  packages/web/src/pages/sign-on/store/sagas.js
Labels: size/XS

#1642 [Flare-97]: sdk changes for isCreator sanity check
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1643 [C-707] Remove extra search bar from the search results page
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
Labels: size/XS

#1644 [C-708] Fix the table styles for sorted columns for dark mode and matrix mode
  packages/web/src/components/tracks-table/TracksTable.module.css
Labels: size/XS

#1645 [C-709] Fix native audio tier
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/XS

#1646 [C-584] Add others link to web notifications
  packages/web/src/components/notification/Notification/FavoriteNotification.tsx
  packages/web/src/components/notification/Notification/FollowNotification.tsx
  packages/web/src/components/notification/Notification/RepostNotification.tsx
  packages/web/src/components/notification/Notification/components/OthersLink.module.css
  packages/web/src/components/notification/Notification/components/OthersLink.tsx
  packages/web/src/components/notification/Notification/utils.ts
Labels: size/M

#1647 [C-710] Update the skeletons for the UserCard and the search bar results
  packages/web/src/components/card/UserCard.js
  packages/web/src/components/card/UserCard.module.css
  packages/web/src/components/search/SearchBarResult.module.css
Labels: size/S

#1648 [C-721] Fix notifications not loading past 20
  packages/web/src/components/notification/Notification/utils.ts
  packages/web/src/components/notification/store/sagas.ts
Labels: size/XS

#1557 Change OAuth user ids to hash ids
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/XS

#1652 Small update to the styling of user searchbar result skeletons
  packages/web/src/components/search/SearchBarResult.js
  packages/web/src/components/search/SearchBarResult.module.css
Labels: size/XS

#1653 [PAY-244][PAY-245] Update tip modal header and extract pill button
  packages/stems/src/components/Modal/ModalHeader.tsx
  packages/stems/src/components/Modal/types.ts
  packages/stems/src/components/PillButton/PillButton.module.css
  packages/stems/src/components/PillButton/PillButton.stories.tsx
  packages/stems/src/components/PillButton/PillButton.tsx
  packages/stems/src/components/PillButton/index.ts
  packages/stems/src/components/PillButton/types.ts
  packages/stems/src/index.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Labels: size/L

#1657 Consume stems 1.1.14 in web
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1658 Fix type errors caused by @audius/common migration
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/rollup.config.js
  packages/common/src/models/index.ts
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/L

#1660 Update artist popover profile picture skeleton to be round
  packages/web/src/components/artist/ArtistCardCover.module.css
  packages/web/src/components/artist/ArtistCardCover.tsx
Labels: size/XS

#1662 Bump libs to 0.0.22 in client
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS
