Repository AudiusProject/audius-client, pull requests merged in 2022-10, with the labels that each got.

#2041 [C-1207] Fix stem downloads
  packages/mobile/src/services/track-download.ts
Labels: size/XS

#2048 [C-1179] Fix edit-profile
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/web/src/common/store/profile/sagas.js
Labels: size/M

#2049 Add cypress prober videos to artifacts C-1011
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#2033 [C-850, C-950] Add AudioTransactionsPage and display test data in AudioTransactionsTable
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.module.css
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/components/audio-transactions-table/index.ts
  packages/web/src/components/test-table/TestTable.module.css
  packages/web/src/components/tracks-table/TracksTable.js
  packages/web/src/pages/App.js
  packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.module.css
  packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
  packages/web/src/pages/audio-transactions-page/index.ts
  packages/web/src/utils/route.ts
Labels: size/XL

#2045 [C-1062] Update loading states for favorites and collection page tables
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/S

#2028 [PAY-668] Set up premium content
  packages/common/src/models/Track.ts
  packages/common/src/schemas/index.ts
  packages/common/src/services/audio-player.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/premiumContentUtils.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/L

#2051 [C-972] Fix go-to-definition for common/stems
  packages/common/tsconfig.json
  packages/stems/tsconfig.json
Labels: size/XS

#2047 [C-1193] Fix oauth
  packages/mobile/.env.dev
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/src/components/oauth/OAuth.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/store/oauth/actions.ts
  packages/mobile/src/store/oauth/reducer.ts
  packages/mobile/src/store/oauth/sagas.ts
  packages/mobile/src/store/oauth/selectors.ts
Labels: size/M

#2050 [C-1201,C-1202] Improve search results rendering and perf
  packages/common/src/store/pages/search-results/reducer.ts
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
Labels: size/M

#2052 [C-1213, C-1216] Fix album artwork corners
  packages/mobile/src/components/track-list/TrackArtwork.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
Labels: size/M

#2053 [C-1224] Prevent duplicate navigation pushes
  packages/mobile/src/hooks/useNavigation.ts
Labels: size/M

#2055 [C-1027] Improve pull to refresh interaction
  packages/mobile/src/components/core/PullToRefresh.tsx
Labels: size/M

#2059 [C-1226] Fix refresh stuck in loop
  packages/mobile/index.js
  packages/mobile/src/components/core/PullToRefresh.tsx
  packages/mobile/src/components/core/SectionList.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/M

#2058 [C-1209] Prompt user for notifications
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/S

#2057 Add image backgrounds, animations, and small search bugfixes
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/image/PlaylistImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/components/image/utils.ts
  packages/mobile/src/components/lineup-tile/styles.ts
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/hooks/usePressScaleAnimation.ts
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
  packages/web/src/common/store/search-bar/sagas.ts
Labels: size/M

#2060 [C-1240, C-1241, C-1242, C-1243, C-1245] QA Updates for new artist dashboard table
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Labels: size/S

#2061 Add try-catch blocks to artist dashboard sagas
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
Labels: size/L

#2056 Prevent rendering root until account fetched
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/S

#2065 Fix initial render condition
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/XS

#2064 [C-1200] Improve lineup and bottom-tab perf
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts
  packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
Labels: size/S

#2062 Allow hiding keyboard when creating playlist C-1215
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
Labels: size/S

#2067 [C-1221] Improve profile socials scroll target
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
Labels: size/XS

#2054 Fix verified badge C-1178
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
Labels: size/M

#2063 [C-1233] hide edit profile when offline
  packages/mobile/src/components/offline-placeholder/OnlineOnly.tsx
  packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
Labels: size/M

#2068 Fix random image C-1212
  packages/common/src/services/RandomImage.ts
Labels: size/S

#2043 [PAY-614][PAY-541] Add recovery flow and modal for buying $AUDIO
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/common/src/store/ui/buy-audio/types.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/transaction-details/types.ts
  packages/common/src/utils/wallet.ts
  packages/web/src/assets/img/iconRaisedHand.svg
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
  packages/web/src/components/buy-audio-modal/BuyAudioRecoveryModal.module.css
  packages/web/src/components/buy-audio-modal/BuyAudioRecoveryModal.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XL

#2069 [C-1254] Fix debounced navigation
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
Labels: size/M

#2070 [C-1267] Fingerprint in react-native
  packages/common/src/services/fingerprint/FingerprintClient.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/android/build.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/fingerprint.ts
  packages/web/package-lock.json
  packages/web/src/services/fingerprint.ts
Labels: size/M

#2072 Fix notif subscription UI
  packages/web/src/common/store/profile/sagas.js
Labels: size/XS

#2074 [C-1269] Fix now-playing drawer and scrubber
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
Labels: size/L

#2075 [C-1166] Avoid only primary image
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/services/audius-backend-instance.ts
Labels: size/M

#2073 [C-1268] Fix height of remixes tile
  packages/mobile/src/components/co-sign/CoSign.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
Labels: size/S

#2077 [C-1185] Get user challenge polling daemon working in native
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/utils/sagaPollingDaemons.ts
Labels: size/M

#2076 [C-1205,C-1273] Improve splash screen animation, root screen management
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/root-screen/HomeScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/splash-screen/SplashScreen.tsx
Labels: size/L

#2080 [C-1252, C-1230] Add feature-flag for artist dashboard new table, and update styles for qa issues
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/components/tracks-table/EmptyTable.module.css
  packages/web/src/hooks/useTabs/TabStyles.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/S

#2078 [C-1246] Fix smart collections
  packages/common/src/store/pages/collection/actions.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
Labels: size/M

#2081 Remove track edit option from new dashboard table overflow menus
  packages/web/src/components/test-table/components/OverflowMenuButton.tsx
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Labels: size/S

#2079 [C-1270] Allow spaces in display name
  packages/mobile/src/screens/signon/ProfileManual.tsx
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#2084 fix ci type error?
  package-lock.json
  packages/mobile/package-lock.json
  packages/web/package-lock.json
Labels: size/XS

#2082 [C-977] Add Screen change analytics
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/utils/navigation.ts
Labels: size/L

#2087 Remove extraneous navState log
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/XS

#2088 Fix lint
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/XS

#2085 [PAY-670] New emoji error code
  packages/common/src/utils/aaoErrorCodes.ts
Labels: size/M

#2093 Remove references to Coinbase in Stripe BuyAudioFlow
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
Labels: size/M

#2094 [PAY-677] Prevent multiple recovery flow triggers
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#2095 [PAY-612] Add separate feature flags for enabling Coinbase/Stripe
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/M

#2071 BuyAudio Recovery Flow Fast Follows
  packages/common/src/utils/wallet.ts
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#2091 [C-854, C-1244] Update table styles to always display actions menu
  packages/web/src/components/test-collectibles-playlist-table/TestCollectiblesPlaylistTable.tsx
  packages/web/src/components/test-table/TestTable.module.css
  packages/web/src/components/test-table/TestTable.tsx
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/L

#2096 Update Stripe JS dependency to match updated docs
  packages/web/public/index.html
Labels: size/XS

#2097 Update SDK/Libs and call saveUserBankTransactionMetadata correctly
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/S

#2098 [C-1284] Fix entropy sync for versions other than 1.1.29
  packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
Labels: size/XS

#2099 Only fetch favorites/profiles once
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/S

#2100 Fix entropy sync part 2
  packages/mobile/src/App.tsx
Labels: size/XS

#2105 [C-1286] Add Hyperpop
  packages/common/src/utils/genres.ts
Labels: size/XS

#2106 Prepend saved tracks to saved lineup
  packages/web/src/common/store/pages/saved/lineups/sagas.js
Labels: size/XS

#2101 [PAY-610] Wire up Stripe modal to store
  packages/web/.env/.env.prod
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/components/stripe-on-ramp-modal/StripeOnRampModal.tsx
  packages/web/src/services/audius-backend/BuyAudio.ts
Labels: size/M

#2104 [PAY-679] Stop BuyAudio flow when user cancels the onramp
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XS

#2108 [HOTFIX] Remove unused import
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
Labels: size/XS

#2109 BuyAudio: Fix for if wallet has no transactions
  packages/web/src/services/audius-backend/BuyAudio.ts
Labels: bug, size/XS

#2083 [C-1184] Fetch lineups after coming back online
  packages/common/src/store/reachability/reducer.ts
  packages/mobile/src/hooks/useReachability.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/backend/selectors.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/reachability/sagas.ts
Labels: size/L

#2102 Fix password input clipping on mobile sign in/up C-1234
  packages/mobile/src/screens/signon/CreatePassword.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/XS

#2103 Keep screen awake when confirming tip
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
Labels: size/S

#2114 [C-1311] Fix Collectibles
  packages/web/src/common/store/profile/sagas.js
Labels: size/M

#2115 [Stripe Demo] Always show a "Buy More $AUDIO" button in tipping dialog
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
Labels: size/S

#2116 Bump libs 1.0.12
  package-lock.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/XS

#2107 [C-1040] Remove extraneous mobile logs
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/fingerprint/FingerprintClient.ts
  packages/common/src/utils/timeUtil.ts
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/notifications.ts
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/services/analytics.ts
  packages/mobile/src/utils/logging.ts
  packages/web/src/common/store/profile/sagas.js
Labels: size/M

#2113 [C-1307] Fix android build
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/fingerprint.ts
Labels: size/XS

#2119 Bring back unhealthySlotDiffPlays
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#2118 [PAY-457] Add Geofilter for Coinbase, Stripe
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/services/Location.ts
Labels: size/L

#2122 [C-1318] Revert "[C-1184] Fetch lineups after coming back online (#2083)"
  packages/common/src/store/reachability/reducer.ts
  packages/mobile/src/hooks/useReachability.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/backend/selectors.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/reachability/sagas.ts
Labels: size/L

#2124 Cherry-pick ef69b70c - which had caused [C-1310]
  packages/common/src/store/reachability/reducer.ts
  packages/mobile/src/hooks/useReachability.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/backend/selectors.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/reachability/sagas.ts
Labels: size/L

#2123 [C-1316] Fix getState undefined crash when opening reopening app on android
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
Labels: size/XS

#2125 [C-1309] Fix playlists/collectibles not loading
  packages/common/src/store/pages/profile/selectors.ts
Labels: size/XS

#2121 [C-1282] Remove followUser social action in profile reducer
  packages/common/src/store/pages/profile/reducer.ts
Labels: size/S

#2127 [C-1319] Fix native profile collectibles
  packages/common/src/services/opensea-client/OpenSeaClient.ts
  packages/common/src/services/opensea-client/index.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/store/storeContext.ts
Labels: size/M

#2132 Bump react-screens to 3.17.0 to avoid crash on android
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
Labels: size/M

#2133 [C-1272] Fix Search UI jank
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/search-screen/SearchBar.tsx
Labels: size/S

#2135 Fix play bar buttons target (Android) C-1264
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/utils/zIndex.ts
Labels: size/S

#2136 Refactor bottom-tab-bar
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/BottomTabBarButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/ExploreButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/FavoritesButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/FeedButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/ProfileButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/TrendingButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/index.ts
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/screens/app-screen/AppTabBar.tsx
Labels: size/L

#2138 [PAY-685] Update Stripe button to use approved brand assets
  packages/web/src/assets/img/LogoStripeLink.svg
  packages/web/src/components/audio-transaction-icon/AudioTransactionIcon.module.css
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/components/on-ramp-button/OnRampButton.module.css
  packages/web/src/components/on-ramp-button/OnRampButton.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#2137 [C-1327] Fix deep linking for tracks with diacritics
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/XS

#2130 Use Hermes for Android app C-1329
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/proguard-rules.pro
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/S

#2142 [C-1328] Fix "Share via" url on mobile
  packages/mobile/src/utils/share.ts
Labels: size/XS

#2139 [C-1291] Add base layout for navbar overhaul
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/remote-config.ts
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/NotificationsButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/index.ts
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/account-screen/index.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerContext.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/app-drawer-screen/index.ts
  packages/mobile/src/screens/app-drawer-screen/useAppDrawerNavigation.ts
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/app-screen/AppScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/NotificationsTabScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/UserNameLink.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
  packages/mobile/src/screens/notifications-screen/NotificationsDrawer.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
  packages/mobile/src/screens/notifications-screen/TopBar.tsx
  packages/mobile/src/screens/notifications-screen/index.ts
  packages/mobile/src/screens/root-screen/HomeScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/services/remote-config/remote-config-instance.ts
  packages/web/src/services/remote-config/remote-config-instance.ts
Labels: size/XL

#2144 Bump ios to 1.1.33
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2134 [C-1295] Update new tables to allow drag to add to playlist
  packages/web/src/components/dragndrop/Draggable.js
  packages/web/src/components/dragndrop/Droppable.js
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/store/dragndrop/actions.js
  packages/web/src/store/dragndrop/reducer.js
  packages/web/src/store/dragndrop/types.ts
Labels: size/M

#2140 [C-1317] Improve client startup tooling
  README.md
  package-lock.json
  package.json
  packages/mobile/.env.dev
  packages/mobile/package.json
  packages/web/.env/.env.ipfs.prod
  packages/web/.env/.env.ipfs.stage
  packages/web/package.json
Labels: size/L

#2131 Add structured data and update head
  packages/web/src/components/mobile-page-container/MobilePageContainer.tsx
  packages/web/src/components/page/Page.js
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/deleted-page/DeletedPage.tsx
  packages/web/src/pages/deleted-page/DeletedPageProvider.tsx
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/deleted-page/components/mobile/DeletedPage.tsx
  packages/web/src/pages/explore-page/ExplorePageProvider.tsx
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/pages/trending-page/TrendingPageProvider.js
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/types.ts
  packages/web/src/pages/trending-playlists/TrendingPlaylistPage.tsx
  packages/web/src/pages/trending-underground/TrendingUndergroundPage.tsx
  packages/web/src/utils/seo.ts
Labels: size/L

#2146 [C-1336] Implement account drawer
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useAccountHasClaimableRewards.ts
  packages/mobile/src/assets/images/iconUserFollowers.svg
  packages/mobile/src/assets/images/iconUserList.svg
  packages/mobile/src/assets/images/tokenBadgeNoTier.svg
  packages/mobile/src/components/audio-rewards/IconAudioBadge.tsx
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/web/src/components/nav/desktop/NavAudio.tsx
Labels: size/XL

#2145 [C-1335] Upgrade and share typescript version
  package-lock.json
  package.json
  packages/common/src/models/Track.ts
  packages/common/src/utils/performance.test.js
  packages/common/src/utils/selectorHelpers.ts
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/components/PillButton/types.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/confirmer/store.test.ts
  packages/web/src/common/store/player/store.test.js
  packages/web/src/components/data-entry/TabSlider.js
  packages/web/src/hooks/useRouteMatch.ts
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
  packages/web/src/services/audio-player/AudioPlayer.test.js
Labels: size/L

#2148 [C-1341] Add notifications bottom tab screen
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/BottomTabBarButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/NotificationsButton.tsx
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/useAppDrawerNavigation.ts
  packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
Labels: size/L

#2149 [C-1322] Android and general performance improvements
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/remote-config.ts
  packages/common/src/store/lineup/actions.ts
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileTrackList.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileArt.tsx
  packages/mobile/src/components/lineup-tile/LineupTileCoSign.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/LineupTileRankIcon.tsx
  packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/styles.ts
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
  packages/mobile/src/components/skeleton/Skeleton.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XL

#2152 [C-1345] redesign primary/secondary screens
  packages/mobile/src/assets/images/iconExplore.svg
  packages/mobile/src/assets/images/iconFavorite.svg
  packages/mobile/src/assets/images/iconFeed.svg
  packages/mobile/src/assets/images/iconNotification.svg
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/components/core/Screen/ScreenContent.tsx
  packages/mobile/src/components/core/Screen/ScreenHeader.tsx
  packages/mobile/src/components/core/Screen/ScreenHeaderButton.tsx
  packages/mobile/src/components/core/Screen/SecondaryScreenTitle.tsx
  packages/mobile/src/components/core/Screen/index.tsx
  packages/mobile/src/components/header/Header.tsx
  packages/mobile/src/components/header/index.ts
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TopAlbumsScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingPlaylistsScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingUndergroundScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedFilterButton.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/search-results-screen/SearchResultsScreen.tsx
  packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingFilterButton.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
Labels: size/XL

#2153 Add rendering trace util
  packages/mobile/devUtils/useRenderingTrace.ts
  packages/web/devUtils/useRenderingTrace.ts
Labels: size/M

#2158 dont deep link oauth
  packages/web/public/.well-known/apple-app-site-association
Labels: size/XS

#2159 [C-1352] Fix twitter deep link
  packages/mobile/ios/AudiusReactNative/AppDelegate.m
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Labels: size/L

#2161 Fix connected eth wallets
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/S

#2112 Auto follow person who referred you upon sign up C-1300
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#2110 [PAY-680] Fix BuyAudio recovery success modal
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/mobile/package-lock.json
  packages/web/package-lock.json
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#2163 [PAY-697]: Put recovery flow behind feature flag
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XS

#2162 SEO updates
  packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/web/src/components/animated-button/AnimatedIconButton.tsx
  packages/web/src/components/bottom-bar/BottomBar.tsx
  packages/web/src/components/bottom-bar/buttons/ExploreButton.tsx
  packages/web/src/components/bottom-bar/buttons/FavoritesButton.tsx
  packages/web/src/components/bottom-bar/buttons/FeedButton.tsx
  packages/web/src/components/bottom-bar/buttons/ProfileButton.tsx
  packages/web/src/components/bottom-bar/buttons/TrendingButton.tsx
  packages/web/src/components/bottom-bar/buttons/types.ts
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/components/card/mobile/Card.tsx
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/track/desktop/Artwork.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTileArt.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/ColorTile.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#2165 [C-1368, C-1354, C-1364] Address mobile-nav qa
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/image/ImageLoader.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/M

#2157 Call getUserListenCountsMonthly in client artist dashboard
  package-lock.json
  package.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
Labels: size/M

#2170 [PAY-705] Fix useLocalStorage hook to use getItem rather than getValue
  packages/web/src/hooks/useLocalStorage.ts
Labels: size/XS

#2166 [C-1302] Fix blank profile picture background color
  packages/web/src/components/profile-picture/ProfilePicture.js
Labels: size/XS

#2172 Update stage config to nethermind RPC
  packages/web/.env/.env.stage
Labels: size/XS

#2174 Update nethermind provider to https
  packages/web/.env/.env.stage
Labels: size/XS

#2168 Update @audius/sdk to 1.0.16
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#2128 Dual writes when setting artist pick
  package-lock.json
  package.json
  packages/common/src/models/User.ts
  packages/common/src/schemas/index.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/M

#2178 Update libs to 1.0.18
  package-lock.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package.json
Labels: size/XS

#2173 [C-1371, C-1372] Address mobile-navbar QA issues #2
  .circleci/config.yml
  .circleci/src/commands/@commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@stems-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  packages/mobile/patches/@react-navigation+drawer+6.3.1.patch
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/useAppDrawerNavigation.ts
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
Labels: size/L

#2179 Fix typecheck
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/store/ui/buy-audio/selectors.ts
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#2167 [C-1340] Fix notification subscriptions
  packages/web/src/common/store/social/users/sagas.ts
Labels: size/S

#2171 [C-1261] Android sign on overflow
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/L

#2180 [C-1369] Fix account screen crash on android
  packages/mobile/patches/react-native-screens+3.17.0.patch
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
Labels: size/M

#2181 Bump sdk to 1.0.19
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#2176 [PAY-703][PAY-698][PAY-699][PAY-686] Various Stripe Fixes pt 1
  packages/common/src/models/Analytics.ts
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#2164 [C-1370] Fix app initialization sequence and assumptions for offline and online startup
  packages/common/src/services/remote-config/remote-config.ts
  packages/common/src/store/account/slice.ts
  packages/common/src/store/reachability/reducer.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/utils/addUsersFromCollections.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessRemixes.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
  packages/web/src/common/store/cache/tracks/utils/helpers.ts
  packages/web/src/common/store/cache/tracks/utils/processAndCacheTracks.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/cache/users/utils/processAndCacheUsers.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/deactivate-account/sagas.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/common/store/pages/history/lineups/sagas.js
  packages/web/src/common/store/pages/profile/lineups/feed/retrieveUserReposts.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/remixes-page/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/search-page/sagas.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/common/store/pages/track/lineups/sagas.ts
  packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
  packages/web/src/common/store/pages/trending-underground/lineups/sagas.ts
  packages/web/src/common/store/pages/trending/lineups/trending/retrieveTrending.ts
  packages/web/src/common/store/pages/trending/lineups/trending/sagas.js
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/search-bar/sagas.ts
  packages/web/src/common/store/service-selection/sagas.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/ui/artist-recommendations/sagas.ts
  packages/web/src/common/store/user-list/utils.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/components/card/desktop/Card.module.css
  packages/web/src/components/notification/Notification/SupporterDethronedNotification.module.css
  packages/web/src/pages/audio-rewards-page/components/SendInputConfirmation.module.css
  packages/web/src/pages/deleted-page/store/lineups/more-by/sagas.ts
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/pages/upload-page/store/utils/sagaHelpers.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/utils/sagaHelpers.ts
Labels: size/L

#2182 [C-1359] Prevent double navigation on android, plus StatusBar fixes
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/store/mobileUi/sagas.ts
Labels: size/M

#2183 Avoid `handleInUse` libs function bc it hits poa
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/S

#2177 Use Hermes for iOS; allow enabling/disabling locally C-1334
  .circleci/src/commands/@mobile-commands.yml
  packages/mobile/README.md
  packages/mobile/disableHermesiOS.js
  packages/mobile/enableHermesiOS.js
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/L

#2186 [C-1377] Move cover photo button to top
  packages/web/src/components/cover-photo/CoverPhoto.module.css
Labels: size/XS

#2184 [C-1375] Fix push notification navigation
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/notifications.ts
Labels: size/L

#2185 [PAY-709][PAY-704][PAY-702][PAY-700][PAY-696][PAY-692][PAY-691] Various Stripe OnRamp Fixes pt 2
  packages/common/src/models/Analytics.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/store/ui/buy-audio/selectors.ts
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/common/src/store/ui/transaction-details/slice.ts
  packages/common/src/store/ui/transaction-details/types.ts
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.module.css
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
  packages/web/src/components/stripe-on-ramp-modal/StripeOnRampModal.tsx
  packages/web/src/components/transaction-details-modal/TransactionDetailsModal.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#2190 Fix mobile lint
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
Labels: size/XS

#2189 Fix artist link badge alignment C-961
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistLink.tsx
Labels: size/M

#2192 Pass retry through for client handle validation
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/M

#2193 [C-1376] Kickoff mobile upload
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/ParamList.ts
  packages/mobile/src/screens/upload-screen/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/index.tsx
Labels: size/L

#2196 [C-1366] Add disabed tooltip text for hidden tracks tab in artist dashboard
  packages/web/src/hooks/useTabs/useTabs.tsx
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Labels: size/S

#2197 Truncate balance in account-drawer
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
Labels: size/XS

#2147 [C-1385] Stream mp3 instead of segments
  packages/common/src/services/audio-player.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/L

#2194 Add notification navigation hook and update profile screen to accept id param
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/notifications.ts
  packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FavoriteNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FollowNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RepostNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawer.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
Labels: size/L

#2200 [C-1383] Add upload track form
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/assets/images/iconGenre.svg
  packages/mobile/src/assets/images/iconImage.svg
  packages/mobile/src/components/core/ContextualSubmenu.tsx
  packages/mobile/src/components/core/InputErrorMessage.tsx
  packages/mobile/src/components/core/RadioButton.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/list-selection-screen/index.ts
  packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/ParamList.ts
  packages/mobile/src/screens/upload-screen/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadingTracksScreen.tsx
  packages/mobile/src/screens/upload-screen/fields/ContextualSubmenuField.tsx
  packages/mobile/src/screens/upload-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/upload-screen/fields/SelectGenreField.tsx
  packages/mobile/src/screens/upload-screen/fields/TextField.tsx
  packages/mobile/src/screens/upload-screen/fields/index.ts
  packages/mobile/src/screens/upload-screen/fields/types.ts
  packages/mobile/src/screens/upload-screen/index.tsx
  packages/mobile/src/screens/upload-screen/types.ts
Labels: size/XL

#2202 Use feature flag for mp3 stream toggle
  packages/common/src/services/audio-player.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/L

#2201 Fix upload
  packages/common/src/utils/sagaHelpers.ts
Labels: size/XS

#2203 Cherry pick f1c28bdf - add feature flag to mp3 streaming change
  packages/common/src/services/audio-player.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/L

#2195 PAY-687 Add new UI to tipping linking to the BuyAudio flow
  packages/common/src/models/Analytics.ts
  packages/web/src/components/on-ramp-button/OnRampButton.module.css
  packages/web/src/components/on-ramp-button/OnRampButton.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
Labels: size/L

#2187 [C-1323] Somewhat improve upload metrics
  packages/common/src/models/Analytics.ts
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/pages/upload-page/store/utils/sagaHelpers.ts
Labels: size/L

#2204 Fix cover photo button alignment
  packages/web/src/components/cover-photo/CoverPhoto.module.css
Labels: size/XS
