Repository AudiusProject/audius-client, pull requests merged in 2022-03, with the labels that each got.

#997 [AUD-1630] Add UploadTrack button and drawer
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/GradientIcon.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
  packages/mobile/src/components/mobile-upload-drawer/index.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/UploadTrackButton.tsx
  packages/mobile/src/styles/typography.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/ui/mobile-upload-drawer/selectors.ts
  packages/web/src/common/store/ui/mobile-upload-drawer/slice.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
  packages/web/src/pages/profile-page/components/mobile/UploadButton.tsx
Labels: size/L

#999 Consume libs 1.2.87
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1000 [AUD-972] Fill out explainer and tiers of audio page
  packages/mobile/src/assets/images/iconReceive.svg
  packages/mobile/src/assets/images/iconSend.svg
  packages/mobile/src/assets/images/tokenBadgeBronze108.png
  packages/mobile/src/assets/images/tokenBadgeGold108.png
  packages/mobile/src/assets/images/tokenBadgePlatinum108.png
  packages/mobile/src/assets/images/tokenBadgeSilver108.png
  packages/mobile/src/assets/images/tokenSpinStill.png
  packages/mobile/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/audio-screen/Tier.tsx
  packages/mobile/src/styles/typography.ts
Labels: size/XL

#996 [AUD-1629] Connect ProfileScreen
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/components/core/Link.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/screens/edit-profile-screen/CoverPhotoInput.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/ProfilePictureInput.tsx
  packages/mobile/src/screens/edit-profile-screen/launchSelectImageActionSheet.ts
  packages/mobile/src/screens/edit-profile-screen/types.ts
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/Sites.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
  packages/mobile/src/screens/profile-screen/utils.ts
Labels: size/L

#998 [AUD-1631] Improve app navigation
  packages/mobile/src/components/app-navigator/AppNavigator.tsx
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/TopBar.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ArtistCard.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/search-screen/content/SeeMoreResultsButton.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenHeader.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserChip.tsx
Labels: size/L

#993 [AUD-1627] Refactor EmptyCard to EmptyTile
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/EmptyCard.tsx
  packages/mobile/src/components/core/EmptyTile.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/favorites-screen/EmptyTab.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
Labels: size/L

#978 Create playlist folder functionality
  packages/web/src/common/models/PlaylistLibrary.ts
  packages/web/src/common/store/ui/createPlaylistModal/actions.ts
  packages/web/src/common/store/ui/createPlaylistModal/reducer.ts
  packages/web/src/common/store/ui/createPlaylistModal/selectors.ts
  packages/web/src/common/store/ui/createPlaylistModal/types.ts
  packages/web/src/components/create-playlist/CreatePlaylistModal.tsx
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/nav/desktop/NavColumn.js
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/saved-page/components/mobile/NewPlaylistButton.tsx
  packages/web/src/store/playlist-library/helpers.ts
Labels: size/L

#1002 Fix profile track-tab loadMore
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
Labels: size/S

#1004 Bump Stems to 0.3.24
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1006 Bump libs to 1.2.88
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1003 [AUD-1097] Add SignOutConfirmationDrawer
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
  packages/mobile/src/components/sign-out-confirmation-drawer/index.ts
  packages/mobile/src/screens/settings-screen/AccountSettingsItem.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/sign-out/sagas.ts
  packages/web/src/common/store/sign-out/slice.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#1001 [AUD-1632] ProfileScreen performance
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/hooks/selectors.ts
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/Sites.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
  packages/mobile/src/screens/profile-screen/utils.ts
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
Labels: size/L

#1008 [AUD-972] Add discord drawer
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/assets/images/iconCopy.svg
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/copy-text-tile/CopyTextTile.tsx
  packages/mobile/src/components/copy-text-tile/index.ts
  packages/mobile/src/components/discord-drawer/DiscordDrawer.tsx
  packages/mobile/src/components/discord-drawer/index.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/L

#994 Allow editing playlists from the sidebar
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.module.css
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
Labels: size/XL

#1010 [AUD-1616] Disallow identical track uploads in same session
  packages/web/src/pages/upload-page/UploadPage.js
Labels: size/S

#1007 [AUD-1634] Conditionally render native drawers
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/action-drawer/ActionDrawer.tsx
  packages/mobile/src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/cognito-drawer/CognitoDrawer.tsx
  packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
  packages/mobile/src/components/connect-wallets-drawer/ConnectWalletsDrawer.tsx
  packages/mobile/src/components/deactivate-account-confirmation-drawer/DeactivateAccountConfirmationDrawer.tsx
  packages/mobile/src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
  packages/mobile/src/components/drawer/AppDrawer.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/NativeDrawer.tsx
  packages/mobile/src/components/drawer/index.ts
  packages/mobile/src/components/edit-collectibles-drawer/EditCollectiblesDrawer.tsx
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/components/feed-filter-drawer/FeedFilterDrawer.tsx
  packages/mobile/src/components/forgot-password-drawer/ForgotPasswordDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
  packages/mobile/src/components/transfer-audio-mobile-drawer/TransferAudioMobileDrawer.tsx
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/hooks/useDrawer.ts
  packages/mobile/src/screens/trending-screen/TrendingFilterDrawer.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/common/hooks/useModalState.ts
  packages/web/src/common/store/ui/mobile-overflow-menu/sagas.ts
  packages/web/src/common/store/ui/mobile-overflow-menu/selectors.ts
  packages/web/src/common/store/ui/mobile-overflow-menu/slice.ts
  packages/web/src/common/store/ui/mobile-overflow-menu/types.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/components/confirm-audio-to-waudio/desktop/ConfirmAudioToWAudioModal.tsx
  packages/web/src/components/mobile-connect-wallets-drawer/MobileConnectWalletsDrawer.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/user-badges/TierExplainerDrawer.tsx
  packages/web/src/components/user-badges/TierExplainerModal.tsx
  packages/web/src/store/sagas.ts
Labels: size/XL

#1009 [AUD-1639] conditionally render NotificationDrawer
  packages/mobile/src/App.tsx
  packages/mobile/src/components/notifications/Notifications.tsx
Labels: size/M

#1013 [AUD-1638] Partial web -> mobile state syncing
  packages/mobile/src/WebAppManager.tsx
  packages/mobile/src/hooks/useSelectorWeb.ts
  packages/mobile/src/message/handleMessage.ts
  packages/mobile/src/message/handlers/commonState.ts
  packages/mobile/src/message/types.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/store/common/slice.ts
  packages/mobile/src/store/index.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/store/configureStore.ts
Labels: size/M

#1014 Remove logic to individually enable RN screens
  packages/mobile/src/components/app-navigator/AppNavigator.tsx
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
Labels: size/M

#1012 Redirect to signup if auth rate limit error
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/models/Analytics.ts
  packages/web/src/common/store/errors/actions.ts
  packages/web/src/common/store/errors/sagas.ts
  packages/web/src/pages/sign-on/store/actions.js
  packages/web/src/pages/sign-on/store/errorSagas.js
  packages/web/src/pages/sign-on/store/sagas.js
Labels: size/L

#1011 [AUD-1640] Add null renderer for native
  packages/web/.env/.env.mobile
  packages/web/.env/.env.mobile.prod
  packages/web/.env/.env.mobile.stage
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/animated-switch/AnimatedSwitch.tsx
  packages/web/src/components/app-redirect-popover/AppRedirectListener.tsx
  packages/web/src/components/bottom-bar/BottomBar.tsx
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/components/header/mobile/HeaderContextProvider.tsx
  packages/web/src/components/nav/desktop/NavColumn.js
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/hooks/useHasChangedRoute.ts
  packages/web/src/hooks/useRouteMatch.ts
  packages/web/src/index.tsx
  packages/web/src/pages/explore-page/ExploreCollectionsPageProvider.tsx
  packages/web/src/pages/visualizer/Visualizer.tsx
  packages/web/src/types/react-nil/react-nil.d.ts
Labels: size/L

#932 Check for empty endpoint config
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
Labels: size/XS

#1015 [AUD-1361] Improve bottom tab button performance
  packages/mobile/package-lock.json
  packages/mobile/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/mobile/src/components/app-navigator/AppNavigator.tsx
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/bottom-tab-bar/index.ts
  packages/mobile/src/message/handlers/commonState.ts
  packages/mobile/src/store/common/actions.ts
  packages/mobile/src/store/common/reducer.ts
  packages/mobile/src/store/common/slice.ts
  packages/mobile/src/store/index.ts
  packages/web/.env/.env.mobile.prod
Labels: size/L

#1018 [AUD-1642]: Reduce web-app rerenders
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/web/src/common/store/pages/profile/selectors.ts
  packages/web/src/common/store/stems-upload/selectors.ts
  packages/web/src/common/store/ui/artist-recommendations/selectors.ts
  packages/web/src/common/utils/selectorHelpers.ts
  packages/web/src/pages/Modals.tsx
Labels: size/M

#1020 [AUD-1647] Fix Scrollbar
  packages/mobile/src/components/core/VirtualizedScrollView.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
Labels: size/S

#1021 [AUD-1652] Don't show header on SignOn
  packages/mobile/src/components/app-navigator/AppNavigator.tsx
Labels: size/XS

#1022 Fix settings-page when null-rendering
  packages/web/src/components/data-entry/TabSlider.js
  packages/web/src/pages/App.js
  packages/web/src/services/Logging.ts
  packages/web/src/services/native-mobile-interface/logging.ts
Labels: size/S

#1019 [AUD-972] Finish $AUDIO mobile page
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/assets/images/iconInfo.svg
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/audio-breakdown-drawer/index.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/progress-bar/ProgressBar.tsx
  packages/mobile/src/components/progress-bar/index.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/mobile/src/screens/audio-screen/Panel.tsx
  packages/mobile/src/screens/audio-screen/TrendingRewards.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/mobile/src/utils/theme.ts
  packages/web/src/common/utils/fillString.ts
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: size/XXL

#1023 [AUD-1653] Fixes $AUDIO sent associated token account creation
  packages/web/.env/.env.prod
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/wallet-client/WalletClient.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/L

#1025 Quick fix for update dot styles
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
Labels: size/XS

#1026 [AUD-1646] Various native fixes
  packages/mobile/src/components/app-navigator/TopBarIconButton.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/IconButton.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/edit-profile-screen/CoverPhotoInput.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/UploadTrackButton.tsx
  packages/mobile/src/screens/trending-screen/TrendingFilterDrawer.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
Labels: size/L

#1024 [AUD-732] Finish react native scrubber
  packages/mobile/package-lock.json
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/now-playing-drawer/Scrubber.tsx
  packages/mobile/src/components/scrubber/Scrubber.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/mobile/src/components/scrubber/index.ts
  packages/mobile/src/utils/animation.ts
Labels: size/XL

#1028 Revert change in env var
  packages/web/.env/.env.mobile.prod
Labels: size/XS

#1027 [AUD-1657] Improve native header perf
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/app-navigator/TopBar.tsx
  packages/mobile/src/components/app-navigator/TopBarArrowBack.tsx
  packages/mobile/src/components/app-navigator/baseStackScreenOptions.tsx
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/core/SearchInput.tsx
  packages/mobile/src/components/notifications/Notifications.tsx
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
Labels: size/L

#1029 [AUD-1648] RN Scroll To Top
  packages/mobile/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/VirtualizedScrollView.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/hooks/useScrollToTop.ts
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
Labels: size/L

#1031 [AUD-1622] Fix stacked profile-tab nav, improve goBack animation
  packages/mobile/src/components/app-navigator/baseStackScreenOptions.tsx
Labels: size/XS

#1033 Fix bug in NPD when track is playing
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Labels: size/XS

#1032 Fix more styling issues in the nav column 😩
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
Labels: size/M

#1036 Clean up misc styles
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/mobile/src/components/top-tab-bar/TopTabBar.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/Sites.tsx
  packages/mobile/src/screens/profile-screen/UploadTrackButton.tsx
  packages/mobile/src/styles/typography.ts
Labels: size/L

#1035 [AUD-1661] Improve ProfileScreen load time
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/hooks/selectors.ts
  packages/mobile/src/hooks/useRoute.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/common/store/pages/collection/selectors.ts
  packages/web/src/common/store/pages/profile/selectors.ts
  packages/web/src/common/store/pages/track/selectors.ts
Labels: size/L

#1030 Remove nav audio flag
  packages/web/src/common/models/User.ts
  packages/web/src/components/nav/desktop/NavAudio.tsx
Labels: size/S

#1037 [AUD-1667] Improve user-list performance
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/hooks/useRoute.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx
  packages/mobile/src/screens/user-list-screen/FavoritesList.tsx
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowingList.tsx
  packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
  packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserChip.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
Labels: size/L

#1039 [AUD-1681] Add profile-screen pull-to-refresh
  packages/mobile/src/components/core/VirtualizedScrollView.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/M

#1038 [AUD-1682] Support search deep linking properly
  packages/mobile/src/components/artist-card/ArtistCard.tsx
  packages/mobile/src/components/artist-card/index.ts
  packages/mobile/src/components/collection-card/CollectionCard.tsx
  packages/mobile/src/components/collection-card/index.ts
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
Labels: size/L

#1040 [AUD-1680] Remove topbar title flash
  packages/mobile/src/components/app-navigator/baseStackScreenOptions.tsx
Labels: size/XS

#1041 [AUD-1669] Add tile press animation
  packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
  packages/mobile/src/components/core/Tile.tsx
Labels: size/L

#1044 [AUD-1603] Fix overflow menu nav, close now-playing drawer on navigate
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
Labels: size/M

#1043 [AUD-1552, AUD-1555, AUD-1556, AUD-1557] Add smart collection screens
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/explore-screen/collections.ts
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/explore-screen/smartCollections.ts
  packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
Labels: size/L

#1045 [AUD-1625] TrackScreen performance and DynamicImage fix
  packages/mobile/src/WebAppManager.tsx
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/M

#1046 [AUD-1623] Fix LineupTile layout shift
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileRoot.tsx
  packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
Labels: size/M

#1034 Implement expanding/collapsing folders
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
Labels: size/L

#1048 [AUD-1674] Use linear gradient for bottom tab button underlay
  packages/mobile/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/bottom-tab-bar/buttons/AnimatedBottomButton.tsx
  packages/mobile/src/components/bottom-tab-bar/buttons/types.ts
Labels: size/L

#1049 [AUD-1558] Add MoodCollectionScreen and add mood screens to BottomTabNavigator
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/components/with-loader/WithLoader.tsx
  packages/mobile/src/screens/explore-screen/collections.ts
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
Labels: size/L

#1050 [PAY-83] Remove step counts from rewards config
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/M

#1051 [AUD-1551, AUD-1554] Add LetThemDJ and TopAlbums screens for explore screen
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TopAlbumsScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/index.ts
Labels: size/M

#1052 Add commas to numbers
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  packages/mobile/src/screens/audio-screen/Panel.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/M

#1047 Add playlists to folders functionality
  packages/web/src/components/dragndrop/Droppable.js
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/store/playlist-library/helpers.test.js
  packages/web/src/store/playlist-library/helpers.ts
Labels: size/XL

#1056 [AUD-1685] Optimize AddToPlaylist and AudioBeakdown drawers
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/web/WebApp.tsx
  packages/mobile/src/hooks/useScrollToTop.ts
  packages/web/src/common/store/ui/add-to-playlist/reducer.ts
  packages/web/src/common/store/ui/add-to-playlist/selectors.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/add-to-playlist/store/sagas.ts
  packages/web/src/components/nav/mobile/TopLevelPage.tsx
  packages/web/src/components/play-bar/PlayBarProvider.tsx
Labels: size/M

#1054 [AUD-1684]: ProfileScreen performance
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/components/app-navigator/TopTabNavigator.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/hooks/selectors.ts
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/Sites.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
  packages/mobile/src/screens/profile-screen/utils.ts
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserChip.tsx
  packages/web/src/common/store/pages/profile/selectors.ts
Labels: size/XL

#1058 [AUD-1694] Add clear search icon
  packages/mobile/src/components/core/SearchInput.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
Labels: size/M

#1059 [AUD-1548 AUD-1550] Add trending playlists screen and heavy rotation screen
  packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingPlaylistsScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/index.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/trending-playlists/lineups/actions.ts
  packages/web/src/common/store/pages/trending-playlists/lineups/reducer.ts
  packages/web/src/common/store/pages/trending-playlists/lineups/selectors.ts
  packages/web/src/common/store/pages/trending-playlists/slice.ts
  packages/web/src/pages/trending-playlists/TrendingPlaylistPage.tsx
  packages/web/src/pages/trending-playlists/store/lineups/collections/sagas.ts
  packages/web/src/pages/trending-playlists/store/lineups/collections/selectors.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/M

#1055 Add fp
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/fingerprint/FingerprintClient.ts
  packages/web/src/store/account/sagas.js
  packages/web/src/store/backend/sagas.js
Labels: size/M

#1062 Increment build number by 2 to unblock apple
  packages/mobile/ios/fastlane/Fastfile
Labels: size/XS

#1066 [AUD-1703] Remove Remixables feature flag
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/Section.module.css
  packages/web/src/pages/explore-page/components/desktop/Section.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.module.css
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
Labels: size/M

#1067 [AUD-1704] Remove NFT image picker feature flag
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.js
Labels: size/S

#1065 [AUD-1692] Native bottom button performance round 2
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/web/src/store/configureStore.ts
Labels: size/L

#1063 [AUD-1545] Implement and wire up tag search
  packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx
  packages/mobile/src/components/app-navigator/types.ts
  packages/mobile/src/hooks/useRoute.ts
  packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx
  packages/mobile/src/screens/search-results-screen/index.ts
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/L

#1064 Resolve temp playlists within folders
  packages/web/src/store/playlist-library/helpers.test.js
  packages/web/src/store/playlist-library/helpers.ts
  packages/web/src/store/playlist-library/sagas.ts
Labels: size/L

#1053 Enable reordering playlists and folders
  packages/web/src/components/dragndrop/Droppable.js
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/store/playlist-library/helpers.test.js
  packages/web/src/store/playlist-library/helpers.ts
Labels: size/XXL

#1069 Reorder folders and playlists - correct base branch lol
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/store/playlist-library/helpers.test.js
  packages/web/src/store/playlist-library/helpers.ts
Labels: size/XXL

#1060 Record IP if not recent
  packages/web/src/services/audius-backend/RecordIP.ts
  packages/web/src/store/account/sagas.js
Labels: size/M

#1071 Remove sol collectibles feature flag
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.js
  packages/web/src/pages/profile-page/sagas.js
Labels: size/M

#1075 [AUD-1641] Add notification badge in native
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/M

#1073 [AUD-1724] Fix useImageHook default bug on native
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileArt.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/notifications/content/UserImages.tsx
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/track-list/TrackArtwork.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/hooks/useCollectionCoverArt.ts
  packages/mobile/src/hooks/useImageSize.ts
  packages/mobile/src/hooks/useTrackCoverArt.ts
  packages/mobile/src/hooks/useUserCoverPhoto.ts
  packages/mobile/src/hooks/useUserProfilePicture.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/CoverPhotoInput.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/ProfilePictureInput.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
Labels: size/L

#1074 [AUD-1687] Reduce AnimatedButton rerenders and move to core
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/favorite-button/FavoriteButton.tsx
  packages/mobile/src/components/favorite-button/index.ts
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/repost-button/RepostButton.tsx
  packages/mobile/src/components/repost-button/index.ts
Labels: size/L

#1076 [AUD-1686] Button style fixes in native
  packages/mobile/src/components/core/Button.tsx
Labels: size/XS

#1077 [AUD-1636] Add hidden track header on native
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#1078 Add Amplitude events for playlist folders feature
  packages/web/src/common/models/Analytics.ts
  packages/web/src/components/create-playlist/CreatePlaylistModal.tsx
  packages/web/src/components/edit-folder-modal/EditFolderModal.tsx
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/store/playlist-library/helpers.ts
Labels: size/L

#1079 [AUD-1462] Add TrackRemixesScreen in native
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/remixes/lineup/actions.ts
  packages/web/src/common/store/pages/remixes/lineup/reducer.ts
  packages/web/src/common/store/pages/remixes/selectors.ts
  packages/web/src/common/store/pages/remixes/slice.ts
  packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
  packages/web/src/pages/remixes-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/remixes-page/store/sagas.ts
  packages/web/src/pages/remixes-page/store/selectors.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#1080 Fix album draggable bug
  packages/web/src/components/card/mobile/Card.tsx
  packages/web/src/components/lineup/CardLineup.tsx
  packages/web/src/pages/explore-page/components/mobile/CollectionsPage.tsx
Labels: size/XS

#1083 Add resend recovery email saga and functionality
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/recovery-email/sagas.ts
  packages/web/src/common/store/recovery-email/slice.ts
  packages/web/src/store/sagas.ts
Labels: size/M

#1084 [AUD-1742] Fix issue with DynamicImage rerenders
  packages/mobile/src/components/core/DynamicImage.tsx
Labels: size/XS

#1081 v1.1.3
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1085 Fix local storage temp playlist bug
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/store/playlist-library/helpers.test.js
  packages/web/src/store/playlist-library/helpers.ts
Labels: size/L

#1086 Fix playlist modal
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
Labels: size/S

#1087 [AUD-1728] Use drawer nav to support notifs
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/com/audiusreactnative/MainActivity.java
  packages/mobile/android/build.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/AppDelegate.m
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/src/components/audio/GoogleCast.tsx
  packages/mobile/src/components/notifications/NotificationsScreen.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
  packages/mobile/src/screens/app-screen/transitionSpec.ts
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/notifications-screen/Empty.tsx
  packages/mobile/src/screens/notifications-screen/List.tsx
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/notifications-screen/TopBar.tsx
  packages/mobile/src/screens/notifications-screen/content/Announcement.tsx
  packages/mobile/src/screens/notifications-screen/content/ChallengeReward.tsx
  packages/mobile/src/screens/notifications-screen/content/Cosign.tsx
  packages/mobile/src/screens/notifications-screen/content/Entity.tsx
  packages/mobile/src/screens/notifications-screen/content/Favorite.tsx
  packages/mobile/src/screens/notifications-screen/content/Follow.tsx
  packages/mobile/src/screens/notifications-screen/content/Milestone.tsx
  packages/mobile/src/screens/notifications-screen/content/NotificationContent.tsx
  packages/mobile/src/screens/notifications-screen/content/Remix.tsx
  packages/mobile/src/screens/notifications-screen/content/Repost.tsx
  packages/mobile/src/screens/notifications-screen/content/Subscription.tsx
  packages/mobile/src/screens/notifications-screen/content/TierChange.tsx
  packages/mobile/src/screens/notifications-screen/content/Trending.tsx
  packages/mobile/src/screens/notifications-screen/content/TwitterShare.tsx
  packages/mobile/src/screens/notifications-screen/content/User.tsx
  packages/mobile/src/screens/notifications-screen/content/UserImages.tsx
  packages/mobile/src/screens/notifications-screen/routeUtil.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/store/googleCast/controller.ts
Labels: size/XXL

#1089 Add ChangePasswordScreen and all required components
  packages/mobile/src/components/confirm-credentials/ConfirmCredentials.tsx
  packages/mobile/src/components/confirm-credentials/index.ts
  packages/mobile/src/components/enter-password/EnterPassword.tsx
  packages/mobile/src/components/enter-password/index.ts
  packages/mobile/src/components/status-message/StatusMessage.tsx
  packages/mobile/src/components/status-message/index.ts
  packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/settings-screen/ChangePasswordScreen.tsx
  packages/mobile/src/screens/settings-screen/index.ts
  packages/web/src/common/store/change-password/selectors.ts
  packages/web/src/common/store/change-password/slice.ts
  packages/web/src/common/store/index.ts
  packages/web/src/components/change-password/ChangePassword.tsx
  packages/web/src/components/change-password/ChangePasswordModal.tsx
  packages/web/src/components/change-password/ConfirmCredentials.tsx
  packages/web/src/components/change-password/store/sagas.ts
  packages/web/src/pages/settings-page/components/mobile/ChangePasswordPage.tsx
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/XL

#1093 Bump Stems to 0.3.25
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1095 Bump Stems to 0.3.26
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1090 Switch out scrollbar for new one in add playlist modal and nav bar to avoid jumpiness
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.module.css
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/nav/desktop/NavColumn.js
  packages/web/src/components/nav/desktop/NavColumn.module.css
Labels: size/M

#1099 [AUD-1741] [AUD-1744] Fix Play button state on track/collection screen
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#1101 [AUD-1759] Improve bottom spacing and content clipping
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/bottom-tab-bar/constants.ts
  packages/mobile/src/components/bottom-tab-bar/index.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/constants.ts
  packages/mobile/src/components/now-playing-drawer/index.tsx
  packages/mobile/src/screens/app-screen/AppTabBar.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
Labels: size/L

#1100 Add account verification screen
  packages/mobile/src/components/status-message/StatusMessage.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
Labels: size/L

#1098 [AUD-1738] Hide profile button until profile is available
  packages/mobile/package-lock.json
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
Labels: size/M

#1103 Enable native mobile in prod
  packages/mobile/.env.prod.tmpl
Labels: size/XS

#1102 [AUD-1740] Add now playing links
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/TitleBar.tsx
  packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
Labels: size/M

#1105 [AUD-1749] Update explore screen layout to match design
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
Labels: size/M

#1108 Bump ios version to 1.1.11
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#1110 Fix Simplebar scroll
  packages/web/src/index.css
Labels: size/XS

#1113 [AUD-1773] Fix user-list name overflow
  packages/mobile/src/screens/user-list-screen/UserChip.tsx
Labels: size/S

#1109 [AUD-1761, AUD-1670] Add shadow offset and multiple shadows
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/components/core/Tile/TileShadow.tsx
  packages/mobile/src/components/core/Tile/index.ts
Labels: size/L

#1115 [AUD-1765] Saving of smart collections
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/playlist-library/helpers.ts
  packages/web/src/components/edit-folder-modal/EditFolderModal.tsx
  packages/web/src/components/nav/desktop/NavColumn.js
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/pages/smart-collection/SmartCollectionPage.tsx
  packages/web/src/store/playlist-library/helpers.test.js
  packages/web/src/store/playlist-library/sagas.ts
  packages/web/src/store/social/collections/sagas.ts
Labels: size/M

#1112 [AUD-1637] Add horizontal padding to tabs
  packages/mobile/src/components/top-tab-bar/TopTabBar.tsx
Labels: size/M

#1117 [AUD-1783] Fix scrubber bug
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/scrubber/Scrubber.tsx
Labels: size/M

#1116 [AUD-1668] Fix Airplay
  packages/mobile/ios/AirplayEvent.m
  packages/mobile/src/App.tsx
  packages/mobile/src/components/audio/Airplay.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/message/handleMessage.ts
  packages/mobile/src/message/handlers/cast.ts
  packages/mobile/src/message/types.ts
  packages/web/src/common/store/cast/selectors.ts
  packages/web/src/common/store/cast/slice.ts
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/now-playing/store/actions.ts
  packages/web/src/components/now-playing/store/reducers.ts
  packages/web/src/components/now-playing/store/selectors.ts
  packages/web/src/components/now-playing/store/types.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#1119 [AUD-1782] Fix profile links
  packages/mobile/src/screens/profile-screen/Sites.tsx
Labels: size/XS

#1122 Be smarter about URL intercept
  packages/mobile/src/components/web/WebApp.tsx
Labels: size/XS

#1111 [AUD-1649] Implement custom pull to refresh
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/PullToRefresh.tsx
  packages/mobile/src/components/core/SectionList.tsx
  packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/notifications-screen/List.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/mobile/src/utils/animation.ts
  packages/mobile/src/utils/colorizeLottie.ts
  packages/web/src/common/store/notifications/actions.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/store/reducers.ts
Labels: size/XL

#1118 [AUD-1772] Fix empty search results styles
  packages/mobile/src/screens/search-results-screen/EmptyResults.tsx
Labels: size/M

#1120 [AUD-1753] Add seek buttons for podcasts on mobile
  packages/mobile/src/assets/images/iconPodcastBack.svg
  packages/mobile/src/assets/images/iconPodcastForward.svg
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Labels: size/M

#1121 [AUD-1768] Update artist info in now playing drawer to center icons
  packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
Labels: size/S

#1124 [AUD-1775] Improve search results loading state
  packages/mobile/src/screens/search-results-screen/SearchFocusContext.tsx
  packages/mobile/src/screens/search-results-screen/SearchResultsScreen.tsx
  packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx
  packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
Labels: size/M

#1131 Bump libs to 1.2.94
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1125 [AUD-1788] Fix play track from search-results
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
Labels: size/XS

#1130 [AUD-1779] Improve track tile click animation fluidity
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/M

#1132 [AUD-1770] Use latest react-native-linear-gradient
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/XS

#1133 [AUD-1790] Fix now-playing artist text truncate
  packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
Labels: size/M

#1126 [AUD-1785] Upgrade & fix chromecast integration
  packages/mobile/ios/AudiusReactNative/AppDelegate.m
  packages/mobile/src/App.tsx
  packages/mobile/src/components/audio/Airplay.tsx
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/audio/GoogleCast.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/screens/settings-screen/CastSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/store/googleCast/actions.ts
  packages/mobile/src/store/googleCast/controller.ts
  packages/mobile/src/store/googleCast/reducer.ts
  packages/mobile/src/store/googleCast/selectors.ts
  packages/mobile/src/store/index.ts
Labels: size/XL

#1128 [AUD-1778] Improve now playing drawer performance
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/constants.ts
  packages/mobile/src/components/drawer/index.ts
  packages/mobile/src/components/now-playing-drawer/Logo.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
  packages/mobile/src/components/now-playing-drawer/constants.ts
  packages/mobile/src/screens/app-screen/AppTabBar.tsx
Labels: size/L

#1134 Turn on CI mode to unblock builds
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#1135 [AUD-1793] Fix display of play counts on track screen
  packages/mobile/src/components/details-tile/DetailsStat.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#1138 [AUD-1712] Remove TikTok feature flag
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
Labels: size/S

#1139 [AUD-1480] Adjust referral button gradient
  packages/mobile/src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx
Labels: size/XS

#1140 [AUD-1671] Prevent Drawer from popping to top of screen
  packages/mobile/src/components/drawer/Drawer.tsx
Labels: size/XS

#1142 [AUD-1796] Fix wormhole compilation issue
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1141 [AUD-1757] Mood Overflow
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#1144 [AUD-1676, AUD-1677] Update dark mode colors
  packages/mobile/src/assets/images/iconVerified.svg
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/M

#1143 [AUD-1791] Combine audio/tier logic for web and mobile
  packages/mobile/src/components/audio-rewards/IconAudioBadge.tsx
  packages/mobile/src/components/audio-rewards/TierText.tsx
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/components/audio-rewards/audioTier.ts
  packages/mobile/src/components/audio-rewards/index.ts
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/hooks/useSelectTierInfo.ts
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/content/TierChange.tsx
  packages/mobile/src/screens/notifications-screen/content/TwitterShare.tsx
  packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
  packages/mobile/src/screens/profile-screen/constants.ts
  packages/mobile/src/screens/profile-screen/utils.ts
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/web/src/common/hooks/wallet.tsx
  packages/web/src/common/store/wallet/utils.ts
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.js
  packages/web/src/components/nav/desktop/NavAudio.tsx
  packages/web/src/components/notification/components/formatText.tsx
  packages/web/src/components/search-bar/ConnectedSearchBar.js
  packages/web/src/components/user-badges/ProfilePageBadge.tsx
  packages/web/src/components/user-badges/TierExplainerDrawer.tsx
  packages/web/src/components/user-badges/TierExplainerModal.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
Labels: size/L

#1129 Add drag auto scroll capability for custom scrollbar containers
  packages/web/package.json
  packages/web/src/components/drag-autoscroller/DragAutoscroller.tsx
  packages/web/src/components/nav/desktop/NavColumn.js
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
Labels: size/L

#1137 Remove Artist Recommendations Feature Flag
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendationsDropdown.tsx
  packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.tsx
Labels: size/S

#1146 [AUD-1766] NowPlayingDrawer layout
  packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/bottom-tab-bar/constants.ts
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/now-playing-drawer/Logo.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/TitleBar.tsx
  packages/mobile/src/components/now-playing-drawer/constants.ts
  packages/mobile/src/styles/makeStyles.ts
Labels: size/L

#1147 [AUD-1797] Add CreatePlaylistScreen
  packages/mobile/src/components/core/FormTextInput.tsx
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/components/form-screen/FormScreen.tsx
  packages/mobile/src/components/form-screen/index.ts
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/FavoritesTabScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/PlaylistDescriptionInput.tsx
  packages/mobile/src/screens/edit-playlist-screen/PlaylistImageInput.tsx
  packages/mobile/src/screens/edit-playlist-screen/PlaylistNameInput.tsx
  packages/mobile/src/screens/edit-playlist-screen/RandomImageButton.tsx
  packages/mobile/src/screens/edit-playlist-screen/index.ts
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/web/src/common/store/cache/collections/actions.ts
  packages/web/src/common/store/cache/collections/sagas.js
Labels: size/XL

#1145 [AUD-1739] Add missing haptics
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/core/SegmentedControl.tsx
  packages/mobile/src/components/favorite-button/FavoriteButton.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/repost-button/RepostButton.tsx
  packages/mobile/src/haptics.ts
Labels: size/M

#1149 Update AnimatedButton and colorize icons passed to animated buttons
  packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/favorite-button/FavoriteButton.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/FavoriteButton.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
  packages/mobile/src/components/now-playing-drawer/RepeatButton.tsx
  packages/mobile/src/components/now-playing-drawer/RepostButton.tsx
  packages/mobile/src/components/now-playing-drawer/ShuffleButton.tsx
  packages/mobile/src/components/repost-button/RepostButton.tsx
Labels: size/XL
