Repository AudiusProject/audius-client, pull requests merged in 2022-08, with the labels that each got.

#1650 Convert AudiusBackend to typescript
  packages/common/src/models/Collection.ts
  packages/common/src/models/User.ts
  packages/web/package-lock.json
  packages/web/src/audio/AudioStream.ts
  packages/web/src/common/store/cache/tracks/utils/reformat.ts
  packages/web/src/common/store/cache/users/utils/reformat.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/deactivate-account-page/store/sagas.ts
  packages/web/src/pages/search-page/store/sagas.js
  packages/web/src/services/AudiusBackend.ts
  packages/web/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/services/audius-backend/Explore.ts
  packages/web/src/services/web3-modal/index.ts
  packages/web/src/store/recommendation/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/XXL

#1664 [C-733] Fix mobile menu on narrow
  packages/web/src/pages/PublicSite.tsx
Labels: size/S

#1659 Add ModalContentPages to stems
  packages/stems/src/components/Modal/ModalContentPages.module.css
  packages/stems/src/components/Modal/ModalContentPages.stories.tsx
  packages/stems/src/components/Modal/ModalContentPages.tsx
  packages/stems/src/components/Modal/index.ts
Labels: size/L

#1665 Default endpoints to empty array instead of null
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
Labels: size/XS

#1661 Fix local env entity manager address
  packages/web/scripts/configureLocalEnv.js
Labels: size/XS

#1669 Update explore endpoints in libs to use v1
  package-lock.json
  packages/web/package-lock.json
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/services/audius-backend/Explore.ts
Labels: size/M

#1672 Fix typecheck for mobile after AudiusBackend ts migration
  packages/mobile/tsconfig.json
  packages/web/src/services/AudiusBackend.ts
  packages/web/src/services/web3-modal/index.ts
  packages/web/src/store/account/mobileSagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/M

#1654 [PAY-416] Early access mode & feature flag refactor
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useFeatureFlag.ts
  packages/common/src/hooks/useRemoteVar.ts
  packages/common/src/index.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/index.ts
  packages/common/src/services/remote-config/remote-config.ts
  packages/mobile/src/hooks/useRemoteConfig.ts
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/services/remote-config/remote-config-instance.ts
  packages/web/src/common/hooks/useFeatureFlag.ts
  packages/web/src/common/store/remote-config/selectors.ts
  packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
  packages/web/src/components/nav/desktop/NavHeader.js
  packages/web/src/components/nav/desktop/NavHeader.module.css
  packages/web/src/components/nav/mobile/NavBar.module.css
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/hooks/useRemoteConfig.ts
  packages/web/src/pages/explore-page/ExplorePage.tsx
  packages/web/src/services/remote-config/featureFlagHelpers.ts
  packages/web/src/services/remote-config/remote-config-instance.ts
Labels: size/XL

#1671 [C-771] Update native metro-config to enable @audius/sdk
  package-lock.json
  packages/mobile/android/settings.gradle
  packages/mobile/index.js
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/metro.config.js
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/src/components/Modal/ModalContentPages.stories.tsx
  packages/stems/src/components/Modal/ModalContentPages.tsx
  packages/web/package-lock.json
Labels: size/L

#1676 Fix native build with new metro-config dependencies
  packages/mobile/ios/Podfile.lock
  packages/mobile/metro.config.js
Labels: size/XS

#1683 [C-782] Catch fetch errors in AudiusBackend
  packages/web/src/services/AudiusBackend.ts
Labels: size/M

#1684 [C-781] Add minimum threshold to common password check
  packages/web/src/utils/commonPasswordCheck.ts
Labels: size/S

#1677 [C-780] Update AudiusBackend to work in native context
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/__mocks__/fetchCID.js
  packages/web/src/audio/AudioStream.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/services/AudiusBackend.ts
  packages/web/src/services/audius-backend/AudiusLibsLazyLoader.ts
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/audius-backend/fetchCID.ts
  packages/web/src/services/audius-backend/index.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/utils/hlsUtil.test.js
Labels: size/L

#1685 [C-774] Move audius-backend to common, add native libs-instance
  packages/mobile/.env.dev.tmpl
  packages/mobile/.env.prod.tmpl
  packages/mobile/.env.stage.tmpl
  packages/mobile/index.js
  packages/mobile/metro.config.js
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/services/monitoringCallbacks.ts
  packages/mobile/src/services/remote-config/getFeatureEnabled.ts
  packages/mobile/src/services/remote-config/index.ts
  packages/mobile/src/services/remote-config/remote-config-instance.ts
  packages/web/src/__mocks__/AudiusBackend.js
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/services/audius-backend/index.ts
  packages/web/src/common/services/audius-backend/types.ts
  packages/web/src/pages/sign-on/components/desktop/MetaMaskModal.js
  packages/web/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/services/audius-backend/Cognito.ts
  packages/web/src/services/audius-backend/Explore.ts
  packages/web/src/services/audius-backend/RecordIP.ts
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/L

#1686 [C-795] Fix user-list tag imports
  packages/web/src/common/store/user-list/favorites/reducers.ts
  packages/web/src/common/store/user-list/favorites/types.ts
  packages/web/src/common/store/user-list/followers/reducers.ts
  packages/web/src/common/store/user-list/followers/types.ts
  packages/web/src/common/store/user-list/following/reducers.ts
  packages/web/src/common/store/user-list/following/types.ts
  packages/web/src/common/store/user-list/reposts/reducers.ts
  packages/web/src/common/store/user-list/reposts/types.ts
  packages/web/src/common/store/user-list/supporting/reducers.ts
  packages/web/src/common/store/user-list/supporting/types.ts
  packages/web/src/common/store/user-list/top-supporters/reducers.ts
  packages/web/src/common/store/user-list/top-supporters/types.ts
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistChipTips.tsx
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
  packages/web/src/pages/favorites-page/FavoritesPage.tsx
  packages/web/src/pages/favorites-page/sagas.ts
  packages/web/src/pages/followers-page/FollowersPage.tsx
  packages/web/src/pages/followers-page/sagas.ts
  packages/web/src/pages/following-page/FollowingPage.tsx
  packages/web/src/pages/following-page/sagas.ts
  packages/web/src/pages/reposts-page/RepostsPage.tsx
  packages/web/src/pages/reposts-page/sagas.ts
  packages/web/src/pages/supporting-page/SupportingPage.tsx
  packages/web/src/pages/supporting-page/sagas.ts
  packages/web/src/pages/top-supporters-page/TopSupportersPage.tsx
  packages/web/src/pages/top-supporters-page/sagas.ts
Labels: size/M

#1688 [C-799] Add saga context, refactor backend state
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/backend/actions.ts
  packages/web/src/common/store/backend/errorSagas.ts
  packages/web/src/common/store/backend/reducer.ts
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/backend/selectors.ts
  packages/web/src/common/store/backend/types.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/effects.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/common/store/pages/explore/sagas.ts
  packages/web/src/common/store/reducers.ts
  packages/web/src/common/store/sagas.ts
  packages/web/src/common/store/storeContext.ts
  packages/web/src/components/change-password/store/sagas.ts
  packages/web/src/components/notification/store/mobileSagas.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/components/search-bar/store/sagas.js
  packages/web/src/components/service-selection/store/sagas.ts
  packages/web/src/components/service-selection/store/store.test.js
  packages/web/src/pages/App.js
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/audio-rewards-page/store/store.test.ts
  packages/web/src/pages/deactivate-account-page/store/sagas.ts
  packages/web/src/pages/feed-page/store/sagas.ts
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/remixes-page/store/sagas.ts
  packages/web/src/pages/search-page/store/sagas.js
  packages/web/src/pages/settings-page/store/mobileSagas.ts
  packages/web/src/pages/settings-page/store/sagas.ts
  packages/web/src/pages/sign-on/store/sagas.js
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/pages/track-page/store/sagas.js
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/store/account/sagas.js
  packages/web/src/store/backend/reducer.js
  packages/web/src/store/backend/selectors.js
  packages/web/src/store/configureStore.ts
  packages/web/src/store/lineup/store.test.js
  packages/web/src/store/playlist-library/sagas.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/social/collections/sagas.ts
  packages/web/src/store/social/collections/store.test.js
  packages/web/src/store/social/tracks/sagas.ts
  packages/web/src/store/social/tracks/store.test.js
  packages/web/src/store/social/users/sagas.ts
  packages/web/src/store/social/users/store.test.js
  packages/web/src/store/solana/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/store/types.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/L

#1691 [C-803] Add common state and backend sagas to native
  packages/mobile/src/services/fingerprint.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/services/fingerprint/FingerprintClient.ts
  packages/web/src/common/services/fingerprint/index.ts
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/storeContext.ts
  packages/web/src/services/fingerprint.ts
  packages/web/src/store/account/sagas.js
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
Labels: size/M

#1694 [C-794] Add typecheck to web ci
  .circleci/src/jobs/@web-jobs.yml
  packages/web/.hooks/pre-push.json
  packages/web/src/types/images/images.d.ts
Labels: size/M

#1695 [PAY-267, C-753] Remove tipping feature flags, Fix mutuals icon
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
  packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/Bio.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/CollapsedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandHeaderToggleButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileMutualsButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileTierTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialsAndSites.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTileSkeleton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ViewAllSupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/index.ts
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileHeaderV2.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/index.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
  packages/mobile/src/screens/user-list-screen/MutualsScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserChip.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
  packages/mobile/src/services/fingerprint.ts
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/store/tipping/sagas.ts
Labels: size/XL

#1692 Fix associated wallets
  packages/web/src/store/account/disconnected_wallet_fix.json
  packages/web/src/store/account/sagas.js
Labels: size/XXL

#1697 [C-804] Show playlist count for non-artists in native
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
Labels: size/M

#1689 [C-798] Remove owned/created stamp from collectible tile
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/web/src/components/collectibles/components/CollectibleDetails.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/services/audius-backend/audius-backend-instance.ts
Labels: size/M

#1696 [C-805] Fix artifact on small card
  packages/web/src/components/card/desktop/Card.module.css
Labels: size/XS

#1707 Add extends null to fix electron build
  packages/web/package.json
Labels: size/XS

#1705 [C-797] Fix track-remix-screen text color
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
Labels: size/XS

#1698 [C-806] Prevent multiple overflow menus at a time
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/utils/domUtils.ts
Labels: size/L

#1706 [C-801] Add tag search text to mobile
  packages/mobile/src/components/core/Tag.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/header/Header.tsx
  packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/M

#1708 [C-808] Don't show unnecessarily show profile option on overflow menu
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/hooks/useNavigation.ts
Labels: size/S

#1693 [PAY-466] Display AAO emoji errors for failed reward claims
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/pages/audio-rewards/selectors.ts
  packages/web/src/common/store/pages/audio-rewards/slice.ts
  packages/web/src/common/utils/aaoErrorCodes.ts
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
Labels: size/L

#1711 [C-820] Move apiClient into saga context, Add WalletClient to context
  packages/mobile/src/services/wallet-client.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/services/wallet-client/WalletClient.ts
  packages/web/src/common/services/wallet-client/index.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessRemixes.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/pages/profile/lineups/feed/retrieveUserReposts.ts
  packages/web/src/common/store/pages/profile/lineups/tracks/retrieveUserTracks.ts
  packages/web/src/common/store/storeContext.ts
  packages/web/src/common/store/ui/artist-recommendations/sagas.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
  packages/web/src/components/search-bar/store/sagas.js
  packages/web/src/components/share-sound-to-tiktok-modal/store/sagas.ts
  packages/web/src/components/user-list/utils.ts
  packages/web/src/pages/audio-rewards-page/components/SendInputBody.tsx
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/favorites-page/sagas.ts
  packages/web/src/pages/feed-page/store/lineups/feed/sagas.ts
  packages/web/src/pages/followers-page/sagas.ts
  packages/web/src/pages/following-page/sagas.ts
  packages/web/src/pages/history-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/remixes-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/reposts-page/sagas.ts
  packages/web/src/pages/saved-page/store/sagas.js
  packages/web/src/pages/search-page/store/sagas.js
  packages/web/src/pages/sign-on/store/sagas.js
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/pages/track-page/store/retrieveTrending.ts
  packages/web/src/pages/track-page/store/sagas.js
  packages/web/src/pages/trending-playlists/store/lineups/collections/sagas.ts
  packages/web/src/pages/trending-underground/store/lineups/tracks/sagas.ts
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/services/audius-backend/Explore.ts
  packages/web/src/services/wallet-client.ts
  packages/web/src/store/confirmer/sagas.ts
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/recommendation/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/L

#1712 [PAY-521] Add web dethroned notification
  packages/common/src/models/Analytics.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/assets/img/crown2x.png
  packages/web/src/common/hooks/useTwitterButtonStatus.ts
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/SupporterDethronedNotification.module.css
  packages/web/src/components/notification/Notification/SupporterDethronedNotification.tsx
  packages/web/src/components/notification/Notification/components/TwitterShareButton.tsx
  packages/web/src/components/notification/store/sagas.ts
Labels: size/L

#1704 [C-773] Prevent showing file explorer on pressing enter
  packages/web/src/components/image-selection/ImageSelectionButton.js
Labels: size/XS

#1666 Add sagas for OnRamp to AUDIO
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/buy-audio/constants.ts
  packages/web/src/common/store/buy-audio/selectors.ts
  packages/web/src/common/store/buy-audio/slice.ts
  packages/web/src/common/store/reducers.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/common/utils/wallet.ts
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/audius-backend/waudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#1713 [C-826] Move remote-config-instance to saga context
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/service-selection/errorSagas.ts
  packages/web/src/common/store/service-selection/sagas.ts
  packages/web/src/common/store/service-selection/selectors.ts
  packages/web/src/common/store/service-selection/slice.ts
  packages/web/src/common/store/service-selection/store.test.js
  packages/web/src/common/store/ui/artist-recommendations/sagas.ts
  packages/web/src/components/collectibles/ethCollectibleHelpers.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/components/service-selection/SelectedServices.tsx
  packages/web/src/components/service-selection/ServiceSelectionModal.js
  packages/web/src/pages/App.js
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/sign-on/store/sagas.js
  packages/web/src/pages/track-page/store/sagas.js
  packages/web/src/pages/trending-playlists/store/lineups/collections/sagas.ts
  packages/web/src/pages/trending-underground/store/lineups/tracks/sagas.ts
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/services/opensea-client/OpenSeaClient.ts
  packages/web/src/services/opensea-client/ethCollectibleHelpers.ts
  packages/web/src/services/solana-client/SolanaClient.ts
  packages/web/src/services/solana-client/solCollectibleHelpers.ts
  packages/web/src/store/oauth/sagas.ts
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/types.ts
  packages/web/src/store/wallet/sagas.ts
  packages/web/src/utils/signOut.js
Labels: size/XL

#1715 Fix typecheck with updated sdk version
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/src/store/sagas.ts
Labels: size/XS

#1714 [PAY-529] Add native dethroned notification
  packages/common/src/models/Analytics.ts
  packages/mobile/src/assets/images/crown2x.png
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationBody.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationHeader.tsx
  packages/mobile/src/screens/notifications-screen/Notification/index.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
  packages/mobile/src/screens/tip-artist-screen/ReceiverDetails.tsx
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
Labels: size/L

#1702 [C-768] Fix toast on no artwork
  packages/web/src/components/toast/Toast.module.css
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/components/upload/UploadArtwork.module.css
Labels: size/M

#1703 [C-767] Fix tooltip on cards and new playlist
  packages/web/src/components/actions-tab/ActionsTab.js
  packages/web/src/components/card/desktop/Card.module.css
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/tooltip/Tooltip.tsx
  packages/web/src/components/tooltip/types.ts
Labels: size/S

#1678 [Snyk] Upgrade @cloudflare/kv-asset-handler from 0.0.11 to 0.2.0
  packages/stems/scripts/workers-site/package-lock.json
  packages/stems/scripts/workers-site/package.json
Labels: size/XS

#1679 [Snyk] Upgrade deepcopy from 0.3.3 to 0.6.3
  packages/web/src/utils/visualizer/gl-vignette-background/package.json
Labels: size/XS

#1680 [Snyk] Upgrade glsl-random from 0.0.4 to 0.0.5
  packages/web/src/utils/visualizer/gl-vignette-background/package.json
Labels: size/XS

#1701 [C-608] Fix tooltip bugs
  packages/web/src/components/actions-tab/ActionsTab.js
  packages/web/src/components/card/desktop/Card.module.css
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/tooltip/Tooltip.tsx
  packages/web/src/components/tooltip/types.ts
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/M

#1709 [C-786] Fix width of foreground hero image
  packages/web/src/pages/landing-page/components/Hero.module.css
Labels: size/S

#1716 [C-829] Fix upload error
  packages/web/src/pages/upload-page/store/sagas.js
Labels: size/XS

#1717 [C-815] Fix electron update
  packages/web/src/electron.js
Labels: size/M

#1722 Fix missing audiusBackendInstance in search-bar saga
  packages/web/src/components/search-bar/store/sagas.js
Labels: size/XS

#1723 Remove common sagas from native
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
Labels: size/XS

#1725 Re-add native store context to fix optimizely import resolution
  packages/mobile/src/store/store.ts
Labels: size/XS

#1726 Fix wallet-client usages
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/M

#1728 [PAY-537] Adds new AAO error code emojis
  packages/web/src/common/utils/aaoErrorCodes.ts
Labels: size/XS

#1727 [C-841] Put getFeatureEnabled in storeContext
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/storeContext.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/pages/sign-on/store/sagas.js
  packages/web/src/store/storeContext.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/M

#1730 [C-842] Add scrypt and account sagas to mobile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
Labels: size/M

#1732 Fix no-undef, add rule back to eslint-config
  packages/eslint-config-audius/src/index.js
  packages/web/src/common/store/cache/collections/sagas.js
Labels: size/S

#1667 [PAY-545] [PAY-542] Buy $AUDIO tile on $AUDIO page
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/assets/img/coinbase-pay/LogoCoinbase.svg
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/pages/audio-rewards-page/Tiers.module.css
  packages/web/src/pages/audio-rewards-page/Tiles.module.css
  packages/web/src/pages/audio-rewards-page/components/ExplainerTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/L

#1729 [PAY-497] Fix native mobile install challenge
  packages/web/src/common/store/challenges/selectors/optimistic-challenges.ts
Labels: size/XS

#1733 [C-830] Move account to common store and set up with sign in
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/signon/selectors.ts
  packages/mobile/src/store/store.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/package-lock.json
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/errorSagas.ts
  packages/web/src/common/store/pages/signon/mobileSagas.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/signon/selectors.js
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/common/store/pages/signon/verifiedChecker.test.js
  packages/web/src/common/store/pages/signon/verifiedChecker.ts
  packages/web/src/common/store/reducers.ts
  packages/web/src/common/store/storeContext.ts
  packages/web/src/components/create-account/ButtonCreateAccount.js
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/nav/mobile/ConnectedBottomBar.tsx
  packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
  packages/web/src/components/service-selection/SelectedServices.tsx
  packages/web/src/components/service-selection/ServiceSelectionModal.js
  packages/web/src/hooks/useRequiresAccount.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/feed-page/FeedPageProvider.js
  packages/web/src/pages/feed-page/store/lineups/feed/sagas.ts
  packages/web/src/pages/feed-page/store/sagas.ts
  packages/web/src/pages/sign-on/SignOn.tsx
  packages/web/src/pages/sign-on/SignOnProvider.tsx
  packages/web/src/pages/sign-on/components/desktop/FollowPage.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
  packages/web/src/pages/sign-on/components/mobile/FollowPage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
  packages/web/src/pages/trending-page/TrendingPageProvider.js
  packages/web/src/pages/trending-underground/TrendingUndergroundPage.tsx
  packages/web/src/services/native-mobile-interface/signon.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/social/collections/sagas.ts
  packages/web/src/store/social/tracks/sagas.ts
  packages/web/src/store/social/users/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/store/types.ts
  packages/web/src/utils/sagaHelpers.js
Labels: size/L

#1700 [C-745, C-746, C-747, C-748, C-750, C-752, C-811, C-812] New Tables
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/test-collectibles-playlist-table/TestCollectiblesPlaylistTable.module.css
  packages/web/src/components/test-collectibles-playlist-table/TestCollectiblesPlaylistTable.tsx
  packages/web/src/components/test-collectibles-playlist-table/index.ts
  packages/web/src/components/test-table/TestTable.module.css
  packages/web/src/components/test-table/TestTable.tsx
  packages/web/src/components/test-table/components/OverflowMenuButton.module.css
  packages/web/src/components/test-table/components/OverflowMenuButton.tsx
  packages/web/src/components/test-table/components/TableFavoriteButton.module.css
  packages/web/src/components/test-table/components/TableFavoriteButton.tsx
  packages/web/src/components/test-table/components/TablePlayButton.module.css
  packages/web/src/components/test-table/components/TablePlayButton.tsx
  packages/web/src/components/test-table/components/TableRepostButton.module.css
  packages/web/src/components/test-table/components/TableRepostButton.tsx
  packages/web/src/components/test-table/index.ts
  packages/web/src/components/test-tracks-table/TestTracksTable.module.css
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
  packages/web/src/components/test-tracks-table/index.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/history-page/HistoryPageProvider.tsx
  packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/types/react-table/react-table-config.d.ts
Labels: size/XXL

#1736 [C-856] Use solanaweb3 in native, improve account flow
  packages/mobile/index.js
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-api-client/apiClient.ts
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/services/local-storage/LocalStorage.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/services/audius-backend/RecordIP.ts
Labels: size/M

#1737 Fix eager discovery loader
  packages/web/src/services/audius-backend/eagerLoadUtils.ts
Labels: size/S

#1738 [C-857] Add cache and confirmer to mobile sagas
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/account/reducer.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/common/store/cache/store.test.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/users/utils/pruneBlobValues.ts
  packages/web/src/common/store/confirmer/actions.ts
  packages/web/src/common/store/confirmer/reducer.ts
  packages/web/src/common/store/confirmer/sagas.ts
  packages/web/src/common/store/confirmer/selectors.ts
  packages/web/src/common/store/confirmer/store.test.ts
  packages/web/src/common/store/confirmer/types.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/reducers.ts
  packages/web/src/components/unload-dialog/UnloadDialog.js
  packages/web/src/pages/deactivate-account-page/store/sagas.ts
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/store/lineup/store.test.js
  packages/web/src/store/playlist-library/sagas.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/social/collections/sagas.ts
  packages/web/src/store/social/tracks/sagas.ts
  packages/web/src/store/social/users/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/types.ts
Labels: size/L

#1735 [PAY-531] Fix become first supporter bug
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/hooks/useGetFirstOrTopSupporter.ts
Labels: size/M

#1721 [Pay-516] Show see more only if profile header should be expansible on mobile.
  packages/mobile/src/screens/profile-screen/ProfileHeader/Bio.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/CollapsedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
Labels: size/L

#1742 Bump ios version to 1.1.28
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#1739 Get sign in/out working end to end
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
  packages/web/src/common/store/account/reducer.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/sign-out/sagas.ts
Labels: size/L

#1673 [PAY-540] Add analytics to buy audio flow
  packages/common/src/models/Analytics.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#1746 Fix dethroned Twitter share copy
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/web/src/components/notification/Notification/SupporterDethronedNotification.tsx
Labels: size/XS

#1747 Update @audius/sdk to 0.0.37
  package-lock.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-api-client/apiClient.ts
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1740 v1.3.0
  lerna.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1748 Bump iOS
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#1744 Add bounds to $AUDIO purchase
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/common/store/buy-audio/slice.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#1750 [C-859] Omit `is_verified` from metadata that gets stored in user cache from fetchCID
  packages/web/src/pages/profile-page/sagas.js
Labels: size/XS

#1741 Move Coinbase button into its own component
  packages/web/src/components/coinbase-pay-button/CoinbasePayButtonCustom.module.css
  packages/web/src/components/coinbase-pay-button/CoinbasePayButtonCustom.tsx
  packages/web/src/components/coinbase-pay-button/index.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/L

#1751 [C-861] Remove /macro usage for typed-redux-saga
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessRemixes.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/common/store/reachability/sagas.ts
  packages/web/src/common/store/service-selection/sagas.ts
  packages/web/src/common/store/ui/delete-playlist-confirmation-modal/sagas.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
  packages/web/src/common/store/ui/share-modal/sagas.ts
  packages/web/src/common/store/user-list/notifications/sagas.ts
  packages/web/src/components/notification/store/mobileSagas.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/components/share-sound-to-tiktok-modal/store/sagas.ts
  packages/web/src/components/user-list/utils.ts
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/deactivate-account-page/store/sagas.ts
  packages/web/src/pages/deleted-page/store/lineups/more-by/sagas.ts
  packages/web/src/pages/favorites-page/sagas.ts
  packages/web/src/pages/followers-page/sagas.ts
  packages/web/src/pages/following-page/sagas.ts
  packages/web/src/pages/mutuals-page/sagas.ts
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/pages/top-supporters-page/sagas.ts
  packages/web/src/services/native-mobile-interface/helpers.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/application/ui/cookieBanner/sagas.ts
  packages/web/src/store/application/ui/scrollLock/sagas.ts
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/queue/mobileSagas.ts
  packages/web/src/store/queue/sagas.ts
  packages/web/src/store/social/collections/sagas.ts
  packages/web/src/store/social/tracks/sagas.ts
  packages/web/src/store/social/users/sagas.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/M

#1749 [C-860] Fix failing mac ci build due to peer deps
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1754 [PAY-564] Enable LayoutAnimation on android for profile screen
  packages/mobile/src/App.tsx
Labels: size/XS

#1752 Fix margin issue
  packages/web/src/components/upload/UploadChip.module.css
Labels: size/XS

#1674 Update playlist actions to use entity manager
  package-lock.json
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/.env.dev.tmpl
  packages/mobile/.env.stage.tmpl
  packages/mobile/package-lock.json
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
  packages/mobile/src/services/audius-backend-instance.ts
  packages/web/.env/.env.dev
  packages/web/.env/.env.stage
  packages/web/package-lock.json
  packages/web/scripts/configureLocalEnv.js
  packages/web/src/common/services/audius-api-client/ResponseAdapter.ts
  packages/web/src/common/services/audius-api-client/types.ts
  packages/web/src/common/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/cache/collections/actions.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/add-to-playlist/mobile/AddToPlaylist.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/utils/tempPlaylistId.ts
Labels: size/XL

#1755 Remove /macro usage for typed-redux-saga (#1751)
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessRemixes.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/common/store/reachability/sagas.ts
  packages/web/src/common/store/service-selection/sagas.ts
  packages/web/src/common/store/ui/delete-playlist-confirmation-modal/sagas.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
  packages/web/src/common/store/ui/share-modal/sagas.ts
  packages/web/src/common/store/user-list/notifications/sagas.ts
  packages/web/src/components/notification/store/mobileSagas.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/components/share-sound-to-tiktok-modal/store/sagas.ts
  packages/web/src/components/user-list/utils.ts
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/deactivate-account-page/store/sagas.ts
  packages/web/src/pages/deleted-page/store/lineups/more-by/sagas.ts
  packages/web/src/pages/favorites-page/sagas.ts
  packages/web/src/pages/followers-page/sagas.ts
  packages/web/src/pages/following-page/sagas.ts
  packages/web/src/pages/mutuals-page/sagas.ts
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/pages/top-supporters-page/sagas.ts
  packages/web/src/services/native-mobile-interface/helpers.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/application/ui/cookieBanner/sagas.ts
  packages/web/src/store/application/ui/scrollLock/sagas.ts
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/queue/mobileSagas.ts
  packages/web/src/store/queue/sagas.ts
  packages/web/src/store/social/collections/sagas.ts
  packages/web/src/store/social/tracks/sagas.ts
  packages/web/src/store/social/users/sagas.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/wallet/sagas.ts
Labels: size/M

#1757 Update @audius/sdk to 0.0.38
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1762 Remove eager discprov logs
  packages/web/src/common/services/audius-api-client/AudiusAPIClient.ts
Labels: size/XS

#1745 Add pill radio button
  packages/stems/src/components/RadioButtonGroup/RadioButtonGroup.stories.tsx
  packages/stems/src/components/RadioButtonGroup/RadioButtonGroup.tsx
  packages/stems/src/components/RadioButtonGroup/RadioGroupContext.ts
  packages/stems/src/components/RadioButtonGroup/index.ts
  packages/stems/src/components/RadioPillButton/RadioPillButton.module.css
  packages/stems/src/components/RadioPillButton/RadioPillButton.stories.tsx
  packages/stems/src/components/RadioPillButton/RadioPillButton.tsx
  packages/stems/src/components/RadioPillButton/index.ts
  packages/stems/src/hooks/useControlled.ts
  packages/stems/src/index.tsx
Labels: size/L

#1760 [PAY-438] Fix Twitter icon fill color in matrix mode
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
Labels: size/XS

#1720 [PAY-431] Slide in supporters after loading
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
Labels: size/S

#1731 [PAY-546] Add memo instruction to final onramp transfer, fix rent min problem
  packages/web/src/common/store/buy-audio/slice.ts
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#1764 [C-875] Remove blocklist
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/.env.dev.tmpl
  packages/mobile/.env.prod.tmpl
  packages/mobile/.env.stage.tmpl
  packages/web/.env/.env.dev
  packages/web/.env/.env.ipfs.prod
  packages/web/.env/.env.ipfs.stage
  packages/web/.env/.env.prod
  packages/web/public/index.html
  packages/web/scripts/configureLocalEnv.js
  packages/web/src/common/store/cache/tracks/utils/blocklist.ts
  packages/web/src/common/store/cache/tracks/utils/processAndCacheTracks.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/components/search-bar/store/sagas.js
  packages/web/src/components/search-bar/store/sagas.ts
Labels: size/L

#1766 Add entity manager address for prod env
  packages/mobile/.env.prod.tmpl
  packages/web/.env/.env.prod
Labels: size/XS

#1769 Add back modal hook functionality
  packages/web/src/common/hooks/useModalState.ts
Labels: size/S

#1770 Wire up initial BuyAudioModal
  packages/common/src/store/ui/buy-audio/selectors.ts
  packages/web/src/components/buy-audio-modal/BuyAudioModal.module.css
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
  packages/web/src/components/coinbase-pay-button/index.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/M

#1768 [C-858] Add track page sagas to native, Refactor TrackScreen
  packages/common/package.json
  packages/common/src/store/pages/track/actions.ts
  packages/mobile/src/hooks/useImageSize.ts
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/store/sagas.ts
Labels: size/M

#1763 Add entity manager address to configInternalWeb3
  packages/mobile/src/services/audius-backend-instance.ts
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1773 Update @coinbase/cbpay-js to v1.2.0 and @solana/web3.js to 1.53.0
  packages/mobile/package-lock.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1775 [C-890] Polyfill TextEncoder, fixes builds
  packages/mobile/index.js
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
Labels: size/XS

#1772 [PAY-571] Move Jupiter out of bundle, attach BuyAudio sagas
  packages/common/src/utils/wallet.ts
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#1776 [C-887] Host sourcemaps on s3, fixes cloudflare deploy
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@web-jobs.yml
  package-lock.json
  packages/common/package-lock.json
  packages/mobile/package-lock.json
  packages/web/craco.config.ts
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#1774 Fix order playlist to use updated playlist
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/pages/collection-page/store/lineups/tracks/sagas.js
Labels: size/XS

#1781 Cleans up code for Challenge Twitter icon fill color
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
Labels: size/XS

#1777 [PAY-458] Buy Audio Modal Input Page
  packages/web/src/app.tsx
  packages/web/src/assets/img/iconAUDIO.png
  packages/web/src/assets/img/iconSOL.png
  packages/web/src/assets/img/iconUSD.png
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.module.css
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.module.css
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/PurchaseQuote.module.css
  packages/web/src/components/buy-audio-modal/components/PurchaseQuote.tsx
  packages/web/src/components/coinbase-pay-button/CoinbasePayButtonProvider.tsx
Labels: size/XL

#1778 [PAY-575] [PAY-574] [PAY-573] [PAY-572] [PAY-581] Coinbase Pay Button and Rewards Page Fixes
  packages/stems/src/components/RadioPillButton/RadioPillButton.module.css
  packages/web/src/components/coinbase-pay-button/CoinbasePayButtonCustom.module.css
  packages/web/src/components/coinbase-pay-button/CoinbasePayButtonCustom.tsx
  packages/web/src/components/toggle-collapse-button/ToggleCollapseButton.module.css
  packages/web/src/components/toggle-collapse-button/ToggleCollapseButton.tsx
  packages/web/src/components/toggle-collapse-button/index.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/L

#1780 [PAY-476] Display error when send to wallet fails
  packages/web/src/store/wallet/sagas.ts
Labels: size/XS

#1784 [C-871] Migrate player state to common
  packages/common/src/store/index.ts
  packages/common/src/store/player/index.ts
  packages/common/src/store/player/selectors.ts
  packages/common/src/store/player/slice.ts
  packages/common/src/store/player/types.ts
  packages/common/src/store/reducers.ts
  packages/web/src/audio/AudioStream.ts
  packages/web/src/audio/NativeMobileAudio.ts
  packages/web/src/common/store/queue/selectors.ts
  packages/web/src/components/cookie-banner/CookieBanner.tsx
  packages/web/src/components/lineup/hooks.ts
  packages/web/src/components/mobile-page-container/MobilePageContainer.tsx
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/PlayBarProvider.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.js
  packages/web/src/components/play-bar/mobile/PlayBar.tsx
  packages/web/src/components/play-bar/next-button/NextButtonProvider.tsx
  packages/web/src/components/play-bar/previous-button/PreviousButtonProvider.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/pages/collectibles-playlist-page/CollectiblesPlaylistPageProvider.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/deleted-page/DeletedPageProvider.tsx
  packages/web/src/pages/feed-page/FeedPageProvider.js
  packages/web/src/pages/history-page/HistoryPageProvider.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/search-page/SearchPageProvider.js
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/trending-page/TrendingPageProvider.js
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/store/lineup/sagas.js
  packages/web/src/store/lineup/store.test.js
  packages/web/src/store/player/errorSagas.ts
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/player/selectors.ts
  packages/web/src/store/player/store.test.js
  packages/web/src/store/player/types.ts
  packages/web/src/store/queue/mobileSagas.ts
  packages/web/src/store/queue/sagas.ts
  packages/web/src/store/queue/store.test.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/XL

#1786 Migrate queue selectors to common
  packages/common/src/store/queue/index.ts
  packages/common/src/store/queue/selectors.ts
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/web/src/components/lineup/hooks.ts
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.js
  packages/web/src/components/play-bar/mobile/PlayBar.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/deleted-page/DeletedPageProvider.tsx
  packages/web/src/pages/feed-page/FeedPageProvider.js
  packages/web/src/pages/history-page/HistoryPageProvider.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/search-page/SearchPageProvider.js
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/trending-page/TrendingPageProvider.js
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/store/lineup/sagas.js
  packages/web/src/store/queue/mobileSagas.ts
  packages/web/src/store/queue/sagas.ts
Labels: size/L

#1783 [PAY-577] Add "in progress" page to Buy Audio Modal
  packages/common/src/utils/formatUtil.ts
  packages/web/src/components/buy-audio-modal/components/Icons.tsx
  packages/web/src/components/buy-audio-modal/components/InProgressPage.module.css
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
  packages/web/src/components/buy-audio-modal/components/PurchaseQuote.tsx
  packages/web/src/components/collapsible-content/CollapsibleContent.module.css
  packages/web/src/components/collapsible-content/CollapsibleContent.tsx
  packages/web/src/components/collapsible-content/index.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/L

#1785 Dynamically resize ModalContentPages
  packages/stems/src/components/Modal/ModalContentPages.module.css
  packages/stems/src/components/Modal/ModalContentPages.stories.tsx
  packages/stems/src/components/Modal/ModalContentPages.tsx
  packages/stems/src/index.tsx
Labels: size/M

#1788 Fix bug with renamed component
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
  packages/web/src/components/collapsible-content/index.ts
Labels: size/XS

#1787 [PAY-552] Change playllenge challenge button text
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/XS

#1789 Add Text Button type to Stems
  packages/stems/src/components/Button/Button.module.css
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/Button/types.ts
Labels: size/M

#1792 Move sagaHelpers to common
  packages/common/src/utils/index.ts
  packages/common/src/utils/sagaHelpers.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/utils/addUsersFromCollections.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessRemixes.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
  packages/web/src/common/store/cache/tracks/utils/helpers.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/confirmer/sagas.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/service-selection/sagas.ts
  packages/web/src/common/store/ui/artist-recommendations/sagas.ts
  packages/web/src/components/add-to-playlist/store/sagas.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/components/search-bar/store/sagas.ts
  packages/web/src/components/user-list/utils.ts
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
  packages/web/src/pages/collection-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/deactivate-account-page/store/sagas.ts
  packages/web/src/pages/deleted-page/store/lineups/more-by/sagas.ts
  packages/web/src/pages/feed-page/store/lineups/feed/sagas.ts
  packages/web/src/pages/history-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/remixes-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/saved-page/store/sagas.js
  packages/web/src/pages/search-page/store/sagas.js
  packages/web/src/pages/settings-page/store/mobileSagas.ts
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/trending-page/store/lineups/trending/sagas.js
  packages/web/src/pages/trending-playlists/store/lineups/collections/sagas.ts
  packages/web/src/pages/trending-underground/store/lineups/tracks/sagas.ts
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/pages/upload-page/store/utils/sagaHelpers.ts
  packages/web/src/store/application/ui/theme/sagas.ts
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/playlist-library/sagas.ts
  packages/web/src/store/queue/mobileSagas.ts
  packages/web/src/store/queue/sagas.ts
  packages/web/src/store/social/collections/sagas.ts
  packages/web/src/store/social/tracks/sagas.ts
  packages/web/src/store/social/users/sagas.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/wallet/sagas.ts
  packages/web/src/utils/requiresAccount.ts
Labels: size/L

#1793 [C-897] Add explore service to saga context
  packages/common/src/services/explore/Explore.ts
  packages/common/src/services/explore/index.ts
  packages/common/src/services/index.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/services/explore.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/services/explore.ts
  packages/web/src/store/recommendation/sagas.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#1795 [C-900] Move queue, lineup, feed-page sagas to common
  packages/common/src/store/pages/feed/lineup/actions.ts
  packages/common/src/store/storeContext.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/common/store/pages/feed/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/queue/mobileSagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/common/store/queue/store.test.js
  packages/web/src/common/store/recommendation/sagas.ts
  packages/web/src/pages/collection-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/deleted-page/store/lineups/more-by/sagas.ts
  packages/web/src/pages/history-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/remixes-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/saved-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/search-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/smart-collection/store/sagas.ts
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/trending-page/store/lineups/trending/sagas.js
  packages/web/src/pages/trending-playlists/store/lineups/collections/sagas.ts
  packages/web/src/pages/trending-underground/store/lineups/tracks/sagas.ts
  packages/web/src/store/lineup/lineupForRoute.js
  packages/web/src/store/lineup/store.test.js
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#1797 [C-901] Move audioPlayer to saga context
  packages/common/src/services/audio-player.ts
  packages/common/src/services/index.ts
  packages/common/src/store/player/index.ts
  packages/common/src/store/player/selectors.ts
  packages/common/src/store/player/slice.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/queue/store.test.js
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.js
  packages/web/src/components/play-bar/mobile/PlayBar.tsx
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/services/audio-player/AudioPlayer.test.js
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/services/audio-player/NativeMobileAudio.ts
  packages/web/src/services/audio-player/index.ts
  packages/web/src/store/player/sagas.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#1791 [PAY-580] Add Success Page to BuyAudio Modal
  packages/web/src/components/buy-audio-modal/components/SuccessPage.module.css
  packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
Labels: size/L

#1798 [C-902] Move collection page to native
  packages/common/package.json
  packages/common/src/store/pages/collection/actions.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/store/sagas.ts
Labels: size/M

#1794 [PAY-44] Rename getAssociatedTokenAccountInfo and getUserBank
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/audius-backend/waudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#1796 [C-817] Deep link /settings on mobile
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Labels: size/XS

#1801 Add packages/common start cmd
  packages/common/package.json
Labels: size/XS

#1800 Add all the pages to the BuyAudioModal
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
Labels: size/M

#1803 Add ButtonType.TEXT story
  packages/stems/src/components/Button/Button.stories.tsx
Labels: size/XS

#1802 [PAY-589] Add error UI to InProgress page of BuyAudio modal
  packages/common/src/store/ui/buy-audio/selectors.ts
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/web/src/components/buy-audio-modal/components/InProgressPage.module.css
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#1790 Consume new Text button in CollapsibleContent
  packages/web/src/components/buy-audio-modal/components/InProgressPage.module.css
  packages/web/src/components/collapsible-content/CollapsibleContent.module.css
  packages/web/src/components/collapsible-content/CollapsibleContent.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/M

#1805 [C-906] Migrate queue sagas and hls-utils to common
  packages/common/src/store/player/selectors.ts
  packages/common/src/store/player/slice.ts
  packages/common/src/store/queue/slice.ts
  packages/common/src/utils/hls.test.js
  packages/common/src/utils/hls.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/web/src/common/store/player/errorSagas.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/player/store.test.js
  packages/web/src/common/store/queue/mobileSagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/services/audio-player/NativeMobileAudio.ts
  packages/web/src/store/errors/level.ts
  packages/web/src/store/sagas.ts
  packages/web/src/utils/hlsUtil.js
Labels: size/L

#1779 [PAY-479] Check recipient wallet SOL before send
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/pages/token-dashboard/selectors.ts
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/common/src/store/pages/token-dashboard/types.ts
  packages/web/src/pages/audio-rewards-page/components/SendInputConfirmation.module.css
  packages/web/src/pages/audio-rewards-page/components/SendInputConfirmation.tsx
  packages/web/src/store/wallet/sagas.ts
Labels: size/L

#1809 Cleanup from native search PR
  packages/mobile/src/message/handleMessage.ts
  packages/mobile/src/message/handlers/search.ts
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/store/search/actions.ts
  packages/mobile/src/store/search/reducer.ts
  packages/mobile/src/store/search/selectors.ts
  packages/web/src/components/search-bar/SearchBar.tsx
  packages/web/src/services/native-mobile-interface/search.ts
  packages/web/src/utils/nativeRoute.ts
Labels: size/L

#1808 [React Native Reloaded] Make mobile search fully native
  packages/mobile/src/message/handleMessage.ts
  packages/mobile/src/message/handlers/search.ts
  packages/mobile/src/screens/search-results-screen/EmptyResults.tsx
  packages/mobile/src/screens/search-results-screen/SearchQueryContext.ts
  packages/mobile/src/screens/search-results-screen/SearchResultsScreen.tsx
  packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx
  packages/mobile/src/screens/search-results-screen/constants.ts
  packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/useFetchTabResultsEffect.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/mobile/src/screens/search-screen/SearchHistory.tsx
  packages/mobile/src/screens/search-screen/SearchResults.tsx
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/search-screen/content/SeeMoreResultsButton.tsx
  packages/mobile/src/screens/search-screen/utils.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/search/actions.ts
  packages/mobile/src/store/search/reducer.ts
  packages/mobile/src/store/search/selectors.ts
  packages/web/src/common/store/pages/search-page/sagas.js
  packages/web/src/common/store/search-bar/mobileSagas.ts
  packages/web/src/common/store/search-bar/reducer.ts
  packages/web/src/common/store/search-bar/sagas.ts
  packages/web/src/common/store/search-bar/selectors.js
  packages/web/src/common/store/search-bar/selectors.ts
  packages/web/src/components/search-bar/SearchBar.tsx
  packages/web/src/pages/search-page/store/lineups/tracks/sagas.js
  packages/web/src/services/native-mobile-interface/search.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
  packages/web/src/utils/nativeRoute.ts
Labels: size/XL

#1813 Update @audius/sdk to 1.0.0
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1812 Fix lineup types in mobile build
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/lineup/sagas.d.ts
  packages/web/src/common/store/player/sagas.ts
Labels: size/M

#1807 [C-872] Play audio in native
  packages/common/src/services/native-mobile-interface/types.ts
  packages/common/src/store/player/selectors.ts
  packages/common/src/store/queue/slice.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/audio/GoogleCast.tsx
  packages/mobile/src/components/core/PlayBarChin.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileTrackList.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
  packages/mobile/src/components/scrubber/Scrubber.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/web/WebApp.tsx
  packages/mobile/src/message/handleMessage.ts
  packages/mobile/src/message/handlers/audio.ts
  packages/mobile/src/message/types.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/services/audio-player/NativeMobileAudio.ts
  packages/mobile/src/services/audio-player/index.ts
  packages/mobile/src/store/audio/actions.ts
  packages/mobile/src/store/audio/reducer.ts
  packages/mobile/src/store/audio/selectors.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
  packages/mobile/src/store/storeContext.ts
  packages/mobile/src/utils/postMessage.ts
  packages/web/src/common/store/queue/mobileSagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/services/audio-player/NativeMobileAudio.ts
  packages/web/src/services/native-mobile-interface/helpers.ts
  packages/web/src/services/native-mobile-interface/player.ts
  packages/web/src/services/native-mobile-interface/queue.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#1810 [C-778] Native notifications
  packages/common/package.json
  packages/common/src/services/native-mobile-interface/types.ts
  packages/common/src/store/notifications/actions.ts
  packages/mobile/src/hooks/useAppState.ts
  packages/mobile/src/message/handlers/notification.ts
  packages/mobile/src/message/types.ts
  packages/mobile/src/notifications.ts
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/UserNameLink.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FavoriteNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FollowNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RepostNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/store/lifecycle/actions.ts
  packages/mobile/src/store/notifications/actions.ts
  packages/mobile/src/store/notifications/reducer.ts
  packages/mobile/src/store/notifications/sagas.ts
  packages/mobile/src/store/notifications/selectors.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
  packages/web/src/common/store/notifications/errorSagas.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/components/notification/store/mobileSagas.ts
  packages/web/src/services/audio-player/NativeMobileAudio.ts
  packages/web/src/services/native-mobile-interface/index.ts
  packages/web/src/services/native-mobile-interface/notifications.ts
  packages/web/src/services/native-mobile-interface/queue.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/store/notifications/sagas.ts
  packages/web/src/store/sagas.ts
  packages/web/src/utils/nativeRoute.ts
Labels: size/XL

#1814 [C-918] Move trending saga to common
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/pages/collection/actions.ts
  packages/common/src/utils/hashIds.ts
  packages/web/src/common/store/pages/trending/lineups/trending/retrieveTrending.ts
  packages/web/src/common/store/pages/trending/lineups/trending/sagas.js
  packages/web/src/common/store/pages/trending/sagas.js
  packages/web/src/store/sagas.ts
Labels: size/M

#1815 Fix track removal from playlist with entity manager
  packages/web/src/common/store/cache/collections/sagas.js
Labels: size/S

#1817 Follow up fix track removal from playlist with entity manager
  packages/web/src/common/store/cache/collections/sagas.js
Labels: size/S

#1818 [C-926] Migrate explore sagas to common
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/env.ts
  packages/common/src/store/pages/explore/selectors.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/common/store/pages/explore/sagas.ts
  packages/web/src/common/store/pages/track/lineups/sagas.ts
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
  packages/web/src/common/store/pages/trending-playlists/sagas.ts
  packages/web/src/common/store/pages/trending-underground/lineups/sagas.ts
  packages/web/src/common/store/pages/trending-underground/sagas.ts
  packages/web/src/common/store/pages/trending/lineups/trending/retrieveTrending.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/common/store/smart-collection/smartCollections.ts
  packages/web/src/common/utils/requiresAccount.ts
  packages/web/src/components/add-to-playlist/store/sagas.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
  packages/web/src/pages/collectibles-playlist-page/CollectiblesPlaylistPageProvider.tsx
  packages/web/src/pages/collection-page/store/lineups/sagas.js
  packages/web/src/pages/collection-page/store/sagas.js
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/services/env.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#1804 [PAY-590] Add Transaction Details to Store
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/transaction-details/selectors.ts
  packages/common/src/store/ui/transaction-details/slice.ts
  packages/common/src/store/ui/transaction-details/types.ts
Labels: size/L

#1806 [PAY-544] Add Transaction Details Modal
  packages/stems/src/components/IconButton/IconButton.tsx
  packages/stems/src/components/IconButton/types.ts
  packages/web/src/assets/img/LogoCoinbase.svg
  packages/web/src/assets/img/LogoStripe.svg
  packages/web/src/assets/img/iconCoinbaseMini.svg
  packages/web/src/assets/img/iconExternalLink.svg
  packages/web/src/assets/img/iconStripeMini.svg
  packages/web/src/assets/img/iconTransaction.svg
  packages/web/src/components/transaction-details-modal/TransactionDetailsModal.module.css
  packages/web/src/components/transaction-details-modal/TransactionDetailsModal.tsx
  packages/web/src/components/transaction-details-modal/components/Block.module.css
  packages/web/src/components/transaction-details-modal/components/Block.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
  packages/web/src/components/transaction-details-modal/index.ts
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#1821 [C-928] Migrate saved sagas to common
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/pages/saved/lineups/sagas.js
  packages/web/src/common/store/pages/saved/sagas.js
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/components/now-playing/components/ActionsBar.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
  packages/web/src/pages/collection-page/store/sagas.js
  packages/web/src/store/sagas.ts
Labels: size/M

#1822 [C-930] Migrate social sagas to common
  packages/web/src/common/store/social/collections/errorSagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/collections/store.test.js
  packages/web/src/common/store/social/sagas.ts
  packages/web/src/common/store/social/tracks/errorSagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/tracks/store.test.js
  packages/web/src/common/store/social/users/errorSagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/social/users/store.test.js
  packages/web/src/store/sagas.ts
Labels: size/XS

#1827 [PAY-594] Edit 'not enough SOL' error message
  packages/web/src/pages/audio-rewards-page/components/SendInputConfirmation.tsx
Labels: size/XS

#1826 [C-919] Migrate profile sagas to common
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/models/CollectibleState.ts
  packages/common/src/models/OpenSea.ts
  packages/common/src/models/index.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/index.ts
  packages/common/src/services/opensea-client/OpenSeaClient.ts
  packages/common/src/services/opensea-client/ethCollectibleHelpers.ts
  packages/common/src/services/opensea-client/index.ts
  packages/common/src/services/solana-client/SolanaClient.ts
  packages/common/src/services/solana-client/index.ts
  packages/common/src/services/solana-client/solCollectibleHelpers.ts
  packages/common/src/services/solana-client/types.ts
  packages/common/src/store/storeContext.ts
  packages/common/src/types/promise.allsettled/index.d.ts
  packages/common/src/utils/constants.ts
  packages/common/src/utils/fileUtils.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ViewAllSupportingTile.tsx
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/account/mobileSagas.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/pages/signon/mobileSagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/tipping/support/SupportingList.tsx
  packages/web/src/components/tipping/support/TopSupporters.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/audius-backend/fetchCID.ts
  packages/web/src/services/audius-backend/index.ts
  packages/web/src/store/playlist-library/sagas.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/utils/constants.ts
Labels: size/L

#1829 [C-934] Migrate user-list sagas to common
  packages/web/src/common/store/user-list/favorites/sagas.ts
  packages/web/src/common/store/user-list/followers/sagas.ts
  packages/web/src/common/store/user-list/following/sagas.ts
  packages/web/src/common/store/user-list/mutuals/sagas.ts
  packages/web/src/common/store/user-list/reposts/sagas.ts
  packages/web/src/common/store/user-list/supporting/sagas.ts
  packages/web/src/common/store/user-list/top-supporters/sagas.ts
  packages/web/src/common/store/user-list/utils.ts
  packages/web/src/store/sagas.ts
Labels: size/S

#1830 [C-934] Add fully native user lists
  packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
  packages/mobile/src/screens/user-list-screen/MutualsScreen.tsx
  packages/mobile/src/screens/user-list-screen/NotificationUsersScreen.tsx
  packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx
  packages/mobile/src/screens/user-list-screen/SupportingUsersScreen.tsx
  packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
  packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
  packages/mobile/src/store/sagas.ts
Labels: size/L

#1833 [C-703] Fix segmented control font color
  packages/stems/src/components/SegmentedControl/SegmentedControl.module.css
Labels: size/XS

#1835 [C-836] Fix enter on search
  packages/web/src/components/search/SearchBar.js
Labels: size/XS

#1834 [C-916] Native Profile Screen
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/opensea-client/OpenSeaClient.ts
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ViewAllSupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
  packages/mobile/src/screens/profile-screen/utils.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
Labels: size/L

#1836 [Stems] Don't rewrite to /index.html on stems.audius.co
  packages/stems/scripts/workers-site/index.js
Labels: size/XS
