Repository AudiusProject/audius-client, pull requests merged in 2022-11, with the labels that each got.

#2205 Update secondary screen background color
  packages/mobile/src/components/core/Screen/Screen.tsx
Labels: size/M

#2207 [C-1395, C-1398] Add listening history to account drawer
  packages/mobile/src/assets/images/emojis/trophy.png
  packages/mobile/src/assets/images/iconListeningHistory.svg
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/components/core/Screen/SecondaryScreenTitle.tsx
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/settings-screen/CastSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingRowLabel.tsx
  packages/mobile/src/screens/settings-screen/SettingsRow.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
Labels: size/L

#2209 Fix circle-ci restore_cache due to lock-file mispelling
  .circleci/config.yml
Labels: size/XS

#2206 [C-1394] Add uploading and upload-complete screens
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/core/LinearProgress.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/ParamList.ts
  packages/mobile/src/screens/upload-screen/UploadCompleteScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadStackScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadingTrackTile.tsx
  packages/mobile/src/screens/upload-screen/UploadingTracksScreen.tsx
  packages/mobile/src/screens/upload-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/upload-screen/index.tsx
  packages/mobile/src/screens/upload-screen/types.ts
  packages/mobile/src/utils/theme.ts
Labels: size/XL

#2210 [PAY-716] Go to Trending after BuyAudio flow if not opened from Tip
  packages/common/src/store/ui/buy-audio/selectors.ts
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/M

#2211 Fix splashscreen animation glitch when running on hermes
  packages/mobile/src/screens/splash-screen/SplashScreen.tsx
Labels: size/M

#2154 [C-1283][C-1386] Offline Mode - Favorites download and playback
  packages/common/src/models/User.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/assets/images/iconDownloadPurple.svg
  packages/mobile/src/assets/images/iconDownloading.svg
  packages/mobile/src/assets/images/iconNotDownloaded.svg
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/offline-downloads/TrackDownloadIndicator.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/hooks/useOfflineTrackUri.ts
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
  packages/mobile/src/store/store.ts
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/pages/saved/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/track/desktop/TrackTile.module.css
Labels: size/XL

#2214 [C-1315] Remove all references of new tables feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/pages/saved/sagas.js
Labels: size/S

#2213 [C-1145] Update favorites table to use client side sorting and filtering when all tracks are loaded
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/M

#2216 Update README.md
  README.md
Labels: size/XS

#2217 [C-882] Try to fix too often confetti bug
  packages/common/src/models/User.ts
  packages/common/src/store/account/selectors.ts
  packages/common/src/store/account/slice.ts
  packages/common/src/store/challenges/selectors/profile-progress.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/profile-progress/ConnectedProfileCompletionPane.js
Labels: size/L

#2215 [C-1402] Migrate upload store to common
  packages/common/src/store/index.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/upload/actions.ts
  packages/common/src/store/upload/index.ts
  packages/common/src/store/upload/reducer.ts
  packages/common/src/store/upload/selectors.ts
  packages/common/src/store/upload/types.ts
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/upload-page/UploadPage.js
  packages/web/src/pages/upload-page/components/EditPage.js
  packages/web/src/pages/upload-page/components/FinishPage.js
  packages/web/src/pages/upload-page/components/SelectPage.js
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/pages/upload-page/components/TracksPreview.js
  packages/web/src/pages/upload-page/components/uploadType.ts
  packages/web/src/pages/upload-page/store/errorSagas.ts
  packages/web/src/pages/upload-page/store/sagas.js
  packages/web/src/pages/upload-page/store/selectors.ts
  packages/web/src/pages/upload-page/store/types.ts
  packages/web/src/pages/upload-page/store/utils/sagaHelpers.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#2199 Use confirmer wrapper when updating user
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/M

#2221 Fix nethermind configs for mobile
  packages/mobile/.env.stage
  packages/web/.env/.env.stage
Labels: size/XS

#2198 Read artist pick from discovery behind feature flag
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/M

#2220 [C-1414] Implement mobile upload business logic
  packages/common/src/store/upload/selectors.ts
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/ParamList.ts
  packages/mobile/src/screens/upload-screen/UploadCompleteScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadingTrackTile.tsx
  packages/mobile/src/screens/upload-screen/UploadingTracksScreen.tsx
  packages/mobile/src/screens/upload-screen/processTrackFile.ts
  packages/mobile/src/screens/upload-screen/types.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/upload/errorSagas.ts
  packages/web/src/common/store/upload/sagaHelpers.ts
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/store/application/ui/stemsUpload/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#2222 Fix card padding
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
Labels: size/XS

#2224 Remove prefetch first segment functionality
  packages/web/src/common/store/cache/tracks/sagas.js
Labels: size/M

#2225 [C-885] Update mobile environments
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/workflows/mobile.yml
  packages/mobile/README.md
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative.xcodeproj/xcshareddata/xcschemes/Staging.xcscheme
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/114.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/120.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/180.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/29.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/40.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/57.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/58.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/60.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/80.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/87.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/Contents.json
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/114.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/120.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/180.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/29.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/40.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/57.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/58.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/60.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/80.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/87.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/Contents.json
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/120@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/120@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/180@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/40@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/58@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/60@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/80@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/87@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/Contents.json
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/fastlane/Fastfile
  packages/mobile/package.json
Labels: size/L

#2226 [C-1428] Fix tip reactions in notifications tab
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawer.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
Labels: size/M

#2228 [C-1389] Create release-candidate.staging.audius.co
  .circleci/src/jobs/@web-jobs.yml
  .circleci/src/workflows/web.yml
  packages/web/wrangler.toml
Labels: size/S

#2229 [C-1420] Show your owned albums and playlists in favorites
  packages/common/src/store/account/selectors.ts
  packages/mobile/src/screens/favorites-screen/selectors.ts
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
Labels: size/S

#2223 Send handle to relay
  package-lock.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/S

#2230 [C-1424] Finalize v1 upload flow
  packages/common/src/store/upload/types.ts
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/ContextualSubmenu.tsx
  packages/mobile/src/components/core/ErrorText.tsx
  packages/mobile/src/components/core/InputErrorMessage.tsx
  packages/mobile/src/components/core/RadioButton.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/hooks/usePressColorAnimation.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/ParamList.ts
  packages/mobile/src/screens/upload-screen/SelectTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadStackScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadingTracksScreen.tsx
  packages/mobile/src/screens/upload-screen/fields/DescriptionField.tsx
  packages/mobile/src/screens/upload-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/upload-screen/fields/SelectGenreField.tsx
  packages/mobile/src/screens/upload-screen/fields/TextField.tsx
  packages/mobile/src/screens/upload-screen/fields/index.ts
  packages/mobile/src/screens/upload-screen/index.tsx
  packages/mobile/src/screens/upload-screen/processTrackFile.ts
  packages/mobile/src/screens/upload-screen/types.ts
  packages/mobile/src/utils/convertHexToRGBA.ts
  packages/mobile/src/utils/mergeRefs.ts
Labels: size/XL

#2234 [C-1435] Add native TagInput
  packages/mobile/src/assets/images/iconSave.svg
  packages/mobile/src/components/core/TagInput.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/fields/ContextualSubmenuField.tsx
  packages/mobile/src/screens/upload-screen/fields/DescriptionField.tsx
  packages/mobile/src/screens/upload-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/upload-screen/fields/TagField.tsx
  packages/mobile/src/screens/upload-screen/fields/index.ts
Labels: size/L

#2233 Dual write user subscriptions to discovery / identity
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/social/users/actions.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/social/users/errorSagas.ts
  packages/web/src/common/store/social/users/sagas.ts
Labels: size/L

#2232 Update notif navigation hook to handle the push notification payloads from identity
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/hooks/useNotificationNavigation.ts
Labels: size/L

#2236 [C-1422] Implement remix settings upload field
  packages/common/src/services/env.ts
  packages/common/src/store/index.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/remix-settings/index.ts
  packages/common/src/store/remix-settings/selectors.ts
  packages/common/src/store/remix-settings/slice.ts
  packages/mobile/src/assets/images/iconMood.svg
  packages/mobile/src/components/core/ContextualSubmenu.tsx
  packages/mobile/src/components/core/Pill.tsx
  packages/mobile/src/components/core/Switch.tsx
  packages/mobile/src/components/core/TagInput.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/ParamList.ts
  packages/mobile/src/screens/upload-screen/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/components/RemixTrackPill.tsx
  packages/mobile/src/screens/upload-screen/components/index.ts
  packages/mobile/src/screens/upload-screen/fields/ContextualSubmenuField.tsx
  packages/mobile/src/screens/upload-screen/fields/RemixSettingsField.tsx
  packages/mobile/src/screens/upload-screen/fields/SelectGenreField.tsx
  packages/mobile/src/screens/upload-screen/fields/SelectMoodField.tsx
  packages/mobile/src/screens/upload-screen/fields/SubmenuList.tsx
  packages/mobile/src/screens/upload-screen/fields/index.ts
  packages/mobile/src/screens/upload-screen/index.tsx
  packages/mobile/src/screens/upload-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectGenreScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectMoodScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/index.ts
  packages/mobile/src/services/env.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/remix-settings/sagas.ts
  packages/web/src/components/remix-settings-modal/ConnectedRemixSettingsModal.tsx
  packages/web/src/components/remix-settings-modal/store/sagas.ts
  packages/web/src/components/remix-settings-modal/store/selectors.ts
  packages/web/src/services/env.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
Labels: size/XL

#2235 Enable share to stories with dummy assets C-1412
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/web/package-lock.json
Labels: size/M

#2238 [C-1439] Update favorites page styles to align the favorites table
  packages/web/src/components/page/Page.js
  packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css
Labels: size/XS

#2239 [C-1451] Use package.json version number in mobile updateRequired check
  packages/mobile/src/hooks/useUpdateRequired.ts
Labels: size/XS

#2240 [C-1443] Fix error page analytics
  packages/web/src/store/errors/sagas.ts
Labels: size/XS

#2241 [C-1445] Implement track-visibility upload flow
  packages/mobile/src/assets/images/iconIndent.svg
  packages/mobile/src/components/core/ContextualSubmenu.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackStack.tsx
  packages/mobile/src/screens/upload-screen/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadStackScreen.tsx
  packages/mobile/src/screens/upload-screen/fields/AdvancedOptionsField.tsx
  packages/mobile/src/screens/upload-screen/fields/ContextualSubmenuField.tsx
  packages/mobile/src/screens/upload-screen/fields/RemixSettingsField.tsx
  packages/mobile/src/screens/upload-screen/fields/SubmenuList.tsx
  packages/mobile/src/screens/upload-screen/fields/SwitchField.tsx
  packages/mobile/src/screens/upload-screen/fields/TrackVisibilityField.tsx
  packages/mobile/src/screens/upload-screen/fields/index.ts
  packages/mobile/src/screens/upload-screen/screens/AdvancedOptionsScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectGenreScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectMoodScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/TrackVisibilityScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/index.ts
Labels: size/L

#2244 Fix race condition checking stream_mp3 feature flag
  packages/web/src/common/store/player/sagas.ts
Labels: size/XS

#2246 [C-1452] Implement release-date field
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/screens/upload-screen/fields/ReleaseDateField.tsx
  packages/mobile/src/screens/upload-screen/fields/index.ts
  packages/mobile/src/screens/upload-screen/screens/AdvancedOptionsScreen.tsx
Labels: size/L

#2248 [C-1461] Implement license-type/isrc upload flow
  packages/mobile/src/assets/images/creativeCommons/by.svg
  packages/mobile/src/assets/images/creativeCommons/cc.svg
  packages/mobile/src/assets/images/creativeCommons/nc.svg
  packages/mobile/src/assets/images/creativeCommons/nd.svg
  packages/mobile/src/assets/images/creativeCommons/sa.svg
  packages/mobile/src/components/core/ContextualSubmenu.tsx
  packages/mobile/src/components/core/SegmentedControl.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackStack.tsx
  packages/mobile/src/screens/upload-screen/SelectTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/fields/IsrcIswcField.tsx
  packages/mobile/src/screens/upload-screen/fields/LicenseTypeField.tsx
  packages/mobile/src/screens/upload-screen/fields/ReleaseDateField.tsx
  packages/mobile/src/screens/upload-screen/fields/TrackVisibilityField.tsx
  packages/mobile/src/screens/upload-screen/fields/index.ts
  packages/mobile/src/screens/upload-screen/screens/AdvancedOptionsScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/IsrcIswcScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/LicenseTypeScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/index.ts
  packages/mobile/src/screens/upload-screen/utils/computeLicenseIcons.ts
  packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/utils/creativeCommons.ts
Labels: size/XL

#2247 Update push notification types, update notif navigation hook, and remove userInteraction check in onNotification method
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/notifications.ts
Labels: size/L

#2249 [C-1430] Stop propagation on repost button click in tracks tables
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/XS

#2242 v1.4.0
  lerna.json
  package-lock.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#2252 [C-839] Fix playTrack test
  packages/web/src/components/skeleton/Skeleton.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/XS

#2218 [PAY-720] [PAY-721] Stripe OnRamp hotfixes
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/services/Location.ts
Labels: size/M

#2255 Update push notificaiton navigation to work when the app is closed
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/notifications.ts
  packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
Labels: size/M

#2257 [C-1380] Ensure toasts show below dynamic island
  packages/mobile/src/components/toast/ToastView.tsx
Labels: size/XS

#2250 Create gradient video with ffmpeg [C-1446] [C-1413]
  packages/mobile/android/build.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/M

#2254 [C-1440 C-1457 C-1458 C-1459] Address mobile upload QA
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/ContextualSubmenu.tsx
  packages/mobile/src/components/core/InputErrorMessage.tsx
  packages/mobile/src/components/core/Pill.tsx
  packages/mobile/src/components/core/RadioButton.tsx
  packages/mobile/src/components/core/TagInput.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/index.ts
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/screens/upload-screen/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadCompleteScreen.tsx
  packages/mobile/src/screens/upload-screen/UploadingTracksScreen.tsx
  packages/mobile/src/screens/upload-screen/fields/LicenseTypeField.tsx
  packages/mobile/src/screens/upload-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/upload-screen/fields/ReleaseDateField.tsx
  packages/mobile/src/screens/upload-screen/fields/SelectMoodField.tsx
  packages/mobile/src/screens/upload-screen/fields/SubmenuList.tsx
  packages/mobile/src/screens/upload-screen/fields/TagField.tsx
  packages/mobile/src/screens/upload-screen/fields/TextField.tsx
  packages/mobile/src/screens/upload-screen/screens/AdvancedOptionsScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/LicenseTypeScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectGenreScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectMoodScreen.tsx
Labels: size/L

#2261 Add audio preview to share to IG video [C-1464]
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/S

#2256 [C-1463] Fix android builds
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/L

#2263 [C-1467] Make previous button restart track within 3 seconds
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Labels: size/M

#2266 [ARCH-1996] hotfix: takeLatest was registering after action already fired
  packages/web/src/common/store/pages/saved/sagas.js
Labels: size/XS

#2245 [PAY-695] Get signatures for nft-gated premium tracks
  packages/common/src/models/Track.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/premiumContent/actions.ts
  packages/web/src/common/store/premiumContent/reducer.ts
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/common/store/premiumContent/selectors.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
Labels: size/L

#2264 [C-1486] Remove mobile-nav-overhaul feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/components/core/Screen/ScreenHeader.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/app-drawer-screen/useAppDrawerNavigation.ts
  packages/mobile/src/screens/app-screen/AppScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
  packages/mobile/src/screens/notifications-screen/NotificationsDrawer.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerScreen.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/TopBar.tsx
  packages/mobile/src/screens/notifications-screen/index.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
Labels: size/XL

#2259 [C-1482] Fix visualizer on mp3 stream
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/M

#2231 [C-981] Add suggested follows to feed if empty
  packages/mobile/src/components/core/SectionList.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
  packages/mobile/src/components/suggested-follows/index.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/signon/FirstFollows.tsx
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/pages/feed-page/components/EmptyFeed.js
Labels: size/XXL

#2272 Bump stems limit from 5 to 10
  packages/web/src/components/source-files-modal/SourceFilesModal.tsx
Labels: size/XS

#2262 [Flare-120] Avoid hitting notification settings on each session
  packages/mobile/src/store/notifications/sagas.ts
  packages/web/src/store/notifications/sagas.ts
Labels: size/XS

#2273 Fix mobile seek
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/XS

#2258 Read subscriptions from discovery behind feature flag
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#2271 [C-1493] Add script to update @audius/sdk
  package.json
Labels: size/XS

#2268 Fix makeStyles types
  packages/common/src/utils/typeUtils.ts
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/styles/makeStyles.ts
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
Labels: size/L

#2274 [C-1494] Listens not being recorded properly?
  packages/common/src/store/player/slice.ts
  packages/web/src/common/store/player/sagas.ts
Labels: size/XS

#2253 [C-1419][C-1073] Offline download and playback for collections
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/offline-downloads/index.ts
  packages/mobile/src/components/offline-placeholder/OfflinePlaceholder.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/hooks/useIsOfflineModeEnabled.ts
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/hooks/useOfflineTrackUri.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/XL

#2275 [C-1495] Bump target api to 31
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/build.gradle
Labels: size/S

#2276 Fix various lock files
  package-lock.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
Labels: size/S

#2277 [C-1514] Prevent next track playing when playback is paused
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/XS

#2278 [C-1496 C-1497 C-1498,C-1499 C-1501 C-1502 C-1503] Address Design-QA
  packages/mobile/src/components/core/TagInput.tsx
  packages/mobile/src/screens/list-selection-screen/index.ts
  packages/mobile/src/screens/upload-screen/screens/ListSelectionScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectGenreScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectMoodScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Labels: size/L

#2269 Wait for backend account for BuyAudio feature flag
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XS

#2280 [C-1515] Allow repeat pushes via useNavigation inside nested navigator
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/utils/navigation.ts
Labels: size/M

#2279 [PAY-724] Special Error Treatment and libs/sdk bump to 1.0.23
  packages/common/src/models/Analytics.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/errorSagas.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/something-wrong/SomethingWrong.tsx
  packages/web/src/store/errors/actions.ts
  packages/web/src/store/errors/reducers.ts
  packages/web/src/store/errors/selectors.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/M

#2281 [C-1239] Fix bottom-tab-bar highlighting
  packages/mobile/src/components/core/AnimatedButton.tsx
Labels: size/S

#2283 [C-1399] Fix chromecast
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/audio/GoogleCast.tsx
Labels: size/M

#2284 [C-1527] Hide tip tile when no tips
  packages/web/src/common/store/tipping/sagas.ts
Labels: size/XS

#2282 [PAY-731] Update streaming logic for premium content
  packages/common/src/services/audio-player.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/index.ts
  packages/common/src/store/premiumContent/actions.ts
  packages/common/src/store/premiumContent/index.ts
  packages/common/src/store/premiumContent/reducer.ts
  packages/common/src/store/premiumContent/selectors.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/premiumContentUtils.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/common/store/premiumContent/selectors.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/store/reducers.ts
Labels: size/L

#2285 [C-1505 C-1507 C-1510 C-1511 C-1512] Address Design-QA round 2
  packages/common/src/store/upload/types.ts
  packages/mobile/src/components/core/TagInput.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/hooks/useDrawer.ts
  packages/mobile/src/screens/upload-screen/components/CancelUploadDrawer.tsx
  packages/mobile/src/screens/upload-screen/components/UploadingTrackTile.tsx
  packages/mobile/src/screens/upload-screen/components/index.ts
  packages/mobile/src/screens/upload-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen/CompleteTrackForm.tsx
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen/CompleteTrackStack.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#2288 Fix locks again
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
Labels: size/S

#2290 Fix premium content types
  packages/common/src/store/index.ts
  packages/common/src/store/premium-content/actions.ts
  packages/common/src/store/premium-content/index.ts
  packages/common/src/store/premium-content/reducer.ts
  packages/common/src/store/premium-content/selectors.ts
  packages/common/src/store/reducers.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/store/types.ts
Labels: size/M

#2291 [C-1509] Add input-accessory-view
  packages/mobile/src/components/core/TextInput.tsx
Labels: size/M

#2289 [C-1411] Improve loading splash
  packages/common/src/store/reachability/reducer.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/com/audiusreactnative/MainActivity.java
  packages/mobile/android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  packages/mobile/android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  packages/mobile/android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  packages/mobile/android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  packages/mobile/android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  packages/mobile/android/app/src/main/res/values/colors.xml
  packages/mobile/android/app/src/main/res/values/styles.xml
  packages/mobile/android/build.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/AppDelegate.m
  packages/mobile/ios/AudiusReactNative/Base.lproj/LaunchScreen.xib
  packages/mobile/ios/AudiusReactNative/BootSplash.storyboard
  packages/mobile/ios/AudiusReactNative/Images.xcassets/BootSplashLogo.imageset/Contents.json
  packages/mobile/ios/AudiusReactNative/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/src/assets/images/bootsplash_logo.png
  packages/mobile/src/assets/images/bootsplash_logo.svg
  packages/mobile/src/assets/images/bootsplash_logo@1,5x.png
  packages/mobile/src/assets/images/bootsplash_logo@2x.png
  packages/mobile/src/assets/images/bootsplash_logo@3x.png
  packages/mobile/src/assets/images/bootsplash_logo@4x.png
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/screens/account-screen/AccountDrawer.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/splash-screen/SplashScreen.tsx
  packages/mobile/src/screens/splash-screen/index.ts
  packages/mobile/src/screens/splash-screen/useSplashScreenKey.ts
  packages/mobile/src/utils/zIndex.ts
  packages/web/src/common/store/account/sagas.js
Labels: size/L

#2293 [C-1535] Add mobile-upload analytics, fix remix field
  packages/common/src/schemas/index.ts
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/edit-track-screen/EditExistingTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/fields/RemixSettingsField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/types.ts
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
Labels: size/L

#2295 Improve mobile image fetching
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/artist-card/ArtistCard.tsx
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/collection-card/CollectionCard.tsx
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/core/FormImageInput.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/ImageLoader.tsx
  packages/mobile/src/components/image/PlaylistImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/image/UserCoverImage.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileArt.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/styles.ts
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/scrubber/Scrubber.tsx
  packages/mobile/src/components/skeleton/Skeleton.tsx
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
  packages/mobile/src/components/track-list/TrackArtwork.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/hooks/useCollectionCoverArt.ts
  packages/mobile/src/hooks/useContentNodeImage.ts
  packages/mobile/src/hooks/useTrackCoverArt.ts
  packages/mobile/src/hooks/useUserCoverPhoto.ts
  packages/mobile/src/hooks/useUserProfilePicture.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditExistingTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/RemixTrackPill.tsx
  packages/mobile/src/screens/edit-track-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/upload-screen/components/UploadingTrackTile.tsx
Labels: size/XXL

#2294 [C-1404] Add initial mobile wallet-connect
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/hooks/useAsyncStorage.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/wallet-connect/ConfirmWalletConnectionScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectStack.tsx
  packages/mobile/src/screens/wallet-connect/index.ts
  packages/mobile/src/screens/wallet-connect/types.ts
  packages/mobile/src/screens/wallet-connect/utils.ts
Labels: size/L

#2297 [C-1534] Use navigation.navigate for search
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/XS

#2300 Hide bootsplash earlier
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/splash-screen/SplashScreen.tsx
Labels: size/XS

#2301 Bump android ci image size
  .circleci/src/jobs/@mobile-jobs.yml
Labels: size/XS

#2302 Fix edit images
  packages/mobile/src/components/core/FormImageInput.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditExistingTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/fields/PickArtworkField.tsx
Labels: size/S

#2305 iOS fast follows
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
Labels: size/XS

#2304 [C-1531] Remove open in app from landing page
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
  packages/web/src/devUtils/useRenderingTrace.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/landing-page/LandingPage.tsx
Labels: size/S

#2286 [C-1326] Fix open in app drawer to open the app properly
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
Labels: size/S

#2306 Bump ios
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2307 [C-1549] Fix mobile share-drawer
  packages/common/src/store/ui/share-modal/selectors.ts
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/S

#2308 Bump ios version to 1.1.41, format plist
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/L

#2309 Fix android double play
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Labels: size/M

#2311 [Share to IG] Add waves to IG video; increase quality C-1473
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/XS

#2312 [C-1536] Update icons and display names
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/114.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/120.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/180.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/29.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/40.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/57.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/58.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/60.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/80.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/87.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/114.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/120.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/180.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/29.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/40.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/57.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/58.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/60.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/80.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/87.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/114.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/120.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/120@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/120@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/180.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/180@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/29.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/40.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/40@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/57.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/58.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/58@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/60.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/60@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/80.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/80@2x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/87.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/87@3x.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/Contents.json
Labels: size/M

#2287 [C-1069] Use persistent queue for offline downloads
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2314 Fix android search input style
  packages/mobile/src/components/core/TextInput.tsx
Labels: size/XS

#2316 [QA-223] Close notification panel when clicking entity link
  packages/web/src/components/notification/Notification/components/EntityLink.tsx
Labels: size/S

#2310 [C-1548] Integrate native WalletConnect
  package-lock.json
  package.json
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/assets/images/iconPhantom.svg
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/transfer-audio-mobile-drawer/TransferAudioMobileDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectStack.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletsDrawer.tsx
  packages/mobile/src/screens/wallet-connect/components/index.ts
  packages/mobile/src/store/drawers/slice.ts
Labels: size/XL

#2315 [C-1559] Fix audio-breakdown-drawer
  packages/common/src/store/pages/token-dashboard/types.ts
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/audio-breakdown-drawer/Wallet.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/L

#2313 [C-1550] Improve left-nav open/close animation
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/account-screen/index.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavLink.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/index.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/L

#2318 Fix logged out offline startup
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/S

#2319 Always fetch content node images from cache
  packages/mobile/src/hooks/useContentNodeImage.ts
Labels: size/XS

#2320 [C-1565 C-1566 C-1567] Improve upload copy, colors
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/fields/PickArtworkField.tsx
  packages/mobile/src/screens/profile-screen/UploadTrackButton.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
Labels: size/M

#2322 Finalize mobile-upload feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/edit-track-screen/fields/PickArtworkField.tsx
Labels: size/XS

#2325 [QA-225] Fix flashing uploading track cover art
  packages/mobile/src/screens/upload-screen/components/UploadingTrackTile.tsx
Labels: size/XS

#2324 [C-1572] Add react-native-threads, dominantColors thread
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/com/audiusreactnative/MainApplication.java
  packages/mobile/android/settings.gradle
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/threads/getDominantColors.ts
  packages/mobile/threads/dominantColors.thread.js
  packages/mobile/threads/jimp.min.js
Labels: size/L

#2321 Fix mac build
  .circleci/src/jobs/@web-jobs.yml
  package-lock.json
  packages/common/package.json
  packages/web/package.json
Labels: size/XS

#2326 Update react native music control
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/XS

#2327 [C-1586] Null check image source in EditProfileScreen
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
Labels: size/XS

#2330 [hotfix]: Location detection fix
  packages/web/src/services/Location.ts
Labels: size/XS
