Repository AudiusProject/audius-client, pull requests merged in 2022-04, with the labels that each got.

#1153 [AUD-1784] Fix offline indicator state and pointer events
  packages/mobile/src/components/reachability-bar/ReachabilityBar.tsx
Labels: size/S

#1152 [AUD-1805] Remove lazy screen option for profile
  packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
Labels: size/S

#1155 [AUD-1810] Add docs to run local libs in audius-client
  packages/web/README.md
Labels: size/S

#1154 [AUD-1781] Fix issue with feed not loading after sign in
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/S

#1157 Consume libs 1.2.101
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/models/Analytics.ts
  packages/web/src/services/audius-backend/Rewards.ts
Labels: size/M

#1160 [AUD-1806] Update SegmentedControl component to set initial width and left position
  packages/mobile/src/components/core/SegmentedControl.tsx
Labels: size/M

#1159 [AUD-1784] Fix ReachabilityBar height
  packages/mobile/src/components/reachability-bar/ReachabilityBar.tsx
Labels: size/XS

#1161 Fix reachability-bar reachable state
  packages/mobile/src/components/reachability-bar/ReachabilityBar.tsx
Labels: size/XS

#1165 Consume libs 1.2.102
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1166 [AUD-1700] Remove TRENDING_UNDERGROUND feature flag
  packages/web/src/common/services/remote-config/feature-flags.ts
Labels: size/XS

#1164 Remove userbank signup creation flag
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/audius-backend/waudio.ts
Labels: size/S

#1158 [AUD-1812] Prevent unnecessary store syncs
  packages/web/src/common/store/notifications/reducer.ts
  packages/web/src/common/store/pages/audio-rewards/slice.ts
Labels: size/M

#1167 [AUD-1817] Fix PlayBar opacity
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
Labels: size/XS

#1169 [AUD-1823] Update play button to use staticWhite color unless using matrix theme
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
Labels: size/S

#1170 Fix libs browser config
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1173 Version bump
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1171 [AUD-1800] Remove pull-to-refresh on track screen
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/PullToRefresh.tsx
  packages/mobile/src/components/core/SectionList.tsx
Labels: size/M

#1172 [AUD-1824] Improve track-tile skeleton transition
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
Labels: size/XS

#1174 [AUD-1820] Prevent Tiles from triggering when scrolling
  packages/mobile/package-lock.json
  packages/mobile/src/components/core/Pressable.tsx
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
Labels: size/M

#1175 Remove react-native-shadow-2 from tiles to improve performance
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/components/core/Tile/TileShadow.tsx
  packages/mobile/src/styles/index.ts
  packages/mobile/src/styles/shadow.ts
Labels: size/L

#1176 Fix audio screen bottom padding
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/S

#1177 [AUD-1852] Fix opacity interpolation for the mobile tracking bar
  packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
Labels: size/XS

#1178 [AUD-1851,AUD-1847] Fix badge gradient, account settings button variant
  packages/mobile/src/components/audio-rewards/index.ts
  packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsItem.tsx
Labels: size/S

#1180 [AUD-1807] Fix Chromecast permissions
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
Labels: size/S

#1182 [AUD-1853] Reduce lag on play
  packages/mobile/babel.config.js
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
  packages/mobile/src/hooks/useSelectTierInfo.ts
  packages/mobile/src/screens/notifications-screen/List.tsx
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/store/audio/selectors.ts
Labels: size/L

#1184 [AUD-1843] Update styles for deleted track list items
  packages/mobile/src/components/track-list/TrackListItem.tsx
Labels: size/S

#1183 Upgrade libs to 1.2.105, adds constants patch
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/LocalStorage.ts
  packages/web/src/types/libs/libs.d.ts
Labels: size/S

#1179 Upgrade xcode version
  .circleci/src/jobs/@mobile-jobs.yml
  packages/mobile/src/screens/settings-screen/SettingsRowDescription.tsx
  packages/web/src/components/bottom-bar/BottomBar.tsx
Labels: size/XS

#1185 [AUD-1857] Fix issue with scrolling to bottom of Lineup
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/M

#1162 Allow confirmer calls to be parallelized and squashed + allow consolidation of success callbacks
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/types.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/reducer.js
  packages/web/src/components/confirmer-preview/ConfirmerPreview.tsx
  packages/web/src/components/dragndrop/Draggable.js
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/store/configureStore.ts
  packages/web/src/store/confirmer/actions.js
  packages/web/src/store/confirmer/actions.ts
  packages/web/src/store/confirmer/reducer.js
  packages/web/src/store/confirmer/reducer.ts
  packages/web/src/store/confirmer/sagas.js
  packages/web/src/store/confirmer/sagas.ts
  packages/web/src/store/confirmer/selectors.js
  packages/web/src/store/confirmer/selectors.ts
  packages/web/src/store/confirmer/store.test.js
  packages/web/src/store/confirmer/store.test.ts
  packages/web/src/store/confirmer/types.ts
Labels: size/XXL

#1189 [AUD-1845] Configure deep linking
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/components/web/WebApp.tsx
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/app-screen/FavoritesTabScreen.tsx
  packages/mobile/src/screens/app-screen/FeedTabScreen.tsx
  packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
  packages/mobile/src/screens/app-screen/TrendingTabScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/L

#1188 [AUD-1858] Move isPlayingUid logic back into TrackTile and CollectionTile and fix Collectiontile play-pause logic
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/M

#1104 Deprecate icon button from client in favor of stems
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/components/icon-button/IconButton.module.css
  packages/web/src/components/icon-button/IconButton.tsx
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/components/notification/components/mobile/Announcement.tsx
  packages/web/src/components/notification/components/mobile/Notification.tsx
  packages/web/src/components/now-playing/components/ActionsBar.tsx
  packages/web/src/components/popup-menu-icon-button/PopupMenuIconButton.tsx
  packages/web/src/components/source-files-modal/SourceFilesModal.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/pages/profile-page/components/mobile/ShareUserButton.tsx
  packages/web/src/pages/track-page/components/mobile/ActionButtonRow.tsx
Labels: size/L

#1194 [AUD-1787] Hyperlink scroll
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
Labels: size/L

#1195 [AUD-1855] Improve drawer performance
  packages/web/src/store/configureStore.ts
Labels: size/M

#1196 [AUD-1862] Add DeletePlaylistConfirmationDrawer
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/delete-playlist-confirmation-drawer/DeletePlaylistConfirmationDrawer.tsx
  packages/mobile/src/components/delete-playlist-confirmation-drawer/index.ts
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/ui/delete-playlist-confirmation-modal/actions.ts
  packages/web/src/common/store/ui/delete-playlist-confirmation-modal/reducers.ts
  packages/web/src/common/store/ui/delete-playlist-confirmation-modal/sagas.ts
  packages/web/src/common/store/ui/delete-playlist-confirmation-modal/selectors.ts
  packages/web/src/common/store/ui/delete-playlist-confirmation-modal/slice.ts
  packages/web/src/common/store/ui/modals/slice.ts
  packages/web/src/components/delete-playlist-confirmation-modal/DeletePlaylistConfirmationModal.tsx
  packages/web/src/components/delete-playlist-confirmation-modal/components/DeletePlaylistConfirmationModal.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#1198 Add back state sync debounce
  packages/web/src/store/configureStore.ts
Labels: size/M

#1203 [AUD-1890] Add formatting for profile stats
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
Labels: size/XS

#1202 [AUD-1885] Enable full screen drawer swipe and disable on stack pages
  packages/mobile/src/hooks/useIsStackOpen.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/utils/navigation.ts
Labels: size/M

#1199 [AUD-1883] Fix trending genre selection
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/web/src/common/store/pages/trending/lineup/actions.ts
  packages/web/src/common/store/pages/trending/lineup/reducer.ts
Labels: size/M

#1200 [AUD-1886] Fix search results refresh
  packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
Labels: size/XS

#1201 [AUD-1884] Fix scrollTo bug on initial scroll
  packages/mobile/src/components/core/PullToRefresh.tsx
Labels: size/XS

#1193 [AUD-1861] Minor release styling and fixes
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileRoot.tsx
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
Labels: size/L

#1205 [AUD-1859] Fix lock screen media controls when chromecasting
  packages/mobile/ios/AudiusReactNative/AppDelegate.m
  packages/mobile/src/components/audio/GoogleCast.tsx
Labels: size/S

#1207 [AUD-1896] Fix text on remixes lineup
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
Labels: size/XS

#1206 [AUD-1848] Improve app layout when PlayBar active
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/PlayBarChin.tsx
  packages/mobile/src/components/core/ScrollView.tsx
  packages/mobile/src/components/core/SectionList.tsx
  packages/mobile/src/components/core/VirtualizedScrollView.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/with-loader/WithLoader.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
  packages/mobile/src/screens/notifications-screen/List.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/screens/search-screen/SearchResults.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
Labels: size/L

#1208 [AUD-1891] Fix Profile left header, back button
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/S

#1210 Remove extraneous goBack in appScreenOptions
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/XS

#1211 [AUD-1897] Add haptics to follow/subscribe buttons
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/favorite-button/FavoriteButton.tsx
  packages/mobile/src/components/now-playing-drawer/FavoriteButton.tsx
  packages/mobile/src/components/now-playing-drawer/RepeatButton.tsx
  packages/mobile/src/components/now-playing-drawer/RepostButton.tsx
  packages/mobile/src/components/now-playing-drawer/ShuffleButton.tsx
  packages/mobile/src/components/repost-button/RepostButton.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
Labels: size/L

#1212 Allow TrackTile click in the action button section
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
Labels: size/XS

#1213 Silently disable play button on track screen until the lineup loads
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#1215 [AUD-1898] Fix overlap at bottom of lineup
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/M

#1214 [AUD-1894] Remix Lineup fixes
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
  packages/web/src/common/store/pages/track/lineup/reducer.js
Labels: size/L

#1216 [AUD-1902] Fix scroll to end of lineup on profile page
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/SectionList.tsx
Labels: size/S

#1218 Prevent ColorTile presses when swiping
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
Labels: size/XS

#1219 Fix various swipe issues
  packages/mobile/patches/react-native+0.66.3.patch
  packages/mobile/patches/react-native-pager-view+5.4.6.patch
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/M

#1220 Fix track not playable bug
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/track-page/store/sagas.js
Labels: size/L

#1221 [AUD-1899] Reduce notif rerenders on navigation
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/notifications-screen/content/Entity.tsx
  packages/mobile/src/screens/notifications-screen/content/User.tsx
  packages/mobile/src/screens/notifications-screen/content/UserImages.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
Labels: size/M

#1222 [AUD-1905 AUD-1907] Add small fixes to mobile UserList
  packages/mobile/src/screens/user-list-screen/UserChip.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
Labels: size/XS

#1223 Improve profile social loading and cls
  packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
Labels: size/S

#1225 Consolidate loading spinner
  packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
Labels: size/M

#1217 Consume Libs 1.2.107
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1224 [AUD-1888] Notification transitions
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/transitionSpec.ts
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/content/Entity.tsx
  packages/mobile/src/screens/notifications-screen/content/User.tsx
  packages/mobile/src/screens/notifications-screen/content/UserImages.tsx
  packages/mobile/src/screens/notifications-screen/routeUtil.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Labels: size/L

#1226 Notifications transitions pt 2
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
Labels: size/S

#1227 [AUD-1906] Make artist suggestions pressable
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistLink.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
Labels: size/M

#1228 [AUD-1916] Improve makeStyles perf
  packages/mobile/src/styles/makeStyles.ts
Labels: size/M

#1231 Reduce the delay for the lineup metadata saga
  packages/web/src/store/lineup/sagas.js
Labels: size/XS

#1230 Fix swipe on first tab
  packages/mobile/patches/@react-navigation+drawer+6.3.1.patch
Labels: size/S

#1232 Rename trending ThisYear to AllTime
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Labels: size/XS

#1233 [AUD-1904] Use high res artwork on NowPlaying
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
Labels: size/XS

#1235 [AUD-1927] Vertically align user badges on now playing
  packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
Labels: size/XS

#1229 Revert "Fix track not playable bug (#1220)"
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/track-page/store/sagas.js
Labels: size/L

#1236 Fix behavior of track screen play button
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/M

#1239 [AUD-1921] Don't render ArtistRecommendations when empty
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
Labels: size/XS

#1238 [AUD-1920] Fix TrendingRewardsDrawer navigation
  packages/mobile/src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
  packages/mobile/src/components/button-with-arrow/ButtonWithArrow.tsx
  packages/mobile/src/components/button-with-arrow/index.ts
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
Labels: size/L

#1237 Update lineup saga delay up to 100ms to avoid flakeyness
  packages/web/src/store/lineup/sagas.js
Labels: size/XS

#1240 [AUD-1922] Replace search with share-profile on profile screen
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/S

#1241 [AUD-1930] Avoid showing content that gets a 403 (stop-gap)
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/cache/reducer.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/services/AudiusBackend.js
Labels: size/M

#1243 Add haptics to other play buttons
  packages/mobile/src/components/details-tile/DetailsTile.tsx
Labels: size/XS

#1247 [C-405] Fix legacy android build profile freeze
  packages/mobile/src/components/audio-rewards/TierText.tsx
Labels: size/XS

#1248 [C-293, AUD-1936] Fix track scrubber gestures
  packages/mobile/src/components/scrubber/Slider.tsx
Labels: size/S

#1249 [C-366] Remove antd Spin component and replace with LoadingSpinner
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/nav/desktop/NavButton.js
  packages/web/src/components/nav/desktop/NavButton.module.css
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.module.css
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/CollectionsPage.module.css
  packages/web/src/pages/explore-page/components/mobile/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.module.css
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/history-page/components/desktop/HistoryPage.module.css
  packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.module.css
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/requires-update/RequiresUpdate.module.css
  packages/web/src/pages/requires-update/RequiresUpdate.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.module.css
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.module.css
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.module.css
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
  packages/web/src/pages/sign-on/components/LoadingPage.js
  packages/web/src/pages/sign-on/components/LoadingPage.module.css
Labels: size/L

#1242 Bump resource class size
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
Labels: size/S

#1250 [C-316] Fix user-list background and spinner
  packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
  packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
Labels: size/M

#1234 Fix waudio amount check and error message
  packages/web/src/store/wallet/sagas.ts
Labels: size/XS

#1246 [C-403] Fix lineup with artist pick
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/web/src/common/models/Lineup.ts
  packages/web/src/common/store/lineup/actions.ts
  packages/web/src/common/store/lineup/reducer.ts
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/search-results/reducer.ts
  packages/web/src/components/lineup/Lineup.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/store/lineup/sagas.js
Labels: size/M

#1253 Upgrade libs to 1.2.112, use core entrypoint
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/AudiusBackend.js
  packages/web/src/services/LocalStorage.ts
Labels: size/S

#1256 [C-375] Remove antd from mobile CollectionHeader
  packages/web/src/components/collection/mobile/CollectionHeader.js
  packages/web/src/components/collection/mobile/CollectionHeader.module.css
Labels: size/S

#1251 Fix "More by artist" not updating correctly after track play bug fix
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.js
  packages/web/src/pages/track-page/store/lineups/tracks/sagas.ts
  packages/web/src/pages/track-page/store/sagas.js
Labels: size/L

#1257 [C-370] Remove Tabs component
  packages/web/src/components/navigation/Tabs.js
  packages/web/src/components/navigation/Tabs.module.css
Labels: size/L

#1258 [C-419] Fix react native Android profile screen crash
  packages/mobile/package-lock.json
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
Labels: size/S

#1260 [C-412] Set title alignment
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/XS

#1262 [C427] Fix malformed js calls error
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/XS

#1263 [C-362] Remove antd from mobile ProfileHeader
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
Labels: size/M

#1264 Remove mobile SkeletonTile
  packages/web/src/components/track/mobile/SkeletonTile.module.css
  packages/web/src/components/track/mobile/SkeletonTile.tsx
Labels: size/L

#1265 [C-414] Fix size of PlayButton on android
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
Labels: size/XS

#1267 [C-421] Fix play button state on android
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
  packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
Labels: size/M

#1269 [C-420] Remove header back button on android
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/XS

#1259 [AUD-1645] Prevent app error on resize
  packages/web/src/components/nav/store/context.tsx
Labels: size/XS

#1268 [C-372 C-376] Add Input component and remove antd input from collection header and filter input
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/filter-input/FilterInput.module.css
  packages/web/src/components/filter-input/FilterInput.tsx
  packages/web/src/components/input/Input.module.css
  packages/web/src/components/input/Input.tsx
  packages/web/src/components/input/index.ts
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/default.ts
  packages/web/src/utils/theme/matrix.ts
Labels: size/L

#1270 [C-431] Fix trending terms link
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/styles/typography.ts
Labels: size/M
