Repository AudiusProject/audius-client, pull requests merged in 2022-09, with the labels that each got.

#1840 Update deactivate copy
  packages/mobile/src/components/deactivate-account-confirmation-drawer/DeactivateAccountConfirmationDrawer.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/web/src/pages/deactivate-account-page/DeactivateAccountPage.tsx
Labels: size/S

#1838 [C-939] Refactor discord modal
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/vip-discord-modal/sagas.ts
  packages/common/src/store/ui/vip-discord-modal/selectors.ts
  packages/common/src/store/ui/vip-discord-modal/slice.ts
  packages/common/src/store/ui/vip-discord-modal/types.ts
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/discord-drawer/index.ts
  packages/mobile/src/components/vip-discord-drawer/VipDiscordDrawer.tsx
  packages/mobile/src/components/vip-discord-drawer/index.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/pages/audio-rewards-page/WalletModal.module.css
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/pages/audio-rewards-page/components/DiscordModalBody.module.css
  packages/web/src/pages/audio-rewards-page/components/DiscordModalBody.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/VipDiscordModal.module.css
  packages/web/src/pages/audio-rewards-page/components/modals/VipDiscordModal.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/L

#1837 [PAY-507] Fix feed tip tile tip button resizing
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
Labels: size/L

#1841 [PAY-591] Improve supporter count visibility
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
Labels: size/S

#1843 [C-877] Make tooltips use updated colors when theme is applied
  packages/web/src/components/co-sign/CoSign.tsx
  packages/web/src/components/profile-progress/components/ProfileCompletionTooltip.js
  packages/web/src/components/tooltip/Tooltip.module.css
  packages/web/src/components/tooltip/Tooltip.tsx
  packages/web/src/components/tooltip/types.ts
  packages/web/src/utils/theme/theme.ts
Labels: size/M

#1844 [C-957] Fix autocomplete when signed out
  packages/web/src/components/search-bar/store/sagas.ts
Labels: size/XS

#1832 [PAY-598] Prepopulate TransactionDetails after purchasing $AUDIO
  packages/common/src/store/ui/transaction-details/types.ts
  packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
  packages/web/src/components/transaction-details-modal/TransactionDetailsModal.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XL

#1845 Add reordering to new tables for playlists
  packages/web/src/components/test-table/TestTable.module.css
  packages/web/src/components/test-table/TestTable.tsx
  packages/web/src/components/test-table/components/OverflowMenuButton.tsx
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/L

#1847 Split up sign-out saga to web and native
  packages/common/src/store/sign-out/slice.ts
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/settings/sagas.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/common/store/pages/settings/errorSagas.ts
  packages/web/src/common/store/pages/settings/sagas.ts
  packages/web/src/common/store/sign-out/sagas.ts
  packages/web/src/components/nav/mobile/SignOut.tsx
  packages/web/src/pages/deactivate-account-page/store/sagas.ts
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/store/sagas.ts
  packages/web/src/services/native-mobile-interface/lifecycle.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/sign-out/sagas.ts
  packages/web/src/store/sign-out/signOut.ts
Labels: size/L

#1848 [C-955] Fully native settings screen
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/CastSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/EmailFrequencyControlRow.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/screens/settings-screen/NotificationRow.tsx
  packages/mobile/src/store/application/ui/theme/sagas.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/theme.ts
  packages/web/src/common/store/pages/history/lineups/sagas.js
  packages/web/src/common/store/pages/history/sagas.js
  packages/web/src/pages/history-page/store/sagas.js
  packages/web/src/store/sagas.ts
Labels: size/L

#1842 Bump SDK to v1.0.1
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1851 [C-937] Refactor theme state, Implement native theme
  packages/common/src/models/Theme.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/theme/actionTypes.ts
  packages/common/src/store/ui/theme/actions.ts
  packages/common/src/store/ui/theme/reducer.ts
  packages/common/src/store/ui/theme/selectors.ts
  packages/common/src/store/ui/theme/slice.ts
  packages/common/src/store/ui/theme/types.ts
  packages/mobile/src/App.tsx
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/components/theme/ThemeContext.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/mobile/src/store/application/ui/theme/sagas.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/theme/sagas.ts
  packages/mobile/src/styles/makeStyles.ts
  packages/mobile/src/theme.ts
  packages/mobile/src/utils/theme.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/services/native-mobile-interface/android/theme.ts
  packages/web/src/services/native-mobile-interface/theme.ts
  packages/web/src/store/application/ui/theme/sagas.ts
  packages/web/src/utils/theme/theme.ts
Labels: size/XL

#1852 [C-959] Migrate tipping sagas
  packages/common/src/services/audius-backend/Tipping.ts
  packages/common/src/services/audius-backend/index.ts
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/message/handlers/tipping.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/tipping/storageUtils.ts
  packages/web/src/common/store/tipping/mobileSagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/tipping/storageUtils.ts
  packages/web/src/common/store/user-list/supporting/sagas.ts
  packages/web/src/common/store/user-list/top-supporters/sagas.ts
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/tipping/storageUtils.ts
  packages/web/src/utils/constants.ts
Labels: size/L

#1854 [C-960] Add native push/email settings
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/mobile/src/store/notifications/sagas.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/settings/sagas.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/common/store/notifications/sagas.ts
Labels: size/M

#1855 [C-953] Migrate profile supporters/supporting
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileTierTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
  packages/mobile/src/screens/profile-screen/UploadTrackButton.tsx
  packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/ReceiverDetails.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx
  packages/mobile/src/screens/tip-artist-screen/TipArtistModal.tsx
  packages/mobile/src/screens/tip-artist-screen/TipHeader.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/SupportingInfo.tsx
  packages/web/src/common/store/tipping/mobileSagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/services/native-mobile-interface/tipping.ts
Labels: size/L

#1856 [C-962, C-904] Native recovery email
  packages/common/src/store/recovery-email/index.ts
  packages/common/src/store/recovery-email/selectors.ts
  packages/common/src/store/recovery-email/slice.ts
  packages/common/src/store/reducers.ts
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/recovery-email/sagas.ts
Labels: size/M

#1857 [C-963] Migrate wallet sagas
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/S

#1858 [C-965] Add native reset-password
  packages/mobile/src/components/confirm-credentials/index.ts
  packages/mobile/src/components/enter-password/index.ts
  packages/mobile/src/screens/settings-screen/ChangePasswordScreen/ChangePasswordScreen.tsx
  packages/mobile/src/screens/settings-screen/ChangePasswordScreen/ConfirmCredentials.tsx
  packages/mobile/src/screens/settings-screen/ChangePasswordScreen/EnterPassword.tsx
  packages/mobile/src/screens/settings-screen/ChangePasswordScreen/index.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/change-password/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/M

#1846 [PAY-605][PAY-601][PAY-548] Buy Audio modal design changes
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.module.css
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
  packages/web/src/components/buy-audio-modal/components/PurchaseQuote.module.css
  packages/web/src/components/buy-audio-modal/components/PurchaseQuote.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#1862 [C-944] Adjust badge sizes and alignment
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/co-sign/HoverInfo.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx
  packages/web/src/components/search/SearchBarResult.js
  packages/web/src/components/search/SearchBarResult.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
Labels: size/S

#1859 [C-967] Add native deactivate-account sagas
  packages/common/src/store/pages/deactivate-account/index.ts
  packages/common/src/store/pages/deactivate-account/selectors.ts
  packages/common/src/store/pages/deactivate-account/slice.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/recovery-email/slice.ts
  packages/common/src/store/reducers.ts
  packages/mobile/src/components/deactivate-account-confirmation-drawer/DeactivateAccountConfirmationDrawer.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/deactivate-account/sagas.ts
  packages/web/src/pages/deactivate-account-page/DeactivateAccountPage.tsx
  packages/web/src/pages/deactivate-account-page/store/selectors.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
Labels: size/L

#1261 Fix optimizely for local dev
  packages/web/scripts/configureLocalEnv.js
Labels: size/XS

#1863 C-822 Fix dark mode "Follows you" chip
  packages/web/src/components/artist/ArtistChip.module.css
  packages/web/src/components/artist/ArtistChipFollowers.tsx
Labels: size/S

#1864 Fix send $AUDIO flow after saga migration
  packages/web/src/common/store/wallet/sagas.ts
Labels: size/S

#1865 [C-879] Fix rewards page navigation
  packages/web/src/hooks/useRequiresAccount.ts
Labels: size/S

#1867 [C-914] Fix windows build
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#1866 Clean up remote-config init handlers
  packages/common/src/services/remote-config/index.ts
  packages/common/src/services/remote-config/remote-config.ts
  packages/common/src/store/remote-config/sagas.ts
  packages/web/src/common/store/account/sagas.js
Labels: size/L

#1871 Fix profile left nav tile spacing and order
  packages/web/src/components/upload/UploadChip.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileTags.module.css
Labels: size/XS

#1861 [PAY-600][PAY-599][PAY-607][PAY-617] RemoteConfig for Buy Audio and better transactiondetails link
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
  packages/web/src/components/transaction-details-modal/components/Block.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#1872 Update feed tip tile per QA feedback
  packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
Labels: size/XS

#1879 Fixes profile pictures in top supporters tile
  packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
Labels: size/S

#1877 [C-878] Show invalid file errors on upload
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.js
  packages/web/src/components/source-files-modal/SourceFilesModal.tsx
  packages/web/src/components/upload/Dropzone.tsx
  packages/web/src/pages/upload-page/UploadPage.js
  packages/web/src/pages/upload-page/components/SelectPage.js
  packages/web/src/pages/upload-page/store/utils/processFiles.ts
Labels: size/M

#1876 [C-868] Remove IPFS from client build steps
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@web-jobs.yml
  .circleci/src/workflows/web.yml
Labels: size/L

#1873 [C-969] Add native audio-screen
  packages/common/src/services/cognito/Cognito.ts
  packages/common/src/services/cognito/index.ts
  packages/common/src/services/env.ts
  packages/common/src/services/index.ts
  packages/common/src/services/native-mobile-interface/types.ts
  packages/common/src/store/index.ts
  packages/common/src/store/music-confetti/index.ts
  packages/common/src/store/music-confetti/selectors.ts
  packages/common/src/store/music-confetti/slice.ts
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ReferralRewardContents.tsx
  packages/mobile/src/components/cognito-drawer/CognitoDrawer.tsx
  packages/mobile/src/components/hcaptcha/HCaptcha.tsx
  packages/mobile/src/message/types.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/mobile/src/screens/audio-screen/TrendingRewards.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/services/cognito.ts
  packages/mobile/src/services/env.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/store.test.ts
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/components/first-upload-modal/FirstUploadModal.tsx
  packages/web/src/components/music-confetti/ConnectedMusicConfetti.tsx
  packages/web/src/components/share-sound-to-tiktok-modal/store/sagas.ts
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/store/mobileSagas.ts
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/services/cognito.ts
  packages/web/src/services/env.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/types.ts
Labels: size/XL

#1875 [C-988] Fix social actions by fixing metro imports
  packages/common/package.json
  packages/mobile/metro.config.js
Labels: size/S

#1849 Use bulk tracks from API client
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
Labels: size/M

#1880 [C-989] Add common track-download
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/services/index.ts
  packages/common/src/services/native-mobile-interface/types.ts
  packages/common/src/services/track-download/TrackDownload.ts
  packages/common/src/services/track-download/index.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/message/types.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/services/track-download.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/services/audius-backend/TrackDownload.js
  packages/web/src/services/native-mobile-interface/downloadTrack.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/services/track-download.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#1874 Fix optimizely for local dev
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/env.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/services/env.ts
  packages/web/scripts/configureLocalEnv.js
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/env.ts
Labels: size/M

#1884 [C-974] Migrate account sagas
  packages/common/src/services/audius-backend/RecordIP.ts
  packages/common/src/services/audius-backend/index.ts
  packages/common/src/services/audius-backend/waudio.ts
  packages/common/src/store/account/index.ts
  packages/common/src/store/account/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/playlist-library/index.ts
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/common/store/playlist-library/slice.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/components/edit-folder-modal/EditFolderModal.tsx
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/services/audius-backend/waudio.ts
  packages/web/src/services/sentry.ts
  packages/web/src/store/account/sagas.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/store/types.ts
Labels: size/XL

#1886 [C-995] Remove message passing interfaces
  packages/common/src/services/native-mobile-interface/types.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/message/types.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/account/mobileSagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/components/drawer/Drawer.tsx
  packages/web/src/components/mobile-connect-wallets-drawer/MobileConnectWalletsDrawer.tsx
  packages/web/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/now-playing/NowPlayingDrawer.tsx
  packages/web/src/components/now-playing/components/ActionsBar.module.css
  packages/web/src/components/now-playing/components/ActionsBar.tsx
  packages/web/src/components/play-bar/PlayBarProvider.tsx
  packages/web/src/components/pull-to-refresh/PullToRefresh.tsx
  packages/web/src/components/pull-to-refresh/hooks.ts
  packages/web/src/components/track/mobile/TrackList.tsx
  packages/web/src/components/user-badges/TierExplainerDrawer.tsx
  packages/web/src/pages/settings-page/components/mobile/AboutSettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/NotificationsSettingsPage.tsx
  packages/web/src/pages/sign-on/components/mobile/InitialPage.tsx
  packages/web/src/pages/sign-on/components/mobile/PasswordPage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
  packages/web/src/pages/something-wrong/SomethingWrong.tsx
  packages/web/src/root.tsx
  packages/web/src/services/Logging.ts
  packages/web/src/services/analytics/index.ts
  packages/web/src/services/native-mobile-interface/analytics.ts
  packages/web/src/services/native-mobile-interface/android/pulltorefresh.ts
  packages/web/src/services/native-mobile-interface/cast.ts
  packages/web/src/services/native-mobile-interface/googleCast.ts
  packages/web/src/services/native-mobile-interface/haptics.ts
  packages/web/src/services/native-mobile-interface/helpers.ts
  packages/web/src/services/native-mobile-interface/lifecycle.ts
  packages/web/src/services/native-mobile-interface/linking.ts
  packages/web/src/services/native-mobile-interface/logging.ts
  packages/web/src/services/native-mobile-interface/notifications.ts
  packages/web/src/services/native-mobile-interface/share.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/services/native-mobile-interface/version.ts
  packages/web/src/store/analytics/sagas.ts
  packages/web/src/store/application/ui/mobileKeyboard/reducer.ts
  packages/web/src/store/application/ui/mobileKeyboard/selectors.ts
  packages/web/src/store/application/ui/mobileKeyboard/types.ts
  packages/web/src/store/configureStore.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/routing/mobileSagas.ts
  packages/web/src/store/routing/sagas.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/store/types.ts
  packages/web/src/utils/share.ts
Labels: size/XL

#1883 Native-fy search results tracks lineup
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/search-page/sagas.js
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
  packages/web/src/store/sagas.ts
Labels: size/M

#1888 [C-958] Add native tip reaction
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
  packages/web/src/services/audius-backend/Reactions.ts
Labels: size/M

#1890 [C-1003] Native Account Sagas
  packages/common/src/store/account/slice.ts
  packages/mobile/src/store/account/sagas.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/account/mobileSagas.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/components/password-reset/PasswordResetModal.tsx
  packages/web/src/services/native-mobile-interface/lifecycle.ts
  packages/web/src/store/sign-out/signOut.ts
Labels: size/L

#1892 Consume @audius/sdk@1.0.4
  packages/common/package.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1896 [C-1006] Improve initial load, hotfix missing web worker
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/web/src/services/WebWorker.js
Labels: size/M

#1889 [C-892] Fix multiple menus open at once
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/components/test-collectibles-playlist-table/TestCollectiblesPlaylistTable.tsx
  packages/web/src/components/test-table/TestTable.tsx
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
  packages/web/src/components/tracks-table/TracksTable.js
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Labels: bug, size/L

#1891 [PAY-625] Playlist challenge optimistic claiming
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/web/src/common/store/cache/collections/sagas.js
Labels: size/S

#1897 [PAY-626] Change playlist+tip challenges copy and emoji
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/assets/fonts/emojis/treble-clef.png
  packages/web/src/assets/styles/emoji.css
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/S

#1898 [C-1001] Fix lineup state persisting across profile screens
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/S

#1899 [C-1014] Fix edit profile screen
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
Labels: size/S

#1887 Nativefy remixes screen
  packages/common/src/store/pages/remixes/slice.ts
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/remixes-page/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/remixes-page/sagas.ts
  packages/web/src/pages/remixes-page/store/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#1900 Clean up some more instances of useSelectorWeb/useDispatchWeb
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useSelectTierInfo.ts
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/hooks/selectors.ts
  packages/mobile/src/hooks/useSelectTierInfo.ts
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileTierTile.tsx
  packages/mobile/src/screens/profile-screen/utils.ts
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.js
  packages/web/src/components/nav/desktop/NavAudio.tsx
  packages/web/src/components/user-badges/ProfilePageBadge.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/hooks/wallet.tsx
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/L

#1903 [C-711] Change useSize to useMeasure in ProfileBio
  packages/web/src/hooks/useSize.ts
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
Labels: size/M

#1901 [C-1009] Fix misaligned social icons
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
Labels: size/M

#1885 [C-990] Nativefy oauth
  packages/common/package-lock.json
  packages/common/src/services/env.ts
  packages/common/src/services/index.ts
  packages/common/src/services/oauth/formatSocialProfile.ts
  packages/common/src/services/oauth/index.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/services/env.ts
  packages/mobile/src/store/oauth/actions.ts
  packages/mobile/src/store/oauth/sagas.ts
  packages/mobile/src/store/oauth/types.ts
  packages/mobile/src/store/settings/sagas.ts
  packages/mobile/src/store/storeContext.ts
  packages/stems/package-lock.json
  packages/web/package-lock.json
  packages/web/src/common/store/oauth/actions.ts
  packages/web/src/common/store/oauth/mobileSagas.ts
  packages/web/src/common/store/oauth/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/components/twitter-auth/TwitterAuth.js
  packages/web/src/pages/sign-on/components/ProfileForm.js
  packages/web/src/pages/sign-on/components/desktop/ProfilePage.js
  packages/web/src/pages/sign-on/components/mobile/ProfilePage.tsx
  packages/web/src/services/env.ts
  packages/web/src/services/native-mobile-interface/oauth.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/utils/imageProcessingUtil.ts
Labels: size/XL

#1853 Update social features to use entity manager
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/M

#1906 Remove react-nil and NATIVE_NAVIGATION
  packages/web/craco.config.ts
  packages/web/package.json
  packages/web/src/index.tsx
Labels: size/S

#1908 Fix profile clearing
  packages/common/src/store/pages/profile/lineups/tracks/actions.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/S

#1909 [C-1026] Improve bottom-bar perf
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
Labels: size/M

#1907 [C-1012] Remove web build from mobile build
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/workflows/mobile.yml
  packages/mobile/README.md
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/tsconfig.json
Labels: size/L

#1910 Migrate useGetFirstOrTopSupporter
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useGetFirstOrTopSupporter.ts
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
Labels: size/S

#1912 [C-1029, C-1036] Fix pull-to-refresh
  packages/mobile/src/components/core/PullToRefresh.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
Labels: size/L

#1914 No more useSelectorWeb C-1022
  packages/mobile/src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx
  packages/mobile/src/hooks/useSelectorWeb.ts
Labels: size/S

#1915 [C-1057] Fix blank edit-profile screen
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
Labels: size/S

#1916 [C-1050] Fix profile search crash
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
Labels: size/S

#1917 [C-1053] Fix ios status color in dark/light modes
  packages/mobile/src/store/theme/sagas.ts
Labels: size/XS

#1911 [C-1031] Improve profile expand section touch target
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandHeaderToggleButton.tsx
Labels: size/XS

#1918 Wait for libs before signing data
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#1905 [PAY-578] Fade in socials on mobile user screen
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
Labels: size/S

#1919 [C-1060] Fix /check page
  packages/web/src/pages/check-page/CheckPage.tsx
Labels: size/S

#1920 [C-1041] Fix infinite 404
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/mobile/src/services/audius-api-client/apiClient.ts
  packages/web/src/services/audius-api-client/apiClient.ts
Labels: size/S

#1921 [Reloaded] [C-1017] Fix more by artist lineup
  packages/common/src/store/pages/track/reducer.ts
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/common/store/pages/track/sagas.js
Labels: size/S

#1924 Fix account profile screen loading
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/XS

#1925 Fix pull to refresh
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/XS

#1922 [C-907] Fix react native push notifications
  packages/mobile/src/App.tsx
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
  packages/mobile/src/store/settings/sagas.ts
Labels: size/M

#1926 Update mobile readme install instructions
  packages/mobile/README.md
Labels: size/M

#1913 Detach mobile reachability state from non existent webview C-938
  package-lock.json
  packages/common/src/services/native-mobile-interface/types.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/src/message/types.ts
  packages/mobile/src/utils/connectivity.ts
  packages/web/package-lock.json
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.js
  packages/web/src/common/utils/isMobileWeb.ts
  packages/web/src/services/native-mobile-interface/lifecycle.ts
  packages/web/src/services/native-mobile-interface/types.ts
  packages/web/src/store/reachability/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#1719 [C-838] Fix desktop update banner flow
  packages/web/src/electron.js
  packages/web/src/pages/App.js
Labels: size/M

#1928 Remove console exporter and change default to undefined
  packages/mobile/package-lock.json
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/utils/tracer.ts
Labels: size/S

#1927 [Reloaded] No more useDispatchWeb, messages C-1089
  packages/common/src/services/index.ts
  packages/common/src/services/native-mobile-interface/index.ts
  packages/common/src/services/native-mobile-interface/types.ts
  packages/mobile/src/components/oauth/OAuth.tsx
  packages/mobile/src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx
  packages/mobile/src/hooks/useDispatchWeb.ts
  packages/mobile/src/message/index.ts
  packages/mobile/src/message/types.ts
  packages/mobile/src/store/oauth/reducer.ts
  packages/mobile/src/store/oauth/types.ts
  packages/web/src/services/native-mobile-interface/helpers.ts
  packages/web/src/services/native-mobile-interface/types.ts
Labels: size/L

#1929 Upgrade SDK to 1.0.5
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#1850 Add request pagination for favorites for the new table
  packages/common/src/models/Kind.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/lineup/selectors.ts
  packages/common/src/store/pages/saved-page/actions.ts
  packages/common/src/store/pages/saved-page/reducer.ts
  packages/common/src/store/pages/saved-page/selectors.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/saved/lineups/sagas.js
  packages/web/src/common/store/pages/saved/sagas.js
  packages/web/src/components/test-collectibles-playlist-table/TestCollectiblesPlaylistTable.tsx
  packages/web/src/components/test-table/TestTable.module.css
  packages/web/src/components/test-table/TestTable.tsx
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
  packages/web/src/components/tracks-table/EmptyTable.js
  packages/web/src/components/tracks-table/EmptyTable.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/XL

#1932 [C-1091] Improve selector performance
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/hooks/useProxySelector.ts
Labels: size/M

#1933 Fix rewards claiming on mobile C-1043
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#1934 Fix broken signup on web
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/S

#1935 [C-1113] Improve native render performance
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useProxySelector.ts
  packages/common/src/hooks/useSelectTierInfo.ts
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FavoriteNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FollowNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RepostNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
  packages/web/src/common/store/profile/sagas.js
Labels: size/L

#1936 [C-1064] Show "You're Offline" component on mobile
  packages/common/src/utils/index.ts
  packages/common/src/utils/timingUtils.ts
  packages/mobile/README.md
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/App.tsx
  packages/mobile/src/assets/images/iconNoWifi.svg
  packages/mobile/src/assets/images/iconRefresh.svg
  packages/mobile/src/components/offline-placeholder/OfflinePlaceholder.tsx
  packages/mobile/src/components/offline-placeholder/index.ts
  packages/mobile/src/components/offline-placeholder/messages.ts
  packages/mobile/src/components/reachability-bar/ReachabilityBar.tsx
  packages/mobile/src/components/reachability-bar/index.ts
  packages/mobile/src/screens/ScreenContent.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Labels: size/L

#1938 [C-1023] [C-1039] Sync account entropy from webview and improve splashscreen
  packages/common/src/store/account/slice.ts
  packages/mobile/.env.dev.tmpl
  packages/mobile/.env.prod.tmpl
  packages/mobile/.env.stage.tmpl
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/splash-screen/SplashScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/backend/sagas.ts
Labels: size/L

#1937 [C-1118] Send tip -> send audio
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
  packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx
  packages/mobile/src/screens/tip-artist-screen/BecomeFirstSupporter.tsx
  packages/mobile/src/screens/tip-artist-screen/BecomeTopSupporter.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/utils/challenges.tsx
Labels: size/L

#1940 [C-940] Fix infinite lineup fetch
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/XS

#1944 [C-894] Allow scroll on AddToPlaylist drawer
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
Labels: size/S

#1942 Send Amplitude event when app crashes
  packages/mobile/src/ErrorBoundary.tsx
  packages/mobile/src/types/analytics.ts
Labels: size/S

#1941 [C-1067] Add feature flag for offline mode
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#1943 [C-561] MusicControl artwork
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/S

#1869 [PAY-565] TokenValueInputV2 Component
  packages/stems/src/components/TokenAmountInput/TokenAmountInput.module.css
  packages/stems/src/components/TokenAmountInput/TokenAmountInput.stories.tsx
  packages/stems/src/components/TokenAmountInput/TokenAmountInput.tsx
  packages/stems/src/components/TokenAmountInput/index.ts
  packages/stems/src/components/TokenAmountInput/types.ts
  packages/stems/src/components/TokenValueInput/TokenValueInput.tsx
  packages/stems/src/index.tsx
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.module.css
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
Labels: size/L

#1946 Upload sourcemaps for prod and release-candidate
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#1948 [PAY-428] Wrap link text in notifications
  packages/web/src/components/notification/Notification/components/EntityLink.module.css
  packages/web/src/components/notification/Notification/components/UserNameLink.module.css
Labels: size/XS

#1953 [C-867] Fix hover state for the new tables
  packages/web/src/components/test-tracks-table/TestTracksTable.module.css
Labels: size/XS

#1945 Fix native profile render
  packages/mobile/src/screens/profile-screen/selectors.ts
Labels: size/XS

#1951 Apply accessbility patch for ios16 and xcode14
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: size/S

#1958 [C-1103, C-1105, C-1106] Fix new table styling
  packages/web/src/common/store/pages/saved/sagas.js
  packages/web/src/components/test-table/TestTable.module.css
  packages/web/src/components/test-table/TestTable.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css
Labels: size/S

#1949 [PAY-634] On Ramp Design Fixes (Part 1)
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.module.css
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#1955 Fix search result -> track screen bug [C-1124]
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/S

#1743 Add feature flag and entity track manager to client
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/M

#1959 c-1127 Fix more search results track lineup
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
Labels: size/M

#1962 [C-1133] Prevent toasts from appearing when overflow menu is clicked
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
Labels: size/XS

#1964 [C-863] Update new table styles for table action buttons
  packages/web/src/components/test-tracks-table/TestTracksTable.module.css
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
Labels: size/S

#1965 [C-978] Check for track repeat before advancing shuffle
  packages/common/src/store/queue/slice.ts
  packages/web/src/common/store/queue/store.test.js
Labels: size/M

#1963 [C-1090] Improve profile store layout
  packages/common/src/store/challenges/selectors/profile-progress.ts
  packages/common/src/store/lineup/actions.ts
  packages/common/src/store/lineup/reducer.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/lineups/feed/reducer.ts
  packages/common/src/store/pages/profile/lineups/tracks/reducer.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/common/src/store/pages/profile/types.ts
  packages/mobile/package-lock.json
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
  packages/mobile/src/screens/profile-screen/utils.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/store/configureStore.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/storeContext.ts
Labels: size/XL

#1968 [C-1004] Fix sign-up -> sign-in email bug
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/XS

#1971 [C-976] Fix native artist-recommendations
  packages/common/src/store/ui/artist-recommendations/selectors.ts
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/M

#1967 [C-1137] Add debounce to change in NetworkInfo status
  packages/mobile/src/utils/connectivity.ts
Labels: size/XS

#1972 Disable account-sync to test app failure
  packages/mobile/src/App.tsx
Labels: size/S

#1969 [C-1141, C-1142, C-1143, C-1144] Update new table styles for qa issues
  packages/web/src/components/test-table/TestTable.tsx
  packages/web/src/components/test-tracks-table/TestTracksTable.tsx
Labels: size/M

#1970 [C-951] Fix "track not found" error in collection tiles
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/XS

#1974 Fix playlist challenge optimistic update
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/web/src/common/store/cache/collections/sagas.js
Labels: size/S

#1975 [C-1152] Improve favorites tab performance
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/favorites-screen/selectors.ts
  packages/mobile/src/screens/favorites-screen/types.ts
Labels: size/L

#1978 Update staging to use goerli addresses
  packages/web/.env/.env.stage
Labels: size/XS

#1976 [c-1104] Fix playlist link in tile overflow menu
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
Labels: size/XS

#1973 [Reloaded] Keep relevant search results in store c-1117
  packages/common/src/store/pages/search-results/reducer.ts
  packages/common/src/store/pages/search-results/selectors.ts
  packages/common/src/store/pages/search-results/types.ts
  packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/useFetchTabResultsEffect.tsx
  packages/web/src/common/store/pages/search-page/sagas.js
Labels: size/L

#1982 [C-1162] Remove trimtoalphanumeric on search web
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
Labels: size/XS

#1983 Fix tag search more results
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.js
Labels: size/S

#1986 Fix mac build
  packages/eslint-config-audius/package.json
Labels: size/M

#1987 Update stage mobile env to goerli
  packages/mobile/.env.stage.tmpl
Labels: size/XS

#1981 Fix mobile favorites c-831
  packages/mobile/src/screens/favorites-screen/selectors.ts
Labels: size/XS

#1980 [C-1160,C-1161] Fix search navigation
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/L

#1985 [C-1048] Reset scrubber on song repeat
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Labels: size/S

#1984 [C-1151] Fix empty profile tab
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
Labels: size/S

#1979 [PLAT-98] Add feature flag for auto sub
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/social/users/sagas.ts
Labels: size/S

#1988 [C-482] Fix android navigation bar clipping
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/hooks/useAndroidNavigationBarHeight.ts
  packages/mobile/src/store/common/actions.ts
  packages/mobile/src/store/common/reducer.ts
  packages/mobile/src/store/mobileUi/sagas.ts
  packages/mobile/src/store/mobileUi/selectors.ts
  packages/mobile/src/store/mobileUi/slice.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
  packages/mobile/src/store/theme/sagas.ts
Labels: size/L

#1957 [C-1114] Prevent track restart
  packages/mobile/src/App.tsx
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/M

#1989 Fix TopSupporters, TrackScreen caching
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/M

#1990 [C-1172] Add screen freeze
  packages/mobile/index.js
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/S

#1992 Fix now-playing navigation
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabBar.tsx
Labels: size/S

#1993 [C-536] Cache makeStyles StyleSheets
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/styles/makeStyles.ts
Labels: size/S

#1994 [C-1176] Improve ExploreScreen performance
  packages/common/src/store/pages/explore/selectors.ts
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
Labels: size/M

#1997 Remove tmpl env vars
  .circleci/src/jobs/@mobile-jobs.yml
  packages/mobile/.env.dev
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/.gitignore
  packages/mobile/README.md
Labels: size/S

#1998 [C-1174] Fix blank listening history screen
  packages/mobile/src/components/empty-tile-cta/EmptyTileCTA.tsx
  packages/mobile/src/components/empty-tile-cta/index.ts
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingRowLabel.tsx
Labels: size/M

#1999 [C-1156, C-1055, C-1159] Fix profile follow button
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
Labels: size/S

#2000 [C-1167,C-1171] Fix missing tip data, fix tipping
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
Labels: size/S

#1577 [INF-180] Update client for new compose local dev
  packages/mobile/package.json
  packages/web/.env/.env.dev
  packages/web/README.md
  packages/web/package.json
  packages/web/scripts/configureLocalEnv.js
Labels: size/L

#2001 [C-1150, C-1165] Fix app-tab navigation
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts
  packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
  packages/mobile/src/screens/app-screen/index.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/L

#2003 Fix start:dev command
  packages/web/package.json
Labels: size/XS

#2004 Use .env.dev instead of .env.dev.local
  packages/web/package.json
Labels: size/XS

#2006 Omit creator_node_endpoint when updating metadata via collectible fetch
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/src/common/store/profile/sagas.js
Labels: size/S

#2007 Remove more webview instructions from readme
  packages/mobile/README.md
Labels: size/S

#2008 Hardcode web-sync static-server port
  packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
Labels: size/XS

#2012 Upgrade sdk 1.0.6
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#2015 Cast port to number
  packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
Labels: size/XS

#2005 [C-1164] Fix collections screen loading issues
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/M
