Repository AudiusProject/audius-client, pull requests merged in 2022-05, with the labels that each got.

#1271 [C-415] Fix search styling on android
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/FormTextInput.tsx
  packages/mobile/src/components/core/SearchInput.tsx
  packages/mobile/src/components/core/SegmentedControl.tsx
Labels: size/S

#1274 [C-404] Fix "Conent" typo
  packages/mobile/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
Labels: size/XS

#1275 [C-422] Add pull to refresh on android
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/SectionList.tsx
Labels: size/M

#1273 [PAY-161] Redesign Follow Notification
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/notification/Notifications/FollowNotification.tsx
  packages/web/src/components/notification/Notifications/NotificationBody.module.css
  packages/web/src/components/notification/Notifications/NotificationBody.tsx
  packages/web/src/components/notification/Notifications/NotificationFooter.module.css
  packages/web/src/components/notification/Notifications/NotificationFooter.tsx
  packages/web/src/components/notification/Notifications/NotificationHeader.module.css
  packages/web/src/components/notification/Notifications/NotificationHeader.tsx
  packages/web/src/components/notification/Notifications/NotificationTile.module.css
  packages/web/src/components/notification/Notifications/NotificationTile.tsx
  packages/web/src/components/notification/Notifications/ProfilePicture.module.css
  packages/web/src/components/notification/Notifications/ProfilePicture.tsx
  packages/web/src/components/notification/Notifications/UserNameLink.module.css
  packages/web/src/components/notification/Notifications/UserNameLink.tsx
  packages/web/src/components/notification/Notifications/UserProfilePictureList.module.css
  packages/web/src/components/notification/Notifications/UserProfilePictureList.tsx
  packages/web/src/components/notification/Notifications/index.ts
Labels: size/L

#1279 Remove core poa network
  packages/web/.env/.env.prod
Labels: size/XS

#1281 [AUD-1940] Fix libs contract-client init
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1280 Update stems version to 0.3.31
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/assets/styles/colors.css
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/default.ts
  packages/web/src/utils/theme/matrix.ts
Labels: size/S

#1282 [C-363] Remove antd progress component and use stems ProgressBar component
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/upload/ProgressBar.js
  packages/web/src/components/upload/ProgressBar.module.css
  packages/web/src/pages/upload-page/components/FinishPage.js
  packages/web/src/pages/upload-page/components/FinishPage.module.css
Labels: size/M

#1278 OAuth login form setup
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/app.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/styles/OAuthLoginPage.module.css
  packages/web/src/utils/route.ts
Labels: size/L

#1255 Add tipping audio to artists
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/assets/img/iconCaretLeft.svg
  packages/web/src/assets/img/iconQuestionCircle.svg
  packages/web/src/assets/img/iconVerifiedGreen.svg
  packages/web/src/common/models/Analytics.ts
  packages/web/src/common/models/Tipping.ts
  packages/web/src/common/models/User.ts
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
  packages/web/src/common/utils/wallet.ts
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/components/transition-container/TransitionContainer.tsx
  packages/web/src/pages/Modals.tsx
  packages/web/src/pages/audio-rewards-page/components/SendInputBody.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.js
  packages/web/src/services/audius-api-client/types.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/tipping/sagas.ts
Labels: size/XXL

#1284 [C-377] Replace antd popover with popup from stems
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist/ArtistPopover.module.css
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/utils/zIndex.ts
Labels: size/L

#1287 Fix DiscoveryAPI libs import
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/AudiusBackend.js
  packages/web/src/types/libs/libs.d.ts
Labels: size/XS

#1285 [C-457 C-461] Improve search-results collection/track screen load
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/mobile/src/store/search/types.ts
  packages/web/src/common/store/pages/track/lineup/actions.ts
Labels: size/L

#1288 [PAY-158] Add TipSentNotification
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/notification/Notifications/NotificationBody.tsx
  packages/web/src/components/notification/Notifications/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notifications/TipSentNotification.module.css
  packages/web/src/components/notification/Notifications/TipSentNotification.tsx
  packages/web/src/components/notification/Notifications/UserNameLink.module.css
  packages/web/src/components/notification/Notifications/UserNameLink.tsx
Labels: size/M

#1290 Revert ArtistPopover zIndex value to its previous value
  packages/web/src/utils/zIndex.ts
Labels: size/XS

#1289 [PAY-157,PAY-160] Add TopSupporter/SupportingNotification
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/content/NotificationContent.tsx
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/notification/Notifications/TipSentNotification.tsx
  packages/web/src/components/notification/Notifications/TopSupporterNotification.module.css
  packages/web/src/components/notification/Notifications/TopSupporterNotification.tsx
  packages/web/src/components/notification/Notifications/TopSupportingNotification.module.css
  packages/web/src/components/notification/Notifications/TopSupportingNotification.tsx
  packages/web/src/components/notification/Notifications/TwitterShareButton.module.css
Labels: size/L

#1291 Update libs and anchor solana config for client
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/scripts/configureLocalEnv.js
  packages/web/src/services/AudiusBackend.js
Labels: size/M

#1295 Fix AudioScreen typos
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/XS

#1294 [C-458] Fix CollectiblesTab text and links
  packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
  packages/mobile/src/components/collectible-details-drawer/helpers.ts
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/utils/routes.tsx
  packages/web/src/common/store/ui/collectible-details/selectors.ts
  packages/web/src/common/store/ui/collectible-details/slice.ts
Labels: size/L

#1296 [C-467] Fix missing clear button with existing search
  packages/mobile/src/screens/search-screen/SearchBar.tsx
Labels: size/XS

#1292 [PAY-156] Add TipReceivedNotification
  packages/web/src/components/notification/Notifications/NotificationTile.module.css
  packages/web/src/components/notification/Notifications/NotificationTile.tsx
  packages/web/src/components/notification/Notifications/TipReceivedNotification.module.css
  packages/web/src/components/notification/Notifications/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notifications/reactions/Reaction.module.css
  packages/web/src/components/notification/Notifications/reactions/Reaction.tsx
  packages/web/src/components/notification/Notifications/reactions/index.tsx
Labels: size/L

#1300 [C-462] Fix legacy image loading for native
  packages/web/src/services/AudiusBackend.js
Labels: size/M

#1298 [C-471] Fix AudioScreen audio tier min amount
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/XS

#1301 [C-424] Fix profile screen bio links on android
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
Labels: size/L

#1303 [C-475] Fix RemixesScreen header text alignment
  packages/mobile/package-lock.json
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/utils/formatUtil.ts
Labels: size/M

#1299 [PAY-177] Implement notification share to twitter actions
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/notification/Notifications/ChallengeRewardNotification.tsx
  packages/web/src/components/notification/Notifications/FavoriteNotification.tsx
  packages/web/src/components/notification/Notifications/FollowNotification.tsx
  packages/web/src/components/notification/Notifications/MilestoneNotification.tsx
  packages/web/src/components/notification/Notifications/RemixCosignNotification.tsx
  packages/web/src/components/notification/Notifications/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notifications/RepostNotification.tsx
  packages/web/src/components/notification/Notifications/TierChangeNotification.tsx
  packages/web/src/components/notification/Notifications/TrendingTrackNotification.tsx
  packages/web/src/components/notification/Notifications/TwitterShareButton.tsx
  packages/web/src/components/notification/Notifications/UserSubscriptionNotification.tsx
  packages/web/src/components/notification/Notifications/utils.ts
Labels: size/L

#1302 [PAY-179] Implement Notification click events
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/notification/Notifications/ChallengeRewardNotification.tsx
  packages/web/src/components/notification/Notifications/FollowNotification.tsx
  packages/web/src/components/notification/Notifications/MilestoneNotification.tsx
  packages/web/src/components/notification/Notifications/NotificationTile.tsx
  packages/web/src/components/notification/Notifications/RemixCosignNotification.tsx
  packages/web/src/components/notification/Notifications/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notifications/TrendingTrackNotification.tsx
  packages/web/src/components/notification/Notifications/UserSubscriptionNotification.tsx
  packages/web/src/components/notification/Notifications/types.ts
  packages/web/src/components/notification/Notifications/utils.ts
Labels: size/L

#1304 [C-416] Fix swiping behavior with tabs/notifications on android
  packages/mobile/src/components/top-tab-bar/TopTabNavigator.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/notifications-screen/content/Entity.tsx
  packages/mobile/src/screens/notifications-screen/content/User.tsx
  packages/mobile/src/screens/notifications-screen/content/UserImages.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/M

#1305 [C-460] Enable os back on android
  packages/mobile/src/components/web/WebApp.tsx
Labels: size/M

#1307 Revert "Remove tik tok feature flag"
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
Labels: size/S

#1309 Remove numeric separators to fix react native build
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/XS

#1308 [PAY-176] Implement NotificationPanel redesign
  packages/web/src/components/nav/desktop/NavHeader.js
  packages/web/src/components/notification/NotificationPanel.module.css
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/components/notification/Notifications/EntityLink.module.css
  packages/web/src/components/notification/Notifications/EntityLink.tsx
  packages/web/src/components/notification/Notifications/FavoriteNotification.tsx
  packages/web/src/components/notification/Notifications/FollowNotification.tsx
  packages/web/src/components/notification/Notifications/MilestoneNotification.tsx
  packages/web/src/components/notification/Notifications/Notification.tsx
  packages/web/src/components/notification/Notifications/NotificationBody.module.css
  packages/web/src/components/notification/Notifications/NotificationBody.tsx
  packages/web/src/components/notification/Notifications/NotificationTile.tsx
  packages/web/src/components/notification/Notifications/ProfilePicture.tsx
  packages/web/src/components/notification/Notifications/RemixCosignNotification.tsx
  packages/web/src/components/notification/Notifications/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notifications/RepostNotification.tsx
  packages/web/src/components/notification/Notifications/TwitterShareButton.tsx
  packages/web/src/components/notification/Notifications/UserNameLink.module.css
  packages/web/src/components/notification/Notifications/UserNameLink.tsx
  packages/web/src/components/notification/Notifications/UserProfilePictureList.tsx
  packages/web/src/components/notification/Notifications/UserSubscriptionNotification.module.css
  packages/web/src/components/notification/Notifications/UserSubscriptionNotification.tsx
  packages/web/src/components/notification/Notifications/icons.module.css
  packages/web/src/components/notification/Notifications/icons.tsx
  packages/web/src/components/notification/Notifications/index.ts
  packages/web/src/components/notification/Notifications/utils.ts
Labels: size/XL

#1310 Libs 1.2.116
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1311 C-408 Send OAuth read-only response
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/services/AudiusBackend.js
Labels: size/L

#1312 [PAY-186] Address desktop notification qa
  packages/web/src/assets/img/iconAudius.svg
  packages/web/src/common/store/notifications/selectors.ts
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/components/notification/Notifications/AnnouncementNotification.module.css
  packages/web/src/components/notification/Notifications/AnnouncementNotification.tsx
  packages/web/src/components/notification/Notifications/FavoriteNotification.tsx
  packages/web/src/components/notification/Notifications/FollowNotification.tsx
  packages/web/src/components/notification/Notifications/Notification.tsx
  packages/web/src/components/notification/Notifications/NotificationTile.tsx
  packages/web/src/components/notification/Notifications/RepostNotification.tsx
  packages/web/src/components/notification/Notifications/UserProfileList.module.css
  packages/web/src/components/notification/Notifications/UserProfileList.tsx
  packages/web/src/components/notification/Notifications/UserProfilePictureList.module.css
  packages/web/src/components/notification/Notifications/UserProfilePictureList.tsx
  packages/web/src/components/notification/Notifications/icons.module.css
  packages/web/src/components/notification/Notifications/icons.tsx
  packages/web/src/components/notification/Notifications/utils.ts
  packages/web/src/components/notification/components/desktop/NotificationModal.tsx
  packages/web/src/services/AudiusBackend.js
Labels: size/L

#1314 Revert 'Replace antd popover with popup from stems (#1284)
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist/ArtistPopover.module.css
  packages/web/src/components/artist/ArtistPopover.tsx
Labels: size/L

#1316 Fix TipNotification layouts
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/notification/Notifications/Notification.tsx
  packages/web/src/components/notification/Notifications/TipReactionNotification.module.css
  packages/web/src/components/notification/Notifications/TipReactionNotification.tsx
  packages/web/src/components/notification/Notifications/TipReceivedNotification.module.css
  packages/web/src/components/notification/Notifications/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notifications/TipSentNotification.module.css
Labels: size/M

#1315 v1.1.7
  lerna.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1317 (1 liner) Remove state from payload
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/XS

#1318 Fix typecheck by adding missing notif type
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
Labels: size/XS

#1319 Remove CI steps for old way of handling AASA file
  .circleci/config.yml
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#1323 [C-516] Fix typecheck in ci, address existing errors
  packages/mobile/package-lock.json
  packages/mobile/tsconfig.json
  packages/mobile/types/global.d.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/supporting-page/sagas.ts
  packages/web/src/pages/top-supporters-page/sagas.ts
  packages/web/src/services/audius-api-client/ResponseAdapter.ts
  packages/web/src/services/audius-api-client/types.ts
  packages/web/src/store/tipping/sagas.ts
Labels: size/M

#1320 [PAY-207] Refactor ArtistCard and fix usage in notifications
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist/ArtistCard.module.css
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/artist/ArtistCardCover.module.css
  packages/web/src/components/artist/ArtistCardCover.tsx
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/artist/ArtistSupporting.module.css
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/card/desktop/CollectionArtCard.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
  packages/web/src/components/notification/Notification/components/UserNameLink.tsx
  packages/web/src/components/remix-card/RemixCard.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/TrackInfo.js
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/tracks-table/TracksTable.js
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/deleted-page/components/mobile/DeletedPage.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
Labels: size/XL

#1329 [PAY-213] Fix notification user lists
  packages/web/src/common/store/user-list/notifications/reducers.ts
  packages/web/src/common/store/user-list/notifications/sagas.ts
  packages/web/src/common/store/user-list/notifications/types.ts
  packages/web/src/components/notification/Notification/FavoriteNotification.tsx
  packages/web/src/components/notification/Notification/FollowNotification.tsx
  packages/web/src/components/notification/Notification/RepostNotification.tsx
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
  packages/web/src/pages/notification-users-page/NotificationUsersPage.tsx
  packages/web/src/store/application/ui/userListModal/sagas.ts
  packages/web/src/store/application/ui/userListModal/types.ts
Labels: size/M

#1327 [PAY-214] Fix notification profile picture hover/click
  packages/web/src/components/notification/Notification/FavoriteNotification.tsx
  packages/web/src/components/notification/Notification/FollowNotification.tsx
  packages/web/src/components/notification/Notification/RepostNotification.tsx
  packages/web/src/components/notification/Notification/components/ProfilePicture.module.css
  packages/web/src/components/notification/Notification/components/UserNameLink.module.css
  packages/web/src/components/notification/Notification/components/UserNameLink.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
Labels: size/M

#1321 [PAY-208] Replace notification read with viewed
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/web/src/common/store/notifications/actions.ts
  packages/web/src/common/store/notifications/reducer.ts
  packages/web/src/common/store/notifications/selectors.ts
  packages/web/src/common/store/notifications/types.ts
  packages/web/src/common/store/ui/mobile-overflow-menu/types.ts
  packages/web/src/components/menu/Menu.tsx
  packages/web/src/components/menu/NotificationMenu.tsx
  packages/web/src/components/nav/desktop/NavColumn.js
  packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
  packages/web/src/components/notification/Notification/AnnouncementNotification.tsx
  packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
  packages/web/src/components/notification/Notification/FavoriteNotification.tsx
  packages/web/src/components/notification/Notification/FollowNotification.tsx
  packages/web/src/components/notification/Notification/MilestoneNotification.tsx
  packages/web/src/components/notification/Notification/RemixCosignNotification.tsx
  packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notification/RepostNotification.tsx
  packages/web/src/components/notification/Notification/TierChangeNotification.tsx
  packages/web/src/components/notification/Notification/TipReactionNotification.tsx
  packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notification/TipSentNotification.tsx
  packages/web/src/components/notification/Notification/TopSupporterNotification.tsx
  packages/web/src/components/notification/Notification/TopSupportingNotification.tsx
  packages/web/src/components/notification/Notification/TrendingTrackNotification.tsx
  packages/web/src/components/notification/Notification/UserSubscriptionNotification.tsx
  packages/web/src/components/notification/Notification/components/NotificationFooter.tsx
  packages/web/src/components/notification/Notification/components/NotificationTile.tsx
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
  packages/web/src/services/AudiusBackend.js
Labels: size/L

#1325 [PAY-212] Add ErrorBoundary to NotificationTile
  packages/web/src/components/notification/Notification/Notification.tsx
Labels: size/L

#1328 Disable fetching tipping support on profile sagas
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/services/audius-backend/Tipping.ts
  packages/web/src/store/tipping/sagas.ts
Labels: size/S

#1332 [C-521] Improve native notification performance
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/screens/notifications-screen/Empty.tsx
  packages/mobile/src/screens/notifications-screen/EmptyNotifications.tsx
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/notifications-screen/TopBar.tsx
  packages/mobile/src/screens/notifications-screen/index.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/L

#1333 [C-523] Fix native collectibles-drawer
  packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
  packages/web/src/common/store/ui/collectible-details/slice.ts
Labels: size/L

#1335 Support video inside audio nft playlist
  packages/web/src/common/models/Collection.ts
  packages/web/src/components/collectibles/ethCollectibleHelpers.ts
  packages/web/src/components/collectibles/solCollectibleHelpers.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/pages/collectibles-playlist-page/CollectiblesPlaylistPage.module.css
  packages/web/src/pages/collectibles-playlist-page/CollectiblesPlaylistPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.module.css
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/store/account/sagas.js
Labels: size/L

#1334 [C-522] Fix top sentry issues 1.1.13
  packages/mobile/src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/Link.tsx
  packages/mobile/src/components/discord-drawer/DiscordDrawer.tsx
  packages/mobile/src/screens/notifications-screen/content/ChallengeReward.tsx
  packages/mobile/src/screens/notifications-screen/content/Cosign.tsx
  packages/mobile/src/screens/notifications-screen/content/TwitterShare.tsx
  packages/mobile/src/store/search/hooks.ts
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/TopAPI.tsx
  packages/web/src/utils/route.ts
Labels: size/M

#1339 [C-528] Fix nft playlist deep link
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Labels: size/S

#1326 Fix tipping QA
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/tipping/support/SupportingList.tsx
  packages/web/src/components/tipping/support/TopSupporters.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/user-list/utils.ts
  packages/web/src/pages/favorites-page/sagas.ts
  packages/web/src/pages/followers-page/sagas.ts
  packages/web/src/pages/following-page/sagas.ts
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/pages/reposts-page/sagas.ts
  packages/web/src/pages/supporting-page/sagas.ts
  packages/web/src/pages/top-supporters-page/sagas.ts
  packages/web/src/services/audius-backend/Tipping.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/utils/constants.ts
Labels: size/XL

#1340 [C-528] Fix useSelectorWeb return type when using isEqual
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/hooks/selectors.ts
  packages/mobile/src/hooks/useSelectTierInfo.ts
  packages/mobile/src/hooks/useSelectorWeb.ts
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TopAlbumsScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/mobile/src/store/search/types.ts
Labels: size/L

#1322 AUD-1172 Add Lo-Fi Music Genre
  packages/web/src/common/utils/genres.ts
  packages/web/src/components/trending-genre-selection/TrendingGenreSelectionPage.tsx
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
Labels: size/S

#1345 [C-539] Fix long name in playlist causing table misalignment
  packages/web/src/components/tracks-table/TracksTable.module.css
Labels: size/XS

#1344 [C-537] Add button corner prop, text inherit color
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/Text.tsx
Labels: size/M

#1347 OAuth Design QA C-534 C-533 C-532
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/styles/OAuthLoginPage.module.css
Labels: size/M

#1346 [PAY-203] Native user list redesign
  packages/mobile/src/components/core/Divider.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/components/user/FollowsYouChip.tsx
  packages/mobile/src/components/user/index.ts
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/settings-screen/Divider.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
Labels: size/L

#1351 [PAY-239] Add native supporter/supporting user lists
  packages/mobile/src/assets/images/iconTip.svg
  packages/mobile/src/components/core/Audio.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/user/FollowsYouChip.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/SupportingInfo.tsx
  packages/mobile/src/screens/user-list-screen/SupportingUsersScreen.tsx
  packages/mobile/src/screens/user-list-screen/Tip.tsx
  packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
  packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
  packages/mobile/src/screens/user-list-screen/index.ts
  packages/web/src/common/store/tipping/selectors.ts
Labels: size/L

#1352 Add tip tile on feed page
  packages/web/src/common/models/Tipping.ts
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
  packages/web/src/common/store/wallet/selectors.ts
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipProfilePicture.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/services/audius-backend/Tipping.ts
  packages/web/src/store/tipping/sagas.ts
  packages/web/src/store/tipping/utils.ts
  packages/web/src/utils/constants.ts
Labels: size/XL

#1355 aud-1172 show lofi in trending genre pickers
  packages/web/src/common/utils/genres.ts
Labels: size/XS

#1357 Add new waitForUserRemoteConfig for feature flags that depend on user
  packages/web/src/common/services/remote-config/remote-config.ts
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/store/account/sagas.js
Labels: size/M

#1358 [C-545] Fix native screen transition jank
  packages/mobile/src/components/core/Screen.tsx
Labels: size/XS

#1359 [PAY-247] Add TipArtistModal and basic navigation
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/profile-screen/TipArtistButton.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/TipArtistModal.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/index.ts
  packages/mobile/src/screens/tip-artist-screen/navigation.ts
Labels: size/L

#1353 Add postMessage functionality to OAuth popup
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/M

#1360 Rename SearchInput TextInput
  packages/mobile/src/components/confirm-credentials/ConfirmCredentials.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/enter-password/EnterPassword.tsx
  packages/mobile/src/screens/favorites-screen/FilterInput.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/mobile/src/screens/trending-screen/TrendingFilterDrawer.tsx
Labels: size/M

#1361 [C-546] Fix USER_ID cohort feature flags on native
  packages/mobile/src/message/handlers/lifecycle.ts
Labels: size/XS

#1362 [C-547] Wrap tiktok on native in a feature flag
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/XS

#1365 [PAY-231][PAY-180] Fix Tip Modal Animation Transitions
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Labels: bug, size/L

#1364 Add native tipping feature flags
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
Labels: size/M

#1356 [C-534] Upgrade lerna to v5
  package-lock.json
  package.json
  packages/mobile/package-lock.json
  packages/web/package-lock.json
Labels: size/XS

#1363 [PAY-250] Implement SendTipScreen
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/assets/images/tokenBadgeNoTier.png
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/Screen.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/favorites-screen/FilterInput.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
  packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx
  packages/mobile/src/screens/tip-artist-screen/ErrorText.tsx
  packages/mobile/src/screens/tip-artist-screen/ReceiverDetails.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
  packages/mobile/src/screens/tip-artist-screen/TipScreen.tsx
  packages/web/src/common/utils/wallet.ts
Labels: size/L

#1366 Fix more tipping QA issues
  packages/web/src/components/follow-button/FollowButton.js
  packages/web/src/components/follow-button/FollowButton.module.css
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/components/tipping/support/SupportingTile.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/pages/profile-page/sagas.js
  packages/web/src/store/tipping/sagas.ts
Labels: size/L

#1369 [PAY-261] Refactor tipping slice amount type from BNWei to StringAudio
  packages/web/src/common/models/Wallet.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/store/tipping/sagas.ts
Labels: size/M

#1370 [PAY-253] Implement ConfirmSendTipScreen
  packages/mobile/src/assets/images/iconCaretLeft.svg
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/screens/profile-screen/TipArtistButton.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/DescriptionText.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx
  packages/mobile/src/screens/tip-artist-screen/TipArtistModal.tsx
  packages/mobile/src/screens/tip-artist-screen/TipHeader.tsx
Labels: size/L

#1371 [PAY-264] Implement TipSentScreen
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/components/twitter-button/index.ts
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/TipHeader.tsx
  packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
Labels: size/L

#1372 Fix feed tip tile and other tipping QA issues
  packages/web/src/assets/img/iconClose.svg
  packages/web/src/common/store/tipping/selectors.ts
  packages/web/src/common/store/tipping/slice.ts
  packages/web/src/common/store/tipping/types.ts
  packages/web/src/components/artist/ArtistChip.module.css
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistChipTips.tsx
  packages/web/src/components/artist/ArtistSupporting.module.css
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/artist/UserListModal.tsx
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/components/tipping/support/Support.module.css
  packages/web/src/components/tipping/support/SupportingTile.tsx
  packages/web/src/components/tipping/support/TopSupporters.tsx
  packages/web/src/components/user-list/components/UserList.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/store/tipping/sagas.ts
Labels: size/L

#1367 Add Amplitude events
  packages/web/src/common/models/Analytics.ts
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/M

#1373 Fix styling
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
Labels: size/S

#1375 Add native notification error boundary
  packages/mobile/src/screens/notifications-screen/NotificationErrorBoundary.tsx
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
Labels: size/M

#1252 Fix handling unknown AAO error
  packages/web/src/common/models/AudioRewards.ts
  packages/web/src/pages/audio-rewards-page/store/sagas.ts
Labels: size/XS

#1377 [C-552] Fix expandible-bio link render issue
  packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
Labels: size/M

#1374 Bump Stems 0.3.36 for Scrollbar fixes
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#1378 [C-553] Address sentry issues for 1.1.15
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/components/core/Link.tsx
  packages/mobile/src/hooks/useAndroidNavigationBarHeight.ts
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/routeUtil.ts
  packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/store/audio/reducer.ts
  packages/web/src/common/store/cache/collections/selectors.ts
  packages/web/src/common/utils/uid.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/L

#1379 Fix remixes tile margin
  packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
Labels: size/XS

#1380 Fix android drawer height issue
  packages/mobile/src/components/drawer/Drawer.tsx
Labels: size/XS

#1387 Reset scroll threshold to 1000
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/XS

#1381 Fix slider handle position when re-entering from background
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/scrubber/Slider.tsx
Labels: size/S

#1382 Prevent favorites tab from resetting on navigation
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
Labels: size/S

#1383 Fix double press issue when filtering in filter genre drawer
  packages/mobile/src/screens/trending-screen/TrendingFilterDrawer.tsx
Labels: size/XS

#1384 Fix casting for android, setting for ios
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/screens/settings-screen/CastSettingsRow.tsx
Labels: size/M

#1386 [AUD-1146] Clear search history on sign-out
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
Labels: size/S

#1376 [PAY-265] Add native profile screen redesign
  packages/mobile/src/assets/images/iconCaretDown.svg
  packages/mobile/src/components/core/Divider.tsx
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/components/core/Link.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/Bio.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/CollapsedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/MutualsButtonTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileHeaderV2.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileTierTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SocialLink.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SocialsAndSites.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/index.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/utils.ts
Labels: size/XL

#1389 [Pay-202] Add native mutuals screen
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileMutualsButton.tsx
  packages/mobile/src/screens/user-list-screen/MutualsScreen.tsx
  packages/mobile/src/screens/user-list-screen/index.ts
  packages/web/src/common/store/index.ts
  packages/web/src/common/store/user-list/following/actions.ts
  packages/web/src/common/store/user-list/mutuals/actions.ts
  packages/web/src/common/store/user-list/mutuals/errorSagas.ts
  packages/web/src/common/store/user-list/mutuals/reducers.ts
  packages/web/src/common/store/user-list/mutuals/selectors.ts
  packages/web/src/common/store/user-list/mutuals/types.ts
  packages/web/src/pages/mutuals-page/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#1391 [PAY-238] Enable tipping notifications
  packages/web/src/common/services/remote-config/feature-flags.ts
  packages/web/src/components/notification/store/sagas.ts
  packages/web/src/services/AudiusBackend.js
Labels: size/S
