Repository AudiusProject/audius-client, pull requests merged in 2022-12, with the labels that each got.

#2329 [C-1574] Update UI in mobile wallet connect flow
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/confirm-remove-wallet-drawer/ConfirmRemoveWalletDrawer.tsx
  packages/mobile/src/components/confirm-remove-wallet-drawer/index.ts
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectStack.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletsDrawer.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#2323 Update sitemaps
  packages/web/robots.txt
Labels: size/XS

#2333 [C-1597] Fix wallet images
  packages/mobile/src/screens/wallet-connect/components/WalletsDrawer.tsx
Labels: size/S

#2334 hotfix: Extra padding for BuyAudio flow
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#2331 Fix react-native-threads on android
  packages/mobile/react-native.config.js
Labels: size/S

#2336 [C-1573] Fix hidden track centering
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#2338 Disable input accessory on android
  packages/mobile/src/components/core/TextInput.tsx
Labels: size/XS

#2337 hotfix-ff: Unify magic numbers
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#2335 Share to Instagram - Use dominant colors; generate sticker
  package-lock.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/styles/typography.ts
  packages/mobile/src/utils/convertRGBtoHex.ts
  packages/web/package-lock.json
Labels: size/L

#2340 [C-1553] Refactor token-dashboard sagas
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/common/src/store/pages/token-dashboard/types.ts
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/store/token-dashboard/addWalletToUser.ts
  packages/web/src/store/token-dashboard/associateNewWallet.ts
  packages/web/src/store/token-dashboard/checkIsNewWallet.ts
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
  packages/web/src/store/token-dashboard/disconnectWallet.ts
  packages/web/src/store/token-dashboard/establishWalletConnection.ts
  packages/web/src/store/token-dashboard/getAccountMetadataCID.ts
  packages/web/src/store/token-dashboard/getWalletAddress.ts
  packages/web/src/store/token-dashboard/getWalletInfo.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/store/token-dashboard/signMessage.ts
  packages/web/src/store/token-dashboard/types.ts
Labels: size/XXL

#2342 Add loading screen w/ cancel function to Share to IG
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/assets/images/iconWavform.svg
  packages/mobile/src/components/core/LinearProgress.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/mobile/src/store/share-to-story-progress/selectors.ts
  packages/mobile/src/store/share-to-story-progress/slice.ts
  packages/mobile/src/store/store.ts
Labels: size/L

#2343 [C-1675][C-1555] Implement wallet-connect and wallet-adapter-protocol
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/assets/images/iconSolana.svg
  packages/mobile/src/dev-utils/useRenderingTrace.ts
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/components/EthWalletConnectOption.tsx
  packages/mobile/src/screens/wallet-connect/components/PhantomWalletConnectOption.tsx
  packages/mobile/src/screens/wallet-connect/components/SolanaPhoneOption.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/screens/wallet-connect/components/useSolanaPhoneAuthorization.ts
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/mobile/src/store/wallet-connect/sagas/signMessageSaga.ts
  packages/mobile/src/store/wallet-connect/selectors.ts
  packages/mobile/src/store/wallet-connect/slice.ts
  packages/mobile/src/store/wallet-connect/types.ts
Labels: size/XL

#2348 [C-1615] Fix android fullscreen modals
  packages/mobile/src/screens/app-screen/AppScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
  packages/mobile/src/screens/app-screen/index.ts
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/L

#2349 [Share to IG] Fix crash share to IG C-1612
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/threads/dominantColors.thread.js
Labels: size/S

#2352 [C-1624] Fix eager load
  packages/web/package.json
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/utils/addUsersFromCollections.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessRemixes.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
  packages/web/src/common/store/cache/tracks/utils/helpers.ts
  packages/web/src/common/store/cache/tracks/utils/processAndCacheTracks.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/cache/users/utils/processAndCacheUsers.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/deactivate-account/sagas.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/common/store/pages/history/lineups/sagas.js
  packages/web/src/common/store/pages/profile/lineups/feed/retrieveUserReposts.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/remixes-page/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/saved/sagas.js
  packages/web/src/common/store/pages/search-page/sagas.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/common/store/pages/track/lineups/sagas.ts
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
  packages/web/src/common/store/pages/trending-underground/lineups/sagas.ts
  packages/web/src/common/store/pages/trending/lineups/trending/retrieveTrending.ts
  packages/web/src/common/store/pages/trending/lineups/trending/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/search-bar/sagas.ts
  packages/web/src/common/store/service-selection/sagas.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/ui/artist-recommendations/sagas.ts
  packages/web/src/common/store/upload/sagaHelpers.ts
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/common/store/user-list/utils.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/pages/deleted-page/store/lineups/more-by/sagas.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/token-dashboard/getAccountMetadataCID.ts
  packages/web/src/store/token-dashboard/sagas.ts
  packages/web/src/utils/sagaHelpers.ts
Labels: size/L

#2353 [C-1626] Connect phantom wallet-connect with common sagas
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/mobile/src/store/wallet-connect/sagas/signMessageSaga.ts
  packages/web/src/common/store/pages/token-dashboard/addWalletToUser.ts
  packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
  packages/web/src/common/store/pages/token-dashboard/checkIsNewWallet.ts
  packages/web/src/common/store/pages/token-dashboard/getAccountMetadataCID.ts
  packages/web/src/common/store/pages/token-dashboard/getWalletInfo.ts
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/M

#2317 Fetch and store ablum art for oflfine downloads
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/hooks/useLocalImage.ts
  packages/mobile/src/screens/edit-track-screen/EditExistingTrackScreen.tsx
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
Labels: size/L

#2332 [PAY-739] Add view transactions button in Audio page
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/M

#2351 [C-1595] Fix sign out
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/utils/sagaHelpers.ts
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
  packages/mobile/src/components/web-app-account-sync/WebAppAccountClear.tsx
  packages/mobile/src/components/web-app-account-sync/index.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/root-screen/StatusBar.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/mobile/src/store/notifications/sagas.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/settings/sagas.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/change-password/sagas.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/pages/explore/sagas.ts
  packages/web/src/common/store/pages/feed/sagas.ts
  packages/web/src/common/store/pages/remixes-page/sagas.ts
  packages/web/src/common/store/pages/search-page/sagas.js
  packages/web/src/common/store/pages/settings/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/search-bar/sagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
  packages/web/src/store/notifications/sagas.ts
  packages/web/src/store/sign-out/sagas.ts
Labels: size/L

#2350 Update mobile upload for final release
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#2358 [C-1633] Chunk track fetching for large playlists
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
Labels: size/S

#2357 [C-1632] Queue tracks in favorited collections
  packages/common/src/services/remote-config/remote-config.ts
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
Labels: size/L

#2355 [PAY-753][PAY-754] Ensure > 1 $AUDIO quoted before trying recovery
  packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#2361 Fix onramp feature flags for old desktop versions
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/S

#2359 C-1606 C-1609 C-1610 Share to IG Story QA
  packages/mobile/android/app/build.gradle
  packages/mobile/android/build.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/M

#2362 Queue optimizations; batch action for tracks
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/M

#2169 Remove getTrackListens endpoint from audiusBackend
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/M

#2364 [Share to IG] C-1637 C-1636 C-1635 QA - make text static size, make sticker static colors, align icon
  packages/mobile/src/components/core/Divider.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/M

#2365 [C-1628] Add metamask/rainbow mobile wallet-connect
  packages/mobile/src/App.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectProvider.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectStack.tsx
  packages/mobile/src/screens/wallet-connect/components/EthWalletConnectOption.tsx
  packages/mobile/src/screens/wallet-connect/components/SolanaPhoneOption.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/screens/wallet-connect/index.ts
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/mobile/src/store/wallet-connect/sagas/signMessageSaga.ts
  packages/mobile/src/store/wallet-connect/selectors.ts
  packages/mobile/src/store/wallet-connect/slice.ts
  packages/mobile/src/store/wallet-connect/types.ts
  packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
Labels: size/L

#2370 Make default Table isEmptyRow
  packages/web/src/components/table/Table.tsx
Labels: size/S

#2363 [C-1563] Fetch and download all paginated track favorites
  packages/mobile/src/hooks/useFetchAllFavoritedTrackIds.ts
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
Labels: size/L

#2373 Fix social feature lint
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/premium-content/actions.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/profile/sagas.js
Labels: size/S

#2366 [C-1650] Finalize solana-phone integration
  packages/common/src/store/pages/token-dashboard/selectors.ts
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/patches/@walletconnect+react-native-dapp+1.8.0.patch
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/components/EthWalletConnectOption.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/mobile/src/screens/wallet-connect/components/SolanaPhoneOption.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/mobile/src/store/wallet-connect/sagas/signMessageSaga.ts
  packages/mobile/src/store/wallet-connect/types.ts
  packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
Labels: size/L

#2375 [C-1651] Update mobile connect-wallet ui
  packages/mobile/src/screens/wallet-connect/components/EthWalletConnectOption.tsx
  packages/mobile/src/screens/wallet-connect/components/PhantomWalletConnectOption.tsx
  packages/mobile/src/screens/wallet-connect/components/SolanaPhoneOption.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectOption.tsx
Labels: size/M

#2374 [C-1649] Reset libs on app start
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/mobile/src/App.tsx
  packages/mobile/src/services/libs.ts
Labels: size/S

#2368 Expose SDK in client
  packages/web/src/services/audius-sdk/audiusSdk.ts
  packages/web/src/services/audius-sdk/index.ts
Labels: size/XS

#2378 [Share to IG] QA - Pick most colorful colors and adjust the wavform
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/threads/dominantColors.thread.js
Labels: size/M

#2379 Clean up readme
  README.md
Labels: size/S

#2383 [Share to IG] Change Hz to 16000 without impacting audio quality
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/XS

#2384 Upgrade @audius/sdk to 1.0.25
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#2381 [C-1664] Improve lineup, app-tab, rewards perf
  packages/common/src/hooks/useAccountHasClaimableRewards.ts
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/hooks/useAppTabScreen.ts
  packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Labels: size/L

#2385 [C-1641] Use lottie animation for downloading icon and add size prop
  packages/mobile/src/assets/animations/iconDownloading.json
  packages/mobile/src/assets/images/iconDownloadFailed.svg
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
Labels: size/L

#2386 Fix track tile currentScreen check
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
Labels: size/XS

#2389 [C-1665] Fix deleteWallet bug
  packages/common/src/store/cache/reducer.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/S

#2393 Bump @audius/sdk version to 1.0.26
  packages/common/package.json
  packages/web/package.json
Labels: size/XS

#2380 Update amplitude.ts to use gain.audius.co
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/src/services/analytics.ts
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/services/analytics/amplitude.ts
Labels: size/S

#2396 Change IG Feature Flag name
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#2397 Bump ios
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2376 [C-1654] Only show individual tracks on offline tracks tab
  packages/common/src/models/Track.ts
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2394 [C-1663] Update DownloadStatusIndicator to handle collectionIds
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/collection-card/CollectionCard.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
Labels: size/M

#2399 [C-1582] Mobile web complete w/ tiktok + verification
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/sign-on/components/CompleteProfileWithSocial.module.css
  packages/web/src/pages/sign-on/components/CompleteProfileWithSocial.tsx
  packages/web/src/pages/sign-on/components/ProfilePage.module.css
  packages/web/src/pages/sign-on/components/ProfilePage.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
  packages/web/src/pages/sign-on/components/mobile/ProfilePage.module.css
  packages/web/src/pages/sign-on/components/mobile/ProfilePage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
  packages/web/src/pages/sign-on/components/mobile/TwitterOverlay.js
  packages/web/src/pages/sign-on/components/mobile/TwitterOverlay.module.css
Labels: size/XL

#2392 Make sure to read latest app build on desktop
  packages/web/package.json
  packages/web/scripts/dist.js
  packages/web/src/electron.js
Labels: size/M

#2391 [C-1666] Use custom optimizely datafile
  packages/mobile/src/services/remote-config/remote-config-instance.ts
  packages/web/src/services/remote-config/remote-config-instance.ts
Labels: size/M

#2360 [C-1642] Update the mobile app to use react-native-track-player and remove the video element
  package-lock.json
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/com/audiusreactnative/MainApplication.java
  packages/mobile/android/build.gradle
  packages/mobile/audio-service.js
  packages/mobile/index.js
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/react-native-video-5.1.0-alpha2.tgz
  packages/mobile/react-native.config.js
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
  packages/mobile/src/components/scrubber/Scrubber.tsx
Labels: size/XL

#2401 [C-1638] Download collections and display offline
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/hooks/useLocalImage.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
Labels: size/L

#2403 Fix other share drawers
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/XS

#2404 Bump iOS version
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2402 [PAY-767] Change advanced options to more options
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/L

#2406 v1.5.1
  lerna.json
  package-lock.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#2400 [C-1671] Finalize wallet-connect flow
  packages/common/src/schemas/index.ts
  packages/common/src/store/pages/token-dashboard/selectors.ts
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/common/src/store/pages/token-dashboard/types.ts
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/confirm-remove-wallet-drawer/ConfirmRemoveWalletDrawer.tsx
  packages/mobile/src/components/confirm-remove-wallet-drawer/index.ts
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/hooks/useDrawer.ts
  packages/mobile/src/screens/splash-screen/SplashScreen.tsx
  packages/mobile/src/screens/wallet-connect/ConnectNewWalletButton.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectStack.tsx
  packages/mobile/src/screens/wallet-connect/components/ConfirmRemoveWalletDrawer.tsx
  packages/mobile/src/screens/wallet-connect/components/EthWalletConnectOption.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallet.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/screens/wallet-connect/components/index.ts
  packages/mobile/src/screens/wallet-connect/types.ts
  packages/mobile/src/screens/wallet-connect/useCanConnectNewWallet.ts
  packages/mobile/src/screens/wallet-connect/usePhantomConnect.ts
  packages/mobile/src/screens/wallet-connect/useWalletConnect.ts
  packages/mobile/src/screens/wallet-connect/useWalletStatusToasts.ts
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/mobile/src/store/wallet-connect/types.ts
  packages/mobile/src/utils/theme.ts
  packages/web/src/common/store/pages/token-dashboard/addWalletToUser.ts
  packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/common/store/pages/token-dashboard/types.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/XXL

#2407 No expiry on getLocation cache
  packages/web/src/services/Location.ts
Labels: size/S

#2408 [C-1676] Fix android deeplinks
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/web/public/.well-known/assetlinks.json
Labels: size/M

#2409 [C-1677] Fix brick after Share to IG
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/types/global.d.ts
Labels: size/XS

#2405 Fix share to IG with solid color cover art
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/S

#2415 Bump ios version to 1.1.46
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2416 Revert package.lock
  package-lock.json
Labels: size/XS

#2414 [C-1657] Fix wallet-connect on android
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/remote-config/feature-flags.ts
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/wallet-connect/components/ConfirmRemoveWalletDrawer.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#2395 Add is playlist upload to meta on upload
  packages/common/src/models/Track.ts
  packages/common/src/schemas/index.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/web/src/common/store/upload/sagas.js
Labels: size/S

#2418 Fix android lock screen issues and small bugs for track player
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/L

#2369 [PAY-728] Audio Transactions History Table
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/store/pages/audio-transactions/selectors.ts
  packages/common/src/store/pages/audio-transactions/slice.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/transaction-details/types.ts
  packages/common/src/utils/formatUtil.ts
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/components/audio-transaction-icon/AudioTransactionIcon.tsx
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.module.css
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/components/transaction-details-modal/components/Block.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.module.css
  packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
  packages/web/src/store/sagas.ts
Labels: size/XXL

#2398 [PAY-747] Handle solana-nft-gated premium content
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/models/Collectible.ts
  packages/common/src/models/Track.ts
  packages/common/src/services/opensea-client/ethCollectibleHelpers.ts
  packages/common/src/services/solana-client/SolanaClient.ts
  packages/common/src/services/solana-client/solCollectibleHelpers.ts
  packages/common/src/services/solana-client/types.ts
  packages/web/src/common/store/premiumContent/sagas.ts
Labels: size/L

#2422 [PAY-757] Prevent use of premium tracks as remix parents
  packages/web/src/common/store/remix-settings/sagas.ts
Labels: size/XS

#2420 [C-1087] Check for updates to offline items on startup
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/hooks/useFetchAllFavoritedTrackIds.ts
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/services/offline-downloader/index.ts
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
  packages/mobile/src/utils/populateCoverArtSizes.ts
  packages/mobile/src/utils/trackUtils.ts
Labels: size/XL

#2417 Remove entity manager feature flags for tracks and playlists
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/upload/sagas.js
Labels: size/L

#2419 [C-1684] Fix rewards page upload track button
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/utils/challenges.tsx
Labels: size/L

#2423 [C-1688] Finalize mobile wallet-connect
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/audio-breakdown-drawer/Wallet.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallet.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletsTable.tsx
Labels: size/L

#2421 [C-1652] Add solana mobile deployment
  packages/mobile/android/app/api.json
  packages/mobile/android/app/api.txt
  packages/mobile/dapp-store/.asset-manifest.json
  packages/mobile/dapp-store/README.md
  packages/mobile/dapp-store/config.yaml
  packages/mobile/dapp-store/media/app_icon.png
  packages/mobile/dapp-store/media/publisher_icon.png
  packages/mobile/dapp-store/media/screenshot1.png
  packages/mobile/dapp-store/media/screenshot2.png
  packages/mobile/dapp-store/media/screenshot3.png
  packages/mobile/dapp-store/media/screenshot4.png
  packages/mobile/dapp-store/media/screenshot5.png
  packages/mobile/dapp-store/media/screenshot6.png
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/XXL

#2427 Skip offline content sync when offline
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/utils/reachability.ts
Labels: size/S

#2426 [C-1625] Fix mobile profile follow button
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/M

#2425 [C-1675] Fix useCallback
  packages/mobile/ios/Podfile.lock
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/components/collectibles-playlist-table/CollectiblesPlaylistTable.tsx
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/stripe-on-ramp-modal/StripeOnRampModal.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/history-page/HistoryPageProvider.tsx
  packages/web/src/pages/landing-page/components/Description.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileTags.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/sign-on/components/mobile/FollowPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/types/react/useCallback.d.ts
Labels: size/L

#2431 [PAY-771][PAY-773] UI fixes for TransactionDetailsModal
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
Labels: size/S

#2433 [C-880] Prevent track count change when filtering
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/XS

#2434 [C-943] Fix user menu unfollow
  packages/web/src/components/menu/UserMenu.tsx
Labels: size/XS

#2435 [C-712] Improve top-supporter scroll region
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
Labels: size/M

#2436 hotfix: Broken modal headers
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
Labels: size/S

#2430 [C-1689] Simplify insta oauth and add tiktok handle check
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/store/oauth/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/signon/verifiedChecker.ts
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/instagram-button/InstagramButton.tsx
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/pages/settings-page/components/InstagramAccountVerified.tsx
  packages/web/src/pages/sign-on/components/ProfileForm.tsx
  packages/web/src/services/audius-backend/audius-backend-instance.ts
Labels: size/L

#2438 [C-1078] Add offline mode confirmation drawers
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/components/drawers/ConfirmationDrawer.tsx
  packages/mobile/src/components/drawers/DeleteConfirmationDrawer.tsx
  packages/mobile/src/components/drawers/RemoveDownloadedCollectionDrawer.tsx
  packages/mobile/src/components/drawers/RemoveDownloadedFavoritesDrawer.tsx
  packages/mobile/src/components/drawers/UnfavoriteDownloadedCollectionDrawer.tsx
  packages/mobile/src/components/drawers/index.ts
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/hooks/useDrawer.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/CancelEditTrackDrawer.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/store/drawers/selectors.ts
  packages/mobile/src/store/drawers/slice.ts
Labels: size/XL

#2432 [PAY-772] Update table styles to remove the space between the header text and sorters
  packages/web/src/components/table/Table.module.css
Labels: size/XS

#2437 [C-1692] Prevent infinite failed requests while offline
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/mobile/src/utils/reachability.ts
  packages/web/src/common/store/notifications/sagas.ts
Labels: size/M

#2439 [C-1662] Cancel queued downloads on toggle off
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
Labels: size/M

#2442 [C-1674] Fix queue controls for offline playback
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
Labels: size/XS

#2440 [C-1673] Add collection to favorites on download
  packages/common/src/models/Analytics.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
Labels: size/S

#2444 [C-1683] Add Rate CTA Drawer
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/App.tsx
  packages/mobile/src/Drawers.tsx
  packages/mobile/src/assets/images/iconThumbsDown.svg
  packages/mobile/src/assets/images/iconThumbsUp.svg
  packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
  packages/mobile/src/components/rate-cta-drawer/RateCtaReminder.tsx
  packages/mobile/src/components/rate-cta-drawer/constants.ts
  packages/mobile/src/components/rate-cta-drawer/index.ts
  packages/mobile/src/hooks/useAsyncStorage.ts
  packages/mobile/src/store/drawers/slice.ts
  packages/mobile/src/store/rate-cta/sagas.ts
  packages/mobile/src/store/rate-cta/slice.ts
  packages/mobile/src/store/sagas.ts
Labels: size/L

#2445 Don't stop loading if one collection fails
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
Labels: size/M

#2443 [C-1478] Clear offline downloads when switching accounts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/slice.ts
  packages/mobile/src/store/sign-out/sagas.ts
Labels: size/L

#2446 [C-1698] Fix first offline playback stalled
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/hooks/useOfflineTrackUri.ts
Labels: size/L

#2424 [PAY-774] Change Coinbase Pay logo
  packages/web/src/assets/img/coinbase-pay/LogoCoinbase.svg
  packages/web/src/components/on-ramp-button/OnRampButton.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
Labels: size/S

#2448 Fix playlist track removal
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/components/table/components/OverflowMenuButton.tsx
Labels: size/XS

#2447 [C-1646][C-1647] Handle more offline lineup states
  packages/common/src/models/Track.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/hooks/useFetchAllFavoritedTracks.ts
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
Labels: size/L

#2449 Fix AudiusSDK to not select prod discovery nodes on state environment
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/services/audius-sdk/audiusSdk.ts
Labels: size/L

#2453 Fix favorited tracks download
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/hooks/useFetchAllFavoritedTracks.ts
Labels: size/S

#2451 Fix finish page upload title link
  packages/web/src/pages/upload-page/components/FinishPage.js
Labels: size/XS

#2454 Load offline collections properly with the dev override
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
Labels: size/XS

#2455 [C-1714] Improve mobile play count
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/audio/listens.ts
  packages/web/src/common/store/social/tracks/recordListen.ts
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/L

#2457 Fix offline mode QA backdoor
  packages/mobile/src/hooks/useFetchAllFavoritedTracks.ts
  packages/mobile/src/hooks/useIsOfflineModeEnabled.ts
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/selectors.ts
Labels: size/M

#2458 [C-1717] Attempt to fix android crash on scrollToLocation
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/S

#2459 [C-1721] Fix case where cached track is incomplete
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/XS

#2456 [C-1083, C-1080] Add offline play count recording
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/services/offline-downloader/workers/playCounterWorker.ts
  packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
Labels: size/L

#2461 C-1725 Fix sign-up with Instagram
  packages/common/src/services/oauth/formatSocialProfile.ts
Labels: size/S

#2463 Offline mode tweaks
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/web/src/common/store/player/sagas.ts
Labels: size/S

#2460 [C-1724] Add track screen skeleton
  packages/mobile/src/components/skeleton/Skeleton.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenSkeleton.tsx
Labels: size/L

#2464 Fix background reset issues for track player on android 12+
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/S

#2462 [c-1719] QA update for Rate CTA Drawer
  packages/mobile/src/assets/images/iconThumbsDown.svg
  packages/mobile/src/assets/images/iconThumbsUp.svg
  packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
Labels: size/S

#2467 Fix track player artwork, speed up useImage
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
Labels: size/M

#2387 [PAY-740] Use Identity endpoint for location
  packages/common/src/services/audius-backend/eagerLoadUtils.ts
  packages/common/src/services/local-storage/LocalStorage.ts
  packages/web/src/services/Location.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/utils/gdpr.ts
Labels: size/L

#2474 Staging deeplinks on iOS
  .circleci/src/commands/@web-commands.yml
  packages/web/public/.well-known/apple-app-site-association-stage
Labels: size/S

#2473 [C-1699] Add analytics for Rate CTA drawer
  packages/common/src/models/Analytics.ts
  packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
  packages/mobile/src/store/rate-cta/sagas.ts
Labels: size/S

#2471 Fix mobile build due to location changes
  packages/common/src/services/index.ts
  packages/common/src/services/location.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/services/Location.ts
Labels: size/L

#2470 [C-1728] Add collection screen skeleton
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/components/skeletons/EntitySkeleton.tsx
  packages/mobile/src/components/skeletons/index.ts
  packages/mobile/src/components/track-list/TrackListItemSkeleton.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenSkeleton.tsx
  packages/mobile/src/screens/track-screen/TrackScreenSkeleton.tsx
Labels: size/L

#2475 Only show "upload first playlist" if user is an artist C-881 C-766
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/XS

#2477 [C-1581] Mobile Complete w/ TikTok
  packages/common/src/models/Analytics.ts
  packages/common/src/services/oauth/formatSocialProfile.ts
  packages/common/src/store/account/types.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/oauth/OAuth.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/store/oauth/actions.ts
  packages/mobile/src/store/oauth/reducer.ts
  packages/mobile/src/store/oauth/sagas.ts
  packages/mobile/src/store/oauth/selectors.ts
  packages/mobile/src/store/oauth/types.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/pages/sign-on/components/CompleteProfileWithSocial.tsx
  packages/web/src/pages/sign-on/components/ProfilePage.tsx
Labels: size/XL

#2466 Fix api-client types by fixing @audius/common absolute imports
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/local-storage/LocalStorage.ts
  packages/common/src/utils/hashIds.ts
  packages/web/src/common/store/premiumContent/sagas.ts
Labels: size/M

#2476 [C-1660] Clear feed on sign-out
  packages/mobile/src/App.tsx
  packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
  packages/mobile/src/components/rate-cta-drawer/RateCtaReminder.tsx
  packages/mobile/src/components/rate-cta-drawer/constants.ts
  packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
  packages/mobile/src/constants/storage-keys.ts
  packages/mobile/src/hooks/useSessionCount.ts
  packages/mobile/src/notifications.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/account/sagas.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/mobile/src/store/theme/sagas.ts
Labels: size/M

#2479 Fix tooltip on completed upload page C-1516
  packages/web/src/pages/upload-page/components/ShareBanner.module.css
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
Labels: size/S

#2480 Polyfill BigInt
  packages/mobile/index.js
  packages/mobile/package.json
Labels: size/XS

#2472 [C-1648] Address sentry issues
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
Labels: size/M

#2478 [C-1722] Fix suggested follows deselect
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
Labels: size/S

#2481 [C-1729] Add profile/collection card skeletons
  packages/common/src/store/pages/explore/selectors.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/artist-card/index.ts
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/collection-card/index.ts
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/collection-list/CollectionCardSkeleton.tsx
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/profile-list/ProfileCard.tsx
  packages/mobile/src/components/profile-list/ProfileCardSkeleton.tsx
  packages/mobile/src/components/profile-list/ProfileList.tsx
  packages/mobile/src/components/profile-list/index.ts
  packages/mobile/src/components/skeleton/Skeleton.tsx
  packages/mobile/src/components/skeleton/index.ts
  packages/mobile/src/screens/explore-screen/components/TabInfo.tsx
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
  packages/web/src/common/store/cache/users/sagas.js
Labels: size/L

#2483 [C-1738] Fix mobile crash
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/patches/@noble+ed25519+1.7.1.patch
  packages/common/patches/@noble+secp256k1+1.7.0.patch
  packages/mobile/index.js
Labels: size/XXL

#2484 Remove react-native-threads
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/com/audiusreactnative/MainApplication.java
  packages/mobile/android/settings.gradle
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/react-native.config.js
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/services/threads/getDominantColors.ts
  packages/mobile/src/utils/dominantColors.ts
  packages/mobile/threads/jimp.min.js
Labels: size/L

#2485 Replace react-native-dark-mode with react-native-dynamic
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/theme/slice.ts
  packages/mobile/__tests__/App-test.tsx
  packages/mobile/index.js
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/app/ErrorBoundary.tsx
  packages/mobile/src/app/ThemeProvider.tsx
  packages/mobile/src/app/index.ts
  packages/mobile/src/store/theme/sagas.ts
Labels: size/L

#2487 Force polyfill of BigInt on ios as well
  packages/mobile/index.js
  packages/mobile/patches/big-integer+1.6.51.patch
Labels: size/S

#2491 Add getImageSourceOptimistic
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
Labels: size/L

#2492 [C-1672] Add TikTok to settings Verification flow on mobile
  packages/common/src/models/Analytics.ts
  packages/mobile/src/components/social-button/SocialButton.tsx
  packages/mobile/src/components/social-button/index.ts
  packages/mobile/src/components/tiktok-auth/TIkTokAuthButton.tsx
  packages/mobile/src/components/tiktok-auth/index.ts
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/store/oauth/actions.ts
Labels: size/L

#2486 Remove react-native-static-server
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/ThemeProvider.tsx
  packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
  packages/mobile/src/components/web-app-account-sync/WebAppAccountClear.tsx
  packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
  packages/mobile/src/components/web-app-account-sync/index.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/store/sagas.ts
Labels: size/L

#2490 [C-1737] Upgrade react-native to 0.67.5
  packages/mobile/android/app/src/main/res/drawable/rn_edit_text_material.xml
  packages/mobile/android/app/src/main/res/values/styles.xml
  packages/mobile/android/build.gradle
  packages/mobile/android/gradle/wrapper/gradle-wrapper.properties
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
Labels: size/XL

#2489 [C-1733] Refactor suggested follows
  packages/mobile/src/assets/images/iconWand.svg
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/card/index.ts
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/Screen/SafeAreaScreen.tsx
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/components/core/Screen/ScreenHeaderButton.tsx
  packages/mobile/src/components/core/Screen/index.tsx
  packages/mobile/src/components/core/SectionList.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/components/core/ToggleButton.tsx
  packages/mobile/src/components/profile-list/ProfileCard.tsx
  packages/mobile/src/components/profile-list/ProfileList.tsx
  packages/mobile/src/components/profile-list/index.ts
  packages/mobile/src/components/suggested-follows/ArtistCategory.tsx
  packages/mobile/src/components/suggested-follows/ContinueButton.tsx
  packages/mobile/src/components/suggested-follows/PickArtistsForMeButton.tsx
  packages/mobile/src/components/suggested-follows/SelectArtistCategoryButtons.tsx
  packages/mobile/src/components/suggested-follows/SuggestedArtistsList.tsx
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/hooks/usePressScaleAnimation.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
  packages/mobile/src/screens/signon/FirstFollows.tsx
  packages/mobile/src/store/sign-out/sagas.ts
  packages/mobile/src/store/store.ts
  packages/web/src/common/store/pages/signon/selectors.js
  packages/web/src/common/store/pages/signon/types.ts
Labels: size/XXL
