Repository AudiusProject/audius-client, pull requests merged in 2023-09, with the labels that each got.

#3998 [C-2954] Fix hashtag search
  packages/mobile/src/screens/search-screen/SearchBar.tsx
Labels: size/XS

#4000 [C-3017] Reset the new upload flow state when the upload button in the side nav is clicked
  packages/common/src/store/upload/selectors.ts
  packages/web/src/pages/upload-page/UploadPageNew.tsx
Labels: size/M

#3999 [PAY-1734] Implement skeleton withdraw USDC modal
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/modals/withdraw-usdc-modal/index.ts
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.module.css
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.module.css
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.module.css
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/Hint.module.css
  packages/web/src/components/withdraw-usdc-modal/components/Hint.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TextRow.module.css
  packages/web/src/components/withdraw-usdc-modal/components/TextRow.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.module.css
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.module.css
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XL

#3994 Remove unused TrackAvailabilityModal
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
Labels: size/L

#4001 [C-3031] Fix transaction history numbers
  packages/common/src/utils/formatUtil.ts
Labels: size/XS

#4003 [PAY-1764] Update USDCCard icons in artist dashboard
  packages/stems/src/assets/icons/iconWithdraw.svg
  packages/stems/src/assets/icons/logoUSDC.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.module.css
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
Labels: size/S

#4005 [PAY-1723] Purchase content twitter share copy
  packages/common/src/models/Analytics.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
Labels: size/M

#4008 CI fixes for mobile
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@web-jobs.yml
Labels: size/S

#3989 [C-3014] Add prompt on leaving upload form in progress
  packages/web/src/components/navigation-prompt/NavigationPrompt.module.css
  packages/web/src/components/navigation-prompt/NavigationPrompt.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/L

#4006 [C-3004] Scroll to top when switching tracks in upload
  packages/web/src/pages/App.js
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/M

#4002 [PAY-1791] Withdraw USDC - transfer to dest account
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#4011 Prepare 1.5.40 full app release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#4010 [C-3035] Stale stats for offline tracks
  packages/common/src/models/Collection.ts
  packages/common/src/models/Track.ts
  packages/common/src/store/cache/reducer.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
Labels: size/S

#4012 [C-3032] Fix collectible gated upload
  packages/web/src/components/ai-attribution-modal/DropdownInput.js
  packages/web/src/components/data-entry/DropdownInput.d.ts
  packages/web/src/components/data-entry/DropdownInput.js
  packages/web/src/components/data-entry/DropdownInput.module.css
  packages/web/src/components/link/ExternalLink.tsx
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedDescription.tsx
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.module.css
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedRadioField.tsx
Labels: size/L

#4013 Fix release CI
  .circleci/config.yml
  .circleci/src/commands/@mobile-commands.yml
  package-lock.json
  package.json
  packages/web/package.json
Labels: size/XS

#4009 [C-2950 C-3033] Fix and simplify issues resulting from collection fetching
  packages/common/src/store/pages/collection/actions.ts
  packages/common/src/store/pages/collection/selectors.ts
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/utils/route/collectionRouteParser.ts
Labels: size/L

#4016 Fix support email
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
Labels: size/XS

#4020 Install pip for android release
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#4018 [C-3039] Add icon to profile share button
  packages/web/src/components/stat-banner/StatBanner.tsx
Labels: size/M

#4021 [C-2645] Fix icon-info size
  packages/mobile/src/assets/images/iconInfo.svg
  packages/stems/src/assets/icons/iconInfo.svg
  packages/web/src/assets/img/iconInfo.svg
Labels: size/M

#4026 [C-2976] Fix upload form validation timing and display
  packages/web/src/components/form-fields/ArtworkField.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.module.css
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/validation.ts
Labels: size/M

#4030 Add guard to prevent attempted read of undefined queue items
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XS

#4019 [C-2536] Fix track name cutoff
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/delete-chat-drawer/DeleteChatDrawer.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/offline-placeholder/OfflinePlaceholder.tsx
  packages/mobile/src/components/offline-placeholder/messages.ts
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx
Labels: size/M

#4031 [PAY-1793] Use existing SOL to fund dest ATA
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#4028 Empty states for different library category filters PAY-1797
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/components/emptyStateMessages.ts
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/L

#4022 [C-2792] Surface play count for hidden tracks
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/S

#4017 [C-3038] Remove playlist updates feature flags
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/cache/collections/selectors.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/createPlaylistModal/actions.ts
  packages/common/src/store/ui/createPlaylistModal/reducer.ts
  packages/common/src/store/ui/createPlaylistModal/selectors.ts
  packages/common/src/store/ui/createPlaylistModal/types.ts
  packages/common/src/store/ui/index.ts
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/core/FormImageInput.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/screens/app-screen/AppScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/FavoritesTabScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistModalScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/LegacyEditPlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/LegacyPlaylistDescriptionInput.tsx
  packages/mobile/src/screens/edit-playlist-screen/LegacyPlaylistImageInput.tsx
  packages/mobile/src/screens/edit-playlist-screen/LegacyPlaylistNameInput.tsx
  packages/mobile/src/screens/edit-playlist-screen/LegacyRandomImageButton.tsx
  packages/mobile/src/screens/edit-playlist-screen/index.ts
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/create-playlist/CreatePlaylistModal.module.css
  packages/web/src/components/create-playlist/CreatePlaylistModal.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/EmptyLibraryNavLink.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/nav/mobile/TopLevelPage.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/saved-page/components/mobile/NewPlaylistButton.tsx
  packages/web/src/store/types.ts
Labels: size/XXL

#4025 [C-2862] Fix clipped repost message text
  packages/web/src/components/Icon/Icon.module.css
  packages/web/src/components/track/desktop/stats/Stats.module.css
  packages/web/src/components/track/desktop/stats/Stats.tsx
  packages/web/src/components/track/desktop/stats/StatsText.tsx
Labels: size/L

#4033 [C-2924] Fix ArtistRecommendation description alignment
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
Labels: size/XS

#4032 [C-2841] Use limit + offset for feed
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
Labels: size/M

#4029 [PAY-1510] Add pills and clean up artist dashboard
  packages/web/src/components/input/Input.module.css
  packages/web/src/components/input/Input.tsx
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/artist-dashboard-page/components/ArtistCard.module.css
  packages/web/src/pages/artist-dashboard-page/components/ArtistCard.tsx
  packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.module.css
  packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.tsx
  packages/web/src/pages/artist-dashboard-page/store/actions.js
  packages/web/src/pages/artist-dashboard-page/store/reducer.js
  packages/web/src/pages/artist-dashboard-page/store/sagas.js
  packages/web/src/pages/artist-dashboard-page/store/sagas.ts
  packages/web/src/pages/artist-dashboard-page/store/selectors.ts
  packages/web/src/pages/artist-dashboard-page/store/slice.ts
  packages/web/src/pages/artist-dashboard-page/store/types.ts
  packages/web/src/store/reducers.ts
Labels: size/XXL

#4036 Fix Jupiter caching bad route info
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/XS

#4023 Symlink react-native for android release
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#4037 [PAY-1792] Add formik, zod, and proper inputs to USDC withdrawal modal
  packages/common/src/store/ui/modals/createModal.ts
  packages/common/src/store/ui/modals/withdraw-usdc-modal/index.ts
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
  packages/web/src/utils/tokenInput.ts
Labels: size/L

#4038 [C-3044] Add preview functionality to new upload flow
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/pages/EditPage.tsx
  packages/web/src/pages/upload-page/utils/uploadPreviewContext.tsx
Labels: size/L

#4039 [PAY-1725] Display proper amount in track sold notification
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseSellerNotification.tsx
Labels: size/S

#4040 [PAY-1811] Fix default/empty profile picture in now playing bar/dashboard
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx
  packages/web/src/pages/artist-dashboard-page/components/ArtistCard.module.css
  packages/web/src/pages/artist-dashboard-page/components/ArtistCard.tsx
Labels: size/S

#4042 [PAY-1763][PAY-1810] Wire up links to Purchases/Sales pages
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
  packages/web/src/pages/artist-dashboard-page/store/sagas.ts
  packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx
  packages/web/src/pages/purchases-and-sales/PurchasesTable.tsx
  packages/web/src/pages/purchases-and-sales/SalesTable.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/M

#4044 [C-3024] Fix solana dapp store ci
  .circleci/src/commands/@mobile-commands.yml
  packages/mobile/dapp-store/.nvmrc
Labels: size/S

#4045 Wire up withdraw USDC saga to modal state
  packages/common/src/store/ui/withdraw-usdc/slice.ts
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
  packages/web/src/utils/tokenInput.ts
Labels: size/L

#4048 Auto favorite tracks on purchase PAY-1772
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/XS

#4035 Add filter functionality back to library PAY-1771
  packages/common/src/api/library.ts
  packages/common/src/store/cache/collections/selectors.ts
  packages/common/src/utils/collectionUtils.ts
  packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
  packages/web/src/common/store/pages/saved/sagas.ts
Labels: size/M

#4051 Fix mobile deleted track tile
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/L

#4052 [PAY-1814] Store USDC balances in wallet slice
  packages/common/src/hooks/useUSDCBalance.ts
  packages/common/src/store/purchase-content/utils.ts
  packages/common/src/store/wallet/selectors.ts
  packages/common/src/store/wallet/slice.ts
  packages/common/src/utils/wallet.ts
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
Labels: size/L

#4053 Fix balance formatting on USDC card
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
Labels: size/XS

#4054 [PAY-1794] Math.min(withdrawalAmount, latestBalance) after using USDC to pay tx fee
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/S

#4047 PAY-1798 Don't show purchased filter for Library collections tabs
  packages/common/src/store/pages/index.ts
  packages/common/src/store/pages/saved-page/actions.ts
  packages/common/src/store/pages/saved-page/reducer.ts
  packages/common/src/store/pages/saved-page/selectors.ts
  packages/common/src/store/pages/saved-page/types.ts
  packages/common/src/store/pages/saved-page/utils.ts
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/LibraryCategorySelectionMenu.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
  packages/web/src/common/store/pages/saved/sagas.ts
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
  packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/hooks/useCollectionsData.tsx
Labels: size/L

#4046 [C-3049] Fix upload type error where upload type is undefined
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/XS

#4058 Fix sdk:update command after node migration
  package.json
Labels: size/XS

#4049 [C-3056] Fix remix callout text overflow
  packages/mobile/src/components/help-callout/HelpCallout.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
Labels: size/S

#4059 [PAY-1773] Add sorting by buyer name to sales table
  package-lock.json
  packages/common/package.json
  packages/embed/package.json
  packages/mobile/package.json
  packages/web/package.json
  packages/web/src/pages/purchases-and-sales/SalesPage.tsx
  packages/web/src/pages/purchases-and-sales/SalesTable.tsx
Labels: size/S

#4057 Feature flag USDC purchases in library PAY-1799
  packages/mobile/src/screens/favorites-screen/LibraryCategorySelectionMenu.tsx
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
Labels: size/S

#4063 Fix bad merge breaking main
  packages/web/src/pages/saved-page/components/mobile/NewPlaylistButton.tsx
Labels: size/XS

#4050 [C-3052] Fix playlist page theme
  packages/web/src/components/collection/desktop/PublishConfirmationModal.module.css
  packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.module.css
  packages/web/src/components/table/Table.module.css
Labels: size/S

#4034 [C-2548] Fix favorites table saved date filter
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
Labels: size/S

#4060 Fixes solana-dapp-store ci with new node
  .circleci/src/commands/@mobile-commands.yml
Labels: size/S

#4066 [PAY-1833] Increase trending playlists fetch limit
  packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
Labels: size/XS

#4055 [C-3060] Fix mobile outbound link experience
  packages/common/src/utils/index.ts
  packages/common/src/utils/linking.ts
  packages/common/src/utils/urlUtils.ts
  packages/mobile/src/components/action-drawer/ActionDrawer.tsx
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/drawer/AppDrawer.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/DrawerHeader.tsx
  packages/mobile/src/components/feed-filter-drawer/FeedFilterDrawer.tsx
  packages/mobile/src/components/leaving-audius-drawer/LeavingAudiusDrawer.tsx
  packages/mobile/src/components/playback-rate-drawer/PlaybackRateDrawer.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
  packages/mobile/src/screens/chat-screen/LinkPreview.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/CollectiblesTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/selectors.ts
  packages/web/src/components/link/ExternalLink.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#4041 [C-2994] Improve mobile image selection
  package-lock.json
  packages/common/src/store/cache/collections/types.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/components/core/Screen/ScreenContent.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/fields/PickArtworkField.tsx
  packages/mobile/src/components/form-screen/FormScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/ProfileImageField.tsx
  packages/mobile/src/screens/edit-profile-screen/ProfileTextField.tsx
  packages/mobile/src/screens/signon/ProfileImage.tsx
  packages/mobile/src/screens/signon/ProfileManual.tsx
  packages/mobile/src/utils/launchSelectImageActionSheet.ts
  packages/mobile/src/utils/theme.ts
Labels: size/L

#4068 Bump version to v1.5.41 and fix auto version bump
  .circleci/config.yml
  package-lock.json
  package.json
  packages/common/package.json
  packages/embed/package.json
  packages/eslint-config-audius/package.json
  packages/mobile/package.json
  packages/probers/package.json
  packages/stems/package.json
  packages/web/package.json
Labels: size/S
