Repository AudiusProject/audius-client, pull requests merged in 2023-08, with the labels that each got.

#3823 Update userbank function usage to pass config object
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/waudio.ts
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/buyCrypto.ts
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#3832 Fix tag input
  packages/web/src/components/data-entry/TagInput.js
Labels: size/XS

#3835 Fix broken track upload for electronic subgenres on mobile
  packages/common/src/utils/genres.ts
  packages/mobile/src/screens/edit-track-screen/screens/SelectGenreScreen.tsx
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
Labels: size/S

#3837 [PAY-1685] Wire up stripe UI for USDC purchase in mobile
  packages/common/package-lock.json
  packages/common/package.json
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/premium-track-purchase-drawer/StripePurchaseConfirmationButton.tsx
  packages/mobile/src/services/buyCrypto.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/audius-backend/BuyAudio.ts
Labels: size/M

#3833 Add cypress upload test for subgenre
  packages/probers/README.md
  packages/probers/cypress/e2e/uploadTrack.cy.ts
Labels: size/M

#3838 [C-2923] Fix toasts in modal screens
  packages/mobile/src/components/core/ModalScreen.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/app-screen/AppScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistModalScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/index.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/edit-track-screen/index.ts
  packages/mobile/src/screens/tip-artist-screen/TipArtistModalScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/index.ts
  packages/mobile/src/screens/upload-screen/index.ts
  packages/mobile/src/screens/upload-screen/screens/UploadModalScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/index.ts
  packages/mobile/src/screens/wallet-connect/WalletConnectModalScreen.tsx
  packages/mobile/src/screens/wallet-connect/index.ts
Labels: size/L

#3839 Upgrade sdk to beta.105 to fix rewards claiming
  packages/common/package-lock.json
  packages/common/package.json
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3828 [PAY-1687] Web: Share tracks, playlists, and albums via Direct Message
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/create-chat-modal/selectors.ts
  packages/common/src/store/ui/create-chat-modal/slice.ts
  packages/common/src/store/ui/index.ts
  packages/stems/src/assets/icons/iconEmbed.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/components/ShareDialog.module.css
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/components/ShareDrawer.tsx
  packages/web/src/components/share-modal/messages.ts
  packages/web/src/components/share-modal/types.ts
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Labels: size/L

#3836 [C-2907] Add contextual-menu, refactor release-date-field
  packages/mobile/src/components/core/ContextualMenu.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/edit-track-screen/fields/AdvancedOptionsField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/ContextualMenuField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/IsrcIswcField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/LicenseTypeField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/RemixSettingsField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/SelectGenreField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/SelectMoodField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/TrackVisibilityField.tsx
  packages/stems/src/components/Icons/index.ts
  packages/stems/src/components/Icons/types.ts
  packages/stems/src/components/Modal/Modal.module.css
  packages/web/src/components/Icon/Icon.tsx
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/tile/Tile.module.css
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/components/typography/Text.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/components/TrackModalArray.tsx
  packages/web/src/pages/upload-page/fields/ContextualSubmenuField.module.css
  packages/web/src/pages/upload-page/fields/ReleaseDateField.module.css
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.tsx
Labels: size/XL

#3829 Fix dapp store deployment
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
Labels: size/M

#3842 Disable upload redesign
  packages/web/src/pages/upload-page/UploadPage.tsx
Labels: size/XS

#3840 [PAY-1688] Mobile: Share track, collection to DMs
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Labels: size/M

#3803 [Harmony] Add SelectablePill to Harmony PAY-1654
  packages/stems/src/components/HarmonyButton/types.ts
  packages/stems/src/components/SelectablePill/HarmonySelectablePill.module.css
  packages/stems/src/components/SelectablePill/HarmonySelectablePill.stories.tsx
  packages/stems/src/components/SelectablePill/HarmonySelectablePill.tsx
  packages/stems/src/components/SelectablePill/index.ts
  packages/stems/src/components/SelectablePill/types.ts
  packages/stems/src/index.tsx
  packages/stems/src/utils/types.ts
Labels: size/L

#3841 Add prepare step to dapp-store ci flow
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
Labels: size/S

#3844 DMs: Web: Don't nav back when clicking outside the modal
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
Labels: size/XS

#3846 Add npm run clean script
  package.json
  packages/mobile/package.json
Labels: size/XS

#3849 Update SDK to latest 3.0.3-beta.109
  packages/common/package-lock.json
  packages/common/package.json
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3850 Fix send audio flow
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#3847 [C-2675][C-2692] Add multi track navigation sidebar and form controls
  packages/stems/src/components/HarmonyButton/HarmonyButton.module.css
  packages/stems/src/components/HarmonyButton/HarmonyButton.tsx
  packages/stems/src/components/HarmonyButton/types.ts
  packages/web/src/assets/img/iconTrash.svg
  packages/web/src/components/Icon/Icon.tsx
  packages/web/src/components/layout/layout.module.css
  packages/web/src/pages/upload-page/components/EditPageNew.module.css
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/fields/ModalField.module.css
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.module.css
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.module.css
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.module.css
  packages/web/src/pages/upload-page/fields/availability/SpecialAccessFields.module.css
  packages/web/src/pages/upload-page/forms/AttributionModalForm.module.css
  packages/web/src/pages/upload-page/forms/RemixModalForm.module.css
  packages/web/src/pages/upload-page/forms/types.ts
  packages/web/src/pages/upload-page/forms/utils.ts
Labels: size/XL

#3852 [PAY-1692] Rewrite 'Share to DMs' using less stateful logic
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/store/ui/create-chat-modal/slice.ts
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
  packages/mobile/src/store/chat/sagas.ts
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/ChatPageProvider.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/store/application/ui/chat/sagas.ts
Labels: size/L

#3751 [C-2852 PLAT-1094 PLAT-1093] Add fetch collection by permalink
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/account/types.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/card/desktop/CollectionArtCard.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.tsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
  packages/web/src/components/notification/Notification/utils.ts
  packages/web/src/components/search-bar/ConnectedSearchBar.js
  packages/web/src/components/share-modal/utils.ts
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/landing-page/components/FeaturedContent.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/saved-page/components/desktop/CollectionCard.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/upload-page/UploadPageLegacy.js
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/utils/route.ts
  packages/web/src/utils/route/collectionRouteParser.ts
  packages/web/src/utils/seo.ts
Labels: size/XL

#3856 [C-2940] Update google analytics tags and fix embed build
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/embed/preact.config.js
  packages/embed/src/template.html
  packages/embed/src/util/empty.js
  packages/web/.env/.env.prod
  packages/web/public/index.html
Labels: size/M

#3855 [C-2879] Add validation to single track upload flow
  packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
  packages/web/src/components/ai-attribution-modal/DropdownInput.js
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/data-entry/HelperText.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/fields/ModalField.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.module.css
  packages/web/src/pages/upload-page/forms/AttributionModalForm.module.css
  packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
  packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.tsx
Labels: size/L

#3858 [C-2941] Modify cloudflare worker to pull in SEO data from discovery nodes
  packages/web/.gitignore
  packages/web/public/index.html
  packages/web/scripts/workers-site/index.js
  packages/web/wrangler.toml
Labels: size/L

#3859 Add nodes to env for SEO support
  packages/web/wrangler.toml
Labels: size/S

#3861 Minor improvements to SEO flow merged in #3859
  packages/web/scripts/workers-site/index.js
Labels: size/S

#3862 [PAY-1695] DMs: Entrypoint Analytics
  packages/common/src/models/Analytics.ts
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavLink.tsx
  packages/mobile/src/screens/profile-screen/MessageButton.tsx
  packages/web/src/components/banner/DirectMessagesBanner.tsx
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/M

#3863 Fix broken playlist fetch via resolve
  packages/web/scripts/workers-site/index.js
Labels: size/S

#3853 QA-588 Fix collection card profile link
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
Labels: size/XS

#3866 Preserve CIDs for track and collection cover arts
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
  packages/web/src/common/store/cache/collections/utils/optimisticUpdateCollection.ts
  packages/web/src/common/store/cache/tracks/sagas.js
Labels: size/M

#3848 [C-2926] Implement selected values for upload contextual menu fields
  packages/web/src/components/Icon/Icon.tsx
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/form-fields/TextField.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.module.css
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/components/TrackModalArray.module.css
  packages/web/src/pages/upload-page/components/TrackModalArray.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.module.css
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/AttributionField.module.css
  packages/web/src/pages/upload-page/fields/AttributionField.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.module.css
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/TrackInfo.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/index.ts
  packages/web/src/pages/upload-page/fields/RemixSettingsField/types.ts
  packages/web/src/pages/upload-page/fields/SourceFilesField.module.css
  packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
  packages/web/src/pages/upload-page/fields/SwitchRowField.module.css
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.tsx
  packages/web/src/pages/upload-page/fields/availability/SpecialAccessFields.tsx
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.module.css
  packages/web/src/pages/upload-page/hooks.ts
  packages/web/src/pages/upload-page/types.ts
Labels: size/XXL

#3869 Remove .only on upload cypress test
  packages/probers/cypress/e2e/uploadTrack.cy.ts
Labels: size/XS

#3860 [PAY-1430] "Leaving Audius" Warning for External Links (and createModal helper)
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/leaving-audius-modal/index.ts
  packages/common/src/store/ui/modals/createModal.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/iconQuestionCircle.svg
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/DrawerHeader.tsx
  packages/mobile/src/components/help-callout/HelpCallout.tsx
  packages/mobile/src/components/leaving-audius-drawer/LeavingAudiusDrawer.tsx
  packages/mobile/src/components/leaving-audius-drawer/index.ts
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/LinkPreview.tsx
  packages/stems/src/assets/icons/iconExternalLink.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/components/help-callout/HelpCallout.tsx
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.module.css
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/LinkPreview.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#3871 Fix mobile crash on drawer dismiss
  packages/mobile/src/components/drawer/Drawer.tsx
Labels: size/XS

#3834 [PAY-1630] Wire up purchase content sagas
  packages/common/src/models/Analytics.ts
  packages/common/src/models/Track.ts
  packages/common/src/services/audius-backend/index.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/audius-backend/stripe.ts
  packages/common/src/services/audius-backend/waudio.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/store/buy-usdc/index.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/buy-usdc/selectors.ts
  packages/common/src/store/buy-usdc/slice.ts
  packages/common/src/store/buy-usdc/types.ts
  packages/common/src/store/buy-usdc/utils.ts
  packages/common/src/store/index.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/store/purchase-content/index.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/purchase-content/selectors.ts
  packages/common/src/store/purchase-content/slice.ts
  packages/common/src/store/purchase-content/types.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/stripe-modal/sagas.ts
  packages/common/src/store/ui/stripe-modal/selectors.ts
  packages/common/src/store/ui/stripe-modal/slice.ts
  packages/common/src/store/ui/stripe-modal/types.ts
  packages/common/src/utils/formatUtil.ts
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx
  packages/web/.env/.env.stage
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseSellerNotification.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.module.css
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
  packages/web/src/components/stripe-on-ramp-modal/StripeOnRampModal.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/components/track/PremiumConditionsPill.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/pages/audio-rewards-page/components/ReceiveBody.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#3872 [C-2759] Make donation link external
  packages/web/src/pages/profile-page/components/SocialLink.tsx
Labels: size/XS

#3875 Add sdk:update-hotfix
  package.json
Labels: size/XS

#3874 [PAY-1701] Fix "Share to DMs" to work through InboxUnavailableModal
  packages/common/src/store/reducers.ts
  packages/common/src/store/tipping/slice.ts
  packages/common/src/store/tipping/types.ts
  packages/common/src/store/ui/create-chat-modal/index.ts
  packages/common/src/store/ui/create-chat-modal/selectors.ts
  packages/common/src/store/ui/create-chat-modal/slice.ts
  packages/common/src/store/ui/inbox-unavailable-modal/index.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/createModal.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/search-users-modal/selectors.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatPrompt.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/L

#3873 [PAY-1629] Purchase flow cleanup
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/buy-usdc/slice.ts
  packages/common/src/store/purchase-content/index.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/purchase-content/slice.ts
  packages/common/src/store/purchase-content/utils.ts
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/common/src/store/ui/stripe-modal/sagas.ts
  packages/common/src/store/ui/stripe-modal/slice.ts
  packages/common/src/store/ui/stripe-modal/types.ts
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/components/data-entry/HelperText.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.module.css
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/matrix.ts
Labels: size/L

#3881 [PAY-1592] Wire up USDC purchase flow on mobile
  packages/common/src/store/purchase-content/slice.ts
  packages/common/src/store/ui/stripe-modal/sagas.ts
  packages/common/src/store/ui/stripe-modal/selectors.ts
  packages/mobile/.env.stage
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/StripePurchaseConfirmationButton.tsx
  packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampDrawer.tsx
  packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampEmbed.tsx
  packages/mobile/src/components/stripe-onramp-drawer/index.ts
  packages/mobile/src/components/stripe-onramp-embed/index.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/utils/zIndex.ts
Labels: size/XL

#3883 [PAY-1707] Implements usage of existing balance during content purchases
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useUSDCBalance.ts
  packages/common/src/models/Status.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/FormatPrice.module.css
  packages/web/src/components/premium-content-purchase-modal/components/FormatPrice.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
Labels: size/L

#3880 Update twitter icon on mobile
  packages/mobile/src/assets/images/iconTwitterBird.svg
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationTwitterButton.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
Labels: size/M

#3884 Change nullish check to falsey check for collection track times
  packages/web/src/common/store/pages/collection/lineups/sagas.js
Labels: size/XS

#3876 Add fb share page
  packages/web/src/pages/App.js
  packages/web/src/pages/fb-share-page/FbSharePage.module.css
  packages/web/src/pages/fb-share-page/FbSharePage.tsx
Labels: size/M

#3885 [PAY-1588] Use existing balance in purchase flow on mobile
  packages/common/src/store/purchase-content/utils.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
Labels: size/L

#3879 [PAY-1700] Replace navigation if coming from ChatUserListScreen
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/store/chat/sagas.ts
Labels: size/M

#3878 [PAY-1701] Fix "Share to DMs" on mobile to go through InboxUnavailable modal
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#3877 [PAY-1702] Use existing chats as default user list when sharing to DMs
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/ui/create-chat-modal/index.ts
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Labels: size/L

#3870 [C-2685 C-2686] Implement collection upload form
  packages/web/src/components/Icon/Icon.tsx
  packages/web/src/components/form-fields/DropdownField.tsx
  packages/web/src/components/form-fields/SwitchField.tsx
  packages/web/src/components/form-fields/TextField.tsx
  packages/web/src/components/upload/UploadArtwork.d.ts
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/pages/upload-page/fields/SelectGenreField.tsx
  packages/web/src/pages/upload-page/fields/SelectMoodField.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/fields/TrackNameField.tsx
  packages/web/src/pages/upload-page/hooks.ts
  packages/web/src/pages/upload-page/pages/CollectionTrackField.tsx
  packages/web/src/pages/upload-page/pages/CollectionTrackFieldArray.tsx
  packages/web/src/pages/upload-page/pages/UploadCollectionForm.module.css
  packages/web/src/pages/upload-page/pages/UploadCollectionForm.tsx
  packages/web/src/pages/upload-page/types.ts
Labels: size/XL

#3887 [C-2957] Add h1 tag for SEO
  packages/web/scripts/workers-site/index.js
Labels: size/S

#3889 [PAY-1658] Artist pick, hidden track tile tags moved to mid-left
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTilePremiumContentTypeTag.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
Labels: size/L

#3886 [PAY-1717] Make sign in/sign up page overlap banner
  packages/web/src/components/background-animations/BackgroundWaves.js
  packages/web/src/pages/sign-on/components/desktop/SignOn.module.css
Labels: size/XS

#3824 [plat-1055] revert legacy playlist route formatting in embed player to use permalink
  packages/embed/src/components/app.jsx
  packages/embed/src/components/collection/CollectionHelmet.jsx
  packages/embed/src/components/collection/CollectionPlayerCard.jsx
Labels: size/S

#3867 Move setCollectionPermalink within fetchCollectionSucceeded action
  packages/common/src/store/pages/collection/actions.ts
  packages/common/src/store/pages/collection/reducer.ts
  packages/common/src/store/pages/collection/selectors.ts
  packages/common/src/store/pages/collection/types.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/M

#3892 Update seo h1 to be accessibly hidden vs visually hidden
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#3893 Fix playlist form from crashing after double save
  packages/web/src/components/create-playlist/PlaylistForm.tsx
Labels: size/XS

#3894 Fix OAuth login page width
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css
Labels: size/XS

#3895 Minor UI fixes for leaving audius modal
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.module.css
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.tsx
Labels: size/S

#3888 [C-2914] USDC purchase options for new upload UI (web)
  packages/common/src/models/Track.ts
  packages/common/src/models/TrackAvailabilityType.ts
  packages/web/src/components/data-entry/InputV2.module.css
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/modal-radio/ModalRadioItem.module.css
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.module.css
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
Labels: size/L

#3890 [C-2681, C-2682, C-2683] Add new upload finish page
  packages/common/src/models/Analytics.ts
  packages/common/src/store/upload/selectors.ts
  packages/common/src/store/upload/types.ts
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/components/FinishPage.module.css
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.module.css
  packages/web/src/pages/upload-page/components/ShareBannerNew.tsx
Labels: size/XL

#3896 Limit lines in Leaving Audius Modal
  packages/mobile/src/components/help-callout/HelpCallout.tsx
  packages/mobile/src/components/leaving-audius-drawer/LeavingAudiusDrawer.tsx
Labels: size/S

#3854 Fix minor bugs for multi-track upload demo
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/fields/ModalField.module.css
  packages/web/src/pages/upload-page/fields/ModalField.tsx
Labels: size/S

#3897 [PAY-1720] Implements PlainButton
  packages/stems/src/components/HarmonyButton/BaseButton.module.css
  packages/stems/src/components/HarmonyButton/BaseButton.tsx
  packages/stems/src/components/HarmonyButton/HarmonyButton.module.css
  packages/stems/src/components/HarmonyButton/HarmonyButton.stories.tsx
  packages/stems/src/components/HarmonyButton/HarmonyButton.tsx
  packages/stems/src/components/HarmonyButton/HarmonyPlainButton.module.css
  packages/stems/src/components/HarmonyButton/HarmonyPlainButton.stories.tsx
  packages/stems/src/components/HarmonyButton/HarmonyPlainButton.tsx
  packages/stems/src/components/HarmonyButton/index.ts
  packages/stems/src/components/HarmonyButton/types.ts
Labels: size/XL

#3891 [C-2684 C-2955] Improve upload component hierarchy, state, and validation
  packages/web/src/components/data-entry/InputV2.module.css
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/form-fields/ArtworkField.tsx
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
  packages/web/src/pages/upload-page/components/SelectPageNew.tsx
  packages/web/src/pages/upload-page/components/types.ts
  packages/web/src/pages/upload-page/fields/CollectionTrackField.module.css
  packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx
  packages/web/src/pages/upload-page/fields/CollectionTrackFieldArray.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.module.css
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.module.css
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/pages/EditPage.tsx
  packages/web/src/pages/upload-page/types.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XL

#3899 [C-2964] Cannonical URL should be uri encoded
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#3901 [C-2970] Add Link, Improve Text
  packages/stems/rollup.config.js
  packages/stems/src/index.ts
  packages/stems/src/styles/colors.ts
  packages/web/src/components/data-entry/HelperText.tsx
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/link/Link.module.css
  packages/web/src/components/link/Link.tsx
  packages/web/src/components/link/index.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/components/typography/Text.tsx
  packages/web/src/components/typography/typography.module.css
  packages/web/src/pages/upload-page/components/ShareBannerNew.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/TrackInfo.tsx
Labels: size/M

#3902 [C-2971] Add Avatar
  packages/web/src/components/avatar/Avatar.module.css
  packages/web/src/components/avatar/Avatar.tsx
  packages/web/src/components/avatar/index.ts
  packages/web/src/hooks/useUserProfilePicture.ts
Labels: size/L

#3903 Fix lint in useUserProfilePicture
  packages/web/src/hooks/useUserProfilePicture.ts
Labels: size/XS

#3906 [C-2961] Fix LeftNav SEO
  packages/probers/cypress/e2e/uploadTrack.cy.ts
  packages/stems/src/components/Button/Button.module.css
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/Button/types.ts
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/components/Popup/types.ts
  packages/stems/src/types.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist-recommendations/ArtistRecommendationsDropdown.tsx
  packages/web/src/components/avatar/Avatar.tsx
  packages/web/src/components/link/Link.tsx
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/LeftNav.module.css
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/NavButton.module.css
  packages/web/src/components/nav/desktop/NavButton.tsx
  packages/web/src/components/nav/desktop/NavHeader.module.css
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/typography/typography.module.css
  packages/web/src/types.ts
Labels: size/XL

#3905 [C-2969] Fix related artist images not loading
  packages/common/src/audius-query/createApi.ts
  packages/common/src/hooks/chats/useCanSendMessage.ts
  packages/common/src/store/cache/users/utils.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/reachability/sagas.ts
  packages/common/src/store/ui/search-users-modal/sagas.ts
Labels: size/S

#3907 [C-2972] Fix feed, trending track-page seo
  packages/web/src/components/link/Link.module.css
  packages/web/src/components/link/Link.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.module.css
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/components/typography/constants.ts
  packages/web/src/components/typography/types.ts
  packages/web/src/components/typography/typography.module.css
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/L

#3904 [PAY-1628] Navigate to track after purchase
  packages/common/src/store/purchase-content/sagas.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/LoadingPage.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
Labels: size/M

#3909 PAY-1724 Add color specialGreen on mobile
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/core/LockedStatusBadge.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup-tile/LineupTilePremiumContentTypeTag.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/StripePurchaseConfirmationButton.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/M

#3914 Fix stripe modal opening behavior
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
Labels: size/XS

#3913 Fix mobile share of playlist permalink
  packages/mobile/src/utils/routes.tsx
Labels: size/XS

#3917 Fix account details css
  packages/web/src/components/nav/desktop/AccountDetails.module.css
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/LeftNav.module.css
Labels: size/M

#3912 [C-2976] Fix profile-page seo
  packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/web/src/components/link/ExternalLink.tsx
  packages/web/src/components/link/SeoLink.tsx
  packages/web/src/components/link/index.ts
  packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/hooks/useTabs/useTabs.tsx
  packages/web/src/pages/profile-page/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/SocialLink.module.css
  packages/web/src/pages/profile-page/components/SocialLink.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/SocialLink.tsx
Labels: size/L

#3908 [PAY-1706] Merge modalsWithState with modals in common store
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/delete-playlist-confirmation-modal/sagas.ts
  packages/common/src/store/ui/duplicate-add-confirmation-modal/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/mobile-overflow-menu/sagas.ts
  packages/common/src/store/ui/modals/create-chat-modal/index.ts
  packages/common/src/store/ui/modals/createModal.ts
  packages/common/src/store/ui/modals/inbox-unavailable-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/leaving-audius-modal/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/selectors.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/sagas.ts
  packages/common/src/store/ui/share-modal/sagas.ts
  packages/common/src/store/ui/stripe-modal/sagas.ts
  packages/common/src/store/ui/vip-discord-modal/sagas.ts
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#3918 Improve lighthouse score
  packages/web/public/index.html
  packages/web/scripts/workers-site/index.js
Labels: size/S

#3919 Remove ontouchstart from index.html
  packages/web/public/index.html
Labels: size/XS

#3916 [PAY-1741] Add routes for transactional pages
  packages/web/src/utils/route.ts
Labels: size/S

#3920 [PAY-1742] Remove useMetaMask on invalid account
  packages/web/src/common/store/account/sagas.js
  packages/web/src/components/banner/Web3ErrorBanner.tsx
  packages/web/src/hooks/useTabs/useTabs.tsx
  packages/web/src/pages/sign-on/SignOnProvider.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
Labels: size/S

#3925 Revert "Update twitter icon on mobile (#3880)"
  packages/mobile/src/assets/images/iconTwitterBird.svg
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationTwitterButton.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
Labels: size/M

#3921 [PAY-1632] Clean up and improve performance of music confetti
  packages/web/src/assets/img/particles/particleHeartPrimary.svg
  packages/web/src/assets/img/particles/particleHeartSecondary.svg
  packages/web/src/assets/img/particles/particleListensPrimary.svg
  packages/web/src/assets/img/particles/particleListensSecondary.svg
  packages/web/src/assets/img/particles/particleNotePrimary.svg
  packages/web/src/assets/img/particles/particleNoteSecondary.svg
  packages/web/src/assets/img/particles/particlePlaylistPrimary.svg
  packages/web/src/assets/img/particles/particlePlaylistSecondary.svg
  packages/web/src/components/background-animations/MusicConfetti.tsx
  packages/web/src/components/music-confetti/ConnectedMusicConfetti.tsx
  packages/web/src/utils/animations/music-confetti.js
  packages/web/src/utils/zIndex.ts
Labels: size/L

#3923 Fix infinite scrolling cards C-2979
  packages/web/src/hooks/useTabs/TabStyles.module.css
  packages/web/src/hooks/useTabs/useTabs.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css
Labels: size/XS

#3924 Fix useAllPaginated query C-2980
  packages/common/src/audius-query/hooks/usePaginatedQuery.ts
Labels: size/M

#3928 Migrate withdraw USDC saga to web common
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/index.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/withdraw-usdc/selectors.ts
  packages/common/src/store/ui/withdraw-usdc/slice.ts
  packages/common/src/store/withdraw-usdc/index.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#3929 [C-2982] Fix seo based on ahref recommendations
  packages/web/scripts/workers-site/index.js
  packages/web/src/components/page/Page.js
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/utils/seo.ts
Labels: size/M

#3864 Add library albums and playlists audius-query hook + migrate collection reformat util; bump SDK PAY-1679
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/api/index.ts
  packages/common/src/api/library.ts
  packages/common/src/api/reducer.ts
  packages/common/src/audius-query/createApi.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/store/cache/collections/utils/index.ts
  packages/common/src/store/cache/collections/utils/reformatCollection.ts
  packages/common/src/store/cache/index.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/utils/index.ts
  packages/web/src/common/store/cache/collections/utils/processAndCacheCollections.ts
  packages/web/src/common/store/cache/collections/utils/reformat.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/upload/sagas.js
Labels: size/L

#3935 [C-2966] Make sure that collection description limits are set to 1000
  packages/mobile/src/screens/edit-playlist-screen/PlaylistDescriptionField.tsx
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
Labels: size/XS

#3934 [C-2689] Add upload confirmation modal
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/upload-confirmation-modal/sagas.ts
  packages/common/src/store/ui/upload-confirmation-modal/selectors.ts
  packages/common/src/store/ui/upload-confirmation-modal/slice.ts
  packages/common/src/store/ui/upload-confirmation-modal/types.ts
  packages/web/src/components/upload-confirmation-modal/UploadConfirmationModal.module.css
  packages/web/src/components/upload-confirmation-modal/UploadConfirmationModal.tsx
  packages/web/src/components/upload-confirmation-modal/index.ts
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#3938 Fix canonical url consistency
  packages/web/scripts/workers-site/index.js
  packages/web/src/components/mobile-page-container/MobilePageContainer.tsx
Labels: size/XS

#3937 [C-2968] Fix private collection action buttons
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
  packages/web/src/components/collection/desktop/ViewerActionButtons.tsx
Labels: size/S

#3911 Update README.md
  packages/embed/README.md
Labels: size/XS

#3936 [C-2977] Fix collection page seo
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.js
  packages/web/src/components/collection/mobile/CollectionHeader.module.css
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/link/Link.tsx
  packages/web/src/components/link/SeoLink.module.css
  packages/web/src/components/link/SeoLink.tsx
  packages/web/src/components/link/UserLink.module.css
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/link/index.ts
  packages/web/src/components/nav/desktop/AccountDetails.module.css
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/InfoLabel.js
  packages/web/src/components/track/InfoLabel.tsx
  packages/web/src/components/track/mobile/TrackList.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/tracks-table/TracksTable.module.css
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/components/typography/Text.tsx
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/ActionButtonRow.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/XL

#3939 Update pull_request_template.md
  .github/pull_request_template.md
Labels: size/S

#3942 [C-2987] Add UserGeneratedText
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.js
  packages/web/src/components/collection/mobile/CollectionHeader.module.css
  packages/web/src/components/link/ExternalLink.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/typography/Text.tsx
  packages/web/src/components/typography/typography.module.css
  packages/web/src/components/user-generated-text/UserGeneratedText.module.css
  packages/web/src/components/user-generated-text/UserGeneratedText.tsx
  packages/web/src/components/user-generated-text/index.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/profile-page/components/SocialLink.module.css
  packages/web/src/pages/profile-page/components/SocialLink.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/SocialLink.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XL

#3943 Use does_current_user_subscribe API field
  packages/common/src/models/User.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/social/users/sagas.ts
Labels: size/M

#3941 [C-2986] Upload flow qa round 1
  packages/mobile/src/assets/images/iconValidationCheck.svg
  packages/stems/src/assets/icons/iconValidationCheck.svg
  packages/web/src/assets/img/iconValidationCheck.svg
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/data-entry/InputV2.module.css
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/modal-radio/ModalRadioItem.module.css
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.module.css
  packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.module.css
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.tsx
  packages/web/src/pages/upload-page/fields/availability/SpecialAccessFields.module.css
  packages/web/src/pages/upload-page/fields/availability/SpecialAccessFields.tsx
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
Labels: size/L

#3900 [C-2956] Add new Access & Sale modal to legacy upload form
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/upload/sagaHelpers.ts
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/components/data-entry/AccessAndSaleModalLegacy.module.css
  packages/web/src/components/data-entry/AccessAndSaleModalLegacy.tsx
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track-availability-modal/types.ts
  packages/web/src/pages/upload-page/components/EditPage.js
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/types.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XL

#3932 [PAY-1727] USDC Withdrawals saga pt. 1
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/solana.ts
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/services/audius-libs.ts
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#3940 Add embed cloudflare deployment and CI
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/commands/@commands.yml
  .circleci/src/commands/@embed-commands.yml
  .circleci/src/jobs/@embed-jobs.yml
  .circleci/src/workflows/embed.yml
  packages/embed/.eslintignore
  packages/embed/.gitignore
  packages/embed/README.md
  packages/embed/package.json
  packages/embed/workers-site/index.js
  packages/embed/workers-site/package-lock.json
  packages/embed/workers-site/package.json
  packages/embed/workers-site/worker/script.js
  packages/embed/wrangler.toml
  packages/web/scripts/workers-site/index.js
  packages/web/wrangler.toml
Labels: size/L

#3945 quick linting fix
  packages/web/src/pages/upload-page/UploadPageNew.tsx
Labels: size/XS

#3946 [PAY-1748][PAY-1731][PAY-1729][PAY-1730] DMs link fixes
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/web/src/components/link/ExternalLink.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/LinkPreview.module.css
Labels: size/M

#3948 [PAY-1733] Remove Gated Prompt Modal
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/gated-content-upload-prompt-modal/GatedContentUploadPromptModal.module.css
  packages/web/src/components/gated-content-upload-prompt-modal/GatedContentUploadPromptModal.tsx
Labels: size/L

#3949 Fix Share to IG/T/S sticker consistency [C-3009]
  packages/mobile/src/components/action-drawer/ActionDrawer.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/L

#3950 [C-3002] Fix casing of selected values in upload flow
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
Labels: size/S

#3953 [C-3001, C-3003] Fix new upload flow error formatting
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/AttributionField.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.module.css
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/validation.ts
Labels: size/M

#3954 [C-2997] Disable delete on the last collection upload track
  packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx
  packages/web/src/pages/upload-page/fields/CollectionTrackFieldArray.tsx
Labels: size/S

#3955 [C-3015] Add back button to new upload flow edit page
  packages/web/src/pages/upload-page/UploadPageNew.tsx
Labels: size/S

#3956 [C-2791] Use artwork from the file if there is one
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/XS

#3959 [C-3018][C-2965] fix upload album/playlist description field styling
  packages/stems/src/components/HarmonyButton/HarmonyButton.tsx
  packages/stems/src/components/HarmonyButton/types.ts
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/upload/TrackPreviewNew.tsx
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
  packages/web/src/pages/upload-page/fields/CollectionTrackField.module.css
  packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.module.css
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/M

#3958 [C-3012] Fix remixes deep link
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
Labels: size/M

#3960 [C-3023] Fix collectible visibility
  packages/common/src/store/cache/reducer.ts
Labels: size/S

#3961 [C-3025] Fix race-condition with stem/remix fetch
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
Labels: size/M

#3951 [PAY-1712] Implement purchases page
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/api/user.ts
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/hooks/usePaginatedQuery.ts
  packages/common/src/models/USDCTransactions.ts
  packages/common/src/models/index.ts
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/Icon/Icon.module.css
  packages/web/src/components/Icon/Icon.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/purchases-page/PurchasesPage.module.css
  packages/web/src/pages/purchases-page/PurchasesPage.tsx
  packages/web/src/pages/purchases-page/PurchasesTable.module.css
  packages/web/src/pages/purchases-page/PurchasesTable.tsx
  packages/web/src/pages/purchases-page/index.ts
Labels: size/XL

#3957 [PAY-1715] Adds Sales page
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/api/index.ts
  packages/common/src/api/purchases.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/track.ts
  packages/common/src/api/user.ts
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/audius-query/README.md
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/app.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/purchases-and-sales/PurchasesPage.module.css
  packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx
  packages/web/src/pages/purchases-and-sales/PurchasesTable.tsx
  packages/web/src/pages/purchases-and-sales/SalesPage.module.css
  packages/web/src/pages/purchases-and-sales/SalesPage.tsx
  packages/web/src/pages/purchases-and-sales/SalesTable.tsx
  packages/web/src/pages/purchases-and-sales/components/NoPurchasesContent.module.css
  packages/web/src/pages/purchases-and-sales/components/NoPurchasesContent.tsx
  packages/web/src/pages/purchases-and-sales/components/TrackNameWithArtwork.module.css
  packages/web/src/pages/purchases-and-sales/components/TrackNameWithArtwork.tsx
  packages/web/src/pages/purchases-and-sales/components/UserNameWithBadges.module.css
  packages/web/src/pages/purchases-and-sales/components/UserNameWithBadges.tsx
  packages/web/src/pages/purchases-and-sales/index.ts
  packages/web/src/pages/purchases-and-sales/types.ts
  packages/web/src/pages/purchases-and-sales/utils.ts
  packages/web/src/pages/purchases-page/PurchasesTable.module.css
Labels: size/XXL

#3963 [PAY-1506] USDC artist dashboard tile
  packages/common/src/utils/formatUtil.ts
  packages/stems/src/assets/icons/iconQuestionCircle.svg
  packages/stems/src/assets/styles/fonts.css
  packages/stems/src/components/Icons/index.ts
  packages/stems/src/styles/colors.ts
  packages/web/src/components/typography/types.ts
  packages/web/src/components/typography/typography.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Labels: size/L

#3927 [INF-445] Upgrade client to node 18, npm 9, and npm workspaces
  .circleci/config.yml
  .circleci/src/commands/@commands.yml
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@probers-jobs.yml
  .circleci/src/jobs/@root-jobs.yml
  .circleci/src/jobs/@stems-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  .gitignore
  .npmrc
  .nvmrc
  README.md
  lerna.json
  package-lock.json
  package.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/models/ErrorReporting.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/tsconfig.json
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/eslint-config-audius/package-lock.json
  packages/mobile/README.md
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/android/settings.gradle
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/scripts/bundleReactNative.sh
  packages/mobile/ios/scripts/uploadSentryDebugSymbols.sh
  packages/mobile/metro.config.js
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/patches/@noble+secp256k1+1.7.0.patch
  packages/mobile/patches/micro-aes-gcm+0.3.3.patch
  packages/mobile/src/utils/reportToSentry.ts
  packages/mobile/tsconfig.json
  packages/probers/.circleci/config.yml
  packages/probers/package-lock.json
  packages/probers/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/rollup.config.js
  packages/stems/scripts/workers-site/package.json
  packages/stems/src/components/Scrollbar/Scrollbar.tsx
  packages/web/craco.config.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/scripts/publishScripts.sh
  packages/web/scripts/workers-site/package.json
  packages/web/src/index.tsx
  packages/web/src/services/audius-sdk/auth.ts
  packages/web/src/store/configureStore.ts
  packages/web/src/store/errors/reportToSentry.ts
  packages/web/src/types/process/index.d.ts
  scripts/postinstall.sh
Labels: size/XL, size/XXXXL

#3964 [C-3020] Fix errors in usdc purchase field
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
Labels: size/XS

#3965 [C-2999] Verify calendar input styles and update text when finalizing upload
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.module.css
Labels: size/S

#3966 [C-3026] Close now-playing when sharing to dm
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/S

#3967 Fix jupiter Buffer is not defined
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/services/solana/WithdrawUSDC.ts
Labels: size/S

#3969 Fix embed ci with workspaces
  .circleci/src/jobs/@embed-jobs.yml
Labels: size/S

#3970 [PAY-1768] Convert artist dashboard to functional component
  packages/web/src/pages/App.js
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/artist-dashboard-page/components/ArtistProfile.js
  packages/web/src/pages/artist-dashboard-page/components/ArtistProfile.module.css
  packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.module.css
  packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.tsx
  packages/web/src/pages/artist-dashboard-page/components/USDCTile.module.css
  packages/web/src/pages/artist-dashboard-page/components/USDCTile.tsx
Labels: size/XXL

#3972 Improve sentry-cli usage in CI
  packages/mobile/ios/scripts/bundleReactNative.sh
  packages/mobile/ios/scripts/uploadSentryDebugSymbols.sh
Labels: size/XS

#3976 Fix text color for DMs
  packages/stems/src/styles/colors.ts
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/S

#3968 [PAY-1590] Hook up content previews for USDC content
  packages/common/src/models/Analytics.ts
  packages/common/src/models/Track.ts
  packages/common/src/store/lineup/actions.ts
  packages/common/src/store/player/selectors.ts
  packages/common/src/store/player/slice.ts
  packages/common/src/store/queue/slice.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/L

#3978 Fix TextField input spacing
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/fields/TextField.tsx
Labels: size/S

#3971 [PAY-1761] Display USDC balance on artist dashboard
  packages/common/src/store/ui/buy-audio/constants.ts
  packages/common/src/utils/formatUtil.ts
  packages/common/src/utils/wallet.ts
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/artist-dashboard-page/components/USDCTile.tsx
Labels: size/M

#3979 Fix maxLength warning in search bar
  packages/web/src/components/search/SearchBar.js
Labels: size/S

#3981 Fix validation on access and sale modal
  packages/common/src/models/Track.ts
  packages/common/src/utils/dogEarUtils.ts
  packages/web/src/components/data-entry/AccessAndSaleModalLegacy.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Labels: size/L

#3983 Revert premium_conditions empty object change
  packages/common/src/models/Track.ts
  packages/web/src/components/data-entry/AccessAndSaleModalLegacy.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Labels: size/XS

#3974 Add HarmonySelectablePill for mobile + Library filter pill menu
  packages/mobile/src/components/core/HarmonySelectablePill.tsx
Labels: size/L

#3980 [PAY-1755] Withdraw USDC flow: send signature to relay
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#3982 [PAY-1786] Withdraw USDC - create dest token account
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#3985 Update files to account for changes on node 18
  packages/mobile/.gitignore
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
Labels: size/M

#3984 [PAY-1736] Implement new ArtistCard on dashboard
  packages/web/src/hooks/useUserCoverPhoto.ts
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/artist-dashboard-page/components/ArtistCard.module.css
  packages/web/src/pages/artist-dashboard-page/components/ArtistCard.tsx
  packages/web/src/pages/artist-dashboard-page/components/ArtistProfile.js
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.module.css
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
Labels: size/L

#3988 [C-3022] Fix broken multi-track index after deleting
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
Labels: size/S

#3987 [C-3029] Fix embed environment url
  packages/web/wrangler.toml
Labels: size/S

#3990 [C-2995] Add hint to modal radio items
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Labels: size/S

#3986 [PAY-1591][PAY-1775] Implements content previews on native mobile
  packages/common/src/store/player/slice.ts
  packages/common/src/store/queue/types.ts
  packages/common/src/utils/streaming.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/now-playing-drawer/useCurrentTrackDuration.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/player/sagas.ts
Labels: size/L

#3993 [PAY-1776] Fix playing check for track page
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/XS

#3991 [C-3028] make the usdc inputs white
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.module.css
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
Labels: size/S

#3995 Fix misc embed deploy issues
  packages/embed/workers-site/index.js
  packages/embed/workers-site/worker/script.js
  packages/embed/wrangler.toml
Labels: size/S

#3996 Fix AI learn more link
  packages/mobile/src/screens/ai-generated-tracks-screen/ShareAiTracksTile.tsx
  packages/web/src/utils/route.ts
Labels: size/XS

#3992 [C-2915] Implement Mobile USDC field
  packages/mobile/src/components/core/ErrorText.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/fields/PickArtworkField.tsx
  packages/mobile/src/components/fields/TextField.tsx
  packages/mobile/src/hooks/useSetTrackAvailabilityFields.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/index.ts
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/AccessAndSaleField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/BoxedTextField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/PremiumRadioField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPreviewField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPriceField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PublicAvailabilityRadioField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/index.ts
  packages/mobile/src/screens/edit-track-screen/fields/index.ts
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedOptionsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackVisibilityScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/index.ts
  packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts
Labels: size/L

#3997 Fix CI (partially)
  .circleci/src/@continue_config.yml
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@stems-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  package-lock.json
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/Podfile.lock
  packages/stems/package.json
  packages/web/package.json
  scripts/postinstall.sh
Labels: size/M

#3975 Add category to library query endpoint + more useAllPaginated fixes
  packages/common/src/api/library.ts
  packages/common/src/audius-query/hooks/usePaginatedQuery.ts
Labels: size/M
