Repository AudiusProject/audius-client, pull requests merged in 2023-01, with the labels that each got.

#2494 Add missing RN update changes (0.61 -> 0.67.5)
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.java
  packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.java
  packages/mobile/android/app/src/main/java/co/audius/app/ReactNativeFlipper.java
  packages/mobile/android/app/src/main/java/co/foo/CastOptionsProvider.java
  packages/mobile/android/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/android/gradlew
  packages/mobile/android/gradlew.bat
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative.xcodeproj/xcshareddata/xcschemes/AudiusReactNative.xcscheme
  packages/mobile/ios/AudiusReactNative.xcodeproj/xcshareddata/xcschemes/Dev.xcscheme
  packages/mobile/ios/AudiusReactNative.xcodeproj/xcshareddata/xcschemes/Staging.xcscheme
  packages/mobile/ios/AudiusReactNative/AppDelegate.h
  packages/mobile/ios/AudiusReactNative/AppDelegate.m
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/AudiusReactNative/main.m
  packages/mobile/ios/AudiusReactNativeTests/AudiusReactNativeTests.m
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: size/XL

#2493 [C-1732] Add mobile end of feed notice
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/components/suggested-follows/SuggestedArtistsList.tsx
  packages/mobile/src/screens/feed-screen/EmptyFeedSuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/EndOfFeedNotice.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
Labels: size/L

#2495 [C-1738] Upgrade react-native to 0.68.5
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/proguard-rules.pro
  packages/mobile/android/app/src/main/java/co/audius/app/ReactNativeFlipper.java
  packages/mobile/android/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/android/gradlew
  packages/mobile/android/settings.gradle
  packages/mobile/babel.config.js
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/AppDelegate.h
  packages/mobile/ios/AudiusReactNative/AppDelegate.m
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/patches/react-native+0.66.3.patch
  packages/mobile/patches/react-native+0.68.5.patch
  packages/mobile/src/notifications.ts
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/services/createPrivateKey.ts
Labels: size/XXL

#2496 Enable hermes and flipper by default for ios
  .circleci/src/commands/@mobile-commands.yml
  packages/mobile/README.md
  packages/mobile/disableHermesiOS.js
  packages/mobile/enableHermesiOS.js
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/patches/react-native+0.68.5.patch
Labels: size/L

#2498 [C-1741] Upgrade react-native to 0.69.7
  packages/mobile/android/app/build.gradle
  packages/mobile/android/build.gradle
  packages/mobile/android/settings.gradle
  packages/mobile/ios/.xcode.env
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/patches/@audius+sdk+1.0.27.patch
  packages/mobile/patches/react-native+0.69.7.patch
Labels: size/XL

#2501 [QA-269] Update counter effect logic to only reset track position when the track index is the same
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/S

#2504 Update SettingsScreen copy
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
Labels: size/XS

#2503 Move offline mode feature backdoor to about page
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
Labels: size/M

#2500 [C-1530] Improve collectibles details drawer
  packages/mobile/src/components/audio-breakdown-drawer/Wallet.tsx
  packages/mobile/src/components/collectible-details-drawer/CollectibleDate.tsx
  packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
  packages/mobile/src/components/collectible-details-drawer/CollectibleLink.tsx
  packages/mobile/src/components/collectible-details-drawer/CollectibleMedia.tsx
  packages/mobile/src/components/core/ChainLogo.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/video/AutoSizeVideo.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallet.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/utils/routes.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/L

#2505 Add alert logs to offline downloader
  packages/mobile/src/hooks/useIsOfflineModeEnabled.ts
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
Labels: size/M

#2506 [C-1751] Fix staging signup
  packages/common/src/services/location.ts
Labels: size/XS

#2507 Remove radial gradient
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/S

#2508 Replace radial gradient
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/S

#2502 [C-17496 Upgrade react-native to 0.70.6 (latest)
  packages/mobile/.gitignore
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.java
  packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.java
  packages/mobile/android/app/src/main/java/co/audius/app/newarchitecture/MainApplicationReactNativeHost.java
  packages/mobile/android/app/src/main/java/co/audius/app/newarchitecture/components/MainComponentsRegistry.java
  packages/mobile/android/app/src/main/java/co/audius/app/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  packages/mobile/android/app/src/main/jni/CMakeLists.txt
  packages/mobile/android/app/src/main/jni/MainApplicationModuleProvider.cpp
  packages/mobile/android/app/src/main/jni/MainApplicationModuleProvider.h
  packages/mobile/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  packages/mobile/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  packages/mobile/android/app/src/main/jni/MainComponentsRegistry.cpp
  packages/mobile/android/app/src/main/jni/MainComponentsRegistry.h
  packages/mobile/android/app/src/main/jni/OnLoad.cpp
  packages/mobile/android/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/android/gradle/wrapper/gradle-wrapper.properties
  packages/mobile/android/settings.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/patches/react-native+0.70.6.patch
  packages/mobile/react-native.config.js
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
Labels: size/XXL

#2509 use allSettled util instead of Promise.allSettled
  packages/common/src/utils/allSettled.ts
  packages/common/src/utils/index.ts
  packages/mobile/.eslintrc.js
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/utils/populateCoverArtSizes.ts
Labels: size/S

#2499 Enable redux-flipper
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/react-native.config.js
  packages/mobile/src/store/store.ts
Labels: size/M

#2511 [C-1537] Fix positioning of duration on track list items of deleted tracks
  packages/web/src/components/track/desktop/TrackListItem.tsx
Labels: size/S

#2512 [C-1713] Remove UserBadges from desktop card component
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
Labels: size/S

#2482 Share to Snapchat
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/res/xml/file_paths.xml
  packages/mobile/android/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/assets/images/iconSnapchat.svg
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/store/share-to-story-progress/selectors.ts
  packages/mobile/src/store/share-to-story-progress/slice.ts
  packages/mobile/src/types/analytics.ts
Labels: size/XL

#2513 Fix the base58 error on solana nft collection key
  packages/web/src/common/store/premiumContent/sagas.ts
Labels: size/XS

#2514 Update session count hook to respect the startAt prop
  packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
  packages/mobile/src/components/rate-cta-drawer/RateCtaReminder.tsx
  packages/mobile/src/hooks/useSessionCount.ts
Labels: size/S

#2516 Use https on gain.audius.co
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/src/services/analytics.ts
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
Labels: size/S

#2515 Update mobile react 18 types/usages and various packages
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/ErrorBoundary.tsx
  packages/mobile/src/components/copy-text-tile/CopyTextTile.tsx
  packages/mobile/src/components/core/Shadow.tsx
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/screens/audio-screen/Tier.tsx
  packages/mobile/src/screens/explore-screen/collections.ts
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/notifications-screen/NotificationErrorBoundary.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/signon/ProfileImage.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
  packages/mobile/types/react-native-markdown-display.d.ts
  packages/web/package-lock.json
Labels: size/L

#2519 Set snapchat key based on environment
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/S

#2520 [PAY-804] Update AAO error mappings
  packages/common/src/utils/aaoErrorCodes.ts
Labels: size/XS

#2518 Fix local iOS dev/install
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: size/L

#2522 [C-1742] Fix user images
  packages/mobile/src/hooks/useContentNodeImage.ts
Labels: size/M

#2525 Fix amplitude api prefix
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/services/analytics/amplitude.ts
Labels: size/XS

#2524 Fix staging flipper
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/L

#2528 Change where we record user response so that the rate CTA drawer feels more responsive
  packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
Labels: size/XS

#2529 [C-1768] Fix android build w/ snapchat
  packages/mobile/android/build.gradle
Labels: size/XS

#2530 Add react-native-clean-project
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/XS

#2532 Update button variants for rate cta drawer
  packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
Labels: size/XS

#2533 Fix trending button width
  packages/mobile/src/components/core/Screen/ScreenHeaderButton.tsx
Labels: size/XS

#2535 [C-1762] Center snapchat sticker
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/XS

#2536 Fix rate-cta-drawer rerenders
  packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
  packages/mobile/src/components/rate-cta-drawer/RateCtaReminder.tsx
  packages/mobile/src/hooks/useAsyncStorage.ts
Labels: size/M

#2538 Pass blacklist into sanity check and bump libs/sdk to v1.0.32
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#2534 [C-1771] Add various flipper plugins, install instructions
  packages/mobile/README.md
  packages/mobile/index.js
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
Labels: size/M

#2537 [C-1761] Add bottom-bar rive animations
  packages/mobile/android/app/src/main/res/raw/explore.riv
  packages/mobile/android/app/src/main/res/raw/favorites.riv
  packages/mobile/android/app/src/main/res/raw/feed.riv
  packages/mobile/android/app/src/main/res/raw/notifications.riv
  packages/mobile/android/app/src/main/res/raw/trending.riv
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/assets/animations/iconExploreDark.json
  packages/mobile/src/assets/animations/iconExploreLight.json
  packages/mobile/src/assets/animations/iconFavoriteDark.json
  packages/mobile/src/assets/animations/iconFavoriteLight.json
  packages/mobile/src/assets/animations/iconFeedDark.json
  packages/mobile/src/assets/animations/iconFeedLight.json
  packages/mobile/src/assets/animations/iconNotifications.json
  packages/mobile/src/assets/animations/iconProfileDark.json
  packages/mobile/src/assets/animations/iconProfileLight.json
  packages/mobile/src/assets/animations/iconTrendingDark.json
  packages/mobile/src/assets/animations/iconTrendingLight.json
  packages/mobile/src/assets/rive/explore.riv
  packages/mobile/src/assets/rive/favorites.riv
  packages/mobile/src/assets/rive/feed.riv
  packages/mobile/src/assets/rive/notifications.riv
  packages/mobile/src/assets/rive/trending.riv
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/BottomTabBarButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/ExploreButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/FavoritesButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/FeedButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/NotificationsButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/ProfileButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/TrendingButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/index.ts
  packages/mobile/src/components/bottom-tab-bar/index.ts
Labels: size/L

#2539 Bump sdk to 1.0.33
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#2540 Update sdk to v1.0.34
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#2542 Update SDK in Web to v1.0.35
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#2469 [PAY-776] Add premium content to track upload flow on desktop - Part 1
  packages/common/src/models/Collectible.ts
  packages/common/src/models/OpenSea.ts
  packages/common/src/models/Track.ts
  packages/common/src/services/opensea-client/ethCollectibleHelpers.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/collectibles/actions.ts
  packages/common/src/store/collectibles/index.ts
  packages/common/src/store/collectibles/reducer.ts
  packages/common/src/store/index.ts
  packages/common/src/store/premium-content/actions.ts
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/assets/icons/iconCollectible.svg
  packages/stems/src/assets/icons/iconSpecialAccess.svg
  packages/stems/src/assets/icons/iconVisibilityPublic.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/data-entry/FormTile.module.css
  packages/web/src/components/switch/Switch.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
Labels: size/XL

#2544 [C-1703] fix button padding for remove download playlist
  packages/mobile/src/components/core/Button.tsx
Labels: size/XS

#2543 [C-1756][C-1767] Fix job cancellation for track download queue
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
Labels: size/M

#2545 [C-1766][C-1781] Fix loading states on DownloadToggle
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
Labels: size/M

#2541 [C-1779] Improve makeStyles performance
  packages/mobile/android/app/src/debug/java/co/audius/app/ReactNativeFlipper.java
  packages/mobile/android/gradle.properties
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/core/Divider.tsx
  packages/mobile/src/components/core/IconButton.tsx
  packages/mobile/src/components/core/PullToRefresh.tsx
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/components/core/Shadow.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileTierTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialsAndSites.tsx
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/Sites.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/styles/makeStyles.ts
  packages/mobile/src/styles/typography.ts
  packages/mobile/src/utils/theme.ts
Labels: size/XXL

#2550 [C-1788][C-1784][C-1785] Fix offline queue loops and duplicates
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/S

#2523 [C-1418] Add new android bundles
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/workflows/mobile.yml
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/bounce/google-services.json
  packages/mobile/android/app/src/bounce/res/values/strings.xml
  packages/mobile/android/app/src/main/ic_launcher_staging-playstore.png
  packages/mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_bounce.xml
  packages/mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_bounce_round.xml
  packages/mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_staging.xml
  packages/mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_staging_round.xml
  packages/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_bounce.png
  packages/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_staging.png
  packages/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_staging_foreground.png
  packages/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_staging_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_staging_round.png
  packages/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_bounce.png
  packages/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_staging.png
  packages/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_staging_foreground.png
  packages/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_staging_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_staging_round.png
  packages/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_bounce.png
  packages/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_staging.png
  packages/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_staging_foreground.png
  packages/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_staging_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_staging_round.png
  packages/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_bounce.png
  packages/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_staging.png
  packages/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_staging_foreground.png
  packages/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_staging_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_staging_round.png
  packages/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_bounce.png
  packages/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_staging.png
  packages/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_staging_foreground.png
  packages/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_staging_releasecandidate.png
  packages/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_staging_round.png
  packages/mobile/android/app/src/main/res/values/ic_launcher_bounce_background.xml
  packages/mobile/android/app/src/main/res/values/ic_launcher_staging_background.xml
  packages/mobile/android/app/src/releaseCandidate/google-services.json
  packages/mobile/android/app/src/releaseCandidate/res/values/strings.xml
  packages/mobile/android/app/src/staging/google-services.json
  packages/mobile/android/app/src/staging/res/values/strings.xml
  packages/mobile/android/app/src/stagingReleaseCandidate/google-services.json
  packages/mobile/android/fastlane/Fastfile
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: size/L

#2551 [C-1789] Fix lottie colorize crash
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/PullToRefresh.tsx
  packages/mobile/src/components/core/SectionList.tsx
Labels: size/S

#2526 [PAY-808] [PAY-810] Float new playlists to top of library
  packages/common/src/store/pages/profile/reducer.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
Labels: size/S

#2547 [PAY-367] [C-1786 C-1661] Refactor FeedTipTile/Lineup interdependency
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/mobile/src/components/feed-tip-tile/index.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
Labels: size/L

#2531 Add back arm64 exclusion
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Podfile.lock
Labels: size/XS

#2557 Update the feature flag for rate cta drawer
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#2559 [QA-282] Fix app crash on edit playlist screen when missing collection image source
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
Labels: size/XS

#2558 Bump ios to 1.1.51
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2561 [C-1397] Add appVersion to optimizely audience attributes
  packages/common/src/services/remote-config/remote-config.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/remote-config/remote-config-instance.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/remote-config/remote-config-instance.ts
Labels: size/S

#2552 [C-1790] Improve lottie colorize perf
  packages/mobile/src/components/core/PullToRefresh.tsx
  packages/mobile/src/components/favorite-button/FavoriteButton.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
  packages/mobile/src/components/now-playing-drawer/RepeatButton.tsx
  packages/mobile/src/components/now-playing-drawer/RepostButton.tsx
  packages/mobile/src/components/now-playing-drawer/ShuffleButton.tsx
  packages/mobile/src/components/repost-button/RepostButton.tsx
  packages/mobile/src/styles/index.ts
  packages/mobile/src/styles/makeAnimations.ts
Labels: size/XL

#2560 [C-1764] Fix offline app initialization for offline mode
  packages/common/src/store/reachability/reducer.ts
  packages/common/src/store/reachability/types.ts
  packages/mobile/src/store/store.ts
  packages/web/src/common/store/backend/reducer.ts
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/store/reachability/sagas.ts
  packages/web/src/utils/sagaHelpers.ts
Labels: size/L

#2554 [C-1791] Add fast-cache, safe-fast-cache
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/cache/actions.ts
  packages/common/src/store/cache/reducer.ts
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/common/store/cache/store.test.js
Labels: size/L

#2548 [C-1760] Fix lineup-tile animation lag
  packages/mobile/src/components/core/FadeInView.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
Labels: size/L

#2549 Remove EntityManager gating for users and tracks
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/M

#2567 Fix setup states
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/common/store/backend/reducer.ts
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/backend/selectors.ts
  packages/web/src/common/store/backend/types.ts
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/components/reachability-bar/components/ReachabilityBarContainer.tsx
  packages/web/src/store/sagas.ts
Labels: size/M

#2570 [C-1706] Fix sidebar track statistic
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/VanityMetrics.tsx
Labels: size/XS

#2572 [C-1814] Prevent infinite rerender of UserList
  packages/mobile/src/screens/user-list-screen/UserList.tsx
Labels: size/XS

#2573 [C-1815] Fix legacy image loading
  packages/common/src/utils/array.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/components/core/DynamicImage.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
Labels: size/S

#2564 [C-1726] useLocalImage
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/hooks/useLocalImage.ts
Labels: size/L

#2563 DMs UI Part 1
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/web/src/assets/styles/index.css
  packages/web/src/assets/styles/shadows.css
  packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatList.module.css
  packages/web/src/pages/chat-page/components/ChatList.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.module.css
  packages/web/src/pages/chat-page/components/ChatListItem.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.module.css
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/ReactionPopupMenu.module.css
  packages/web/src/pages/chat-page/components/ReactionPopupMenu.tsx
  packages/web/src/utils/route.ts
Labels: size/XL

#2575 Hotfix: Fix mobile build after selector was changed
  packages/mobile/src/screens/chats-screen/ChatsScreen.tsx
Labels: size/XS

#2574 [C-1816] Fix divider color
  packages/mobile/src/components/core/Divider.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
Labels: size/XS

#2577 Bump ios to 1.1.52
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2578 [C-1819] Fix customCheck in waitForValue
  packages/common/src/utils/sagaHelpers.ts
Labels: size/XS

#2556 Entity manager notification writes
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
Labels: size/M

#2581 Add null check for notification navigation hook
  packages/mobile/src/hooks/useNotificationNavigation.ts
Labels: size/XS

#2582 [C-1821] Fix android manual sign up overflow
  packages/mobile/src/components/core/Screen/SafeAreaScreen.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
Labels: size/XS

#2546 [PAY-817] Add premium content to track upload flow on desktop - Part 2
  packages/common/src/models/Collectible.ts
  packages/common/src/models/OpenSea.ts
  packages/common/src/models/Track.ts
  packages/common/src/services/opensea-client/ethCollectibleHelpers.ts
  packages/common/src/services/solana-client/SolanaClient.ts
  packages/common/src/store/collectibles/actions.ts
  packages/common/src/store/collectibles/index.ts
  packages/common/src/store/collectibles/reducer.ts
  packages/common/src/store/collectibles/selectors.ts
  packages/common/src/store/collectibles/slice.ts
  packages/common/src/store/reducers.ts
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/data-entry/DropdownInput.js
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
  packages/web/src/components/track-availability-modal/HiddenAvailability.tsx
  packages/web/src/components/track-availability-modal/PublicAvailability.tsx
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track-availability-modal/types.ts
  packages/web/src/pages/upload-page/UploadPage.js
Labels: size/XXL

#2583 Fix notification userInteraction
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/notifications.ts
Labels: size/S

#2585 Make rc-staging fast-app variant
  .circleci/src/workflows/mobile.yml
Labels: size/XS

#2580 [C-1643] Update track player to work with the queue in the redux store
  packages/common/src/store/queue/slice.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Labels: size/L

#2565 [PAY-778] Update track page for premium tracks
  packages/common/src/models/Analytics.ts
  packages/common/src/models/Track.ts
  packages/stems/src/assets/icons/iconLockedCornerTag.svg
  packages/stems/src/assets/icons/iconUnlocked.svg
  packages/stems/src/assets/icons/iconUnlockedCornerTag.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/PremiumTrackCornerTag.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/utils.ts
Labels: size/XL

#2590 Move stream mp3 feature flag check later so optimizely is ready
  packages/web/src/common/store/player/sagas.ts
Labels: size/S

#2569 update playlist_page route to accept permalink optionally
  packages/web/src/utils/route.ts
Labels: size/M

#2591 [C-1778] Fix update banner styles
  packages/web/src/components/banner/UpdateAppBanner.module.css
Labels: size/XS

#2592 [C-1829] Fix android build due to gradle dep
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/XS

#2593 [DMs] Mark chats as read if the user hits the bottom of the scrollbar
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.tsx
Labels: size/M

#2588 [DMs] Add new message dialog and prompts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/user-list/index.ts
  packages/common/src/store/user-list/search/actions.ts
  packages/common/src/store/user-list/search/reducers.ts
  packages/common/src/store/user-list/search/selectors.ts
  packages/common/src/store/user-list/search/types.ts
  packages/web/src/common/store/user-list/search/sagas.ts
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/components/UserList.tsx
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatList.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.module.css
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatPrompt.module.css
  packages/web/src/pages/chat-page/components/CreateChatPrompt.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/application/ui/chat/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/XL

#2594 [C-1772] Fix share-drawer for tracks with missing images
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/XS

#2586 [DMs] Add styles to DMs composer, scrolling fixes
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/user-list/index.ts
  packages/common/src/store/user-list/search/actions.ts
  packages/common/src/store/user-list/search/reducers.ts
  packages/common/src/store/user-list/search/selectors.ts
  packages/common/src/store/user-list/search/types.ts
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/user-list/search/sagas.ts
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/components/UserList.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/App.module.css
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.module.css
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/ChatList.module.css
  packages/web/src/pages/chat-page/components/ChatList.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/CreateChatModal.module.css
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatPrompt.module.css
  packages/web/src/pages/chat-page/components/CreateChatPrompt.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/application/ui/chat/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#2576 DMs Styling Part 2 - Layout and Header
  package-lock.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/user-list/index.ts
  packages/common/src/store/user-list/search/actions.ts
  packages/common/src/store/user-list/search/reducers.ts
  packages/common/src/store/user-list/search/selectors.ts
  packages/common/src/store/user-list/search/types.ts
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/screens/chats-screen/ChatsScreen.tsx
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/assets/styles/colors.css
  packages/web/src/common/store/user-list/search/sagas.ts
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/page/Page.js
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/components/UserList.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/App.module.css
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.module.css
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.module.css
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/ChatList.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.module.css
  packages/web/src/pages/chat-page/components/ChatListItem.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.module.css
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/ChatUser.module.css
  packages/web/src/pages/chat-page/components/ChatUser.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.module.css
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatPrompt.module.css
  packages/web/src/pages/chat-page/components/CreateChatPrompt.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/application/ui/chat/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#2597 [C-1836] Add null check to the useUpdateRequired hook
  packages/mobile/src/hooks/useUpdateRequired.ts
Labels: size/XS

#2599 [C-1823] Fix twitter auth on android
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/res/values/strings.xml
  packages/mobile/src/screens/signon/ProfileAuto.tsx
Labels: size/S

#2600 Improve useLocalImage perf
  packages/mobile/src/hooks/useLocalImage.ts
Labels: size/S

#2602 [C-1845] Upgrade to reanimated 2.14.0 to fix tab occlusion
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/XS

#2604 Bump SDK version to 1.0.41
  packages/common/package-lock.json
  packages/common/package.json
  packages/eslint-config-audius/package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#2605 [PAY-819] Fix track update cid bug
  packages/common/src/schemas/index.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
Labels: size/XS

#2606 Add proper fix for track cid bug
  packages/common/src/schemas/index.ts
Labels: size/XS

#2497 C-1740 Enable OTA updates using CodePush
  package-lock.json
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.java
  packages/mobile/android/build.gradle
  packages/mobile/android/settings.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
Labels: size/M

#2596 C-1570 Fix toast text alignment
  packages/mobile/src/components/toast/ToastView.tsx
Labels: size/M

#2609 [C-1833, C-1834] Fix track player repeat and auto play behaviors
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/S

#2601 [C-1712] Upgrade typescript to 4.9
  package-lock.json
  package.json
  packages/eslint-config-audius/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/cache/users/sagas.d.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/common/store/upload/sagas.d.ts
Labels: size/M

#2612 Fix search being missing from most pages
  packages/web/src/components/page/Page.js
Labels: size/XS

#2613 [C-1837] Fix infinite spinner bug for search bar
  packages/web/src/components/search/SearchBar.js
Labels: size/XS

#2603 [C-1704] [C-1480] Add missing analytics
  packages/mobile/src/hooks/useTikTokAuth.ts
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/screens/signon/ProfileManual.tsx
  packages/mobile/src/screens/signon/SignOnScreen.tsx
  packages/web/src/hooks/useTikTokAuth.ts
Labels: size/M

#2614 Fix rerenders from useLocalImage
  packages/mobile/src/hooks/useLocalImage.ts
Labels: size/XS

#2608 [C-1690] Sync newly favorited/unfavorited collections
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/L

#2615 [C-1846] Add themed rive bottom bar animations
  packages/mobile/android/app/src/main/res/raw/explore_dark.riv
  packages/mobile/android/app/src/main/res/raw/explore_default.riv
  packages/mobile/android/app/src/main/res/raw/explore_matrix.riv
  packages/mobile/android/app/src/main/res/raw/favorites_dark.riv
  packages/mobile/android/app/src/main/res/raw/favorites_default.riv
  packages/mobile/android/app/src/main/res/raw/favorites_matrix.riv
  packages/mobile/android/app/src/main/res/raw/feed_dark.riv
  packages/mobile/android/app/src/main/res/raw/feed_default.riv
  packages/mobile/android/app/src/main/res/raw/feed_matrix.riv
  packages/mobile/android/app/src/main/res/raw/notifications_dark.riv
  packages/mobile/android/app/src/main/res/raw/notifications_default.riv
  packages/mobile/android/app/src/main/res/raw/notifications_matrix.riv
  packages/mobile/android/app/src/main/res/raw/trending_dark.riv
  packages/mobile/android/app/src/main/res/raw/trending_default.riv
  packages/mobile/android/app/src/main/res/raw/trending_matrix.riv
  packages/mobile/ios/Assets/explore_dark.riv
  packages/mobile/ios/Assets/explore_default.riv
  packages/mobile/ios/Assets/explore_matrix.riv
  packages/mobile/ios/Assets/favorites_dark.riv
  packages/mobile/ios/Assets/favorites_default.riv
  packages/mobile/ios/Assets/favorites_matrix.riv
  packages/mobile/ios/Assets/feed_dark.riv
  packages/mobile/ios/Assets/feed_default.riv
  packages/mobile/ios/Assets/feed_matrix.riv
  packages/mobile/ios/Assets/notifications_dark.riv
  packages/mobile/ios/Assets/notifications_default.riv
  packages/mobile/ios/Assets/notifications_matrix.riv
  packages/mobile/ios/Assets/trending_dark.riv
  packages/mobile/ios/Assets/trending_default.riv
  packages/mobile/ios/Assets/trending_matrix.riv
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/BottomTabBarButton.tsx
Labels: size/L

#2620 Fix BuyAudio flow failure due to local storage type error
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#2618 [C-1832] Fix shuffle for new track player implementation
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/M

#2616 [C-1730] Add auth error messaging
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.module.css
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.module.css
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
  packages/web/src/pages/sign-on/components/ProfilePage.tsx
Labels: size/M

#2619 [PAY-845] Sort rewards tiles by completed/disbursed
  packages/common/src/utils/challenges.ts
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/M

#2621 [C-1862] Add back button to manual profile creation screen
  packages/mobile/src/screens/signon/CreatePassword.tsx
  packages/mobile/src/screens/signon/FirstFollows.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/screens/signon/ProfileManual.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/mobile/src/screens/signon/SignOnScreen.tsx
  packages/mobile/src/screens/signon/SignupHeader.tsx
Labels: size/M

#2617 [C-1810] Block more screens when offline
  packages/mobile/src/components/core/Screen/ScreenContent.tsx
  packages/mobile/src/components/form-screen/FormScreen.tsx
  packages/mobile/src/components/skeletons/EntitySkeleton.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/chats-screen/ChatsScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/FormScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TopAlbumsScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingPlaylistsScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingUndergroundScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/search-results-screen/SearchResultsScreen.tsx
  packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/settings-screen/ChangePasswordScreen/ChangePasswordScreen.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/signon/FirstFollows.tsx
  packages/mobile/src/screens/tip-artist-screen/TipScreen.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
Labels: size/XXL

#2622 [C-1798] Update copy for verification modal
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
Labels: size/S

#2629 [C-1403] Update tracks table to allow dragging to playlists
  packages/web/src/components/table/Table.module.css
  packages/web/src/components/table/Table.tsx
Labels: size/M

#2630 [C-1868] Fix android test app installs
  packages/mobile/android/app/src/releaseCandidate/res/values/strings.xml
  packages/mobile/android/app/src/staging/res/values/strings.xml
  packages/mobile/android/app/src/stagingReleaseCandidate/values/strings.xml
Labels: size/S

#2595 [PAY-780] Premium content track tile - Web
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/desktop/Artwork.module.css
  packages/web/src/components/track/desktop/Artwork.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PremiumContentLabel.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/types.ts
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#2589 Premium track page - continued
  packages/common/src/store/collectibles/slice.ts
  packages/common/src/store/premium-content/actions.ts
  packages/common/src/store/premium-content/index.ts
  packages/common/src/store/premium-content/reducer.ts
  packages/common/src/store/premium-content/selectors.ts
  packages/common/src/store/premium-content/slice.ts
  packages/common/src/store/reducers.ts
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/Artwork.module.css
  packages/web/src/components/track/desktop/Artwork.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PremiumContentLabel.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/types.ts
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/utils/zIndex.ts
Labels: size/XL

#2624 [PAY-835] Use proper icons for DMs
  packages/stems/src/assets/icons/iconCompose.svg
  packages/stems/src/assets/icons/iconPlus.svg
  packages/stems/src/assets/icons/iconSend.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.module.css
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.module.css
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatPrompt.tsx
Labels: size/L

#2579 Fix playlist upload flag in metadata
  packages/web/src/common/store/upload/sagas.js
Labels: size/XS

#2623 [C-1863] filter out missing tracks in offline lineup
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
Labels: size/L

#2631 Fix typecheck
  packages/web/src/components/track/desktop/Artwork.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PremiumContentLabel.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/M

#2611 Add route to ERROR_PAGE event
  packages/common/src/models/Analytics.ts
  packages/web/src/store/configureStore.ts
  packages/web/src/store/errors/sagas.ts
Labels: size/S

#2628 [C-1867] track collection fav/unfavorited states separately
  packages/common/src/models/Collection.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/store/premium-content/index.ts
  packages/common/src/store/premium-content/slice.ts
  packages/mobile/src/components/drawers/RemoveDownloadedFavoritesDrawer.tsx
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2633 Upgrade reanimated to 2.14.4
  packages/mobile/package.json
Labels: size/XS

#2634 Check in package changes for reanimated upgrade
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/web/package-lock.json
Labels: size/XS

#2635 Add sentry on saga error
  packages/mobile/src/store/store.ts
Labels: size/S

#2637 [C-1860][C-1841] Fix disappearing downloaded tracks in lineups
  packages/common/src/store/lineup/actions.ts
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
Labels: size/M

#2638 [C-1828] Defer play count processing until online
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/workers/index.ts
  packages/mobile/src/services/offline-downloader/workers/playCounterWorker.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/M

#2639 [C-1755] Fix repeat jobs and sync inefficiencies
  packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/M

#2640 [C-1804] Add no tracks placeholder and offline content banner
  packages/mobile/src/assets/images/iconDownloadGray.svg
  packages/mobile/src/assets/images/iconNoWifiSmall.svg
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/NoTracksPlaceholder.tsx
  packages/mobile/src/screens/favorites-screen/OfflineContentBanner.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
Labels: size/L

#2641 [C-1864] Fix orphaned tracks after cancellation
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
Labels: size/L

#2646 Fix broken loading state for playlist tiles
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/utils/route.ts
Labels: size/S

#2645 [PAY-852] Fix Solana staging rpc provider
  packages/mobile/.env.stage
  packages/mobile/dapp-store/README.md
  packages/web/.env/.env.stage
Labels: size/XS

#2647 Fix playlist tile lint + bug
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
Labels: size/S

#2636 [PAY-844] Rewards UI improvements
  packages/mobile/src/assets/images/emojis/ballot-box-tick.png
  packages/mobile/src/assets/images/emojis/chart-bar.png
  packages/mobile/src/assets/images/emojis/gear.png
  packages/mobile/src/assets/images/emojis/headphones-white.png
  packages/mobile/src/assets/images/emojis/link-symbol.png
  packages/mobile/src/assets/images/emojis/money-with-wings.png
  packages/mobile/src/assets/images/emojis/right-arrow-curving-up.png
  packages/mobile/src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/screens/audio-screen/Panel.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/assets/fonts/emojis/ballot-box-tick.png
  packages/web/src/assets/fonts/emojis/chart-bar.png
  packages/web/src/assets/fonts/emojis/gear.png
  packages/web/src/assets/fonts/emojis/headphones-white.png
  packages/web/src/assets/fonts/emojis/link-symbol.png
  packages/web/src/assets/fonts/emojis/money-with-wings.png
  packages/web/src/assets/fonts/emojis/right-arrow-curving-up.png
  packages/web/src/assets/styles/emoji.css
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
  packages/web/src/pages/audio-rewards-page/TrendingRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/ButtonWithArrow.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/TrendingRewards.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/L

#2610 Allow fetching by permalink on client desktop
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/store/cache/collections/actions.ts
  packages/common/src/store/cache/collections/reducer.ts
  packages/common/src/store/cache/collections/selectors.ts
  packages/common/src/store/cache/collections/types.ts
  packages/common/src/store/cache/selectors.ts
  packages/common/src/store/pages/collection/actions.ts
  packages/common/src/store/pages/collection/reducer.ts
  packages/common/src/store/pages/collection/selectors.ts
  packages/common/src/store/pages/collection/types.ts
  packages/common/src/store/reducers.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/utils/index.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/utils/route.ts
  packages/web/src/utils/route/collectionRouteParser.ts
Labels: size/L

#2654 [C-1876] Hide download indicator on deleted tracks
  packages/mobile/src/components/track-list/TrackListItem.tsx
Labels: size/XS

#2655 [C-1875] Fix empty favorited tracks lineup on reconnect
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/XS

#2656 [C-1879] Download track when added to downloaded playlists
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/M

#2658 [C-1669] Enable OFFLINE_MODE_ENABLED feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
Labels: size/XS

#2660 Cherry-picks for offline release
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/M

#2649 Memoize sorted challenges
  packages/common/src/utils/challenges.ts
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/M

#2642 [PAY-853] Premium content fixes on web
  packages/common/src/store/pages/track/actions.ts
  packages/common/src/store/premium-content/slice.ts
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/Artwork.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#2650 [C-1885] Improve user socials fetching/loading
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/web/src/common/store/profile/sagas.js
Labels: size/S

#2663 Fix playlist tile click
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/XS

#2664 Fix profile
  packages/web/src/common/store/cache/sagas.js
Labels: size/S

#2665 [C-1894] [C-1904] Fix tiktok verification
  packages/common/src/models/User.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx
  packages/web/src/pages/profile-page/components/mobile/EditProfile.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/M

#2662 [PAY-862] Rewards UI Improvements Followups
  packages/common/src/utils/challenges.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/audio-screen/Panel.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/ButtonWithArrow.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/M

#2669 Listen to add succeeded
  packages/web/src/common/store/premiumContent/sagas.ts
Labels: size/XS

#2667 [C-1854] Prevent crash on settings page
  packages/web/src/components/service-selection/SelectedServices.tsx
Labels: size/XS
