Repository AudiusProject/audius-client, pull requests merged in 2023-02, with the labels that each got.

#2748 [C-1950] Smooth offline<>online playback
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/web/src/common/store/pages/collection/lineups/sagas.js
Labels: size/L

#2733 [C-1952] Show download successful when offline in status indicator
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicatorBase.tsx
Labels: size/S

#2750 Hide buttons on profiles when offline and remove timeout
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
Labels: size/S

#2741 [PAY-872][PAY-873][PAY-874] More premium content QA fixes
  packages/common/src/store/premium-content/slice.ts
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/assets/icons/iconCollectibleCornerTag.svg
  packages/stems/src/assets/icons/iconSpecialAccessCornerTag.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PremiumTrackCornerTag.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PremiumContentLabel.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/hooks/usePremiumContentAccess.ts
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#2746 C-1989 Fix "Download is not re-starting even though there are still many tracks that need to be downloaded"
  packages/mobile/src/services/offline-downloader/offline-sync.ts
Labels: size/M

#2742 [PAY-881] Mobile messages (chats) list screen
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatUser.tsx
  packages/mobile/src/screens/chat-screen/index.ts
  packages/mobile/src/screens/chats-screen/ChatsScreen.tsx
Labels: size/L

#2749 [C-1985] Remove collection tracks when removing favorites
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
Labels: size/XS

#2751 [C-1987][C-1936][C-2009] Queue for collection downloads
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/drawers/RemoveDownloadedCollectionDrawer.tsx
  packages/mobile/src/components/drawers/UnfavoriteDownloadedCollectionDrawer.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/offline-downloads/CollectionDownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicatorBase.tsx
  packages/mobile/src/components/offline-downloads/TrackDownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/index.ts
  packages/mobile/src/components/profile-list/ProfileCard.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/services/offline-downloader/index.ts
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/services/offline-downloader/types.ts
  packages/mobile/src/services/offline-downloader/workers/collectionDownloadWorker.ts
  packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/XXL

#2753 [C-1957] [C-1929] Improve TrackList and offline mode performance
  packages/common/src/hooks/useProxySelector.ts
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/components/track-list/TrackListItemSkeleton.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/hooks/useReachabilityEffect.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenSkeleton.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/web/src/common/store/pages/saved/lineups/sagas.js
  packages/web/src/common/store/pages/saved/sagas.js
Labels: size/XL

#2755 [C-1992] Fix unfavorite downloaded track
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/M

#2758 [C-1968] Fix dequeue track
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
Labels: size/M

#2761 [C-2001] Remove queued downloads if deleted/unlisted/etc
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/workers/collectionDownloadWorker.ts
  packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
Labels: size/L

#2759 C-2002 Un-download deleted playlists on sync
  packages/mobile/src/services/offline-downloader/offline-sync.ts
Labels: size/S

#2760 Refactor lineup hooks
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/useCollectionLineup.ts
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
Labels: size/L

#2708 [PAY-866] Add new remix settings - Part 1
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/data-entry/FormTile.module.css
  packages/web/src/components/modal-radio/ModalRadio.module.css
  packages/web/src/components/modal-radio/ModalRadioGroup.tsx
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/components/remix-settings-modal/ConnectedRemixSettingsModal.tsx
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.module.css
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
  packages/web/src/components/remix-settings-modal/RemixSettingsModalTrigger.module.css
  packages/web/src/components/remix-settings-modal/RemixSettingsModalTrigger.tsx
  packages/web/src/components/switch/Switch.tsx
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
  packages/web/src/components/track-availability-modal/HiddenAvailability.tsx
  packages/web/src/components/track-availability-modal/PublicAvailability.tsx
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track-availability-modal/types.ts
  packages/web/src/components/track/PremiumTrackSection.tsx
Labels: size/XXL

#2756 [PAY-868] Handle follow and tip send states across
  packages/common/src/models/Track.ts
  packages/common/src/store/premium-content/selectors.ts
  packages/common/src/store/premium-content/slice.ts
  packages/common/src/store/tipping/slice.ts
  packages/web/src/common/store/premiumContent/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#2762 [C-2006] Fix download toggle when offline
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx
Labels: size/S

#2763 [C-1921] Make sure to download local saves
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/M

#2764 [C-1974] Add batch remove downloads
  packages/mobile/src/components/drawers/RemoveDownloadedFavoritesDrawer.tsx
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/types.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/removeAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/removeCollectionDownloadsSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/removeTrackDownloadsSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/updateTrackDownloadReasonsSaga.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2767 Consume .env.git to properly tag Sentry release
  .circleci/src/jobs/@web-jobs.yml
  .circleci/src/workflows/web.yml
  packages/web/package.json
Labels: size/S

#2769 [C-2012] [C-1999] [C-1734] Fix collection image loading
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
  packages/web/src/common/store/cache/collections/sagas.js
Labels: size/M

#2771 Fix CI
  packages/web/package.json
Labels: size/S

#2770 [C-1941] Refresh queue when download toggle is flipped
  packages/common/src/store/queue/selectors.ts
  packages/common/src/utils/uid.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/src/common/store/lineup/sagas.js
Labels: size/M

#2772 Improve download toggle, download progress and fetch
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2774 [C-1994] Add download indicator to the track screen
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/TrackDownloadStatusIndicator.tsx
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/M

#2706 [DMs] Redo create chat modal
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/search-users-modal/selectors.ts
  packages/common/src/store/ui/search-users-modal/slice.ts
  packages/common/src/store/user-list/index.ts
  packages/common/src/store/user-list/search/actions.ts
  packages/common/src/store/user-list/search/reducers.ts
  packages/common/src/store/user-list/search/selectors.ts
  packages/common/src/store/user-list/search/types.ts
  packages/stems/src/assets/icons/iconBlockMessages.svg
  packages/stems/src/assets/icons/iconMessage.svg
  packages/stems/src/assets/icons/iconUnblockMessages.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/common/store/search-users-modal/sagas.ts
  packages/web/src/common/store/user-list/search/sagas.ts
  packages/web/src/components/search-users-modal/SearchUsersModal.module.css
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/components/UserList.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatPrompt.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.module.css
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/store/application/ui/chat/sagas.ts
  packages/web/src/store/sagas.ts
  packages/web/src/utils/zIndex.ts
Labels: size/XL

#2776 [C-2036] Fix modals not closing on click outside
  packages/stems/src/components/Modal/Modal.tsx
Labels: size/XS

#2757 C-1958 Show # of downloaded tracks in collection card instead of actual # of tracks in collection when offline
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/utils.ts
Labels: size/L

#2773 C-2022 C-1970 Fix for: When offline and not fully downloaded, queued jobs keep running and fail
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/workers/collectionDownloadWorker.ts
  packages/mobile/src/services/offline-downloader/workers/index.ts
  packages/mobile/src/services/offline-downloader/workers/playCounterWorker.ts
  packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
  packages/mobile/src/services/offline-downloader/workers/utils.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
Labels: size/M

#2775 [C-2034] Cancel all download jobs on log out
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/S

#2766 [C-2015] Debounce the callbacks for the download toggles for favorites and collections
  packages/mobile/src/hooks/useDebouncedCallback.ts
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
Labels: size/M

#2777 Fix download progress numerator going down in the middle of downloading C-2037
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/S

#2778 Improve styling of TrackList on Favorites Screen
  packages/mobile/src/components/core/VirtualizedScrollView.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/screens/favorites-screen/FilterInput.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
Labels: size/M

#2783 Fix remix
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/remix-settings-modal/RemixSettingsModalTrigger.tsx
Labels: size/S

#2782 C-2041 Fix collection lineup not loading when library is only partially downloaded
  packages/mobile/src/screens/collection-screen/useCollectionLineup.ts
Labels: size/S

#2785 Default offline mode off
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#2784 [C-2011] move whole tracks out of offline slice
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/hooks/useOfflineTrackUri.ts
  packages/mobile/src/screens/collection-screen/useCollectionLineup.ts
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/removeAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2786 Fix TikTok association
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#2788 [C-2066] Refactor offline-mode to use redux-persist
  packages/common/src/models/Collection.ts
  packages/common/src/models/Track.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/drawers/RemoveDownloadedCollectionDrawer.tsx
  packages/mobile/src/components/drawers/UnfavoriteDownloadedCollectionDrawer.tsx
  packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx
  packages/mobile/src/constants/storage-keys.ts
  packages/mobile/src/hooks/useLoadOfflineTracks.ts
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/services/offline-downloader/index.ts
  packages/mobile/src/services/offline-downloader/offline-download-queue.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/services/offline-downloader/offline-sync.ts
  packages/mobile/src/services/offline-downloader/types.ts
  packages/mobile/src/services/offline-downloader/workers/collectionDownloadWorker.ts
  packages/mobile/src/services/offline-downloader/workers/index.ts
  packages/mobile/src/services/offline-downloader/workers/playCounterWorker.ts
  packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
  packages/mobile/src/services/offline-downloader/workers/utils.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/clearOfflineDownloadsSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/getIsOfflineEnabled.ts
  packages/mobile/src/store/offline-downloads/sagas/processDownloadQueueSaga/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/processDownloadQueueSaga/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/processDownloadQueueSaga/processDownloadQueueSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/removeAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/removeCollectionDownloadsSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/removeTrackDownloadsSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadFavoritedCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveDownloadedCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveFavoritedDownloadedCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/updateStaleOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/updateTrackDownloadReasonsSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchAddOfflineItems.ts
  packages/mobile/src/store/offline-downloads/sagas/watchAddTrackToPlaylistSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchReachability.ts
  packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
  packages/mobile/src/store/offline-downloads/sagas/watchSaveCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchSaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchUnsaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
  packages/mobile/src/store/offline-downloads/utils.ts
  packages/mobile/src/store/utils/monitorSelector.ts
Labels: size/XXL

#2790 Add redownload logic for rehydration and stale tracks
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/updateStaleOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2791 [C-2079] Fix mobile sign up analytics
  packages/mobile/src/screens/signon/SignOnScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/sign-up/sagas.ts
  packages/mobile/src/store/sign-up/sagas/watchSignUpSucceededSaga.ts
Labels: size/M

#2795 Decode artist pick IDs and fix artist pick reads from discovery
  packages/common/src/models/User.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
Labels: size/S

#2797 [C-2068] Add downloadQueue worker cancellation
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/downloadQueueSagas.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/requestDownloadQueuedItemSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/watchAddOfflineItems.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/watchReachability.ts
  packages/mobile/src/store/offline-downloads/sagas/processDownloadQueueSaga/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/processDownloadQueueSaga/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/processDownloadQueueSaga/processDownloadQueueSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/XL

#2781 Remove identity artist pick path
  packages/common/src/models/User.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/pin-track-confirmation/PinTrackConfirmation.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#2787 [PAY-898] Design fixes for NavMenuPopup
  packages/stems/src/assets/icons/iconDashboard.svg
  packages/stems/src/assets/icons/iconSettings.svg
  packages/stems/src/components/Icons/index.ts
  packages/stems/src/components/PopupMenu/PopupMenu.module.css
  packages/web/src/components/nav/desktop/NavPopupMenu.module.css
Labels: size/M

#2798 Add script to help with linking sdk
  README.md
  package-lock.json
  package.json
  packages/common/tsconfig.json
  packages/mobile/package-lock.json
  packages/web/package-lock.json
  packages/web/package.json
  scripts/link-sdk.sh
Labels: size/M

#2799 Update challenges copy
  packages/common/src/utils/challenges.ts
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/S

#2800 [C-1975] Fix safari stream mp3
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/S

#2801 [C-2072] Add stale collection logic
  packages/mobile/src/store/offline-downloads/sagas/updateStaleOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
Labels: size/L

#2802 [C-2056] Fix lineup scrolling
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/XS

#2804 [C-2039] Fix search query persist
  packages/mobile/src/store/search/slice.ts
Labels: size/XS

#2806 Update sdk to v1.0.45
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#2793 Fix audio tx modal where metadata is null
  packages/common/src/store/ui/transaction-details/types.ts
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
Labels: size/M

#2805 [C-2080] Update value change logic for download toggles for favorites and collection switches
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
Labels: size/M

#2803 [C-2083] Add offline sync to queue
  packages/common/src/models/Favorite.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/mobile/src/hooks/useFetchAllFavoritedTracks.ts
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/services/offline-downloader/index.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/services/offline-downloader/types.ts
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/requestDownloadQueuedItemSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/getIsOfflineEnabled.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/syncOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/updateStaleOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/XL

#2807 [C-1984] Don't use nativeDriver for slider and tracking bar anims
  packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
Labels: size/S

#2810 [C-2058] prevent restart loop
  packages/mobile/src/components/toasts/Toast.tsx
  packages/mobile/src/store/store.ts
Labels: size/S

#2808 [C-2038] Fix unresponsive reactions
  packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/reactions.tsx
Labels: size/M

#2811 Remove clear offline downloads button
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
Labels: size/S

#2812 [C-2090] Reduce file reads on play
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/XS

#2813 Fix onPressRail animation error
  packages/mobile/src/components/scrubber/Slider.tsx
Labels: size/XS

#2815 Don't download on save if all favorites toggle off
  packages/mobile/src/store/offline-downloads/sagas/watchSaveTrackSaga.ts
Labels: size/XS

#2814 [C-2067] Add 'play-count' queue
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/playCounterWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/requestDownloadQueuedItemSaga.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/M

#2821 [C-2065] Only show collection download switch if favorited
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/M

#2816 [C-2040] Improve duration counter accuracy/performance
  packages/mobile/src/components/scrubber/PositionTimestamp.tsx
  packages/mobile/src/components/scrubber/Scrubber.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/mobile/src/components/scrubber/usePosition.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
Labels: size/L

#2822 [C-2087] Add stale track queue worker
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/requestDownloadQueuedItemSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/playCounterWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/staleTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/redownloadStaleTracksSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/syncOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/updateStaleOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2824 [C-2107] Add local saves to offline queue
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
Labels: size/M

#2825 [C-2101] Improve initial download ui performance
  packages/mobile/src/components/drawers/RemoveDownloadedFavoritesDrawer.tsx
  packages/mobile/src/hooks/useReachabilityEffect.ts
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesDownloadSection.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesDownloadStatusIndicator.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2809 [PAY-882] Individual Chat Screen
  packages/common/src/utils/chatUtils.ts
  packages/common/src/utils/constants.ts
  packages/common/src/utils/formatUtil.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/index.ts
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/L

#2829 Set offline mode flag default true
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#2826 [C-2108] Improve local image fetch
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/hooks/useLocalImage.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
Labels: size/L

#2827 [C-2102] Improve online/offline transitions
  packages/mobile/src/components/core/Screen/ScreenContent.tsx
  packages/mobile/src/components/with-loader/WithLoader.tsx
  packages/mobile/src/screens/favorites-screen/FilterInput.tsx
  packages/mobile/src/screens/favorites-screen/NoTracksPlaceholder.tsx
  packages/mobile/src/screens/favorites-screen/OfflineContentBanner.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
Labels: size/M

#2830 [C-2109] Fix favorited collection not downloading
  packages/mobile/src/components/drawers/UnfavoriteDownloadedCollectionDrawer.tsx
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadFavoritedCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchSaveCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchSaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchUnsaveCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchUnsaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2834 remove duplicate selector
  packages/mobile/src/store/offline-downloads/selectors.ts
Labels: size/XS

#2832 Bump SDK to v2.0.1
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-sdk.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
  packages/web/src/services/audius-sdk/audiusSdk.ts
Labels: size/L

#2831 [C-2104] Fix favorites pagination when coming online
  packages/common/src/store/reachability/index.ts
  packages/common/src/store/reachability/sagas.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/utils/reachability.ts
  packages/web/src/store/sagas.ts
Labels: size/M

#2792 C-2052 Fix duplicate tracks are all marked as "playing" if you play one of them
  packages/common/src/utils/selectorHelpers.ts
  packages/mobile/src/screens/collection-screen/useCollectionLineup.ts
Labels: size/M

#2837 [C-2117] Fix favorites loading when starting from an offline session
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
Labels: size/S

#2833 [C-2095] Improve download cancel
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesDownloadStatusIndicator.tsx
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
  packages/mobile/src/services/offline-downloader/index.ts
  packages/mobile/src/services/offline-downloader/offline-downloader.ts
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/constants.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadFile.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/staleTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/getStaleTracks.ts
  packages/mobile/src/store/offline-downloads/sagas/redownloadStaleTracksSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/syncOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchSaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchUnsaveCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchUnsaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/XL

#2836 [C-2089] Distinguish between errored and abandoned
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/staleTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/utils/isCollectionDownloadable.ts
  packages/mobile/src/store/offline-downloads/sagas/utils/isTrackDownloadable.ts
  packages/mobile/src/store/offline-downloads/slice.ts
  packages/mobile/src/utils/trackUtils.ts
Labels: size/L

#2838 [C-2111] Fix lineuptrack uid generation for offline collections
  packages/mobile/src/screens/collection-screen/useCollectionLineup.ts
Labels: size/S

#2839 [C-2125] match uids from queue to preserve smooth playback
  packages/mobile/src/screens/collection-screen/useCollectionLineup.ts
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
Labels: size/M

#2818 [PAY-779][PAY-781] Add premium track page and tile on mobile - Part 3
  packages/common/src/hooks/usePremiumContentAccess.ts
  packages/common/src/services/audius-backend/eagerLoadUtils.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/stringUtils.ts
  packages/mobile/src/assets/images/iconExternalLink.svg
  packages/mobile/src/assets/images/iconLock.svg
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/screens/track-screen/PremiumTrackCornerTag.tsx
  packages/mobile/src/utils/zIndex.ts
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/L

#2819 [PAY-779][PAY-781] Add premium track page and tile on mobile - Part 2
  packages/common/src/hooks/usePremiumContentAccess.ts
  packages/common/src/services/audius-backend/eagerLoadUtils.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/stringUtils.ts
  packages/mobile/src/assets/images/iconExternalLink.svg
  packages/mobile/src/assets/images/iconLock.svg
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/screens/track-screen/PremiumTrackCornerTag.tsx
  packages/mobile/src/utils/zIndex.ts
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/XL

#2820 [PAY-779][PAY-781] Add premium track page and tile on mobile - Part 1
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/usePremiumContentAccess.ts
  packages/common/src/services/audius-backend/eagerLoadUtils.ts
  packages/common/src/store/premium-content/index.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/store/sagas.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/stringUtils.ts
  packages/mobile/src/assets/images/iconCollectibleCornerTag.svg
  packages/mobile/src/assets/images/iconExternalLink.svg
  packages/mobile/src/assets/images/iconLock.svg
  packages/mobile/src/assets/images/iconLockedCornerTag.svg
  packages/mobile/src/assets/images/iconSpecialAccessCornerTag.svg
  packages/mobile/src/assets/images/iconUnlocked.svg
  packages/mobile/src/assets/images/iconVerifiedGreen.svg
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/screens/track-screen/PremiumTrackCornerTag.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/search/types.ts
  packages/mobile/src/utils/theme.ts
  packages/mobile/src/utils/zIndex.ts
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/hooks/usePremiumContentAccess.ts
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
Labels: size/XXL

#2843 C-2129 Decomp shared logic in collections tabs
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/useCollectionScreenData.ts
Labels: size/L

#2842 C-2119 Show downloaded collections only
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/useCollectionScreenData.ts
Labels: size/L

#2840 [C-2123] Fix collection lineup when coming online
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/common/store/pages/collection/lineups/sagas.js
Labels: size/S

#2846 [C-2051] Fix images in AddToPlaylistDrawer
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
Labels: size/S

#2849 [C-2126] Fix empty collections on first session
  packages/web/src/common/store/profile/sagas.js
Labels: size/XS

#2852 [C-2132] unlink is safe on ios but not android
  packages/mobile/src/services/track-download.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
Labels: size/S

#2851 Fix useThrottledCallback trailing config
  packages/mobile/src/hooks/useThrottledCallback.ts
Labels: size/XS

#2854 [C-2134 C-2030] Fix queueStatus on reachability, theme
  packages/mobile/src/assets/images/iconDownloadGray.svg
  packages/mobile/src/assets/images/iconFilter.svg
  packages/mobile/src/assets/images/iconNoWifi.svg
  packages/mobile/src/assets/images/iconNoWifiSmall.svg
  packages/mobile/src/components/offline-placeholder/OfflinePlaceholder.tsx
  packages/mobile/src/screens/favorites-screen/NoTracksPlaceholder.tsx
  packages/mobile/src/screens/favorites-screen/OfflineContentBanner.tsx
  packages/mobile/src/screens/favorites-screen/utils.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/watchReachability.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/M

#2855 Ensure queue always starts back up
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/watchReachability.ts
Labels: size/XS

#2856 Missed merge broke import
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/watchReachability.ts
Labels: size/XS

#2857 [C-2136] Fix smart collection loading
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/XS

#2858 [C-2112] Rename various offline state elements
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/store/offline-downloads/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/downloadQueueSagas.ts
  packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/watchAddOfflineItems.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/offlineQueueSagas.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/requestProccessNextJobSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/watchAddOfflineEntries.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/watchReachability.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadFile.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/playCounterWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/staleTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadFavoritedCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveAllDownloadedFavoritesSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/requestRemoveDownloadedCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/syncOfflineDataSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchAddTrackToPlaylistSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
  packages/mobile/src/store/offline-downloads/sagas/watchSaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchUnsaveCollectionSaga.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
  packages/mobile/src/types/analytics.ts
Labels: size/L

#2860 [C-2139] Fix now playing
  packages/mobile/src/components/drawer/Drawer.tsx
Labels: size/XS

#2796 [DMs] Websockets middleware for Chats
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/store/pages/chat/index.ts
  packages/common/src/store/pages/chat/middleware.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/store/configureStore.ts
Labels: size/L

#2862 Allow errored tracks to be re-enqueued
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/S

#2863 [C-2141] Fix missing lineup when coming back online
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/web/src/common/store/lineup/sagas.js
Labels: size/M

#2865 Fix share to X video colors C-2146
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/XS

#2729 [PAY-848] Fix UploadChip spacing
  packages/web/src/components/upload/UploadChip.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
Labels: bug, size/M

#2864 Update handle spec
  packages/common/src/services/oauth/formatSocialProfile.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/sign-on/components/ProfileForm.tsx
Labels: size/XS

#2678 [C-1890] Improve artist-recommendations fetching/loading
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/web/src/common/store/profile/sagas.js
Labels: size/S

#2871 Show package version on AboutScreen
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
Labels: size/XS

#2868 Fix SDK bootstrap for mobile
  packages/mobile/src/services/audius-sdk.ts
Labels: size/XS

#2869 [PAY-893] UserBadge in chat screen header
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#2870 Improve premium content saga perf
  packages/common/src/store/premium-content/sagas.ts
Labels: size/S

#2872 Rename feature flag OFFLINE_MODE_ENABLED -> OFFLINE_MODE_RELEASE
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/constants/storage-keys.ts
  packages/mobile/src/hooks/useIsOfflineModeEnabled.ts
  packages/mobile/src/store/offline-downloads/sagas/getIsOfflineEnabled.ts
Labels: size/S

#2873 [DMs][PAY-832] Fix compose modal mutuals default
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Labels: size/XS

#2679 [C-1887 C-1888] Improve profile and explore screen performance
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/pages/explore/selectors.ts
  packages/common/src/store/pages/explore/slice.ts
  packages/common/src/store/pages/explore/types.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/common/src/store/pages/profile/types.ts
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/web/src/common/store/cache/collections/utils/addTracksFromCollections.ts
  packages/web/src/common/store/cache/collections/utils/processAndCacheCollections.ts
  packages/web/src/common/store/cache/collections/utils/reformat.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/pages/explore/sagas.ts
  packages/web/src/common/store/profile/fetchProfileCollectionsSaga.ts
  packages/web/src/common/store/profile/sagas.js
Labels: size/L

#2672 [C-1883] Use lazy tabs to improve perf
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/components/top-tab-bar/TopTabNavigator.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Labels: size/L

#2876 [C-2163] Catch image errors in caching logic
  packages/mobile/src/store/account/sagas.ts
Labels: size/M

#2677 [C-1923] Implement fast profile images
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/image/UserCoverImage.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/components/profile-list/ProfileCard.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
Labels: size/L

#2867 [DMs] Unread separator, scrolling, and other bugfixes
  packages/common/package.json
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.module.css
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/store/application/ui/chat/sagas.ts
Labels: size/L

#2875 Use u64 on buy-audio/sagas to fix typecheck
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/S

#2878 Fix saga reachability
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/watchReachability.ts
Labels: size/XS

#2877 Migrate search-users saga + deps to common
  packages/common/src/store/cache/index.ts
  packages/common/src/store/cache/users/utils.ts
  packages/common/src/store/reachability/sagas.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/search-users-modal/sagas.ts
  packages/common/src/utils/sagaHelpers.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/cache/collections/utils/addUsersFromCollections.ts
  packages/web/src/common/store/cache/tracks/utils/helpers.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/cache/users/utils/index.ts
  packages/web/src/common/store/cache/users/utils/processAndCacheUsers.ts
  packages/web/src/common/store/cache/users/utils/reformat.ts
  packages/web/src/common/store/pages/search-page/sagas.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/ui/artist-recommendations/sagas.ts
  packages/web/src/common/store/user-list/utils.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#2880 Update audio player class in mobile to match the type and make small update to playback rate saga
  packages/mobile/src/services/audio-player/NativeMobileAudio.ts
  packages/web/src/common/store/player/sagas.ts
Labels: size/XS

#2879 [C-1301] TikTok native auth
  packages/common/src/hooks/useTikTokAuth.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.java
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/patches/react-native-tiktok+1.1.1.patch
  packages/mobile/src/components/tiktok-auth/TikTokAuthButton.tsx
  packages/mobile/src/components/tiktok-auth/index.ts
  packages/mobile/src/hooks/useTikTokAuth.ts
  packages/mobile/src/store/oauth/actions.ts
Labels: size/L

#2841 [PAY-888][PAY-909][PAY-869] Premium content features and fixes
  packages/common/src/store/pages/track/actions.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/modal-radio/ModalRadio.module.css
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track/EditTrackModal.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/pages/upload-page/components/FinishPage.js
Labels: size/L

#2883 [C-2179] Show solana-phone wallet connect option on saga
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/core/ChainLogo.tsx
  packages/mobile/src/screens/wallet-connect/ConnectNewWalletButton.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallet.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/services/audio-player/NativeMobileAudio.ts
Labels: size/L

#2716 Show Ready to Claim Pill on needsDisbursement
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/XS

#2882 [PAY-936] Search users to chat screen
  packages/mobile/src/assets/images/iconCompose.svg
  packages/mobile/src/assets/images/iconMessage.svg
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
  packages/mobile/src/screens/chat-screen/index.ts
Labels: size/L

#2885 [C-2167] Deduplicate explore playlists
  packages/web/craco.config.ts
  packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
Labels: size/S

#2887 Fix user collections check
  packages/web/src/common/store/cache/collections/utils/processAndCacheCollections.ts
Labels: size/XS

#2886 [C-2166] Fix drawer flicker
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/services/audio-player/NativeMobileAudio.ts
Labels: size/M

#2889 [C-2155 C-2127] Fix duplicate feed fetch
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/hooks/useReachabilityEffect.ts
Labels: size/M

#2892 [C-2176] TikTok sdk improvements
  packages/mobile/.env.stage
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.java
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/patches/react-native-tiktok+1.1.1.patch
  packages/mobile/src/components/loading-spinner/LoadingSpinner.tsx
  packages/mobile/src/hooks/useTikTokAuth.ts
Labels: size/L

#2895 Relay to both POA and ACDC
  packages/mobile/.env.prod
  packages/web/.env/.env.prod
Labels: size/XS

#2894 Rename TikTok video feature flag
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#2890 [C-2169] Fix track-player hot reload
  packages/mobile/index.js
  packages/mobile/patches/react-native-track-player+3.2.0.patch
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/L

#2891 Minor updates to mobile chats
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/utils/chatUtils.ts
  packages/mobile/src/assets/images/iconCompose.svg
  packages/mobile/src/assets/images/iconMessage.svg
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/L

#2896 [C-2178] Complete w/ tiktok qa fixes
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/core/FormTextInput.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/web/src/pages/profile-page/components/SocialLinkInput.module.css
  packages/web/src/pages/profile-page/components/SocialLinkInput.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.module.css
Labels: size/M

#2900 [C-2195] Fix tiktok share on android
  packages/mobile/android/app/build.gradle
Labels: size/XS

#2897 Fix TikTok share permission for iOS
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/M

#2901 Permission copy change
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#2902 [C-2197] Fix image prefetch to work with fast-image
  packages/mobile/src/store/account/sagas.ts
Labels: size/M

#2904 [C-2198] Fix runtime error due to missing drawer data
  packages/mobile/src/app/Drawers.tsx
Labels: size/M

#2906 [C-2200] Fix profile tabs loading/empty states
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/routes.ts
Labels: size/M

#2905 [C-2130] Fix race cond in lineup init
  packages/common/src/store/pages/collection/lineup/reducer.ts
  packages/common/src/store/pages/collection/reducer.ts
  packages/common/src/store/pages/feed/lineup/reducer.ts
  packages/common/src/store/pages/feed/reducer.ts
  packages/common/src/store/pages/history-page/lineups/tracks/reducer.ts
  packages/common/src/store/pages/history-page/reducer.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/remixes/slice.ts
  packages/common/src/store/pages/saved-page/lineups/tracks/reducer.ts
  packages/common/src/store/pages/saved-page/reducer.ts
  packages/common/src/store/pages/search-results/lineup/tracks/reducer.ts
  packages/common/src/store/pages/search-results/reducer.ts
  packages/common/src/store/pages/track/lineup/reducer.ts
  packages/common/src/store/pages/track/reducer.ts
  packages/common/src/store/pages/trending-playlists/slice.ts
  packages/common/src/store/pages/trending-underground/lineup/reducer.ts
  packages/common/src/store/pages/trending-underground/slice.ts
  packages/common/src/store/pages/trending/lineup/reducer.ts
  packages/common/src/store/pages/trending/reducer.ts
  packages/web/src/pages/deleted-page/store/slice.ts
Labels: size/L

#2909 Fix image loading issues w Share to X
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/M

#2908 [C-2186] Fix spacing for longs handles/names
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/web/src/components/first-upload-modal/FirstUploadModal.module.css
  packages/web/src/components/nav/desktop/NavColumn.module.css
  packages/web/src/components/nav/desktop/NavColumn.tsx
Labels: size/M

#2899 [C-2164] add retry and requeue logic to download track jobs
  packages/mobile/src/components/offline-downloads/CollectionDownloadStatusIndicator.tsx
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/requestProccessNextJobSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/staleTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/utils/retryOfflineJob.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/M

#2914 [C-2042] Fix empty collection on deep link
  packages/common/src/store/pages/collection/actions.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/common/store/pages/collection/sagas.js
Labels: size/M

#2903 [C-2171] Fix remove download performance
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/L

#2676 [C-1931] Refactor collection header for private track logic
  packages/web/src/components/collection/desktop/ActionButtons.tsx
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PlayButton.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
  packages/web/src/components/collection/desktop/SmartCollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/ViewerActionButtons.tsx
  packages/web/src/components/collection/desktop/utils.ts
  packages/web/src/components/tooltip/index.ts
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/XXL

#2644 [C-1856] Upgrade react-native to 0.71
  packages/common/package-lock.json
  packages/eslint-config-audius/package-lock.json
  packages/mobile/.eslintrc.js
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/build_defs.bzl
  packages/mobile/android/app/src/debug/java/co/audius/app/ReactNativeFlipper.java
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.java
  packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.java
  packages/mobile/android/app/src/main/java/co/audius/app/newarchitecture/MainApplicationReactNativeHost.java
  packages/mobile/android/app/src/main/java/co/audius/app/newarchitecture/components/MainComponentsRegistry.java
  packages/mobile/android/app/src/main/java/co/audius/app/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  packages/mobile/android/app/src/main/jni/CMakeLists.txt
  packages/mobile/android/app/src/main/jni/MainApplicationModuleProvider.cpp
  packages/mobile/android/app/src/main/jni/MainApplicationModuleProvider.h
  packages/mobile/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  packages/mobile/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  packages/mobile/android/app/src/main/jni/MainComponentsRegistry.cpp
  packages/mobile/android/app/src/main/jni/MainComponentsRegistry.h
  packages/mobile/android/app/src/main/jni/OnLoad.cpp
  packages/mobile/android/app/src/release/java/co/audius/app/ReactNativeFlipper.java
  packages/mobile/android/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/android/settings.gradle
  packages/mobile/ios/AudiusReactNative/AppDelegate.h
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/patches/react-native+0.70.6.patch
  packages/mobile/patches/react-native+0.71.3.patch
  packages/mobile/patches/react-native-code-push+7.0.5.patch
  packages/mobile/react-native.config.js
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/scrubber/usePosition.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
Labels: size/XXL

#2910 [PAY-890] Add locked content drawer on mobile
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/usePremiumContent.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
  packages/mobile/src/components/locked-content-drawer/index.ts
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/components/locked-content-modal/LockedContentModal.module.css
  packages/web/src/components/locked-content-modal/LockedContentModal.tsx
Labels: size/L
