Repository AudiusProject/audius-client, pull requests merged in 2023-03, with the labels that each got.

#2947 [PAY-956] Catch wallet connect errors and reset modal state
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Labels: size/M

#2942 [PAY-972] Handle duplicate wallet connections properly
  packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.module.css
  packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletsTable.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletsTable.tsx
Labels: size/S

#2940 [C-2209] Improve collection-screen perf
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/useFetchCollectionLineup.ts
Labels: size/L

#2943 [PAY-967][PAY-974] Fix nft issues
  packages/common/src/services/opensea-client/OpenSeaClient.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
Labels: size/M

#2944 [C-2205] Wait for user to follow in sign up
  packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
  packages/mobile/src/components/rate-cta-drawer/RateCtaReminder.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/signon/FirstFollows.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/selectors.js
Labels: size/M

#2945 [C-2046] Fix clipped card descenders
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/collection-list/CollectionCardSkeleton.tsx
  packages/mobile/src/components/profile-list/ProfileCardSkeleton.tsx
Labels: size/XS

#2949 Upgrade ios cli
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
Labels: size/XS

#2946 Fix share track url
  packages/mobile/src/utils/routes.tsx
Labels: size/XS

#2938 Send save_of_repost metadata on item save
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/social/collections/actions.ts
  packages/common/src/store/social/tracks/actions.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
Labels: size/M

#2939 [PAY-945][PAY-962][PAY-948][PAY-977] More gated content QA fixes
  packages/mobile/src/assets/images/iconCollectibleCornerTag.svg
  packages/mobile/src/assets/images/iconLockedCornerTag.svg
  packages/mobile/src/assets/images/iconSpecialAccessCornerTag.svg
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileBannerIcon.tsx
  packages/mobile/src/screens/track-screen/PremiumTrackCornerTag.tsx
  packages/stems/src/assets/icons/iconCollectibleCornerTag.svg
  packages/stems/src/assets/icons/iconLockedCornerTag.svg
  packages/stems/src/assets/icons/iconSpecialAccessCornerTag.svg
  packages/stems/src/assets/icons/iconUnlockedCornerTag.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTileCornerTag.tsx
  packages/web/src/components/track/PremiumTrackCornerTag.tsx
  packages/web/src/components/track/TrackBannerIcon.module.css
  packages/web/src/components/track/TrackBannerIcon.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XL

#2936 [PLAT-702] Add repost-of-repost notification
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RepostOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/RepostOfRepostNotification.tsx
Labels: size/L

#2951 Fix get feature enabled types
  packages/common/src/store/storeContext.ts
  packages/web/package-lock.json
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/store/storeContext.ts
Labels: size/M

#2937 [PLAT-733] Add favorite of repost notification
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FavoriteOfRepostNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/web/src/components/notification/Notification/FavoriteOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
Labels: size/L

#2952 Fix track permalink share route
  packages/mobile/src/utils/routes.tsx
Labels: size/XS

#2927 [C-2218] Add repo init script to install nvm and rbenv
  .gitignore
  .nvmrc
  .python-version-dev
  README.md
  package.json
  scripts/postinstall.sh
  scripts/preinstall.sh
Labels: size/M

#2954 [C-2232] Fix android share-to-twitter url
  packages/common/src/utils/index.ts
  packages/common/src/utils/twitter.ts
  packages/mobile/src/components/challenge-rewards-drawer/TwitterShareButton.tsx
  packages/mobile/src/components/share-drawer/utils.ts
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/utils/twitter.ts
  packages/web/src/utils/tweet.ts
Labels: size/M

#2955 Update save and unsave sagas to not append locally saved track unless playing favorites
  packages/web/src/common/store/pages/saved/lineups/sagas.js
Labels: size/M

#2953 [C-2228] Fix link position in Hyperlink
  packages/mobile/src/components/core/Hyperlink.tsx
Labels: size/M

#2941 [PAY-922] Mobile chat drawers and profile screen buttons
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/iconBlockMessages.svg
  packages/mobile/src/components/block-messages/BlockMessages.tsx
  packages/mobile/src/components/block-messages/index.ts
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
  packages/mobile/src/components/chat-actions-drawer/index.ts
  packages/mobile/src/components/profile-actions-drawer/ProfileActionsDrawer.tsx
  packages/mobile/src/components/profile-actions-drawer/index.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/profile-screen/MessageButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#2956 [PAY-980] Treat premium content as deleted in lineups if feature flags disabled
  packages/web/src/common/store/lineup/sagas.js
Labels: size/M

#2957 [C-2194] Disabled the repost and favorite buttons in the NowPlayingDrawer for track owner
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/FavoriteButton.tsx
  packages/mobile/src/components/now-playing-drawer/RepostButton.tsx
Labels: size/L

#2958 [C-2094] Update mount type for the tooltips in the PlayBar
  packages/web/src/components/play-bar/desktop/PlayBar.js
Labels: size/XS

#2960 Fix getFeatureEnabled bug: get from context
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XS

#2933 [PAY-921] Scroll to earliest unread chat
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#2961 Specify pyenv patch version
  .python-version-dev
  scripts/preinstall.sh
Labels: size/XS

#2963 Fix useContext
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XS

#2959 [PAY-981] Add protocol to external collection links
  packages/web/src/components/track/PremiumTrackSection.tsx
Labels: size/S

#2962 Fix button visibilities and other small misc gated related items
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/services/solana-client/SolanaClient.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#2965 [C-2213] Fix save page pagination on web
  packages/web/src/common/store/pages/saved/lineups/sagas.js
  packages/web/src/common/store/pages/saved/sagas.js
Labels: size/M

#2967 [C-2238] Fix tiktok android error
  packages/mobile/src/hooks/useTikTokAuth.ts
Labels: size/S

#2968 [C-1897] Add updated format for long durations on lineup tiles for web and mobile
  packages/common/src/utils/timeUtil.ts
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
Labels: size/M

#2969 v1.5.13
  lerna.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/S

#2913 OTA Updates CI Flow
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/workflows/mobile.yml
  package-lock.json
  packages/mobile/android/app/build.gradle
  packages/mobile/android/fastlane/Fastfile
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/ios/Gemfile.lock
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/fastlane/Fastfile
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
  packages/mobile/src/utils/reportToSentry.ts
  packages/web/package-lock.json
Labels: size/XL

#2971 Fix wait for remote config
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XS

#2972 Fix lint
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XS

#2974 [C-418] Update playlist table column to addedDate
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/XS

#2975 Revert [C-1931] Refactor collection header for private track logic
  packages/web/src/components/collection/desktop/ActionButtons.tsx
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PlayButton.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
  packages/web/src/components/collection/desktop/SmartCollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/ViewerActionButtons.tsx
  packages/web/src/components/collection/desktop/utils.ts
  packages/web/src/components/tooltip/index.ts
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/XXL

#2976 [PAY-1008] - Gated track download by access
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/S

#2978 [PAY-1009] - Fix editing of nft gate after upload
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track-availability-modal/types.ts
Labels: size/XS

#2979 [PAY-996] Fix dropdowns closing immediately in availability UI
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.module.css
Labels: size/XS

#2980 [C-2261] Fix upload form validation
  packages/web/src/pages/upload-page/components/EditPage.js
Labels: size/L

#2981 [PAY-976] Fix NFT picker for artwork
  packages/web/src/components/image-selection/ImageSelectionPopup.js
  packages/web/src/components/image-selection/ImageSelectionPopup.module.css
Labels: size/S

#2966 [PAY-826] Add gated track and connect wallet metrics
  packages/common/src/models/Analytics.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/mobile/src/store/wallet-connect/sagas/signMessageSaga.ts
  packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
  packages/web/src/common/store/pages/token-dashboard/checkIsNewWallet.ts
  packages/web/src/common/store/social/tracks/recordListen.ts
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Labels: size/L

#2977 [C-2551] Fix macos ci step
  .circleci/src/commands/@web-commands.yml
Labels: size/XS

#2983 [PAY-994] Change gated content feature flag names
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/hooks/useIsCollectibleGatedEnabled.ts
  packages/mobile/src/hooks/useIsGatedContentEnabled.ts
  packages/mobile/src/hooks/useIsPremiumContentEnabled.ts
  packages/mobile/src/hooks/useIsSpecialAccessEnabled.ts
  packages/mobile/src/hooks/useIsSpecialAccessGateEnabled.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/fields/TrackVisibilityField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
  packages/web/src/components/remix-settings-modal/RemixSettingsModalTrigger.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantTrackTileCornerTag.tsx
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/PremiumContentLabel.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/Artwork.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/BottomButtons.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#2970 [PLAT-726 C-2246] Add new notification flow
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/store/notifications/reducer.ts
  packages/mobile/src/store/notifications/sagas.ts
  packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
  packages/web/src/common/store/notifications/constants.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/notifications/fetchNotificationsSaga.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/common/store/notifications/playlistUpdates.ts
  packages/web/src/common/store/notifications/refreshNotificationsSaga.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/store/notifications/sagas.ts
Labels: size/XXL

#2985 [PAY-905] Hide embed option for premium tracks
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
Labels: size/S

#2982 [C-2247] Refactor notification state to slice
  packages/common/src/store/notifications/actions.ts
  packages/common/src/store/notifications/index.ts
  packages/common/src/store/notifications/notificationsSlice.ts
  packages/common/src/store/notifications/reducer.ts
  packages/common/src/store/notifications/selectors.ts
  packages/common/src/store/notifications/types.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/mobile/src/store/notifications/sagas.ts
  packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
  packages/web/src/common/store/notifications/errorSagas.ts
  packages/web/src/common/store/notifications/fetchNotificationsSaga.ts
  packages/web/src/common/store/notifications/playlistUpdates.ts
  packages/web/src/common/store/notifications/refreshNotificationsSaga.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/notification/Notification/AnnouncementNotification.tsx
  packages/web/src/components/notification/Notification/components/EntityLink.tsx
  packages/web/src/components/notification/Notification/components/NotificationTile.tsx
  packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
  packages/web/src/components/notification/Notification/components/UserNameLink.tsx
  packages/web/src/components/notification/NotificationPage.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
Labels: size/XL

#2986 [PAY-1014] Fix spacing on special access track screen
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#2988 Wait for remote config
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XS

#2989 Fix mobile web track screen special access spacing
  packages/web/src/components/track/TrackBannerIcon.module.css
Labels: size/XS

#2990 Remove queue removal check to fix end of queue playback
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/M

#2991 [PAY-1019] Fix premium content tags overlap track title
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/S

#2992 Fix lint on CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
Labels: size/S

#2993 Fix lineups with premium content infinite loading for signed out users
  packages/common/src/hooks/usePremiumContent.ts
Labels: size/M

#2996 [PAY-988] [PAY-995] Fix premium content modal issues
  packages/web/src/components/modal-radio/ModalRadioItem.module.css
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.module.css
Labels: size/XS

#3000 [PAY-1020] Refresh collectibles when adding/removing wallets
  packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Labels: size/S

#3002 Remove DMs button temporarily
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/XS

#3003 LINT
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/XS

#3008 Fix general gated content flag on mobile
  packages/mobile/src/hooks/useIsGatedContentEnabled.ts
Labels: size/XS

#3004 [C-2273] Fix gigantic audio coin
  packages/mobile/src/components/audio-rewards/IconAudioBadge.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
Labels: size/L

#3011 [C-1822] Fix cropped artist genre buttons
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/suggested-follows/ArtistCategoryButton.tsx
  packages/mobile/src/components/suggested-follows/SelectArtistCategoryButtons.tsx
Labels: size/L

#3012 Update lineup tile time util func to hide hour text when under 1 hour
  packages/common/src/utils/timeUtil.ts
Labels: size/XS

#2987 [C-2121] Offline downloads settings
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/Horizontal-Logo-Full-Color-Deprecated.png
  packages/mobile/src/assets/images/Horizontal-Logo-Full-Color.png
  packages/mobile/src/assets/images/iconCloudDownload.svg
  packages/mobile/src/assets/images/iconNotificationOn.svg
  packages/mobile/src/assets/images/iconVolume2.svg
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/drawers/RemoveAllDownloadsDrawer.tsx
  packages/mobile/src/components/drawers/index.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/CastSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/DownloadAllFavoritesRow.tsx
  packages/mobile/src/screens/settings-screen/DownloadNetworkPreferenceRow.tsx
  packages/mobile/src/screens/settings-screen/DownloadSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/RemoveAllDownloadsRow.tsx
  packages/mobile/src/screens/settings-screen/SettingRowLabel.tsx
  packages/mobile/src/screens/settings-screen/SettingsRowDescription.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/index.ts
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/offlineQueueSagas.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/watchNetworkType.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/staleTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/utils/shouldCancelJob.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
  packages/mobile/src/utils/reachability.ts
  packages/web/src/assets/img/Horizontal-Logo-Full-Color-Deprecated.png
  packages/web/src/assets/img/publicSite/Horizontal-Logo-Full-Color-Deprecated.png
  packages/web/src/assets/img/publicSite/Horizontal-Logo-Full-Color-Deprecated@2x.png
  packages/web/src/components/public-site/Footer.tsx
  packages/web/src/components/public-site/NavBanner.tsx
  packages/web/src/components/public-site/NavOverlay.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/sign-on/components/mobile/InitialPage.tsx
Labels: size/XL

#3013 Abort jobs on clearOfflineDownloads
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/staleTrackWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/utils/shouldAbortJob.ts
Labels: size/M

#2998 [C-2269] Connect save/repost_of_repost notification
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/notification/Notification/FavoriteOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/RepostOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/components/OthersLink.tsx
  packages/web/src/components/notification/NotificationPage.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/L

#3014 Fix fetchNotifications fallback
  packages/web/src/common/store/notifications/fetchNotifications.ts
Labels: size/XS

#3015 Read subscribers from bulk endpoint
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/S

#3021 [C-2280] Fix error when playing queue with private track
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/M

#3001 Remove upgradeToCreator
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/upload/actions.ts
  packages/web/src/common/store/cache/users/sagas.d.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
  packages/web/src/common/store/upload/errorSagas.ts
Labels: size/L

#3016 Re-add chat features to profile screen
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/profile-actions-drawer/ProfileActionsDrawer.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#3022 [C-2137] Fix mobile status bar theme
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/root-screen/StatusBar.tsx
  packages/mobile/src/screens/splash-screen/SplashScreen.tsx
  packages/mobile/src/store/theme/sagas.ts
  packages/mobile/src/utils/theme.ts
Labels: size/L

#3024 [C-2288] Fix auth error state check
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
Labels: size/XS

#3023 Add custom mandatory update UI for mandatory OTA updates C-2258
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/useSyncCodepush.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/update-required-screen/NewVersionPrompt.tsx
  packages/mobile/src/screens/update-required-screen/RestartRequiredScreen.tsx
  packages/mobile/src/screens/update-required-screen/UpdateRequiredScreen.tsx
  packages/mobile/src/screens/update-required-screen/index.ts
Labels: size/L

#3028 [C-2301] Update dapp-store release, Improve docs
  packages/mobile/android/app/build.gradle
  packages/mobile/dapp-store/.asset-manifest.json
  packages/mobile/dapp-store/.gitignore
  packages/mobile/dapp-store/.nvmrc
  packages/mobile/dapp-store/README.md
  packages/mobile/dapp-store/config.yaml
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/XL

#2994 [C-2220] Upgrade push-notification library
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.java
  packages/mobile/android/settings.gradle
  packages/mobile/ios/AudiusReactNative/AppDelegate.h
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/notifications.ts
Labels: size/L

#3029 Upgrade mobile app versions for release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3026 [C-583] Fix section/flat list generics
  packages/common/src/models/Collection.ts
  packages/common/src/models/Search.ts
  packages/common/src/models/Track.ts
  packages/common/src/models/User.ts
  packages/common/src/models/index.ts
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/SectionList.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/search-screen/SearchResults.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/mobile/src/store/search/types.ts
  packages/mobile/src/types/react.ts
  packages/web/src/common/store/search-bar/types.ts
Labels: size/XL

#3031 Fix native code changes CI comment C-2305
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#3019 Add playback position logic on web for podcasts
  packages/common/src/services/audio-player.ts
  packages/common/src/store/index.ts
  packages/common/src/store/playback-position/index.ts
  packages/common/src/store/playback-position/sagas.ts
  packages/common/src/store/playback-position/selectors.ts
  packages/common/src/store/playback-position/slice.ts
  packages/common/src/store/playback-position/types.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/web/src/assets/img/iconRepeatOff.svg
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTileProgressInfo.tsx
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/store/sagas.ts
Labels: size/XL

#3032 Fix collapsible list typo
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/SectionList.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
Labels: size/S

#3027 [PAY-940] Save permissions in chat permission dialog
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.module.css
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
Labels: size/M

#3036 Fix prod ACDC contract address
  packages/mobile/.env.prod
  packages/web/.env/.env.prod
Labels: size/XS

#3034 [PAY-926] DMs: Desktop Inbox Settings tile on Settings Page
  packages/stems/src/assets/icons/iconMood.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/pages/settings-page/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsCard.module.css
  packages/web/src/pages/settings-page/components/desktop/SettingsCard.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.module.css
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
Labels: size/XL

#3038 Add nvm install step
  .circleci/src/commands/@web-commands.yml
Labels: size/XS

#3039 Hard code entity manager prod address for now
  packages/mobile/src/services/audius-backend-instance.ts
Labels: size/XS

#3040 Revert "Hard code entity manager prod address for now"
  packages/mobile/src/services/audius-backend-instance.ts
Labels: size/XS

#3033 [C-2311] Fix notification timestamp logic
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/store/notifications/types.ts
  packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/notifications/fetchNotificationsSaga.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/common/store/notifications/refreshNotificationsSaga.ts
  packages/web/src/components/notification/Notification/FavoriteOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/RepostOfRepostNotification.tsx
Labels: size/L

#3030 [C-2156] Refactor search-screen ui
  packages/mobile/src/hooks/useDebouncedCallback.ts
  packages/mobile/src/screens/search-screen/EmptySearch.tsx
  packages/mobile/src/screens/search-screen/Fade.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/mobile/src/screens/search-screen/SearchHistory/ClearSearchHistoryListItem.tsx
  packages/mobile/src/screens/search-screen/SearchHistory/SearchHistory.tsx
  packages/mobile/src/screens/search-screen/SearchHistory/SearchHistoryListItem.tsx
  packages/mobile/src/screens/search-screen/SearchHistory/index.ts
  packages/mobile/src/screens/search-screen/SearchResults.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SearchResult.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SearchResults.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SearchSectionHeader.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SeeMoreResultsButton.tsx
  packages/mobile/src/screens/search-screen/SearchResults/index.ts
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
  packages/mobile/src/screens/search-screen/content/SearchItem.tsx
  packages/mobile/src/screens/search-screen/content/SearchSectionHeader.tsx
  packages/mobile/src/store/search/searchSlice.ts
  packages/mobile/src/store/search/selectors.ts
  packages/mobile/src/store/store.ts
  packages/web/src/common/store/search-bar/reducer.ts
  packages/web/src/common/store/search-bar/selectors.ts
  packages/web/src/common/store/search-bar/types.ts
  packages/web/src/store/types.ts
Labels: size/XL

#3018 [C-2276] Fix upload track store updates
  packages/common/src/store/pages/profile/selectors.ts
  packages/common/src/store/upload/actions.ts
  packages/common/src/store/upload/reducer.ts
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/watchUploadTracksSaga.ts
  packages/web/src/common/store/upload/sagas.js
Labels: size/M

#3041 Fix chat middleware
  packages/common/src/store/pages/chat/middleware.ts
Labels: size/XS

#3035 [PAY-997][PAY-1012][PAY-1050][PAY-1053][PAY-1066] - Miscellaneous QA fixes
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileBannerIcon.tsx
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/components/RadioButton/RadioButton.module.css
  packages/web/package.json
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.module.css
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track/EditTrackModal.js
  packages/web/src/components/track/TrackBannerIcon.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/L

#3046 Confirm if block passed
  packages/web/src/common/store/confirmer/sagas.ts
Labels: size/XS

#3047 Fix confirmer lint
  packages/web/src/common/store/confirmer/sagas.ts
Labels: size/XS

#3048 Use wallet instead of ERC wallet
  packages/web/src/common/store/tipping/sagas.ts
Labels: size/XS

#3053 [C-2266] Disabled the PlayBar favorite button for the track owner
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
Labels: size/XS

#3054 [C-2286] Update placement of the repeat single track check from play saga to next saga
  packages/web/src/common/store/queue/sagas.ts
Labels: size/M

#3058 [C-2263 C-2283] Add setCurrentUser profile action and call when we focus a profile screen
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/M

#3042 [PAY-1061] - Only show confetting when unlocking from how to unlock section
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/store/social/users/actions.ts
  packages/common/src/store/tipping/slice.ts
  packages/common/src/store/tipping/types.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/components/track/PremiumTrackSection.tsx
Labels: size/M

#3043 Update dapp-store release and docs
  packages/mobile/dapp-store/.asset-manifest.json
  packages/mobile/dapp-store/README.md
  packages/mobile/dapp-store/config.yaml
Labels: size/XS

#3055 [C-429] Fix edit-profile screen scroll
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
Labels: size/S

#3060 [C-2329] Fix notification navigation
  packages/common/src/models/Analytics.ts
  packages/common/src/services/opensea-client/OpenSeaClient.ts
  packages/common/src/services/solana-client/SolanaClient.ts
  packages/common/src/store/collectibles/selectors.ts
  packages/common/src/store/collectibles/slice.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/store/tipping/selectors.ts
  packages/common/src/store/tipping/slice.ts
  packages/common/src/store/tipping/types.ts
  packages/mobile/src/notifications.ts
  packages/web/src/common/store/tipping/sagas.ts
Labels: size/L

#3044 [PAY-1070] Update TabSlider/SegmentedControl slider size on resize
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/components/SegmentedControl/SegmentedControl.module.css
  packages/stems/src/components/SegmentedControl/SegmentedControl.stories.tsx
  packages/stems/src/components/SegmentedControl/SegmentedControl.tsx
  packages/stems/src/components/SegmentedControl/types.ts
  packages/web/src/components/data-entry/TabSlider.js
  packages/web/src/components/data-entry/TabSlider.module.css
  packages/web/src/components/embed-modal/EmbedModal.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.js
  packages/web/src/components/image-selection/ImageSelectionPopup.module.css
  packages/web/src/pages/audio-rewards-page/components/modals/TrendingRewards.tsx
  packages/web/src/pages/settings-page/components/desktop/NotificationSettings.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/NotificationsSettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
  packages/web/src/pages/upload-page/components/TracksPreview.js
Labels: size/L

#3051 Add playback position logic for mobile
  packages/common/src/store/player/sagas.ts
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/mobile/src/assets/images/iconRepeatOff.svg
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/details-tile/DetailsProgressInfo.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/styles.ts
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/mobile/src/components/scrubber/usePosition.ts
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/services/audio-player/NativeMobileAudio.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PlayPauseButton.tsx
Labels: size/XL

#3062 Remove random line
  packages/web/src/common/store/tipping/sagas.ts
Labels: size/XS

#3057 [PAY-904] - Add gated content upload prompt
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/iconRocket.svg
  packages/mobile/src/components/gated-content-upload-prompt-drawer/GatedContentUploadPromptDrawer.tsx
  packages/mobile/src/components/gated-content-upload-prompt-drawer/index.ts
  packages/mobile/src/hooks/useOneTimeDrawer.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/types.ts
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/gated-content-upload-prompt-modal/GatedContentUploadPromptModal.module.css
  packages/web/src/components/gated-content-upload-prompt-modal/GatedContentUploadPromptModal.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
Labels: size/XL

#3064 [C-2297] Add fallback flag to podcast feature
  packages/common/src/hooks/useFeatureFlag.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/remote-config.ts
  packages/common/src/store/playback-position/sagas.ts
  packages/common/src/store/player/sagas.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/services/remote-config/getFeatureEnabled.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.js
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/services/remote-config/featureFlagHelpers.ts
Labels: size/L

#3065 [C-2339] Update podcast control updates to also work for audiobooks
  packages/common/src/store/playback-position/sagas.ts
  packages/common/src/store/player/sagas.ts
  packages/common/src/utils/timeUtil.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/PlayBarButton.module.css
  packages/web/src/components/play-bar/desktop/PlayBar.js
  packages/web/src/components/play-bar/next-button/NextButtonProvider.tsx
  packages/web/src/components/play-bar/previous-button/PreviousButtonProvider.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/L

#3059 [PAY-1074][PAY-1075][PAY-1076][PAY-1080] - Update availability settings states + more QA fixes
  packages/mobile/src/components/core/RadioButton.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/HiddenAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/PublicAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/index.ts
  packages/mobile/src/screens/edit-track-screen/components/types.ts
  packages/mobile/src/screens/edit-track-screen/screens/ListSelectionScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/TrackList.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/L

#3052 [C-2316] Add remote config for all oauth verification
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
  packages/web/src/pages/sign-on/components/CompleteProfileWithSocial.tsx
  packages/web/src/pages/sign-on/components/ProfilePage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
Labels: size/L

#3056 Fix heavy rotation playlist on client
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/common/store/smart-collection/sagas.ts
Labels: size/M

#3069 Fix web-dist CI steps
  .circleci/src/commands/@web-commands.yml
  packages/web/src/components/track/GiantTrackTile.js
Labels: size/XS

#3071 [C-2345] Move PlaybackRate drawer to common drawers map
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/XS

#3070 [PAY-1056] - More gated content updates and fixes
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/types.ts
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/mobile/src/screens/edit-track-screen/types.ts
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.module.css
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
Labels: size/L

#3067 [PAY-1072] Change "Download App" icon on Settings Page
  packages/stems/src/assets/icons/iconDesktop.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/S

#3072 Update @jup-ag/core to 2.0.0-beta.9
  packages/mobile/ios/Podfile.lock
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3068 [PAY-927] DMs: Empty messages state
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/SendMessagePrompt.module.css
  packages/web/src/pages/chat-page/components/SendMessagePrompt.tsx
Labels: size/M

#3073 [C-2325] Fix playlist table date-added column
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/S

#3074 [C-2349] Default download on wifi only to false
  packages/mobile/src/screens/settings-screen/DownloadNetworkPreferenceRow.tsx
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/watchNetworkType.ts
  packages/mobile/src/store/offline-downloads/sagas/utils/shouldCancelJob.ts
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/store/offline-downloads/slice.ts
Labels: size/M

#3075 [C-2344] Update the web playbar scrubber to respect the playback speed of podcasts
  packages/stems/src/components/Scrubber/Scrubber.tsx
  packages/stems/src/components/Scrubber/Slider.tsx
  packages/stems/src/components/Scrubber/hooks.ts
  packages/stems/src/components/Scrubber/types.ts
  packages/web/src/components/play-bar/desktop/PlayBar.js
Labels: size/M

#3077 Clean up NPM package lock
  packages/mobile/ios/Podfile.lock
  packages/web/package-lock.json
Labels: size/XS

#3078 Update SDK to 2.0.3-beta.0
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3080 Fix broken Main build due to typeerror
  packages/common/src/store/pages/chat/selectors.ts
  packages/web/package-lock.json
  packages/web/src/components/now-playing/NowPlaying.tsx
Labels: size/S

#3082 Remove ports for local dev
  packages/mobile/.env.dev
  packages/web/.env/.env.dev
Labels: size/S

#3084 Fix prod build timeout
  .circleci/src/commands/@web-commands.yml
Labels: size/XS

#3079 [C-2320] Fix profile socials alignment
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileTierTile.tsx
Labels: size/M

#3076 Fix upload and repost probers tests and lint
  .circleci/config.yml
  .circleci/src/jobs/@web-jobs.yml
  packages/probers/.eslintrc.js
  packages/probers/.eslintrc.json
  packages/probers/.gitignore
  packages/probers/cypress/e2e/playTrack.cy.ts
  packages/probers/cypress/e2e/repostTrack.cy.ts
  packages/probers/cypress/e2e/signIn.cy.ts
  packages/probers/cypress/e2e/signOut.cy.ts
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/probers/cypress/e2e/smoke/album.cy.ts
  packages/probers/cypress/e2e/smoke/feed.cy.ts
  packages/probers/cypress/e2e/smoke/playlist.cy.ts
  packages/probers/cypress/e2e/smoke/remix.cy.ts
  packages/probers/cypress/e2e/smoke/remixes.cy.ts
  packages/probers/cypress/e2e/smoke/track.cy.ts
  packages/probers/cypress/e2e/smoke/trending.cy.ts
  packages/probers/cypress/e2e/smoke/upload.cy.ts
  packages/probers/cypress/e2e/uploadTrack.cy.ts
  packages/probers/cypress/fixtures/track.json
  packages/probers/cypress/plugins/index.ts
  packages/probers/cypress/support/commands.ts
  packages/probers/cypress/support/e2e.ts
  packages/probers/package-lock.json
  packages/probers/package.json
Labels: size/XL

#3085 [PAY-1000][PAY-1084][PAY-1096][PAY-1097][PAY-1098] - More gated content fixes
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track/EditTrackModal.js
  packages/web/src/components/track/PremiumTrackSection.tsx
Labels: size/M

#3086 DMs: Fix broken typecheck on main
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/S

#3020 [PAY-907] Mobile chat reactions
  packages/mobile/src/app/App.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/EmptyChatMessages.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Labels: size/XL

#3083 [PAY-923] DMs: Add desktop entrypoints
  packages/common/src/store/pages/chat/selectors.ts
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/components/Popup/types.ts
  packages/stems/src/components/PopupMenu/PopupMenu.tsx
  packages/stems/src/components/PopupMenu/types.tsx
  packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.tsx
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/components/stat-banner/StatBanner.js
  packages/web/src/components/stat-banner/StatBanner.module.css
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/utils/route.ts
Labels: size/XL

#3088 [C-2369] Fix issue where notification poll can break app on signout
  packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
Labels: size/XS

#3087 Use chat.messagesStatus instead of selector
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3091 Fix upload prompt modal learn more url
  packages/mobile/src/components/gated-content-upload-prompt-drawer/GatedContentUploadPromptDrawer.tsx
  packages/web/src/components/gated-content-upload-prompt-modal/GatedContentUploadPromptModal.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#3093 Fix visible collectibles for upload popup
  packages/web/src/components/image-selection/ImageSelectionPopup.js
Labels: size/XS

#3090 [C-2337] Remove reachability mobile web
  packages/common/src/store/account/selectors.ts
  packages/web/scripts/workers-site/index.js
  packages/web/src/app.tsx
  packages/web/src/components/network-connectivity/NetworkConnectivityMonitor.tsx
  packages/web/src/components/notification/NotificationPage.tsx
  packages/web/src/components/reachability-bar/ReachabilityBar.tsx
  packages/web/src/components/reachability-bar/components/ReachabilityBarContainer.module.css
  packages/web/src/components/reachability-bar/components/ReachabilityBarContainer.tsx
  packages/web/src/pages/App.d.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/App.test.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/root.tsx
Labels: size/XL

#3099 [C-2378] Add upload v2 feature flag
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/S

#3101 [C-2365] Update play buttons on web and mobile to show resume when track is current
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/web/src/components/track/PlayPauseButton.tsx
Labels: size/S

#3100 [PAY-1063][PAY-1085][PAY-1086] Update UI for inaccessible gated tracks from favorites and history pages
  packages/common/src/hooks/usePremiumContent.ts
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/table/components/OverflowMenuButton.tsx
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/TrackList.tsx
  packages/web/src/components/track/mobile/TrackListItem.module.css
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/components/tracks-table/TracksTable.module.css
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/L

#3095 [C-2275] Fix android drawer offsets
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/constants.ts
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/store/mobileUi/sagas.ts
  packages/mobile/src/store/mobileUi/selectors.ts
  packages/mobile/src/store/mobileUi/slice.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
Labels: size/M

#3103 [C-2366] Improve web notification selection performance
  packages/web/src/components/notification/Notification/Notification.tsx
Labels: size/M

#3094 [C-2248, C-2373] Use playlistUpdates, remove legacyNotifications
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/notifications/actions.ts
  packages/common/src/store/notifications/index.ts
  packages/common/src/store/notifications/notificationsSelectors.ts
  packages/common/src/store/notifications/reducer.ts
  packages/common/src/store/notifications/types.ts
  packages/common/src/store/playlist-updates/playlistUpdatesSagas.ts
  packages/common/src/store/playlist-updates/playlistUpdatesSelectors.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/user-list/notifications/selectors.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/notifications/playlistUpdates.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/playlist-updates/playlistUpdatesPollingDaemon.ts
  packages/web/src/common/store/playlist-updates/sagas.ts
  packages/web/src/common/store/playlist-updates/updatedPlaylistViewedSaga.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/notification/Notification/AnnouncementNotification.tsx
  packages/web/src/components/notification/Notification/components/EntityLink.tsx
  packages/web/src/components/notification/Notification/components/NotificationTile.tsx
  packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
  packages/web/src/components/notification/Notification/components/UserNameLink.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/store/application/ui/notifications/notificationsUISelectors.ts
  packages/web/src/store/application/ui/notifications/notificationsUISlice.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
Labels: size/XL

#3102 Fix "Pick some for me" button on android
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/components/suggested-follows/PickArtistsForMeButton.tsx
Labels: size/XS

#3097 [C-2353, C-2358] Update playback position tracking for web and mobile
  packages/common/src/store/playback-position/sagas.ts
  packages/common/src/store/player/sagas.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/src/common/store/player/sagas.ts
Labels: size/L

#3104 [C-2382] Update dapp-store cli, short_description length
  packages/mobile/dapp-store/README.md
  packages/mobile/dapp-store/config.yaml
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/S

#3113 Check if messagesStatus undefined in ChatScreen
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3110 [C-2386] Fix notification button not toggling panel
  packages/web/src/components/nav/desktop/NavColumn.tsx
Labels: size/S

#3114 Always include user signature for stream
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/src/common/store/player/sagas.ts
Labels: size/S

#3115 [PAY-1083] - Only allow prompt modal when single track is being uploaded
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/pages/upload-page/components/EditPage.js
Labels: size/S

#3109 [PLAT-695] Add trending notifications to valid_types
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
Labels: size/L
