Repository AudiusProject/audius-client, pull requests merged in 2023-05, with the labels that each got.

#3291 Fix devnet in wallet authorize for saga phone
  packages/mobile/src/screens/wallet-connect/components/useSolanaPhoneAuthorization.ts
Labels: size/XS

#3292 Add EULA
  packages/stems/package-lock.json
  packages/stems/package.json
  packages/stems/src/components/MarkdownViewer/MarkdownViewer.module.css
  packages/stems/src/components/MarkdownViewer/MarkdownViewer.stories.tsx
  packages/stems/src/components/MarkdownViewer/MarkdownViewer.tsx
  packages/stems/src/components/MarkdownViewer/index.ts
  packages/stems/src/index.tsx
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/ai-attribution-settings-modal/AiAttributionSettingsModal.module.css
  packages/web/src/components/ai-attribution-settings-modal/AiAttributionSettingsModal.tsx
  packages/web/src/components/notification/Notification/AnnouncementNotification.module.css
  packages/web/src/components/notification/Notification/AnnouncementNotification.tsx
  packages/web/src/components/notification/NotificationModal.module.css
  packages/web/src/components/notification/NotificationModal.tsx
  packages/web/src/pages/announcement-page/AnnoucementPage.tsx
  packages/web/src/pages/announcement-page/AnnouncementPage.module.css
Labels: size/L

#3287 [C-2543, C-2544] Initial updates to mobile playlist management
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/cache/collections/actions.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/sagas.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/selectors.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/slice.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/types.ts
  packages/common/src/store/ui/toast/slice.ts
  packages/common/src/store/ui/toast/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/iconPencil.svg
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/publish-playlist-drawer/PublishPlaylistDrawer.tsx
  packages/mobile/src/components/publish-playlist-drawer/index.ts
  packages/mobile/src/components/toasts/Toast.tsx
  packages/mobile/src/hooks/useManualToast.ts
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/store/sagas.ts
Labels: size/L

#3289 [CON-674] Make track edit use v2 flow for storage v2 tracks
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/S

#3299 Fix ai attrib upload
  packages/common/src/schemas/index.ts
Labels: size/XS

#3300 Redirect if not allowed ai
  packages/web/src/pages/ai-attributed-tracks-page/AiPageProvider.tsx
Labels: size/XS

#3298 [PAY-1178] Fix new messages on new/unloaded chats
  packages/common/src/store/pages/chat/slice.ts
Labels: size/S

#3301 Fix taste maker copy
  packages/mobile/src/screens/notifications-screen/Notifications/TastemakerNotification.tsx
  packages/web/src/components/notification/Notification/TastemakerNotification.tsx
Labels: size/XS

#3303 [C-2542] Update delete playlist confirmation drawer to conform to new designs
  packages/mobile/src/assets/images/iconTrash.svg
  packages/mobile/src/components/delete-playlist-confirmation-drawer/DeletePlaylistConfirmationDrawer.tsx
Labels: size/L

#3302 Fix eager fetch
  packages/common/src/services/audius-backend/eagerLoadUtils.ts
  packages/common/src/utils/stringUtils.ts
Labels: size/M

#3297 [PAY-901] hotfix: TransactionDetailsModal now expects wei amounts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XS

#3294 [C-2282] Show tracks tab on own profile if all tracks hidden
  packages/common/src/store/account/index.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/account/selectors.ts
  packages/common/src/store/account/slice.ts
  packages/common/src/store/sagas.ts
  packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
  packages/mobile/src/store/account/sagas.ts
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/store/account/sagas.ts
Labels: size/L

#3306 Add search multimap
  packages/common/src/services/audius-api-client/helper.ts
  packages/web/src/common/store/pages/search-page/sagas.js
  packages/web/src/common/store/search-ai-bar/sagas.ts
  packages/web/src/common/store/search-bar/sagas.ts
Labels: size/L

#3285 Pass metadata to libs for addTracksToChainAndCnode
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/upload/sagas.js
Labels: size/S

#3304 [PLAT-904] Fix duplicate notifications
  packages/web/src/common/store/notifications/fetchNotifications.ts
Labels: size/XS

#3308 Fix index issue with constructUrl
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/XS

#3309 [PLAT-863] Fix reaction endpoint when sdk-v2
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorInstance.ts
Labels: size/XS

#3310 Rename sdk_v2 to sdk_discovery_node_selector
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#3264 Notification settings improvements
  packages/common/src/store/pages/settings/actions.ts
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/notifications.ts
  packages/mobile/src/store/settings/sagas.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/settings-page/store/sagas.ts
Labels: size/L

#3305 Debounce reaction for longer on web
  packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
Labels: size/XS

#3312 Fix stylelint
  packages/web/src/components/ai-attribution-modal/SearchBarResult.module.css
  packages/web/src/components/ai-attribution-settings-modal/AiAttributionSettingsModal.module.css
  packages/web/src/components/notification/Notification/AnnouncementNotification.module.css
  packages/web/src/components/track/AiTrackSection.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
Labels: size/S

#3318 [PAY-901] hotfix: Use SPL amounts for BuyAudio flow
  packages/common/src/utils/wallet.ts
  packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#3307 Remove dependency on `download.cid` for determining download eligibility
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/services/track-download/TrackDownload.ts
  packages/common/src/store/cache/tracks/actions.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/services/track-download.ts
Labels: size/L

#3319 I broke main and I'm sorry
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XS

#3316 [C-2560] Improve checking for new notifs
  packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
Labels: size/S

#3320 Fix internal/external audius urls
  packages/common/src/utils/urlUtils.ts
Labels: size/XS

#3321 Fix search-results saga error due to yield*
  packages/web/src/common/store/pages/search-page/sagas.js
Labels: size/XS

#3322 [C-2563] Fix demo build
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#3290 [PAY-1199] Mobile inbox settings functional
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useSetInboxPermissions.ts
  packages/mobile/src/screens/settings-screen/InboxSettingsScreen.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
Labels: size/L

#3324 Update fetchPermission condition
  packages/web/src/common/store/profile/sagas.js
Labels: size/XS

#3326 DMs: Fix store bug sending messages
  packages/common/src/store/pages/chat/slice.ts
Labels: size/XS

#3327 [C-2566] Prevent player error on skip
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/XS

#3005 Remove identity subscriptions reads/writes
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/unfollow-confirmation-modal/UnfollowConfirmationModal.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/L

#3323 [PAY-1207] Use Followers instead of Mutuals on compose chat modal
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Labels: size/S

#3288 Mobile chat housekeeping
  packages/common/src/store/pages/chat/selectors.ts
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatUser.tsx
  packages/mobile/src/screens/chat-screen/index.ts
Labels: size/L

#3328 [HOTFIX] Fix saga download error
  packages/web/src/services/track-download.ts
Labels: size/XS

#3329 DMs: Fix unread indicator not going away
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/S

#3332 Fix keyboard occluding textinput in mobile chat screen
  packages/mobile/src/components/core/KeyboardAvoidingView.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3331 DMs: Don't increment unread if it's your own message
  packages/common/src/store/pages/chat/middleware.ts
Labels: size/XS

#3333 Dismiss keyboard on mobile chat screen top right press
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3335 HOTFIX track notification navigation
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/S

#3330 [C-2568] Silence player/error when audio is loaded
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/S

#3338 Prevent fetchBlockees/blockers when chat disabled
  packages/web/src/common/store/account/sagas.js
Labels: size/XS

#3336 [C-2451] Fix infinite buffering in audio player
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/M

#3339 Upgrade sdk to beta.16, update install script
  package.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-sdk.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/audius-sdk/audiusSdk.ts
Labels: size/S

#3311 Feature flag gates to send metadata directly through chain
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/L

#3341 [C-2519] Ignore TOS deeplink
  packages/web/public/.well-known/apple-app-site-association
  packages/web/public/.well-known/apple-app-site-association-stage
Labels: size/S

#3343 [C-2577] Fix mobile web social buttons by removing pull-to-refresh
  packages/web/src/components/pull-to-refresh/PullToRefresh.module.css
  packages/web/src/components/pull-to-refresh/PullToRefresh.tsx
  packages/web/src/components/pull-to-refresh/hooks.ts
  packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
Labels: size/L

#3314 [CON-676] Support storage v2 playlists+albums, and bump libs version to 2.0.3-beta.17
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/upload/sagas.js
Labels: size/L

#3345 Update sdk to 2.0.3-beta.18
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3344 [C-2565] Improve mobile app-redirect-popover experience
  packages/web/src/app.tsx
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
  packages/web/src/pages/App.d.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/App.test.tsx
  packages/web/src/pages/PublicSite.tsx
  packages/web/src/pages/landing-page/LandingPage.tsx
  packages/web/src/root.tsx
Labels: size/M

#3347 [QA-488] Fix share overflow menu drawer
  packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
  packages/web/src/components/menu/UserMenu.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
Labels: size/M

#3350 [PAY-1208][PAY-1216] Mobile chats unread message count
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
Labels: size/M

#3284 [PAY-1148] Mobile chat user search row disabled when not permitted
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/ui/search-users-modal/sagas.ts
  packages/common/src/store/ui/search-users-modal/slice.ts
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/L

#3348 [C-2579][C-2580] audius-query
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/api/AudiusQueryContext.ts
  packages/common/src/api/createApi.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/api/schema.ts
  packages/common/src/api/track.ts
  packages/common/src/api/types.ts
  packages/common/src/api/user.ts
  packages/common/src/api/utils.ts
  packages/common/src/index.ts
  packages/common/src/store/cache/actions.ts
  packages/common/src/store/cache/collections/reducer.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/common/src/store/cache/users/reducer.ts
  packages/common/src/store/reducers.ts
  packages/mobile/src/app/App.tsx
  packages/web/src/app.tsx
  packages/web/src/components/related-artists/RelatedArtists.tsx
Labels: size/XXL

#3346 [PAY-1217] Mobile DMs new chat tails, fix shadow
  packages/mobile/src/assets/images/ChatTail.svg
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Labels: size/L

#3340 [PAY-1221] Fix message hasTail recalculations when server resends messages
  packages/common/src/store/pages/chat/slice.ts
Labels: size/M

#3351 Clear playback rate on sign out
  packages/common/src/services/local-storage/LocalStorage.ts
  packages/web/src/store/sign-out/signOut.ts
Labels: size/XS

#3342 [PAY-1219] Fix mobile chat reactions popup message getting cut off
  packages/mobile/src/components/core/KeyboardAvoidingView.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#3355 [PAY-1196] Mobile dms search users empty state
  packages/mobile/src/assets/images/leftPointingMagnifyingGlass.png
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/M

#3356 [PAY-1215] Fix create new message crash
  packages/common/src/store/pages/chat/selectors.ts
Labels: size/XS

#3357 [C-2550] Left-nav fixes and improvements
  packages/web/src/components/nav/desktop/LeftNav.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/EditNavItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/EmptyLibraryNavLink.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/ExplorePlaylistNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibraryNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.tsx
  packages/web/src/components/update-dot/UpdateDot.module.css
  packages/web/src/components/update-dot/UpdateDot.tsx
Labels: size/L

#3354 DMs: Use the optimistic unread count if applicable
  packages/common/src/store/pages/chat/slice.ts
Labels: size/XS

#3325 Get call to action for chat permissions
  packages/common/src/hooks/useSetInboxPermissions.ts
  packages/common/src/store/pages/chat/index.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/types.ts
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/L

#3337 [PAY-1202] Refactor saved collections fetching
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useSavedCollections.ts
  packages/common/src/store/index.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/saved-collections/index.ts
  packages/common/src/store/saved-collections/selectors.ts
  packages/common/src/store/saved-collections/slice.ts
  packages/common/src/store/saved-collections/types.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/common/store/pages/explore/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/saved-collections/sagas.ts
  packages/web/src/components/actions-tab/ActionsTab.js
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/components/card/desktop/CollectionArtCard.tsx
  packages/web/src/components/card/desktop/UserArtCard.tsx
  packages/web/src/hooks/useGoToRoute.ts
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/saved-page/components/utils.ts
  packages/web/src/store/sagas.ts
Labels: size/XL

#3363 Fix invite reward claimable state on mobile
  packages/mobile/src/screens/audio-screen/Panel.tsx
Labels: size/XS

#3365 [C-2603] Fix readonly object error in audius-query reducer
  packages/common/src/api/createApi.ts
Labels: size/S

#3366 [PAY-941] Fix "1 new messages" unread tag (web)
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/S

#3359 DMs: Update copy, scroll inbox-settings modal
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
Labels: size/S

#3358 DMs: Fix click handler in search user list for users you can't chat
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Labels: size/XS

#3368 [PAY-1183] Make clicking ChatUser handle/displayname lead to profile
  packages/web/src/pages/chat-page/components/ChatUser.tsx
Labels: size/M

#3362 Fix debounce on notif reaction
  packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
Labels: size/XS

#3364 [C-2602] Improve playlist library layout
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/utils/ensureLoggedIn.ts
  packages/web/src/common/utils/requiresAccount.ts
  packages/web/src/components/banner/CTABanner.tsx
  packages/web/src/components/nav/desktop/GroupHeader.module.css
  packages/web/src/components/nav/desktop/GroupHeader.tsx
  packages/web/src/components/nav/desktop/LeftNav.module.css
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/pill/Pill.js
  packages/web/src/components/pill/Pill.tsx
Labels: size/L

#3367 [C-2596] Add disabled option to audius-query hooks
  packages/common/src/api/createApi.ts
  packages/common/src/api/types.ts
Labels: size/S

#3372 [PAY-1139] Throttle calls to fetchMessages on web scroll
  packages/common/src/utils/chatUtils.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/M

#3370 [PAY-1151] Handle chat reactions near top of screen on mobile
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
  packages/mobile/src/screens/chat-screen/constants.ts
Labels: size/S

#3352 [PAY-1032][PAY-892] Mobile DMs unread indicator, prefetch chats
  packages/common/package.json
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/package.json
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/web/package.json
Labels: size/L

#3379 [C-2614] Fix download stems mobile web
  packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
Labels: size/XS

#3380 Fix lint
  packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
Labels: size/XS

#3381 Clean up artist_pick_track_id in APIUser
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
Labels: size/S

#3382 Hotfix: Fix stems downloads on mobile web
  packages/web/patches/react-lottie+1.2.3.patch
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/S

#3375 [C-2607] Pagination wrapper hooks for audius-query
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/api/AudiusQueryContext.ts
  packages/common/src/api/createApi.ts
  packages/common/src/api/hooks/index.ts
  packages/common/src/api/hooks/usePaginatedQuery.ts
  packages/common/src/api/index.ts
  packages/common/src/api/types.ts
  packages/mobile/src/app/App.tsx
  packages/web/src/app.tsx
Labels: size/L

#3369 [PAY-1145] DMs: Add InboxUnavailableModal
  packages/common/src/models/Analytics.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/types.ts
  packages/stems/src/assets/icons/iconMessageLocked.svg
  packages/stems/src/assets/icons/iconTipping.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.module.css
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/components/stat-banner/StatBanner.module.css
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/L

#3386 [C-2615] Fix favorite tracks error due to empty track entries on web mobile
  packages/web/src/components/add-to-playlist/mobile/AddToPlaylist.tsx
  packages/web/src/pages/explore-page/components/mobile/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/M

#3395 [C-2575] Match length of related artists user list to preview
  packages/web/src/common/store/user-list/related-artists/sagas.ts
Labels: size/XS

#3387 [PAY-1218] Mobile block dms drawer switches block/unblock
  packages/common/src/store/pages/chat/selectors.ts
  packages/mobile/src/components/block-messages/BlockMessages.tsx
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
Labels: size/M

#3391 [PAY-1248] Initial changes to get ready for upcoming PRs that include track and playlist tiles in DMs
  packages/common/src/api/collection.ts
  packages/common/src/api/createApi.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/schema.ts
  packages/common/src/api/track.ts
  packages/common/src/api/types.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/queue/types.ts
  packages/common/src/utils/urlUtils.ts
Labels: size/L

#3376 [PAY-1197] Mobile inbox unavailable modal from profile screen
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/iconMessageLocked.svg
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/components/inbox-unavailable-drawer/index.ts
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#3378 [C-2518, C-2523, C-2611] Improve playlist create sagas
  packages/common/src/models/User.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/cache/collections/actions.ts
  packages/common/src/store/cache/users/selectors.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/common/src/store/pages/profile/types.ts
  packages/common/src/store/ui/toast/sagas.ts
  packages/common/src/store/ui/toast/types.ts
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
  packages/mobile/src/store/cache/collections/createPlaylistRequestedSaga.ts
  packages/mobile/src/store/cache/collections/sagas.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/collections/createPlaylistRequestedSaga.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/webSagas.ts
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/add-to-playlist/mobile/AddToPlaylist.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/EmptyLibraryNavLink.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
  packages/web/src/components/toast/ToastContext.tsx
  packages/web/src/components/toast/mobile/Toast.tsx
  packages/web/src/store/dragndrop/slice.ts
  packages/web/src/store/sagas.ts
  packages/web/src/utils/tempPlaylistId.ts
Labels: size/XL

#3373 Add stylelint to ci
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#3390 [PAY-1144] [PAY-1182] [PAY-1147] DMs: Delete chat, message permissions
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.module.css
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/user-name-and-badges/UserNameAndBadges.module.css
  packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/store/application/ui/chat/sagas.ts
Labels: size/L

#3397 Update locks
  packages/common/package-lock.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3388 [PAY-1028] Fix mobile chat actions drawer touch feedback
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
Labels: size/M

#3371 [PAY-1136][PAY-1129] Add infinite loading to albums on desktop / mobile web
  packages/common/src/hooks/useSavedCollections.ts
  packages/common/src/store/saved-collections/selectors.ts
  packages/common/src/store/saved-collections/types.ts
  packages/web/src/components/lineup/CardLineup.tsx
  packages/web/src/components/lineup/InfiniteCardLineup.module.css
  packages/web/src/components/lineup/InfiniteCardLineup.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.module.css
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/L

#3394 Improve popup-menu a11y
  packages/stems/src/components/PopupMenu/PopupMenu.module.css
  packages/stems/src/components/PopupMenu/PopupMenu.stories.tsx
  packages/stems/src/components/PopupMenu/PopupMenu.tsx
  packages/stems/src/components/PopupMenu/types.tsx
Labels: size/M

#3392 Add useAuthenticatedCallback
  packages/common/src/hooks/useDebouncedCallback.ts
  packages/common/src/hooks/useThrottledCallback.ts
  packages/eslint-config-audius/src/index.js
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/web/src/components/dragndrop/Droppable.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/hooks/useAuthenticatedCallback.ts
Labels: size/M

#3400 [PAY-1220] Fix chat receive bug
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
Labels: size/M

#3399 [PAY-1242] Mobile chats copy message button
  packages/mobile/src/assets/images/iconCopy2.svg
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
  packages/mobile/src/utils/zIndex.ts
Labels: size/L

#3404 Fix upload collection C-2630
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/utils/getUnclaimedPlaylistId.ts
  packages/web/src/common/store/cache/collections/utils/index.ts
  packages/web/src/common/store/upload/sagas.js
Labels: size/M

#3403 Increase space between chat reaction and copy message button
  packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx
Labels: size/XS

#3406 [C-2598] Add types for audius-query hooks
  packages/common/src/api/collection.ts
  packages/common/src/api/createApi.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/api/schema.ts
  packages/common/src/api/track.ts
  packages/common/src/api/types.ts
  packages/common/src/api/user.ts
  packages/web/src/components/related-artists/RelatedArtists.tsx
Labels: size/L

#3402 [PAY-1195] Mobile chat screen unavailable states
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
Labels: size/L

#3405 [C-2299] Fix NowPlayingDrawer navigation deduping bug
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/M

#3407 [PAY-1222] Fix unread messages count
  packages/common/src/store/pages/chat/middleware.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/L

#3410 Mark chat as read on ChatScreen entry
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/S

#3409 [C-2468] Add desktop create flow
  packages/common/src/models/Analytics.ts
  packages/common/src/store/playlist-library/index.ts
  packages/common/src/store/playlist-library/selectors.ts
  packages/common/src/store/playlist-library/slice.ts
  packages/stems/src/components/PopupMenu/PopupMenu.module.css
  packages/stems/src/components/PopupMenu/PopupMenu.tsx
  packages/stems/src/components/PopupMenu/types.tsx
  packages/web/src/components/delete-confirmation/DeleteConfirmationModal.module.css
  packages/web/src/components/delete-confirmation/DeleteConfirmationModal.tsx
  packages/web/src/components/delete-confirmation/index.ts
  packages/web/src/components/edit-folder-modal/EditFolderModal.tsx
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/DeleteCollectionConfirmationModal.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/DeleteFolderConfirmationModal.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/EditNavItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/pill/Pill.module.css
  packages/web/src/components/pill/Pill.tsx
Labels: size/XL

#3411 [C-2601 C-2627 C-2628 C-2638] Playlist library QA
  packages/web/src/components/lineup/CardLineup.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.module.css
Labels: size/L

#3393 [PAY-1241] Skeleton for mobile chat list screen
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListItemSkeleton.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
Labels: size/L

#3420 [PAY-1260] New chat tails on mobile
  packages/mobile/src/assets/images/ChatTail.svg
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Labels: size/S

#3419 [PAY-935] Fix ChatHeader issue
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
Labels: size/XS

#3417 [PAY-1177] Fix double reaction click animation
  packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/XS

#3418 [PAY-925] Adds unread message icons on web
  packages/web/src/components/Icon/Icon.module.css
  packages/web/src/components/Icon/Icon.tsx
  packages/web/src/components/Icon/index.ts
  packages/web/src/components/nav/desktop/NavPopupMenu.module.css
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/components/notification-dot/NotificationDot.module.css
  packages/web/src/components/notification-dot/NotificationDot.tsx
  packages/web/src/components/notification-dot/index.ts
Labels: size/L

#3425 [PAY-1272] Make desktop DM text copyable
  packages/common/src/store/pages/chat/selectors.ts
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
Labels: size/XS

#3426 Type fix for hook options
  packages/common/src/api/schema.ts
  packages/common/src/api/types.ts
Labels: size/S

#3422 [C-2644] Fix issue where new playlist drag-drop not persisting
  packages/common/src/store/playlist-library/helpers.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/common/store/playlist-library/watchAddToFolderSaga.ts
  packages/web/src/common/store/playlist-library/watchReorderLibrarySaga.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.module.css
Labels: size/M

#3374 [C-2508] Update playback positions to be tracked per user id
  packages/common/src/store/playback-position/sagas.ts
  packages/common/src/store/playback-position/selectors.ts
  packages/common/src/store/playback-position/slice.ts
  packages/common/src/store/playback-position/types.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/details-tile/DetailsProgressInfo.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/track/GiantTrackTileProgressInfo.tsx
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/store/storeContext.ts
Labels: size/L

#3427 [C-2597][C-2651] Add audius-query usage docs
  packages/common/README.md
  packages/common/src/api/collection.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/api/track.ts
  packages/common/src/api/user.ts
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/audius-query/README.md
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/hooks/index.ts
  packages/common/src/audius-query/hooks/usePaginatedQuery.ts
  packages/common/src/audius-query/index.ts
  packages/common/src/audius-query/schema.ts
  packages/common/src/audius-query/types.ts
  packages/common/src/audius-query/utils.ts
  packages/common/src/index.ts
Labels: size/L

#3428 [PAY-1251] [PAY-1188] DMs: Add error message to failed message sends
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/stems/src/assets/icons/iconError.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/M

#3421 [PAY-1258] Add toast when chat messages are copied
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Labels: size/M

#3433 [PAY-1273] Fix scrolling issues
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/StickyScrollList.tsx
Labels: size/XS

#3434 Make mobile chat inbox unavailable message unsticky
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
Labels: size/XS

#3424 [PAY-1255] [PAY-1245] DMs: Add confirmation modals
  packages/stems/src/assets/styles/colors.css
  packages/stems/src/components/Button/Button.module.css
  packages/stems/src/components/Button/Button.stories.tsx
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/Button/types.ts
  packages/stems/src/components/Modal/types.ts
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/help-callout/HelpCallout.module.css
  packages/web/src/components/help-callout/HelpCallout.tsx
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.module.css
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.module.css
  packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.tsx
  packages/web/src/pages/chat-page/components/UnblockUserConfirmationModal.module.css
  packages/web/src/pages/chat-page/components/UnblockUserConfirmationModal.tsx
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/default.ts
Labels: size/L

#3431 [CON-678] v2 user profile edit
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/profile/sagas.js
Labels: size/L

#3436 Update legacy playlist screens to use legacy inputs
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/LegacyEditPlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/LegacyPlaylistImageInput.tsx
Labels: size/S

#3435 [PAY-1274] DMs: Unsticky inbox unavailable message
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/InboxUnavailableMessage.module.css
  packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
Labels: size/L

#3377 [PAY-800][PAY-1249][PAY-1250] Display track and playlist tiles in web chats - Part 1
  packages/common/src/api/collection.ts
  packages/common/src/api/track.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/queue/types.ts
  packages/web/src/components/track/Artwork.module.css
  packages/web/src/components/track/Artwork.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTileArt.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.module.css
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.module.css
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
  packages/web/src/pages/chat-page/components/LinkPreview.tsx
  packages/web/src/pages/upload-page/components/FinishPage.js
Labels: size/XL

#3441 [C-2649] Refactor desktop collection header
  packages/web/src/components/collection/desktop/ActionButtons.tsx
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PlayButton.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
  packages/web/src/components/collection/desktop/SmartCollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/ViewerActionButtons.tsx
  packages/web/src/components/collection/desktop/utils.ts
  packages/web/src/components/tooltip/index.ts
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/XXL

#3423 [PAY-946] Handle signed out users across DMs
  packages/common/src/store/pages/chat/sagas.ts
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#3438 [PAY-1142] DMs: Update chat tail
  packages/web/src/assets/img/ChatTail.svg
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
Labels: size/S

#3437 DMs: Use unblock/block confirmation modals on profile
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/M

#3440 Bump SDK version and change walletapi to auth
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-sdk.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/audius-sdk/audiusSdk.ts
Labels: size/S

#3444 Fix mobile native change comment C-2657
  .circleci/src/jobs/@mobile-jobs.yml
Labels: size/XS

#3443 [C-2592] Fix edit playlist
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
  packages/mobile/src/screens/page-form-screen/PageFormScreen.tsx
Labels: size/XS

#3445 [PAY-1150] Disable scrolling when chat reaction popup is active
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3449 [C-2647] Use entire cache to denormalize data
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/common/src/audius-query/utils.ts
Labels: size/L

#3448 [PAY-1243] Mobile chat header touchable feedback
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3447 [PAY-1247] Cap height of chat textinput on mobile
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Labels: size/S

#3450 [C-2653] Add shallow argument to audius-query hooks
  packages/common/src/audius-query/README.md
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/common/src/audius-query/utils.ts
Labels: size/M

#3453 Feature flag unread messages notif bubble
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
Labels: size/XS

#3451 Retry CodePush installs if they failed the first time C-2659
  packages/mobile/src/app/useSyncCodepush.ts
Labels: size/XS

#3446 [PAY-1276] Mobile chats change color on press
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/LinkPreview.tsx
Labels: size/M

#3454 [PAY-1288] DMs: Show max length in composer
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
Labels: size/XS

#3458 [PAY-1246] Mobile delete chat thread UI
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/block-messages-drawer/index.ts
  packages/mobile/src/components/block-messages/index.ts
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
  packages/mobile/src/components/delete-chat-drawer/DeleteChatDrawer.tsx
  packages/mobile/src/components/delete-chat-drawer/index.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/store/chat/sagas.ts
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#3459 [C-2635] Fix offline playback; broken signature fetch
  packages/mobile/src/components/audio/Audio.tsx
Labels: size/XS

#3460 [PAY-1297] DMs: Don't show current user in search results
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Labels: size/XS

#3456 [C-2648] Add redesigned playlist management flow
  packages/stems/src/assets/styles/animations.css
  packages/stems/src/components/Button/Button.module.css
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/Button/types.ts
  packages/stems/src/components/Modal/Modal.module.css
  packages/stems/src/components/Modal/Modal.tsx
  packages/stems/src/components/Modal/ModalContentText.module.css
  packages/stems/src/components/Modal/ModalContentText.tsx
  packages/stems/src/components/Modal/index.ts
  packages/stems/src/components/Modal/types.ts
  packages/stems/src/index.tsx
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
  packages/web/src/components/collection/desktop/PublishConfirmationModalFooter.module.css
  packages/web/src/components/create-playlist/FormActions.module.css
  packages/web/src/components/create-playlist/FormActions.tsx
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/data-entry/Input.js
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/image-selection/ImageSelectionButton.js
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/pages/chat-page/components/StickyScrollList.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/store/application/ui/editPlaylistModal/selectors.ts
  packages/web/src/store/application/ui/editPlaylistModal/slice.ts
Labels: size/XL

#3442 [PAY-1138] Fix headers on Chats and fix old header prod bug
  packages/web/src/components/banner/Banner.module.css
  packages/web/src/components/header/desktop/Header.js
  packages/web/src/components/header/desktop/HeaderGutter.module.css
  packages/web/src/components/header/desktop/HeaderGutter.tsx
  packages/web/src/components/header/mobile/Header.module.css
  packages/web/src/hooks/usePortal.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/App.module.css
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/components/ChatHeader.module.css
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.module.css
Labels: size/XXL

#3464 Fix input with explicit input props
  packages/web/src/components/data-entry/Input.js
Labels: size/XS

#3462 Filter out self from create chat search results on mobile
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
Labels: size/XS

#3461 [PAY-1278] Indicator for end of chat history on mobile
  packages/mobile/src/screens/chat-screen/ChatMessageSeparator.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/constants.ts
Labels: size/L
