Repository AudiusProject/audius-client, pull requests merged in 2023-06, with the labels that each got.

#3481 [C-2702] Remove initialSelectedNode from disc-node selector
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorService.ts
  packages/common/src/services/discovery-node-selector/index.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/services/audius-sdk.ts
  packages/mobile/src/services/discovery-node-selector.ts
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/audius-sdk/audiusSdk.ts
  packages/web/src/services/discovery-node-selector.ts
Labels: size/M

#3483 [PAY-1316] DMs: Do the thing (Fix mobile chats not populating)
  packages/common/src/store/pages/chat/sagas.ts
Labels: size/XS

#3480 [C-2700][C-2701] upload redesign feature flag and placeholder page
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/UploadPageLegacy.js
  packages/web/src/pages/upload-page/UploadPageNew.module.css
  packages/web/src/pages/upload-page/UploadPageNew.tsx
Labels: size/M

#3482 [PAY-1330][PAY-1317][PAY-1321] Polish DMs #1
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
Labels: size/S

#3487 [C-2699] Fix collection action button sizes
  packages/web/src/components/collection/desktop/CollectionActionButton.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/collection/desktop/PlayButton.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
Labels: size/M

#3490 HOTFIX: left-nav delete-confirmation
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
  packages/web/src/common/store/playlist-library/watchReorderLibrarySaga.ts
  packages/web/src/components/edit-folder-modal/EditFolderModal.tsx
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/DeleteCollectionConfirmationModal.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/DeleteFolderConfirmationModal.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
Labels: size/M

#3492 [C-2658] Fix favorite Hot & New in sign up
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#3491 [PAY-1324][PAY-1326][PAY-1323][PAY-1327][PAY-1331][PAY-1328][PAY-1320] DMs UI fixes 2
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx
  packages/web/src/assets/styles/shadows.css
  packages/web/src/components/artist/ArtistChipFollowers.tsx
  packages/web/src/components/page/Page.module.css
  packages/web/src/components/user-badges/FollowsYouBadge.module.css
  packages/web/src/components/user-badges/FollowsYouBadge.tsx
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
Labels: size/M

#3488 [PAY-1303] Add toastSagas to mobile
  packages/mobile/src/store/sagas.ts
Labels: size/XS

#3493 [C-2705] Port upload files page to new upload form
  packages/web/src/pages/upload-page/UploadPageNew.tsx
Labels: size/L

#3495 Push props down to SelectPage
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/SelectPage.js
  packages/web/src/pages/upload-page/components/SelectPage.tsx
Labels: size/L

#3484 [PAY-1308] Use all messages for tracking latest received
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#3485 [] Add styling fixes from mobile playlist updates QA
  packages/mobile/src/components/core/FormImageInput.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/publish-playlist-drawer/PublishPlaylistDrawer.tsx
  packages/mobile/src/components/toasts/Toast.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistForm.tsx
  packages/mobile/src/screens/page-form-screen/PageFormScreen.tsx
Labels: size/L

#3494 [PAY-1337] Fix mobile chat message shadows
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Labels: size/L

#3499 [pay-1311] Reset chat state on sign out
  packages/common/src/store/pages/chat/slice.ts
Labels: size/XS

#3501 [C-2708] Improvements around codepush & force pushing
  packages/mobile/android/fastlane/Fastfile
  packages/mobile/ios/fastlane/Fastfile
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/S

#3439 [PLAT-1005] Parse for add track to playlist notification from backend
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
Labels: size/M

#3489 [PAY-1336] Updates to mobile chats user search screen
  packages/mobile/src/assets/images/iconCloseAlt.svg
  packages/mobile/src/assets/images/iconSearch.svg
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/M

#3500 [PAY-1318] Missing Shadow and Space Between Divider and Header
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/HeaderShadow.tsx
  packages/mobile/src/utils/zIndex.ts
Labels: size/M

#3486 [PAY-1175] DMs: Autofocus, clear search, elevate placeholder
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/search-users-modal/SearchUsersModal.module.css
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Labels: size/M

#3502 Fix upload regression on stage
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/SelectPage.js
  packages/web/src/pages/upload-page/components/SelectPageNew.tsx
Labels: size/L

#3498 Add clientVersion to mobile analytics
  packages/mobile/src/services/analytics.ts
Labels: size/XS

#3432 Remove write_metadata_through_chain flag
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/L

#3506 [PAY-1377] Compose message icon to TouchableOpacity
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
Labels: size/XS

#3508 [PAY-1267] Add space before placeholder in chat textinput
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/XS

#3507 [PAY-1355] Add space before learn more link in inbox unavailable message
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
Labels: size/XS

#3398 [PAY-1137][PAY-1132] Infinite loading of albums on mobile favorites screen
  packages/common/src/hooks/useSavedCollections.ts
  packages/common/src/store/account/slice.ts
  packages/common/src/store/account/types.ts
  packages/common/src/store/saved-collections/selectors.ts
  packages/common/src/utils/collectionUtils.ts
  packages/common/src/utils/index.ts
  packages/mobile/package-lock.json
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/hooks/useOfflineTrackStatus.ts
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/LoadingMoreSpinner.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/favorites-screen/useCollectionScreenData.ts
  packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
  packages/mobile/src/screens/favorites-screen/utils.ts
  packages/mobile/src/store/sagas.ts
  packages/web/package-lock.json
  packages/web/src/common/store/account/sagas.js
  packages/web/src/components/lineup/InfiniteCardLineup.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/XL

#3509 Update SDK to revert comms health changes
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3505 Add mobile hidden track playlist logic
  packages/common/src/store/cache/collections/selectors.ts
  packages/common/src/store/ui/add-to-playlist/actions.ts
  packages/common/src/store/ui/add-to-playlist/reducer.ts
  packages/common/src/store/ui/add-to-playlist/selectors.ts
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/components/track-list/TrackArtwork.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/components/FormScreen.tsx
  packages/web/src/common/store/add-to-playlist/sagas.ts
Labels: size/L

#3511 Remove yield* in js files
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/lineup/sagas.js
Labels: size/S

#3510 [C-2717] Fix playlist create tile bug
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
Labels: size/XS

#3512 Upgrade sdk to 2.0.3-beta.36
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3497 Default true cid metadata flags
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/M

#3513 [PAY-1370] Fix reaction touch targets
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Labels: size/S

#3515 [PAY-1333] Mobile dms end of history only shows with >10 messages
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/constants.ts
Labels: size/S

#3519 [PAY-1390] fix inverted condition for computing track count
  packages/mobile/src/components/collection-list/CollectionCard.tsx
Labels: size/XS

#3521 [PAY-1391] ensure all collections are fetched before attempting to download
  packages/common/src/store/saved-collections/selectors.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/web/src/common/store/saved-collections/sagas.ts
Labels: size/M

#3514 [PAY-1342][PAY-1360] DMs: Show users as chat unlocked by default, optimistic chat navigation
  packages/common/src/hooks/chats/useCanSendMessage.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/S

#3525 Add reason to account slice, handle fetch account failure with sentry
  packages/common/src/store/account/slice.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/store/configureStore.ts
Labels: size/S

#3520 [C-2719] Clean up and document non v1 usage
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/explore/Explore.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/pages/token-dashboard/getAccountMetadataCID.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/components/notification/Notification/utils.ts
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/store/errors/reportToSentry.ts
Labels: size/L

#3522 [PAY-1392] Mobile mark chat as read onscroll, on navigate away
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/constants.ts
Labels: size/S

#3526 [PAY-1365] Disable fullscreen gestures on mobile chat screen
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
Labels: size/XS

#3524 [PAY-1361] Fix reactions button hit area
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/M

#3527 [PAY-1362] Mobile press chat message closes reaction popup
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Labels: size/XS

#3531 [PAY-1149] Mobile chat reactions add android offset
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
  packages/mobile/src/screens/chat-screen/constants.ts
Labels: size/S

#3533 [PAY-1394] DMs: Show global unread indicator if there's unread messages in a loaded chat
  packages/common/src/store/pages/chat/selectors.ts
Labels: size/S

#3532 [PAY-1347] DMs: Don't show unread indicator for first messages
  packages/common/src/utils/chatUtils.ts
Labels: size/XS

#3534 [PAY-1315] Fix mobile chat search screen takes 2 presses
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/XS

#3529 [C-1873, C-2551, C-2552, C-2553] Add hidden track logic for playlists on web
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.module.css
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/share-modal/components/ShareDialog.module.css
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/messages.ts
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/tracks-table/TracksTable.module.css
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/L

#3535 [C-2461, C-2476] Prevent user from dragging hidden tracks to public playlists
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
Labels: size/S

#3530 [PAY-1363] DMs: Add CTA to Create Chat user rows
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.module.css
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#3536 [PAY-1356] Mobile chats scroll to bottom when re-entering chat screen
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#3540 DMs: Fix deletions not causing perms rechecks
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
Labels: size/M

#3528 [PAY-1366] Fix web chat tile artwork and mobile link preview bugs
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
Labels: size/L

#3537 DMs: Wait for tip confirmation then refetch permissions
  packages/web/src/common/store/tipping/sagas.ts
Labels: size/M

#3538 [PAY-1348] clean up ChatUserListScreen and use followers as default list
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/L

#3542 [PAY-1406][PAY-1374][PAY-1353][PAY-1411] Fix DMs UI Issues
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.module.css
Labels: size/M

#3544 [C-2746] Fix favorites album tab styling
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
Labels: size/XS

#3539 [C-2691] Carry values through the form fields
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/data-entry/Input.js
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/components/SelectPageNew.tsx
  packages/web/src/pages/upload-page/components/types.ts
  packages/web/src/pages/upload-page/fields/EditTrackMetadataField.tsx
  packages/web/src/pages/upload-page/fields/TextField.tsx
  packages/web/src/pages/upload-page/fields/types.ts
Labels: size/L

#3549 [PAY-1409] DMs: Deep link into chat from notification
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/hooks/useNotificationNavigation.ts
Labels: size/M

#3548 [PAY-1378] Cap image size on mobile DMs
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/LinkPreview.tsx
  packages/mobile/src/utils/zIndex.ts
Labels: size/S

#3541 [PAY-1367][PAY-1400][PAY-1401][PAY-1402][PAY-1419] Fix chat tile unfurl bugs
  packages/common/src/utils/urlUtils.ts
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
Labels: size/L

#3554 [PAY-1425][PAY-1424] DMs: Fix image unfurls, fix purple halo around unfurls
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/LinkPreview.module.css
Labels: size/L

#3550 [PAY-1403] Fix chat track unfurl reactions
  packages/mobile/src/app/App.tsx
Labels: size/XS

#3555 [PAY-1426] DMs: Simplify unfurl styles for mobile, fix border radius shadow
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/LinkPreview.tsx
Labels: size/M

#3551 Mobile ChatMessageListItem uses message id + selector
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Labels: size/M

#3553 [PAY-1423] Fix empty chat message box with currently playing track
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/EmptyChatMessages.tsx
Labels: size/M

#3552 [PAY-1398] Fix ChatUserListScreen scrolling with keyboard
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/S

#3557 Update plist to 1.1.66
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3558 Force mobile staging build
  packages/mobile/ios/fastlane/Fastfile
Labels: size/XS

#3560 Force mobile staging build - Android
  packages/mobile/android/fastlane/Fastfile
  packages/mobile/ios/fastlane/Fastfile
Labels: size/XS

#3559 DMs: Fix broken messages
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/LinkPreview.tsx
Labels: size/XS

#3561 Force mobile build again
  packages/mobile/ios/fastlane/Fastfile
Labels: size/M

#3562 [PAY-1386] DMs: Mark chat as read on client when new message from self comes through websocket
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
Labels: size/S

#3564 Revert force mobile full staging build
  packages/mobile/android/fastlane/Fastfile
  packages/mobile/ios/fastlane/Fastfile
Labels: size/XS

#3566 [PAY-1389] CTA on create chat when not permitted
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/create-chat-actions-drawer/CreateChatActionsDrawer.tsx
  packages/mobile/src/components/create-chat-actions-drawer/index.ts
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#3567 [PAY-1325] Remove userbadges from chat unavailable message in chat screen
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
Labels: size/S

#3518 [C-2474] Generate playlist artwork from track artwork
  packages/common/src/models/Collection.ts
  packages/common/src/store/cache/collections/actions.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/store/storeContext.ts
  packages/mobile/src/utils/createPlaylistArtwork.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/collections/confirmOrderPlaylist.js
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/fixInvalidTracksInPlaylist.js
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/confirmer/actions.ts
  packages/web/src/common/store/confirmer/types.ts
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/add-to-playlist/mobile/AddToPlaylist.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/store/storeContext.ts
  packages/web/src/utils/imageProcessingUtil.ts
  packages/web/src/workers/createPlaylistArtwork.worker.js
Labels: size/XL

#3568 [C-2716] Improve notifications on fresh account
  packages/common/src/store/notifications/index.ts
  packages/common/src/store/notifications/selectors.ts
  packages/common/src/store/notifications/slice.ts
  packages/common/src/store/user-list/notifications/selectors.ts
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/components/NotificationTile.module.css
  packages/web/src/components/notification/NotificationPage.tsx
  packages/web/src/components/notification/NotificationPanel.module.css
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/L

#3570 [PAY-1446] Set MessageLocked icon in profile screen to 0.4 opacity
  packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx
Labels: size/XS

#3569 [PAY-1434] Dismiss keyboard on create chat screen row press
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/M

#3571 [PAY-1440][PAY-1441] Mobile inbox settings UI fixes
  packages/mobile/src/screens/settings-screen/InboxSettingsScreen.tsx
Labels: size/S

#3504 Upgrade dapp store version to v1.5.26
  packages/mobile/dapp-store/.asset-manifest.json
  packages/mobile/dapp-store/config.yaml
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/S

#3573 Allow drag and dropping tracks into chat
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
Labels: size/S

#3572 [PAY-1442] Fix drawer touchables on android
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
  packages/mobile/src/components/create-chat-actions-drawer/CreateChatActionsDrawer.tsx
Labels: size/XS

#3575 [PAY-1399] Fix Android chat send button color
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/mobile/src/utils/convertHexToRGBA.ts
Labels: size/S

#3577 [C-2472] Update mobile track list items for playlists to have the overflow menu
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/components/table/Table.module.css
Labels: size/S

#3563 [PLAT-659] Metamask sign in/up on ACDC
  package-lock.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/libs.ts
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/pages/audio-rewards-page/components/SendInputBody.tsx
  packages/web/src/pages/sign-on/SignOnProvider.tsx
  packages/web/src/pages/sign-on/components/desktop/MetaMaskModal.module.css
  packages/web/src/services/audius-backend/Cognito.ts
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/audius-sdk/audiusSdk.ts
  packages/web/src/services/entity-manager.ts
Labels: size/M

#3578 [PAY-1435] Navigate to chat after unblocking user on mobile
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/S

#3580 [PAY-1405] Add padding to bottom of chat user search screen
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/XS

#3576 [PAY-1454] Redline mobile header to latest figma design
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/MessageButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/Bio.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandHeaderToggleButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
Labels: size/M

#3586 audius-query debug flag usage in README
  packages/common/src/audius-query/README.md
Labels: size/XS

#3587 [C-2768] Update InputV2, add TextField/TextAreaField
  packages/web/src/components/data-entry/InputV2.module.css
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/form-fields/TextAreaField.tsx
  packages/web/src/components/form-fields/TextField.tsx
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Labels: size/L

#3588 [PAY-1448] End the race between SDK and Libs, once and for all
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/pages/chat/middleware.ts
  packages/web/src/services/audius-sdk/audiusSdk.ts
Labels: size/S

#3581 [C-2761] Add mutations to audius-query
  packages/common/src/audius-query/README.md
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/store/store.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/store/configureStore.ts
Labels: size/XL

#3584 [C-2588] Update share modal and drawer to properly add user twitter handle
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/utils.ts
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/utils.ts
Labels: size/M

#3585 [PAY-1432] Fix chat playlist artist sometimes undefined
  packages/common/src/audius-query/types.ts
  packages/web/src/common/store/cache/tracks/utils/reformat.ts
Labels: size/XS

#3592 Fix mobile textinput borders + labels
  packages/mobile/src/components/core/TextInput.tsx
Labels: size/S

#3574 [C-2713] Add track metadata fields to new upload form
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/data-entry/InlineFormTile.js
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.module.css
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/fields/EditTrackMetadataField.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.module.css
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/utils/Moods.tsx
  packages/web/src/utils/restrictedHandles.js
Labels: size/L

#3594 [PAY-1461] Format follower count in chat search screen
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
Labels: size/XS

#3596 [C-2770] Fix issue where playlist library can disappear
  packages/common/src/store/cache/reducer.ts
Labels: size/XS

#3595 [PAY-1437] Fix drawers sharing state causing crash
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
  packages/mobile/src/components/create-chat-actions-drawer/CreateChatActionsDrawer.tsx
  packages/mobile/src/components/delete-chat-drawer/DeleteChatDrawer.tsx
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/hooks/useDrawer.ts
  packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
  packages/mobile/src/store/drawers/selectors.ts
  packages/mobile/src/store/drawers/slice.ts
Labels: size/M

#3597 Reduce MessageLockedButton size on profile screen
  packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx
Labels: size/XS

#3593 [PAY-1456] Fix followee-gated create chat crash
  packages/common/src/store/pages/chat/selectors.ts
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
Labels: size/L

#3589 [C-2665 C-2714] Add developer apps settings modal
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/api/developer-apps.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/utils.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/assets/img/iconCopyPlain.svg
  packages/web/src/assets/img/iconWarning.svg
  packages/web/src/components/data-entry/InputV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/divider/Divider.module.css
  packages/web/src/components/divider/Divider.tsx
  packages/web/src/components/divider/index.ts
  packages/web/src/pages/chat-page/components/ChatComposer.module.css
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeleteAppConfirmationPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeleteAppConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsCard.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsModal.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/index.ts
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/types.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/XXL

#3599 [PAY-1455] Optimize reactions perf (maybe)
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3603 Add option to cache bust node_modules
  .circleci/config.yml
  .circleci/src/commands/@commands.yml
Labels: size/S

#3604 Wait for libs to init before initting SDK
  packages/web/src/services/audius-sdk/audiusSdk.ts
Labels: size/S

#3565 [PAY-944] DMs: Add Mobile Web drawer prompting app download
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/stems/src/assets/icons/iconSpeaker.svg
  packages/stems/src/assets/icons/iconStars.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/components/download-mobile-app-drawer/DownloadMobileAppDrawer.module.css
  packages/web/src/components/download-mobile-app-drawer/DownloadMobileAppDrawer.tsx
  packages/web/src/components/mobile-upload-drawer/MobileUploadDrawer.module.css
  packages/web/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/ChatPageProvider.tsx
  packages/web/src/pages/chat-page/components/mobile/SkeletonChatPage.tsx
  packages/web/src/pages/profile-page/components/mobile/UploadButton.tsx
Labels: size/L

#3606 [PAY-1484] Allow reactions while keyboard is open on mobile
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3607 [PAY-1476] Inbox unavailable copy update
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
Labels: size/XS

#3609 Developer app modal - small fixes
  packages/common/src/api/developer-apps.ts
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.tsx
Labels: size/S

#3605 Change text to 'Beginning of Conversation'
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/XS

#3590 Lowercase library restricted handle
  packages/web/src/utils/restrictedHandles.js
Labels: size/XS

#3612 [PAY-1486] DMs: Fix purple border around unfurls
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Labels: size/M

#3602 Use emojis instead of 'heart' etc as reactions
  packages/common/src/store/ui/reactions/types.ts
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/reactions.tsx
  packages/web/src/components/notification/Notification/components/Reaction/index.tsx
  packages/web/src/pages/chat-page/components/ReactionPopupMenu.tsx
Labels: size/M

#3614 [PAY-1473] Clear input on chat change
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
Labels: size/XS

#3615 [PAY-1489] Add more space to reacted to messages
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/XS

#3616 [PAY-1469] Clear the search after creating a chat
  packages/common/src/store/pages/chat/sagas.ts
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Labels: size/S

#3613  [PAY-1470] Remove border radius from track/playlist tiles
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
Labels: size/XS

#3618 [PAY-1487] Increase hit slop of mobile dms send button
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Labels: size/XS

#3608 Add overflow menu options for track list items on mobile
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
Labels: size/M

#3617 [PAY-1494] Change chats copy to beginning of message history
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3611 [PAY-1421] Fix android reaction offsets
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Labels: size/M

#3620 [C-2712] Clear favorites on sign-out
  packages/common/src/store/pages/saved-page/reducer.ts
Labels: size/XS

#3622 [PAY-1483] Patch RN to fix textinput multiline onchange not firing
  packages/mobile/patches/README.md
  packages/mobile/patches/react-native+0.71.8.patch
Labels: size/M

#3623 [PAY-1468] Fix mobile chats copy message button
  packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Labels: size/M

#3601 [C-2771, C-2772] Add duplicate add to playlist confirmation drawer and modal
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/duplicate-add-confirmation-modal/sagas.ts
  packages/common/src/store/ui/duplicate-add-confirmation-modal/selectors.ts
  packages/common/src/store/ui/duplicate-add-confirmation-modal/slice.ts
  packages/common/src/store/ui/duplicate-add-confirmation-modal/types.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
  packages/mobile/src/components/duplicate-add-confirmation-drawer/DuplicateAddConfirmationDrawer.tsx
  packages/mobile/src/components/duplicate-add-confirmation-drawer/index.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.module.css
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.tsx
  packages/web/src/components/duplicate-add-confirmation-modal/index.ts
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#3610 [C-2676] Rough release date modal
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/assets/styles/type.css
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/components/ReleaseDateModalField.module.css
  packages/web/src/pages/upload-page/components/ReleaseDateModalField.tsx
  packages/web/src/pages/upload-page/components/TrackModalArray.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.module.css
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
Labels: size/L

#3579 [C-2760, C-2779] Fix header for playlist and artists tabs in explore screen
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/screens/explore-screen/components/TabInfo.tsx
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TopAlbumsScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingUndergroundScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
  packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
Labels: size/M

#3626 [PAY-1498][PAY-1477] Misc mobile DMs UI Fixes
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
Labels: size/S

#3619 [PLAT-1015] Remove entity manager feature flag
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/S

#3625 [PAY-1464] DMs: Go to chat after successful tip
  packages/common/src/store/pages/chat/index.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/store/pages/chat/utils.ts
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Labels: size/L

#3633 [PAY-1191] Finesse keyboard enter/exit animations
  packages/mobile/src/components/core/KeyboardAvoidingView.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/S

#3632 [PAY-1412] Reset player state on app load
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/S

#3627 [PAY-1457] Add amplitude analytics to chat features
  packages/common/src/context/appContext.ts
  packages/common/src/context/index.ts
  packages/common/src/hooks/chats/useCanSendMessage.ts
  packages/common/src/hooks/chats/useSetInboxPermissions.ts
  packages/common/src/index.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/app/App.tsx
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
  packages/mobile/src/services/analytics.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/app.tsx
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/pages/AppContext.tsx
  packages/web/src/pages/AppProviders.tsx
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
  packages/web/src/services/analytics/index.ts
  packages/web/src/store/storeContext.ts
Labels: size/XL

#3624 [C-2784] Refactor track page to use entity button
  packages/web/src/components/collection/desktop/CollectionActionButton.tsx
  packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/PlayButton.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
  packages/web/src/components/entity-page/EntityActionButton.module.css
  packages/web/src/components/entity-page/EntityActionButton.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.module.css
Labels: size/L

#3629 [PAY-1319] Fix emoji keyboard overlapping chat text input
  packages/mobile/src/components/core/KeyboardAvoidingView.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#3631 Refactor: extract reusable modal field component
  packages/web/src/pages/upload-page/components/ReleaseDateModalField.tsx
  packages/web/src/pages/upload-page/components/TrackModalArray.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.module.css
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
  packages/web/src/pages/upload-page/fields/ModalField.module.css
  packages/web/src/pages/upload-page/fields/ModalField.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateModalField.module.css
  packages/web/src/pages/upload-page/fields/ReleaseDateModalField.tsx
Labels: size/L

#3635 [C-2783] Add terms of service link
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/S

#3628 Implement OAuth Write Popup C-2664
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/pages/App.js
  packages/web/src/pages/developer-page/DeveloperPage.module.css
  packages/web/src/pages/developer-page/DeveloperPage.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/oauth-login-page/hooks.ts
  packages/web/src/pages/oauth-login-page/messages.ts
  packages/web/src/pages/oauth-login-page/utils.ts
  packages/web/src/utils/route.ts
Labels: size/XXL

#3634 [C-2763] Fix desktop playlist qa issues
  packages/common/src/store/playlist-library/helpers.ts
  packages/stems/src/assets/styles/animations.css
  packages/stems/src/components/Button/Button.module.css
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/components/collection/desktop/ShareButton.tsx
  packages/web/src/components/collection/desktop/SmartCollectionActionButtons.tsx
  packages/web/src/components/image-selection/ImageSelectionButton.js
  packages/web/src/components/image-selection/ImageSelectionPopup.js
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/pages/App.js
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
Labels: size/L

#3636 [PAY-1516] Chat report abuse flow
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
Labels: size/L

#3637 [C-2475] Add desktop favorites playlist tab
  packages/web/src/assets/img/iconSaveFilled.svg
  packages/web/src/components/tile/Tile.module.css
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/components/tile/index.ts
  packages/web/src/components/tracks-table/EmptyTable.js
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/CollectionCard.tsx
  packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/XL

#3640 Put playlist-artwork generation behind flag
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
Labels: size/S

#3639 Amplitude tracking for chat report abuse
  packages/common/src/models/Analytics.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx
Labels: size/M

#3642 [PAY-1526] Mobile chat reaction picker shadow
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Labels: size/XS

#3641 Update SDK to v3.0.3-beta.56
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3643 Bump app versions for full release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3644 Mobile chats recalculate container bottom on keyboard shown
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS
