Repository AudiusProject/audius-client, pull requests merged in 2023-07, with the labels that each got.

#3688 Update SDK to v3.0.3-beta.63
  packages/common/package-lock.json
  packages/common/package.json
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3685 Migrate `getDogEarType` to common
  packages/common/src/models/DogEar.ts
  packages/common/src/models/index.ts
  packages/common/src/utils/dogEarUtils.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/components/dog-ear/DogEar.tsx
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#3691 [C-2718] Fix mobile sign-up environment issues
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/M

#3693 Fetch chats on app foreground
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#3694 [C-2416] Fix missing hidden playlists on own profile
  packages/common/src/store/pages/profile/selectors.ts
  packages/mobile/src/components/core/EmptyTile.tsx
  packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
  packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
Labels: size/M

#3692 [PAY-1556] Update mobile web gated content experience for TrackTiles
  packages/stems/src/assets/icons/iconCrown.svg
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/alt-button/MoreButton.tsx
  packages/web/src/components/alt-button/ShareButton.tsx
  packages/web/src/components/track/PremiumContentLabel.module.css
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/BottomButtons.module.css
  packages/web/src/components/track/mobile/BottomButtons.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/trackTileMessages.ts
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
  packages/web/src/pages/trending-page/components/RewardsBanner.module.css
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/default.ts
  packages/web/src/utils/theme/matrix.ts
Labels: size/XL

#3695 Fix track screen artist name font weight
  packages/mobile/src/components/details-tile/DetailsTile.tsx
Labels: size/S

#3697 Attach ulid package to window
  packages/common/src/store/pages/chat/sagas.ts
Labels: size/XS

#3696 Mobile gated content updates pt. 2
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
Labels: size/L

#3689 [C-2478 C-2480] Add suggestedTracks
  packages/common/src/api/favorites.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/suggestedTracks.ts
  packages/mobile/src/assets/images/iconRefresh.svg
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/mobile/src/components/suggested-tracks/index.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/stems/src/assets/styles/transforms.css
  packages/web/src/components/divider/Divider.module.css
  packages/web/src/components/divider/Divider.tsx
  packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx
  packages/web/src/hooks/useTrackCoverArt.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/desktop/SuggestedTracks.module.css
  packages/web/src/pages/collection-page/components/desktop/SuggestedTracks.tsx
Labels: size/XL

#3699 [PAY-1563] Fix loading into a chat from a push notification
  packages/common/src/store/pages/chat/selectors.ts
Labels: size/XS

#3703 [QA-560][PAY-1564] Fix hot and new bug
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
Labels: size/XS

#3698 Convert GiantTrackTile to typescript
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantArtwork.tsx
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/GiantTrackTileProgressInfo.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/XXL

#3700 [C-2587] Fix playlist update tooltip
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.tsx
  packages/web/src/pages/collection-page/components/desktop/SuggestedTracks.tsx
Labels: size/M

#3701 [C-2821] Add hidden dog tag to mobile card
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/card/CollectionDogEar.tsx
Labels: size/M

#3702 [C-1379] Add link to playlist in mobile toast
  packages/common/src/store/ui/toast/types.ts
  packages/mobile/src/components/toasts/Toast.tsx
  packages/mobile/src/store/cache/collections/createPlaylistRequestedSaga.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/M

#3705 Minor fixes for premium_content + usdc purchases
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#3707 [C-2830] Move storage node selector to common
  packages/common/src/services/index.ts
  packages/common/src/services/sdk/bootstrapNodes.ts
  packages/common/src/services/sdk/index.ts
  packages/common/src/services/sdk/storageNodeSelector.ts
  packages/mobile/src/services/sdk/storageNodeSelector.ts
  packages/web/src/services/audius-sdk/storageNodeSelector.ts
Labels: size/M

#3708 [C-2827] Fix hidden dog ear on search results
  packages/web/src/components/card/desktop/Card.tsx
Labels: size/XS

#3672 Reregister device token on signin
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/mobile/src/store/settings/sagas.ts
  packages/mobile/src/store/sign-up/sagas/watchSignUpSucceededSaga.ts
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/L

#3709 [PAY-1566] Adds support for passing color directly to primary button
  packages/stems/rollup.config.js
  packages/stems/src/assets/styles/colors.css
  packages/stems/src/assets/styles/shadows.css
  packages/stems/src/components/Button/Button.module.css
  packages/stems/src/components/Button/Button.stories.tsx
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/Button/types.ts
  packages/stems/src/index.tsx
  packages/stems/src/styles/colors.ts
  packages/stems/src/styles/types.ts
  packages/stems/src/utils/styles.ts
Labels: size/L

#3712 [C-2341] Update tracks table to display tracks marked as deleted as deleted
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/S

#3669 [PAY-1534] Allow Popup to be mounted inside a container
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/components/Popup/types.ts
  packages/stems/src/components/PopupMenu/PopupMenu.tsx
  packages/stems/src/components/PopupMenu/types.tsx
  packages/stems/src/utils/scrollParent.ts
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/App.d.ts
  packages/web/src/pages/App.test.tsx
  packages/web/src/pages/MainContentContext.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Labels: size/L

#3690 [PAY-1463] Fix d to set discovery node
  packages/common/src/services/local-storage/LocalStorage.ts
  packages/common/src/services/sdk/discovery-node-selector/DiscoveryNodeSelectorService.ts
  packages/web/src/services/audius-sdk/discoveryNodeSelector.ts
Labels: size/M

#3713 DMs: Make links noreferrer noopener
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/XS

#3715 Revert "[PAY-1534] Allow Popup to be mounted inside a container (#3669)"
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/components/Popup/types.ts
  packages/stems/src/components/PopupMenu/PopupMenu.tsx
  packages/stems/src/components/PopupMenu/types.tsx
  packages/stems/src/utils/scrollParent.ts
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/App.d.ts
  packages/web/src/pages/App.test.tsx
  packages/web/src/pages/MainContentContext.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Labels: size/L

#3716 DMs: Ensure every permission action has a CTA
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
Labels: size/XS

#3714 DMs: Add space to learn more text
  packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
Labels: size/XS

#3718 Call the DN selection callback in AudiusBackend if using a cached DN
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#3719 [PAY-1569] Update blog post link
  packages/common/src/utils/chatUtils.ts
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/TopAPI.tsx
  packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
Labels: size/M

#3706 [C-2829] Finalize SuggestedTracks
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/trending.ts
  packages/common/src/audius-query/hooks/usePaginatedQuery.ts
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.module.css
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/suggested-tracks/index.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/desktop/SuggestedTracks.tsx
Labels: size/XL

#3721 [C-2834] Remove replica set usage in web
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/.env.dev
  packages/mobile/.env.prod
  packages/mobile/src/components/audio/GoogleCast.tsx
  packages/mobile/src/components/image/utils.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/web/.env/.env.dev
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
  packages/web/src/components/ai-attribution-modal/SearchBarResult.js
  packages/web/src/components/search/SearchBar.js
  packages/web/src/components/search/SearchBarResult.js
  packages/web/src/pages/AppContextProvider.tsx
  packages/web/src/pages/AppProviders.tsx
  packages/web/src/pages/PublicSite.tsx
  packages/web/src/pages/landing-page/components/FeaturedContent.tsx
  packages/web/src/pages/oauth-login-page/utils.ts
  packages/web/src/services/audius-backend/audius-backend-instance.ts
Labels: size/L

#3723 [C-2809] Remove user from image hooks
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/image/UserCoverImage.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
  packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx
  packages/mobile/src/store/account/sagas.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
Labels: size/L

#3722 [C-2785] Update collection screen focus effect to fetch lineup
  packages/common/src/store/pages/collection/actions.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/web/src/common/store/pages/collection/sagas.js
Labels: size/S

#3720 [C-2679] Track Availability Modal Form
  packages/web/src/pages/upload-page/components/TrackModalArray.tsx
  packages/web/src/pages/upload-page/fields/SwitchRowField.module.css
  packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
  packages/web/src/pages/upload-page/fields/ToggleRowField.tsx
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.module.css
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.tsx
  packages/web/src/pages/upload-page/fields/availability/SpecialAccessFields.module.css
  packages/web/src/pages/upload-page/fields/availability/SpecialAccessFields.tsx
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedDescription.module.css
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedDescription.tsx
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.module.css
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.module.css
  packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.tsx
  packages/web/src/pages/upload-page/forms/RemixModalForm.module.css
  packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.module.css
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.tsx
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.module.css
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
  packages/web/src/utils/route.ts
Labels: size/XXL

#3711 [PAY-1573] Convert premium content type to union
  packages/common/src/hooks/usePremiumContent.ts
  packages/common/src/models/Track.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/utils/dogEarUtils.ts
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup-tile/LineupTilePremiumContentTypeTag.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/fields/TrackVisibilityField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/NFTCollectionsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/locked-content-modal/LockedContentModal.tsx
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
  packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
  packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/PremiumContentLabel.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#3724 [PAY-1559][PAY-1560] Adds USDC variants for track tiles on web/mobile web
  packages/common/src/utils/wallet.ts
  packages/stems/src/assets/icons/iconCart.svg
  packages/stems/src/assets/styles/colors.css
  packages/stems/src/components/Icons/index.ts
  packages/stems/src/styles/colors.ts
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/dog-ear/DogEar.module.css
  packages/web/src/components/dog-ear/DogEar.tsx
  packages/web/src/components/track/LockedStatusBadge.module.css
  packages/web/src/components/track/LockedStatusBadge.tsx
  packages/web/src/components/track/PremiumConditionsPill.module.css
  packages/web/src/components/track/PremiumConditionsPill.tsx
  packages/web/src/components/track/PremiumContentLabel.module.css
  packages/web/src/components/track/PremiumContentLabel.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/BottomButtons.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/default.ts
Labels: size/L

#3725 [PAY-1514] Mobile USDC track screen changes
  packages/common/src/utils/formatUtil.ts
  packages/mobile/src/assets/images/iconLockUnlocked.svg
  packages/mobile/src/components/core/LockedStatusBadge.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XL

#3728 [C-2547] Lineup pagination fixes
  packages/common/src/models/Lineup.ts
  packages/common/src/store/lineup/reducer.ts
  packages/common/src/store/pages/ai/lineup/reducer.ts
  packages/common/src/store/pages/feed/lineup/reducer.ts
  packages/common/src/store/pages/profile/lineups/feed/reducer.ts
  packages/common/src/store/pages/profile/lineups/tracks/reducer.ts
  packages/common/src/store/pages/remixes/lineup/reducer.ts
  packages/common/src/store/pages/search-results/lineup/tracks/reducer.ts
Labels: size/S

#3726 Remove gated content feature flags from mobile
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/hooks/useIsCollectibleGatedEnabled.ts
  packages/mobile/src/hooks/useIsGatedContentEnabled.ts
  packages/mobile/src/hooks/useIsSpecialAccessEnabled.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/fields/TrackVisibilityField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
Labels: size/L

#3732 [QA-565] Fix notification overflow bug
  packages/stems/src/components/MarkdownViewer/MarkdownViewer.module.css
  packages/web/src/components/ai-attribution-settings-modal/AiAttributionSettingsModal.module.css
Labels: size/XS

#3731 Add dev storage bootstrap nodes
  packages/common/src/services/sdk/bootstrapNodes.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
Labels: size/S

#3734 [C-2844] Ensure all tracks fetched on collection page
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/pages/collection/sagas.js
Labels: size/S

#3730 [CON-765] Default v2 signup and fix local EM
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/.env.dev
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/.env/.env.dev
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#3727 [PAY-1561][PAY-1558] Implement USDC variants on track details page
  packages/stems/src/assets/styles/colors.css
  packages/stems/src/components/Button/Button.module.css
  packages/stems/src/components/Button/Button.stories.tsx
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/Button/types.ts
  packages/web/src/components/locked-content-modal/LockedContentModal.tsx
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/pages/track-page/components/HiddenTrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/ActionButtonRow.module.css
  packages/web/src/pages/track-page/components/mobile/StatsButtonRow.module.css
  packages/web/src/pages/track-page/components/mobile/StatsButtonRow.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XL

#3737 [C-2711] Remove app-store link in force-upgrade for saga
  packages/mobile/dapp-store/.asset-manifest.json
  packages/mobile/dapp-store/config.yaml
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
  packages/mobile/src/screens/update-required-screen/NewVersionPrompt.tsx
  packages/mobile/src/screens/update-required-screen/UpdateRequiredScreen.tsx
Labels: size/XXL

#3735 [C-1608 C-2750] Fix edit profile/cover photo
  packages/common/src/store/cache/reducer.ts
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
Labels: size/M

#3740 Notification cursor reflects clickability
  packages/web/src/components/notification/Notification/components/NotificationTile.module.css
Labels: size/XS

#3742 Bump app versions
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3743 Get the first storage node for o-auth not all of them
  packages/web/src/pages/oauth-login-page/utils.ts
Labels: size/XS

#3744 [PAY-1597] Fix mobile chat screen empty state font
  packages/mobile/src/screens/chat-screen/EmptyChatMessages.tsx
Labels: size/S

#3746 [PAY-1595] Hide chat textinput until chat exists
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.module.css
Labels: size/S

#3741 [C-2851] Add privacy policy to settings page
  packages/mobile/src/hooks/useIsOfflineModeEnabled.ts
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
  packages/web/src/components/groupable-list/Row.module.css
  packages/web/src/components/groupable-list/Row.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/AboutSettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#3748 [PAY-1599] Fix font in Start Conversation prompt
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
Labels: size/S

#3750 Fix android announcement notifs
  packages/mobile/src/screens/notifications-screen/Notifications/AnnouncementNotification.tsx
Labels: size/S

#3753 Manually set the libs state to prevent retry storm
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
Labels: size/XS

#3752 [PAY-1578] Hide USDC-gated tracks if the feature flag is disabled
  packages/web/src/common/store/lineup/sagas.js
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
Labels: size/M

#3757 [PAY-1607] Fix mobile prem content track tile layout
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/styles.ts
Labels: size/L

#3749 Use Text component in mobile DMs
  packages/mobile/src/screens/chat-screen/ChatMessageSeparator.tsx
  packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx
  packages/mobile/src/screens/chat-screen/ResendMessageButton.tsx
Labels: size/M

#3758 [PAY-1612] Change mobile hidden track header color
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#3759 [PAY-1621] Reverse order of mobile lineup tile stat icon and number
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/S

#3761 [C-2858] Fix phantom signing
  packages/web/src/store/token-dashboard/signMessage.ts
Labels: size/S

#3760 [C-2856] Fix track/collection artwork field
  packages/mobile/src/components/fields/PickArtworkField.tsx
  packages/mobile/src/screens/edit-playlist-screen/PlaylistArtworkField.tsx
  packages/mobile/src/screens/edit-playlist-screen/PlaylistImageInput.tsx
  packages/web/src/common/store/cache/tracks/sagas.js
Labels: size/L

#3764 [PAY-1639] Fix mobile hidden track dog ear
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#3763 [C-2853] Fix deletedCount calculation
  packages/web/src/common/store/lineup/sagas.js
Labels: size/XS

#3739 Remove unused notification announcement page
  packages/web/src/pages/App.js
  packages/web/src/pages/announcement-page/AnnoucementPage.tsx
  packages/web/src/pages/announcement-page/AnnouncementPage.module.css
  packages/web/src/utils/route.ts
Labels: size/L

#3762 [C-2842] Improve playlist image generation
  packages/common/src/hooks/useGeneratePlaylistArtwork.ts
  packages/common/src/store/cache/collections/selectors.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/playlist-library/helpers.test.js
  packages/common/src/store/playlist-library/helpers.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/updatePlaylistArtwork.ts
  packages/mobile/src/hooks/useContentNodeImage.ts
  packages/mobile/src/screens/edit-playlist-screen/PlaylistArtworkField.tsx
  packages/mobile/src/utils/createPlaylistArtwork.ts
  packages/mobile/src/utils/generatePlaylistArtwork.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/collections/utils/optimisticUpdateCollection.ts
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/image-selection/ImageSelectionButton.js
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/workers/generatePlaylistArtwork.worker.js
Labels: size/XL

#3747 Add Dapp store publishing in CI
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/workflows/mobile.yml
  .gitignore
  packages/mobile/dapp-store/README.md
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/XXL

#3767 [C-2650] Add playlist-library sanitization hook
  packages/common/src/models/PlaylistLibrary.ts
  packages/common/src/store/playlist-library/helpers.test.js
  packages/common/src/store/playlist-library/helpers.ts
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/useSanitizePlaylistLibrary.ts
Labels: size/XL

#3768 [C-2861] Replace private with hidden
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.js
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/messages.ts
Labels: size/S

#3771 [C-2846] Suggested Tracks QA
  packages/common/src/api/suggestedTracks.ts
  packages/mobile/src/components/core/IconButton.tsx
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistForm.tsx
  packages/web/src/assets/img/iconCaretDownLine.svg
  packages/web/src/assets/img/iconCaretUpLine.svg
  packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.module.css
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx
Labels: size/L

#3769 Remove usages of CN /health_check/verbose
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/models/Analytics.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/utils/route/userRouteParser.test.js
Labels: size/M

#3772 Add fallback url to embed
  packages/embed/src/util/BedtimeClient.js
  packages/embed/src/util/gatewayUtil.js
  packages/embed/src/util/getArtworkUrl.js
Labels: size/S

#3773 [C-2872] Fix image retries
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/M

#3766 [PAY-1638] Fix iconLockUnlocked icon
  packages/mobile/src/assets/images/iconLockUnlocked.svg
Labels: size/XS

#3776 Add support for UDSC Mint in Client
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/.env.dev
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/src/services/audius-backend-instance.ts
  packages/web/.env/.env.dev
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  scripts/link-sdk.sh
Labels: size/S

#3765 [PAY-1634] Fix hidden track tile + add share button
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/L

#3777 [C-2866] Undo secondary button style changes
  packages/stems/src/components/Button/Button.module.css
Labels: size/S

#3775 [PAY-1618] Update DogEar rendering and fix spacing
  packages/mobile/src/assets/images/dogEarRectangle.svg
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/card/CollectionDogEar.tsx
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/web/src/assets/img/dogEarRectangle.svg
  packages/web/src/components/dog-ear/DogEar.module.css
  packages/web/src/components/dog-ear/DogEar.tsx
  packages/web/src/components/tile/Tile.module.css
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#3780 [PAY-1615] Fix display of "Artist Pick" text
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/L

#3779 [PAY-1620] Fix disabled play button for unlocked gated tracks on Mobile Web
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XS

#3781 [PAY-1575] Always show premium DogEars on track details page
  packages/common/src/utils/dogEarUtils.ts
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/S

#3782 [PAY-1635] Always show share button for track owners on hidden tracks
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XS

#3784 Change mobile drawer background to white
  packages/mobile/src/components/drawer/Drawer.tsx
Labels: size/XS

#3783 Fix mobile premcontent locked badge colors
  packages/mobile/src/components/core/LockedStatusBadge.tsx
Labels: size/S

#3786 [PAY-1652] Update LockedContentDrawer on mobile
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/components/track-details-tile/index.ts
Labels: size/L

#3787 [C-2877] Address suggested-tracks qa #2
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/utils/updatePlaylistArtwork.ts
  packages/web/src/common/store/cache/collections/utils/optimisticUpdateCollection.ts
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.module.css
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
Labels: size/L

#3789 Update to reroute to trending when deleting a playlist if the playlist is viewed
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/store/application/ui/editPlaylistModal/selectors.ts
  packages/web/src/store/application/ui/editPlaylistModal/slice.ts
Labels: size/M

#3778 [C-2680] Attribution Modal
  packages/common/src/hooks/usePremiumContent.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/screens/edit-track-screen/fields/LicenseTypeField.tsx
  packages/stems/src/components/SegmentedControl/SegmentedControl.module.css
  packages/stems/src/components/SegmentedControl/SegmentedControl.tsx
  packages/stems/src/components/SegmentedControl/types.ts
  packages/web/src/assets/img/creativeCommons/by.svg
  packages/web/src/assets/img/creativeCommons/cc.svg
  packages/web/src/assets/img/creativeCommons/nc.svg
  packages/web/src/assets/img/creativeCommons/nd.svg
  packages/web/src/assets/img/creativeCommons/sa.svg
  packages/web/src/assets/img/iconCreativeCommons.svg
  packages/web/src/components/layout/layout.module.css
  packages/web/src/pages/upload-page/components/TrackModalArray.tsx
  packages/web/src/pages/upload-page/fields/ModalField.module.css
  packages/web/src/pages/upload-page/fields/ModalField.tsx
  packages/web/src/pages/upload-page/forms/AttributionModalForm.module.css
  packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
  packages/web/src/pages/upload-page/forms/RemixModalForm.module.css
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.module.css
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.module.css
  packages/web/src/pages/upload-page/utils/computeLicenseIcons.ts
Labels: size/XL

#3790 Fix mobile LockedStatusBadge padding
  packages/mobile/src/components/core/LockedStatusBadge.tsx
Labels: size/XS

#3770 [plat-1111] add usdc purchase seller and buyer notifications
  package-lock.json
  packages/common/src/models/Analytics.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/web/src/assets/img/iconCart.svg
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseSellerNotification.tsx
  packages/web/src/components/notification/Notification/components/icons.module.css
  packages/web/src/components/notification/Notification/components/icons.tsx
Labels: size/XL

#3788 [C-2883] Migrate confirmer to common
  packages/common/src/store/confirmer/actions.ts
  packages/common/src/store/confirmer/index.ts
  packages/common/src/store/confirmer/reducer.ts
  packages/common/src/store/confirmer/sagas.ts
  packages/common/src/store/confirmer/selectors.ts
  packages/common/src/store/confirmer/store.test.ts
  packages/common/src/store/confirmer/types.ts
  packages/common/src/store/index.ts
  packages/common/src/store/reducers.ts
  packages/common/src/utils/updatePlaylistArtwork.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/store/store.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/collections/confirmOrderPlaylist.js
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/common/store/cache/store.test.js
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/confirmer/store.test.ts
  packages/web/src/common/store/pages/deactivate-account/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/token-dashboard/addWalletToUser.ts
  packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/components/confirmer-preview/ConfirmerPreview.tsx
  packages/web/src/components/unload-dialog/UnloadDialog.js
  packages/web/src/store/lineup/store.test.js
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
Labels: size/XXL

#3793 [PAY-1587] Mobile USDC Purchase Drawer Skeleton
  packages/common/src/models/Track.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup-tile/LineupTilePremiumContentTypeTag.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/index.ts
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/L

#3792 [C-2886] Improve cache performance
  packages/common/src/models/Cache.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/store/cache/actions.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/cache/selectors.ts
  packages/common/src/store/cache/types.ts
  packages/common/src/store/cache/users/utils.ts
  packages/common/src/store/index.ts
  packages/common/src/store/put.ts
  packages/mobile/src/screens/collection-screen/useFetchCollectionLineup.ts
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/utils/addUsersFromCollections.ts
  packages/web/src/common/store/cache/collections/utils/processAndCacheCollections.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/common/store/cache/tracks/utils/helpers.ts
  packages/web/src/common/store/cache/tracks/utils/processAndCacheTracks.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/components/collection/desktop/Artwork.tsx
Labels: size/L

#3794 [PAY-1651] Implements Harmony Buttons
  packages/stems/src/assets/icons/iconCampFire.svg
  packages/stems/src/assets/icons/iconCampfire.svg
  packages/stems/src/assets/styles/animations.css
  packages/stems/src/assets/styles/colors.css
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/HarmonyButton/HarmonyButton.module.css
  packages/stems/src/components/HarmonyButton/HarmonyButton.stories.tsx
  packages/stems/src/components/HarmonyButton/HarmonyButton.tsx
  packages/stems/src/components/HarmonyButton/index.ts
  packages/stems/src/components/HarmonyButton/types.ts
  packages/stems/src/components/Icons/index.ts
  packages/stems/src/components/Icons/types.ts
  packages/stems/src/index.tsx
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/public-site/NavBanner.tsx
  packages/web/src/components/public-site/NavOverlay.tsx
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/default.ts
  packages/web/src/utils/theme/matrix.ts
Labels: size/XL

#3797 Revert cacheActions.add thunk
  packages/common/src/store/cache/actions.ts
  packages/common/src/store/cache/users/utils.ts
  packages/common/src/store/index.ts
  packages/common/src/store/put.ts
  packages/mobile/src/screens/collection-screen/useFetchCollectionLineup.ts
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/utils/addUsersFromCollections.ts
  packages/web/src/common/store/cache/collections/utils/processAndCacheCollections.ts
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/common/store/cache/tracks/utils/helpers.ts
  packages/web/src/common/store/cache/tracks/utils/processAndCacheTracks.ts
Labels: size/L

#3799 [PAY-1655] Add ColorValue prop to Text component
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
Labels: size/M

#3800 [C-2887] Fix collection button widths
  packages/web/src/components/collection/desktop/utils.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/S

#3801 Prepare for 1.5.34 full app release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3802 [C-2857] Remove get blocknumber
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/components/collection/desktop/Artwork.tsx
Labels: size/S

#3804 Fix mobile prem-content drawer unlocking margin
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
Labels: size/XS

#3796 [C-2890] Add first version of a typography component to web
  packages/web/src/components/typography/Text.tsx
  packages/web/src/components/typography/constants.ts
  packages/web/src/components/typography/index.ts
  packages/web/src/components/typography/types.ts
  packages/web/src/components/typography/typography.module.css
Labels: size/L

#3798 Switch to Stripe package instead of script
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/public/index.html
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
Labels: size/S

#3805 Update typography component to use classnames
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/BottomButtons.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/typography/Text.tsx
  packages/web/src/components/typography/constants.ts
  packages/web/src/components/typography/types.ts
  packages/web/src/components/typography/typography.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
Labels: size/L

#3807 [C-801] Fix oauth nodes
  packages/web/src/pages/oauth-login-page/utils.ts
Labels: size/XS

#3809 [C-2902] Update the upload forms to use the typography component
  packages/web/src/pages/upload-page/fields/SourceFilesView.module.css
  packages/web/src/pages/upload-page/fields/SourceFilesView.tsx
  packages/web/src/pages/upload-page/fields/SwitchRowField.module.css
  packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
  packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
  packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.module.css
  packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.tsx
  packages/web/src/pages/upload-page/forms/RemixModalForm.module.css
  packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.module.css
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.tsx
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.module.css
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
Labels: size/L

#3808 [PAY-1624] Implement Purchase modal
  packages/common/src/store/premium-content/selectors.ts
  packages/common/src/store/premium-content/slice.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/stems/src/assets/styles/colors.css
  packages/stems/src/index.tsx
  packages/web/src/components/Icon/Icon.module.css
  packages/web/src/components/Icon/Icon.tsx
  packages/web/src/components/locked-content-modal/LockedContentModal.module.css
  packages/web/src/components/locked-content-modal/LockedContentModal.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.module.css
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/LoadingPage.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.module.css
  packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.module.css
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.module.css
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
  packages/web/src/components/track/LockedStatusBadge.tsx
  packages/web/src/components/track/LockedTrackDetailsTile.module.css
  packages/web/src/components/track/LockedTrackDetailsTile.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/typography/typography.module.css
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XL

#3810 [C-2905] Update Text types and props to camelCase
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
  packages/web/src/components/typography/Text.tsx
  packages/web/src/components/typography/constants.ts
  packages/web/src/components/typography/types.ts
  packages/web/src/pages/upload-page/fields/SourceFilesView.tsx
  packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
  packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
  packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.tsx
  packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.tsx
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
Labels: size/L

#3811 [C-2901] Fix menu types
  packages/web/src/components/card/desktop/CollectionArtCard.tsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/menu/Menu.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/table/components/OverflowMenuButton.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/L

#3806 [C-2774] Update upload inputs
  packages/web/src/components/data-entry/DropdownInput.d.ts
  packages/web/src/components/data-entry/DropdownInput.js
  packages/web/src/components/data-entry/HelperText.module.css
  packages/web/src/components/data-entry/HelperText.tsx
  packages/web/src/components/data-entry/InputV2.module.css
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/data-entry/TagInput.d.ts
  packages/web/src/components/data-entry/TagInput.js
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/form-fields/ArtworkField.tsx
  packages/web/src/components/form-fields/DropdownField.tsx
  packages/web/src/components/form-fields/TagField.tsx
  packages/web/src/components/form-fields/TextField.tsx
  packages/web/src/components/form-fields/index.ts
  packages/web/src/components/image-selection/ImageSelectionButton.js
  packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
  packages/web/src/components/upload/UploadArtwork.d.ts
  packages/web/src/components/upload/UploadArtwork.js
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/fields/ContextualSubmenuField.module.css
  packages/web/src/pages/upload-page/fields/TextField.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.tsx
Labels: size/XL

#3813 Pin stripe package versions
  packages/web/package.json
Labels: size/XS

#3815 [PAY-1660] Fix layout issues with TrackTile socials row with a lot of stats
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.module.css
Labels: size/S

#3816 [C-2908 C-2744] fix desktop follow button
  packages/web/src/components/follow-button/FollowButton.tsx
  packages/web/src/components/stat-banner/StatBanner.module.css
  packages/web/src/components/stat-banner/StatBanner.tsx
Labels: size/L

#3814 [PAY-1589] Wire up Stripe Onramp in mobile
  packages/common/src/store/account/selectors.ts
  packages/mobile/.env.dev
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/StripePurchaseConfirmationButton.tsx
  packages/mobile/src/components/stripe-onramp-embed/StripeOnrampEmbed.tsx
  packages/mobile/src/components/stripe-onramp-embed/index.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/services/buyCrypto.ts
  packages/mobile/src/services/env.ts
Labels: size/L

#3821 Update bootstrap nodes
  packages/common/src/services/sdk/bootstrapNodes.ts
Labels: size/XS

#3822 Use audius-query in USDC Purchase Drawer
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Labels: size/S

#3819 Update SDK version + ActivityFull type
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/api/developerApps.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/embed/package-lock.json
  packages/embed/package.json
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/sdk/auth.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/audius-sdk/auth.ts
Labels: size/M

#3820 Add purchased + reposted tracks to library PAY-1633
  packages/web/src/common/store/pages/saved/lineups/sagas.js
  packages/web/src/common/store/pages/saved/sagas.js
  packages/web/src/common/store/pages/saved/sagas.ts
Labels: size/L

#3825 Revert "Add purchased + reposted tracks to library PAY-1633 (#3820)"
  packages/web/src/common/store/pages/saved/lineups/sagas.js
  packages/web/src/common/store/pages/saved/sagas.js
  packages/web/src/common/store/pages/saved/sagas.ts
Labels: size/L

#3827 Bump mobile versions for client v1.5.35 full app release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3818 [C-2742] Multi-track form pagination
  packages/web/src/components/data-entry/TagInput.d.ts
  packages/web/src/components/data-entry/TagInput.js
  packages/web/src/components/form-fields/TagField.tsx
  packages/web/src/components/form-fields/TextAreaField.tsx
  packages/web/src/pages/upload-page/components/EditPageNew.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
  packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.tsx
  packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
  packages/web/src/pages/upload-page/forms/SourceFilesModalForm.tsx
  packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
  packages/web/src/pages/upload-page/forms/types.ts
  packages/web/src/pages/upload-page/forms/utils.ts
Labels: size/L

#3826 [C-2857] Revert remove get blocknumber (#3802)"
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
Labels: size/S
