Repository AudiusProject/audius-client, pull requests merged in 2023-04, with the labels that each got.

#3141 [C-2391 PLAT-833] Handle get-discovery-notification error, notification processing
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
Labels: size/L

#3143 [PLAT-834]: Fix notifications last seen new tag
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/components/nav/desktop/NavColumn.tsx
Labels: size/XS

#3107 update to xcode 14.2.0
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  .ruby-version
Labels: size/M

#3145 [C-2398] Clean up playlist-update feature flags
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/cache/users/reducer.ts
  packages/common/src/store/pages/chat/middleware.ts
  packages/common/src/store/playlist-updates/playlistUpdatesSagas.ts
  packages/common/src/store/playlist-updates/playlistUpdatesSelectors.ts
  packages/common/src/store/premium-content/sagas.ts
Labels: size/M

#3146 [C-2404] Fix ios build on xcode 14.3
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: size/S

#3148 [C-2406] Prevent non finite set of currentTime
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/XS

#3147 [C-2227] Clear wallet state on sign-out
  packages/common/src/store/cache/tracks/selectors.ts
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/store/sign-out/sagas.ts
Labels: size/M

#3150 [C-2406] Null check localStorage
  packages/web/src/store/storeContext.ts
Labels: size/XS

#3149 [C-2336, C-2388] Playlist style and bug fixes
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
Labels: size/S

#3153 Mobile chats scrolling improvements
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#3157 [C-2406] Fix repeated edits of same track
  packages/web/src/common/store/cache/tracks/sagas.js
Labels: size/XS

#3154 Mobile chats use push instead of navigate
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/store/chat/sagas.ts
Labels: size/S

#3151 [PLAT-819]: Fix copy for repost and save of albums notifications
  packages/mobile/src/screens/notifications-screen/Notifications/FavoriteNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FavoriteOfRepostNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RepostNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RepostOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/FavoriteNotification.tsx
  packages/web/src/components/notification/Notification/FavoriteOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/RepostNotification.tsx
  packages/web/src/components/notification/Notification/RepostOfRepostNotification.tsx
Labels: size/M

#3161 Fix permissions message for adding to photos C-2379
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3164 [C-2419] Fix offline lineup loading
  packages/mobile/src/hooks/useReachabilityEffect.ts
Labels: size/S

#3166 [C-2059] Show toast when email check fails due to blocked user
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/S

#3167 [QA-443] Fix cache case matching for handles and permalinks
  packages/common/src/store/cache/collections/reducer.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/common/src/store/cache/users/reducer.ts
Labels: size/S

#3160 Update @audius/sdk to 2.0.3-beta.4
  packages/common/package-lock.json
  packages/common/package.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/XS

#3165 [C-2364] Fix missing artist-card badges on android
  packages/mobile/src/components/card/Card.tsx
Labels: size/S

#3168 [C-2347] Improve popover zIndex
  packages/stems/src/assets/styles/layers.css
  packages/stems/src/components/Popup/Popup.module.css
  packages/stems/src/index.tsx
Labels: size/S

#3155 [PAY-924][Desktop] DMs: Blocking/Unblocking Wire Up/UI
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/L

#3096 [PAY-799] DMs: Link previews
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/LinkPreview.module.css
  packages/web/src/pages/chat-page/components/LinkPreview.tsx
Labels: size/L

#3125 [PLAT-814] Use sdk discovery-node-selection in libs
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorInstance.ts
  packages/common/src/services/discovery-node-selector/index.ts
  packages/common/src/services/index.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/pages/chat/middleware.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/services/audius-api-client/apiClient.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/services/audius-sdk.ts
  packages/mobile/src/services/discovery-node-selector.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/audius-api-client/apiClient.ts
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/audius-sdk/audiusSdk.ts
  packages/web/src/services/discovery-node-selector.ts
Labels: size/L

#3163 Fix edit profile button not working after you submit the first time
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
Labels: size/S

#3169 [PAY-1143] Desktop: Overflow menu on Chat Header
  packages/stems/src/assets/icons/iconTrash.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/pages/chat-page/components/ChatHeader.module.css
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
Labels: size/M

#3159 [PAY-1041][PAY-1040][PAY-1126] Mobile search users screen improvements
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Labels: size/M

#3171 Fix scrolling on ChatListScreen
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
Labels: size/XS

#3156 [PAY-829][PAY-1044] Desktop: Chats search users modal permissions/blocks and profile page permissions/blocks
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.module.css
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/L

#3172 Disallow sharing premium content to social media, remove feature flags C-2334 C-2420
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/M

#3178 Update readme with deps, remove sudo
  README.md
  packages/mobile/README.md
Labels: size/M

#3179 [C-2427] Fix preinstall checks for ruby and python versions
  scripts/preinstall.sh
Labels: size/XS

#3174 Use RNGH touchables for mobile chats
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Labels: size/S

#3170 [PAY-1127] Improve mobile chats performance: remove index dep
  packages/common/src/models/Chat.ts
  packages/common/src/models/index.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Labels: size/L

#3184 [C-2428] Handle null in cache map handle/permalink adds
  packages/common/src/store/cache/collections/reducer.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/common/src/store/cache/users/reducer.ts
Labels: size/S

#3138 Fix track upload cover art name
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/components/data-entry/FormTile.js
Labels: size/S

#3182 Fix missing track on Sammie's page C-2342
  packages/mobile/src/screens/profile-screen/TracksTab.tsx
Labels: size/S

#3176 Fix Snap sharing with weird track names C-2081
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
Labels: size/XS

#3186 [C-2306] Fix sign-in sign-up invalid email bug
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/S

#3187 [C-1504] Prevent user from following themselves
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#3173 [C-2418] Fix mobile web open in app banner
  packages/web/scripts/workers-site/index.js
  packages/web/src/app.tsx
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
  packages/web/src/pages/App.d.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/App.test.tsx
  packages/web/src/root.tsx
Labels: size/M

#3188 [C-2412] Opaque id deeplinks
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Labels: size/M

#3162 [PLAT-847]: Fix user subscription create album notification copy
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
Labels: size/XS

#3189 No playlists text fix C-2296
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
Labels: size/XS

#3191 [C-2431] Add tastmaker notification to mobile
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/assets/images/iconTastemaker.svg
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TastemakerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/web/src/assets/img/iconTastemaker.svg
  packages/web/src/components/notification/Notification/components/icons.tsx
Labels: size/L

#3190 allow create notification to handle playlist id as array or int
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#3192 [C-2287] Update wallet connect language, flags, icons
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/iconWallet.svg
  packages/mobile/src/components/connect-wallets-drawer/ConnectWalletsDrawer.tsx
  packages/mobile/src/components/connect-wallets-drawer/index.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/web/src/components/mobile-connect-wallets-drawer/MobileConnectWalletsDrawer.tsx
  packages/web/src/pages/audio-rewards-page/Tiles.tsx
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletActionsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/L

#3194 [C-2187] Improve sign-up error messages
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/sign-on/components/desktop/EmailPage.tsx
Labels: size/M

#3183 [C-2271] Update data passed to edit playlist form to update playlist properly
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
Labels: size/XS

#3196 [C-2223] Flex on Finnuh
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/M

#3195 [C-2303] Ensure consistent play/active state for entity tiles
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
Labels: size/XXL

#3197 [C-2309] Fix track title hover state
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/XS

#3185 [PAY-918] Mobile chat link unfurling
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/LinkPreview.tsx
  packages/mobile/src/screens/chat-screen/constants.ts
Labels: size/L

#3201 [C-2434] Fix remix image styles
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
Labels: size/M

#3198 [C-2332] Fix follow artist stat
  packages/common/src/store/cache/users/utils.ts
Labels: size/XS

#3199 [PAY-1152] Chats selector to check if is equal to popupMessageId
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/M

#3158 [C-2406] Fix app crash when profile cid fails to fetch
  packages/web/src/common/store/profile/sagas.js
Labels: size/M

#3204 [C-2441] Improve icon-verified styles
  packages/mobile/src/assets/images/iconVerified.svg
  packages/mobile/src/assets/images/iconVerifiedGreen.svg
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/utils/theme.ts
  packages/web/src/assets/img/iconVerifiedGreen.svg
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PremiumTrackSection.tsx
Labels: size/M

#3207 [C-2335] Fix smart collection track count
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/XS

#3208 [C-2082] Fix busted profile edits
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/components/image/UserCoverImage.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
  packages/web/src/common/store/cache/sagas.js
  packages/web/src/common/store/cache/users/sagas.js
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/L

#3193 [PAY-1156] Cache message link unfurl responses
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useLinkUnfurlMetadata.ts
  packages/common/src/models/Chat.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/LinkPreview.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/LinkPreview.tsx
Labels: size/L

#3203 [PAY-748] Fix supporter count alignment
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/mobile/src/screens/notifications-screen/Notification/constants.ts
Labels: size/M

#3213 [C-2444] Fix notification panel notification count
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/S

#3215 Fix safari refresh event not being captured
  packages/web/src/components/unload-dialog/UnloadDialog.js
Labels: size/XS

#3216 [C-2321] Update notification entity link styles to prevent overflow
  packages/web/src/components/notification/Notification/components/EntityLink.module.css
Labels: size/XS

#3202 [PAY-827][PAY-1154] Use DN stream endpoint for track download and offline mode
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/services/track-download/TrackDownload.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/store/social/tracks/actions.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/streaming.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/services/track-download.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/services/track-download.ts
Labels: size/L

#3220 Fix lint
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/S

#3222 Fix the entity id in supporter rank up notification
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#3223 [C-2422] Update linkify links to navigate audius links in app and external links in new tab
  packages/common/src/utils/index.ts
  packages/common/src/utils/urlUtils.ts
  packages/web/src/components/collection/desktop/CollectionHeader.js
  packages/web/src/components/track/GiantTrackTile.js
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#3217 Gate v2 signups
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/S

#3212 [C-2442] Remove cognito
  packages/common/src/models/Analytics.ts
  packages/common/src/models/AudioRewards.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/Rewards.ts
  packages/common/src/services/cognito/Cognito.ts
  packages/common/src/services/cognito/index.ts
  packages/common/src/services/index.ts
  packages/common/src/store/pages/audio-rewards/selectors.ts
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/common/src/store/pages/audio-rewards/types.ts
  packages/common/src/store/storeContext.ts
  packages/common/src/store/ui/modals/slice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/cognito-drawer/CognitoDrawer.tsx
  packages/mobile/src/services/cognito.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/.env/.env.dev
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/store.test.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/CognitoModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/RewardsModals.tsx
  packages/web/src/pages/check-page/CheckPage.module.css
  packages/web/src/pages/check-page/CheckPage.tsx
  packages/web/src/services/audius-backend/Cognito.ts
  packages/web/src/services/cognito.ts
  packages/web/src/store/storeContext.ts
  packages/web/src/utils/constants.ts
  packages/web/src/utils/route.ts
  packages/web/src/utils/zIndex.ts
Labels: size/XL

#3218 [PAY-1128] Update logic for showing "earn/claim $AUDIO" pill
  packages/common/src/store/wallet/selectors.ts
  packages/common/src/store/wallet/slice.ts
  packages/web/src/components/nav/desktop/NavAudio.module.css
  packages/web/src/components/nav/desktop/NavAudio.tsx
Labels: size/L

#3229 Only mark notifications as viewed when notif panel is open
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/XS

#3228 Revert "[PAY-827][PAY-1154] Use DN stream endpoint for track download and offline mode (#3202)
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/services/track-download/TrackDownload.ts
  packages/common/src/store/social/tracks/actions.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/streaming.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/services/track-download.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/services/track-download.ts
Labels: size/L

#3224 [C-2448] Fix common dependencies and lint
  .circleci/src/commands/@commands.yml
  .circleci/src/commands/@common-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  package-lock.json
  package.json
  packages/common/.eslintrc.js
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/account/index.ts
  packages/common/src/store/account/slice.ts
  packages/common/src/store/collectibles/index.ts
  packages/common/src/store/collectibles/slice.ts
  packages/common/src/store/premium-content/index.ts
  packages/common/src/store/premium-content/sagas.ts
  packages/common/src/store/premium-content/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/utils/timeUtil.ts
  packages/eslint-config-audius/package.json
  packages/eslint-config-audius/src/index.js
  packages/mobile/metro.config.js
  packages/web/craco.config.ts
Labels: size/L

#3225 [C-2429] Remove hls
  packages/common/src/services/audio-player.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/utils/hls.test.js
  packages/common/src/utils/hls.ts
  packages/common/src/utils/index.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/components/audio/Audio.tsx
  packages/web/package.json
  packages/web/scripts/publishScripts.sh
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/services/audio-player/AudioPlayer.test.js
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/setupTests.js
Labels: size/XL

#3231 [C-2219] Hide desktop modals until needed
  packages/stems/src/components/Modal/Modal.tsx
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/RewardsModals.tsx
  packages/web/src/pages/modals/AppModal.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#3211 [PAY-986][PAY-1087][PAY-1091] Fix a bunch of UI issues
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/HiddenAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/PremiumTrackSection.tsx
Labels: size/XL

#3233 Improve oauth errors/logging
  packages/mobile/src/store/oauth/sagas.ts
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/twitter-auth/TwitterAuth.tsx
Labels: size/S

#3227 [PAY-1140] Prevent spacebar from attempting to play inaccessible tracks
  packages/common/src/store/lineup/selectors.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/streaming.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/play-bar/desktop/PlayBar.js
Labels: size/L

#3235 Fix lint in common
  packages/common/src/utils/streaming.ts
Labels: size/S

#3232 [C-2440] Remove useThemedStyles
  packages/mobile/src/components/action-drawer/ActionDrawer.tsx
  packages/mobile/src/components/button/Button.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx
  packages/mobile/src/components/challenge-rewards-drawer/TwitterShareButton.tsx
  packages/mobile/src/components/details-tile/DetailsStat.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
  packages/mobile/src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
  packages/mobile/src/components/edit-collectibles-drawer/EditCollectiblesDrawer.tsx
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/components/forgot-password-drawer/ForgotPasswordDrawer.tsx
  packages/mobile/src/components/lineup-tile/LineupTileRankIcon.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup/Delineator.tsx
  packages/mobile/src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx
  packages/mobile/src/hooks/useThemedStyles.ts
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/utils/theme.ts
Labels: size/XXL

#3236 Fix dev-mode hot-key modals
  packages/web/src/pages/App.js
  packages/web/src/pages/modals/Modals.tsx
Labels: size/S

#3230 [C-2338][C-2487][C-2489] Add Related Artists on Profile (web)
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/artist-recommendations/selectors.ts
  packages/common/src/store/ui/artist-recommendations/slice.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/common/src/store/ui/related-artists/selectors.ts
  packages/common/src/store/ui/related-artists/slice.ts
  packages/common/src/store/ui/related-artists/types.ts
  packages/common/src/store/user-list/index.ts
  packages/common/src/store/user-list/related-artists/actions.ts
  packages/common/src/store/user-list/related-artists/reducers.ts
  packages/common/src/store/user-list/related-artists/selectors.ts
  packages/common/src/store/user-list/related-artists/types.ts
  packages/common/src/utils/constants.ts
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/store/sagas.ts
  packages/stems/src/assets/icons/iconUserGroup.svg
  packages/stems/src/components/Icons/index.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/user-list/related-artists/errorSagas.ts
  packages/web/src/common/store/user-list/related-artists/sagas.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/related-artists/RelatedArtists.module.css
  packages/web/src/components/related-artists/RelatedArtists.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/store/application/ui/userListModal/sagas.ts
  packages/web/src/store/application/ui/userListModal/types.ts
  packages/web/src/store/sagas.ts
Labels: size/XL

#3234 [PAY-937] Fix empty state for transactions table
  packages/common/src/models/Status.ts
  packages/common/src/store/pages/audio-transactions/selectors.ts
  packages/common/src/store/pages/audio-transactions/slice.ts
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
Labels: size/L

#3238 Bump mobile version
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#3239 Fix call to player.getPosition
  packages/web/src/common/store/player/sagas.ts
Labels: size/XS

#3241 Remove service selection modal
  package-lock.json
  packages/mobile/package-lock.json
  packages/web/package-lock.json
  packages/web/src/common/store/service-selection/errorSagas.ts
  packages/web/src/common/store/service-selection/sagas.ts
  packages/web/src/common/store/service-selection/selectors.ts
  packages/web/src/common/store/service-selection/slice.ts
  packages/web/src/common/store/service-selection/store.test.js
  packages/web/src/components/service-selection/SelectedServices.module.css
  packages/web/src/components/service-selection/SelectedServices.tsx
  packages/web/src/components/service-selection/ServiceSelectionModal.js
  packages/web/src/components/service-selection/ServiceSelectionModal.module.css
  packages/web/src/components/service-selection/components/Service.js
  packages/web/src/components/service-selection/components/Service.module.css
  packages/web/src/components/service-selection/index.ts
  packages/web/src/components/service-selection/utils.ts
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/upload-page/components/SelectPage.js
  packages/web/src/store/configureStore.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/sagas.ts
  packages/web/src/store/types.ts
Labels: size/XXL

#3237 [C-2494] Refactor drag-drop to typescript + performance
  package-lock.json
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useDebouncedCallback.ts
  packages/common/src/hooks/useThrottledCallback.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/playlist-library/helpers.ts
  packages/mobile/package-lock.json
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/stems/src/components/Scrollbar/Scrollbar.tsx
  packages/web/package-lock.json
  packages/web/src/components/dragndrop/Draggable.js
  packages/web/src/components/dragndrop/Draggable.tsx
  packages/web/src/components/dragndrop/Droppable.js
  packages/web/src/components/dragndrop/Droppable.tsx
  packages/web/src/components/dragndrop/index.ts
  packages/web/src/components/lineup/CardLineup.tsx
  packages/web/src/components/nav/desktop/NavColumn.tsx
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/store/dragndrop/actions.js
  packages/web/src/store/dragndrop/reducer.js
  packages/web/src/store/dragndrop/selectors.js
  packages/web/src/store/dragndrop/slice.ts
  packages/web/src/store/dragndrop/types.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/XL

#3242 PLAT-725: browser push misconfigured
  packages/web/src/store/account/sagas.ts
Labels: size/S

#3240 [C-2486] Add Related Artists on Profile (mobile)
  packages/mobile/src/assets/images/iconUserGroup.svg
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileRelatedArtistsButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/user-list-screen/RelatedArtistsScreen.tsx
  packages/mobile/src/screens/user-list-screen/index.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/user-list/related-artists/sagas.ts
Labels: size/L

#3243 [C-2495] Refactor left-nav to typescript, update naming, improve perf
  packages/common/src/store/upload/selectors.ts
  packages/web/src/components/nav/Navigator.module.css
  packages/web/src/components/nav/Navigator.tsx
  packages/web/src/components/nav/desktop/LeftNav.module.css
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/NavButton.js
  packages/web/src/components/nav/desktop/NavButton.tsx
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/components/nav/desktop/RouteNav.js
  packages/web/src/components/nav/desktop/RouteNav.tsx
  packages/web/src/components/nav/mobile/ConnectedBottomBar.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/pages/App.js
Labels: size/XL

#3245 [C-574] Add migration path to @react-spring/web
  packages/stems/.eslintrc.js
  packages/stems/src/components/Modal/Modal.tsx
  packages/stems/src/components/Modal/ModalContentPages.tsx
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/components/SegmentedControl/SegmentedControl.tsx
  packages/web/.eslintrc.js
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/animated-switch/AnimatedSwitch.tsx
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
  packages/web/src/components/artist-recommendations/ArtistRecommendationsDropdown.tsx
  packages/web/src/components/change-password/ConfirmCredentials.tsx
  packages/web/src/components/drawer/Drawer.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/nav/desktop/NavAudio.tsx
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/components/now-playing/NowPlayingDrawer.tsx
  packages/web/src/components/page/Page.js
  packages/web/src/components/perspective-card/PerspectiveCard.tsx
  packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx
  packages/web/src/components/profile-progress/ConnectedProfileCompletionHeroCard.js
  packages/web/src/components/profile-progress/ConnectedProfileCompletionPane.js
  packages/web/src/components/profile-progress/components/ProfileCompletionHeroCard.js
  packages/web/src/components/profile-progress/components/ProfileCompletionPanel.js
  packages/web/src/components/profile-progress/hooks/index.js
  packages/web/src/components/pull-to-refresh/PullToRefresh.tsx
  packages/web/src/components/pull-to-refresh/hooks.ts
  packages/web/src/components/search/SearchBar.js
  packages/web/src/components/sign-on/SignOnModal.js
  packages/web/src/components/status-message/StatusMessage.js
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/components/toast/ToastContext.tsx
  packages/web/src/components/transition-container/TransitionContainer.tsx
  packages/web/src/components/upload/InvalidFileType.js
  packages/web/src/hooks/useCardWeight.ts
  packages/web/src/hooks/useTabs/useTabs.tsx
  packages/web/src/pages/landing-page/components/ArtistTestimonials.tsx
  packages/web/src/pages/landing-page/components/CTAListening.tsx
  packages/web/src/pages/landing-page/components/Description.tsx
  packages/web/src/pages/landing-page/components/FeaturedContent.tsx
  packages/web/src/pages/landing-page/components/JoinTheCommunity.tsx
  packages/web/src/pages/landing-page/components/PlatformFeatures.tsx
  packages/web/src/pages/landing-page/components/PlatformTagline.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/mobile/GrowingCoverPhoto.tsx
  packages/web/src/pages/sign-on/components/CompleteProfileWithSocial.tsx
  packages/web/src/pages/sign-on/components/ProfileForm.tsx
  packages/web/src/pages/sign-on/components/desktop/EmailPage.tsx
  packages/web/src/pages/sign-on/components/desktop/SignInPage.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
  packages/web/src/pages/sign-on/components/mobile/InitialPage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
  packages/web/src/pages/upload-page/UploadPage.js
Labels: size/M

#3247 [C-2493] separate state for suggested follows vs related artists
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/common/src/store/ui/related-artists/selectors.ts
  packages/common/src/store/ui/related-artists/slice.ts
  packages/common/src/store/ui/related-artists/types.ts
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/M

#3249 Fix signout test
  packages/common/src/store/lineup/selectors.ts
  packages/web/src/components/play-bar/desktop/PlayBar.js
Labels: size/S

#3248 Run CI flows when certain files change
  .circleci/config.yml
Labels: size/XS

#3251 Update TOS
  packages/web/public/documents/ServiceTerms.pdf
  packages/web/public/documents/TermsOfUse.pdf
  packages/web/src/pages/PublicSite.tsx
  packages/web/src/pages/service-terms-page/ServiceTermsPage.module.css
  packages/web/src/pages/service-terms-page/ServiceTermsPage.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#3250 [C-2501] Use proxy-wormhole libs
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/craco.config.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/audius-backend/getLibs.ts
Labels: size/M

#3253 C-2502: extend store history
  packages/web/src/store/configureStore.ts
Labels: size/XS

#3254 Fix react-router issues
  packages/web/craco.config.ts
Labels: size/XS

#3252 PLAT-725: fix browser push
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/store/sagas.ts
Labels: size/XS

#3246 [PAY-1166] Make SDK respect DN override (client-side)
  packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorInstance.ts
  packages/common/src/services/local-storage/LocalStorage.ts
  packages/mobile/src/services/discovery-node-selector.ts
  packages/web/src/services/discovery-node-selector.ts
Labels: size/M

#3257 fix lint
  packages/web/src/store/sagas.ts
Labels: size/XS

#3256 [PAY-1162] Update rendering overflow for some "Supporting" lists
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useRankedSupporters.ts
  packages/common/src/utils/constants.ts
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ViewAllSupportingTile.tsx
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/components/tipping/support/SupportingList.tsx
Labels: size/L

#3255 [C-2484] Fix edit playlist actions
  packages/common/src/store/cache/collections/actions.ts
  packages/common/src/store/cache/collections/types.ts
  packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
  packages/mobile/src/screens/edit-playlist-screen/types.ts
  packages/web/src/common/store/cache/collections/sagas.js
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
Labels: size/L

#3258 [C-2514] Fix empty related artists when logged out (web)
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/web/src/common/store/user-list/related-artists/sagas.ts
Labels: size/S

#3259 [C-2516] Always filter followed users from suggested
  packages/common/src/store/ui/related-artists/selectors.ts
Labels: size/XS

#3260 [C-2511] Don't delay mutuals fetch
  packages/web/src/common/store/profile/sagas.js
Labels: size/XS

#3262 [PAY-1122] Mobile chats keyboard improvements
  packages/mobile/src/components/core/KeyboardAvoidingView.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/L

#3265 SDK respects DN override using initialSelectedNode
  packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorInstance.ts
  packages/mobile/src/services/discovery-node-selector.ts
  packages/web/src/services/discovery-node-selector.ts
Labels: size/S

#3266 [C-2512] Fix scrolling on modals and related artists
  packages/stems/src/components/Scrollbar/Scrollbar.tsx
  packages/web/src/common/store/user-list/related-artists/sagas.ts
Labels: size/S

#3269 put back the ref
  packages/stems/src/components/Scrollbar/Scrollbar.tsx
Labels: size/XS

#3267 Mobile chats block/unblock users
  packages/mobile/src/components/block-messages/BlockMessages.tsx
  packages/mobile/src/components/profile-actions-drawer/ProfileActionsDrawer.tsx
Labels: size/M

#3270 [PLAT-903] Fix missing remix notifications
  packages/common/src/store/notifications/notificationsSelectors.ts
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
Labels: size/M

#3268 [PLAT-908] Fix new notifications not tagged in ui
  packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/XS

#3273 [C-1998] Reset notification state on sign-out
  packages/common/src/store/notifications/notificationsSlice.ts
Labels: size/XS

#3274 [C-2526] Remove pagination from related artists as endpoint doesn't support it
  packages/web/src/common/store/user-list/related-artists/sagas.ts
Labels: size/S

#3275 [C-2527] Remove cognito from mobile
  packages/web/.env/.env.dev
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/pages/App.js
  packages/web/src/pages/check-page/CheckPage.module.css
  packages/web/src/pages/check-page/CheckPage.tsx
  packages/web/src/services/audius-backend/Cognito.ts
  packages/web/src/utils/constants.ts
  packages/web/src/utils/route.ts
Labels: size/L

#3277 [CON-660] Prefer duration from track metadata over track_segments calculation
  packages/common/src/schemas/index.ts
  packages/common/src/services/audio-player.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/services/audio-player/AudioPlayer.test.js
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/M

#3271 [PAY-1106] Unmount reaction popup animations
  packages/mobile/src/hooks/usePopupAnimation.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
  packages/mobile/src/screens/chat-screen/constants.ts
Labels: size/L

#3278 [PAY-1187][PAY-1190][PAY-1176] Update SDK: User Chat Permissions to match backend
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/package-lock.json
  packages/mobile/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/M

#3276 [PAY-827][PAY-1154] Use DN stream endpoint for track download and offline mode
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/services/track-download/TrackDownload.ts
  packages/common/src/store/social/tracks/actions.ts
  packages/mobile/src/components/audio/Audio.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/mobile/src/services/track-download.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/services/track-download.ts
Labels: size/L

#3279 [C-2524] Fix mobile notification reactions
  packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Labels: size/S

#3280 Better fix for reactions using LayoutEvent
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Labels: size/M

#3282 [PAY-1158] Haptic feedback when opening chat reactions popup
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Labels: size/XS

#3272 [C-2496, C-2497] Refactor Playlist Library UI
  packages/common/src/models/PlaylistLibrary.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/playlist-library/index.ts
  packages/common/src/store/playlist-library/slice.ts
  packages/stems/src/components/IconButton/index.ts
  packages/stems/src/components/IconButton/types.ts
  packages/stems/src/index.tsx
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/common/store/playlist-library/watchAddToFolderSaga.ts
  packages/web/src/common/store/playlist-library/watchReorderLibrarySaga.ts
  packages/web/src/components/dragndrop/Draggable.tsx
  packages/web/src/components/dragndrop/Droppable.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.module.css
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/AudioNftPlaylistNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/EditNavItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/EditPlaylistNavItemButton.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/ExplorePlaylistNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibraryNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/index.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary/useAddAudioNftPlaylistToLibrary.ts
  packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
  packages/web/src/components/tooltip/index.ts
  packages/web/src/components/update-dot/index.ts
  packages/web/src/store/dragndrop/slice.ts
Labels: size/XXL

#3281 [CON-664] Split storage v2 feature flag into signup+upload
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/components/data-entry/FormTile.js
Labels: size/M

#3283 Fix parsing create notification track owner id
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#3152 [C-2348] Change offline download location
  packages/mobile/src/services/offline-downloader/offline-storage.ts
  packages/mobile/src/store/offline-downloads/sagas/migrateOfflineDataPathSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/mobile/src/types/analytics.ts
Labels: size/L

#3286 hotfix: Stripe onramp modal
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XS
